### ISSUE TITLE
Inconsistent treatment of R file extensions

### ISSUE THREAD

**Issue by kevin820606** [nvim-neo-tree/neo-tree.nvim#1001]
I've noticed an inconsistency in how the neotree handles file extensions. When creating an R file with an uppercase file extension (e.g., `.R`), neotree does not recognize it as an R file. However, if I use a lowercase file extension (e.g., `.r`), neotree correctly identifies it as an R file. It is worth mentioning that most style guides for R language recommend using uppercase file extensions (even in R's source code). Additionally, the [lualine](https://github.com/nvim-lualine/lualine.nvim) plugin does not exhibit this inconsistency and treats both uppercase and lowercase R file extensions as the same.

While this issue is not critical, I would appreciate guidance on configuring neotree to treat both `.R` and `.r` file extensions consistently. Alternatively, if there is a possibility of addressing this in the plugin's source code, I'm not familiar with Lua scripting and would appreciate help in submitting a request.

Please refer to the following screenshots for clarification:
- In neotree, `.R` and `.r` are treated differently.
   ![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/25343233/e61360c8-d8e8-4581-a6f7-6b3978811749)
- In lualine, both `.R` and `.r` are treated equally.
   ![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/25343233/387d6504-dd31-473f-b0d9-b96b242fc2ea)
   ![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/25343233/2f1931c5-97d4-4b39-bec2-633fbd2fd720)

Thank you for your attention to this matter. I would appreciate any suggestions or guidance on how to resolve this inconsistency.

**Comment by cseickel** [comment]
It looks like this has come up before in the icon library we use and they mostly addressed it, but we didn't get the fix because we pass in the extension instead of letting nvim-web-devicon figure it out for us.

https://github.com/nvim-tree/nvim-web-devicons/issues/44

It is a quick fix to just lowercase the extension before calling `get_icon()`. I'll put up that PR.

**Comment by kevin820606** [comment]
Thank you @cseickel for fixing this issue!
