### ISSUE TITLE
":Neotree toggle" closes and reopens neotree when source is "git_status"

### ISSUE THREAD

**Issue by gualcasas** [nvim-neo-tree/neo-tree.nvim#1009]
If I open neotree with ```:Neotree toggle``` and then change source from the default "filesystem" to "git_status" with ```>```

if I then do ```:Neotree toggle``` to close the open neotree, neotree is closed and immediately reopened with source "filesystem".

Is there a way to have ```:Neotree toggle``` close neotree if it's open regardless of the current source?

**Comment by cseickel** [comment]
No. The paradigms don't really fit. If you use the source selector, it means you want to leave it open all the time and just switch between the various sources.

The original paradigm that fits the best is to treat each source as a distinct tool that has no connection to other sources. Going with that idea, you should have a separate toggle mapping for each source. For example:

`|` for `:Neotree filesystem reveal left toggle`
`<leader>s` for `:Neotree git_status left toggle`
`<leader>b` for `:Neotree buffers left toggle`
