### ISSUE TITLE
Invalid window ID + focus file issues

### ISSUE THREAD

**Issue by levouh** [nvim-neo-tree/neo-tree.nvim#102]
I added an extra bit to the `log.error` output to get the `id` that caused the error (seen below inside of the `[...]` charcters) in the result of the `debounce` call, which gets printed out as follows:

```
[neo-tree.nvim] [ERROR 22:21:16] ...ite/pack/packer/opt/neo-tree.nvim/lua/neo-tree/utils.lua:73: Error in neo-tr...[filesystem_navigate]:  ...im/site/pack/packer/start/nui.nvim/lua/nui/tree/init.lua:219: Invalid window id: 1010
```

and each time that I open the tree, I get the invalid window ID number increases by one. Along with this, focusing the current file (`,ef` for me) can be seen working for a split second, but then the entire tree gets collapsed. Doing a bit of bisecting:

- `751ee6b4e840d36915ab5ac7234e848aa45db1ac`: works
- `4787b637895fccfedb813c9bf8926453f187c2e8`: borked

See below:

https://user-images.githubusercontent.com/31262046/151648934-ffd9e749-5eae-45e2-85dd-6883186368ae.mp4

**Comment by tristone13th** [comment]
I'm facing the same problem since the last update.

**Comment by cseickel** [comment]
It turns out the call to state.position.save was failing, which seems to indicate the window was being lost in between the is_valid check and trying to get the cursor position, which is surprising to me. 

Perhaps the larger issue that I still need to figure out is: navigate fires twice in a row for one action, and it's only the second call that has the error. I need to find and squash that redundant second call.

**Comment by levouh** [comment]
It seems that the reveal file action is still broken for me (note the first time I open it in the above screen cast how it does not focus the current file). Should I open up another issue for that @cseickel or is:

>Perhaps the larger issue that I still need to figure out is: navigate fires twice in a row for one action, and it's only the second call that has the error. I need to find and squash that redundant second call.

noting that is already being looked at?

**Comment by levouh** [comment]
I created #105 for the secondary issue here, feel free to close it if need be.
