### ISSUE TITLE
Diagnostics icon not showing in the "filesystem"

### ISSUE THREAD

**Issue by tristone13th** [nvim-neo-tree/neo-tree.nvim#103]
Here's my config:
```lua
	require("neo-tree").setup({
		enable_git_status = true,
		enable_diagnostics = true,
		filesystem = {
			show_hidden = true,
			window = {
				position = "left",
				width = 28,
				mappings = {
					["o"] = "open",
					["q"] = "navigate_up",
					["c"] = "set_root",
					["y"] = "copy_to_clipboard",
					["x"] = "cut_to_clipboard",
					["p"] = "paste_from_clipboard",
				},
			},
			search_limit = 50, -- max number of search results when using filters
			filters = {
				show_hidden = true,
				respect_gitignore = true,
			},
			bind_to_cwd = true, -- true creates a 2-way binding between vim's cwd and neo-tree's root
			renderers = {
				directory = {
					{
						"icon",
						folder_closed = " ",
						folder_open = " ",
						padding = "",
					},
					{ "current_filter" },
					{ "name" },
					{
						"clipboard",
						highlight = "NeoTreeDimText",
					},
					{ "git_status", highlight = "NeoTreeDimText" },
				},
				file = {
					{
						"icon",
						default = "*",
						padding = " ",
					},
					{ "name", use_git_status_colors = true },
					{
						"clipboard",
						highlight = "NeoTreeDimText",
					},
					{ "diagnostics" },
					{
						"git_status",
						highlight = "NeoTreeDimText",
					},
				},
			},
		},
	})

```

**Comment by cseickel** [comment]
I don't believe I didn't notice this myself, thanks for reporting!

**Comment by tristone13th** [comment]
> I don't believe I didn't notice this myself, thanks for reporting!

Thanks for your effort,  but it seems that this problem didn't go away when I updated to the new release. Here is the screenshot, you can see that the file name of plug_config.py is blue and has some diagnostics (H) but the icon just didn't show up, any advice you can give me?
![2022-01-29 23-34-29 的屏幕截图](https://user-images.githubusercontent.com/17382962/151666969-5cba9ee9-f0b1-4ce4-b99d-9831349b74a0.png)

**Comment by cseickel** [comment]
The letters are the fallback if you have not defined any symbols in your vim config. Checkout `:h neo-tree-diagnostics` for an example on how to configure that.

**Comment by tristone13th** [comment]
> The letters are the fallback if you have not defined any symbols in your vim config. Checkout `:h neo-tree-diagnostics` for an example on how to configure that.

I get it, many thanks!
