### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by guivazcabral** [nvim-neo-tree/neo-tree.nvim#1034]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.9.1 

### Operating System / Version

MacOS 13.4.1

### Describe the Bug

Not showing the correct icons for files with "two extensions" like `.spec.ts` - it's rendering the icon for .ts files.

Running `lua print(require'nvim-web-devicons'.get_icon("something", "spec.ts"))` returns the correct icon

### Screenshots, Traceback

using the minimum config below for reproducing

<img width="1506" alt="image" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/5154363/7899395d-18de-405c-8241-40a52dd5a2b8">

### Steps to Reproduce

Have two files `something.ts` and `something.spec.ts` (or `.test.ts`). They should have different icons (regardless of your config of nvim-web-devicons), but they show the same icon

### Expected Behavior

Expected to have different icons for .ts and .spec.ts files

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {
    { "<Leader>e", "<Cmd>Neotree<CR>" }, -- change or remove this line if relevant.
  },
  opts = {
    -- Your config here
    -- ...
  },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by guivazcabral** [comment]
Added Telescope to the minimal config above and it shows the icons correctly
<img width="1512" alt="image" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/5154363/113b4cd0-c3a6-48c1-91d4-5ae376f67c48">

**Comment by pysan3** [comment]
Hi @guivazcabral 

Thanks for the bug report.

Would you update the title of this issue to be a bit more precise?
The content is very easy to read, but I can only see `BUG:` as the title.

Thanks in advance ;)

**Comment by miversen33** [comment]
#1044 has been merged into main, closing this out :)

**Comment by guivazcabral** [comment]
@pysan3 sorry! completely missed the title of the issue 😓  thanks for fixing!
