### ISSUE TITLE
BUG: Error opening file: vim/_editor.lua:0: nvim_exec2()..BufReadPost Autocommands for "*"

### ISSUE THREAD

**Issue by linrongbin16** [nvim-neo-tree/neo-tree.nvim#1036]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

v9.1.0

### Operating System / Version

ubuntu 22.04 x86_64 (virtual machine running on Windows 10)

### Describe the Bug

When opening a file, there's an error:

```
[Neo-tree ERROR] Error opening file: vim/_editor.lua:0: nvim_exec2()..BufReadPost Autocommands for "*": Vim(lua):E5108: Error executing lua [string ":lua"]
```

### Screenshots, Traceback

![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/6496887/13ef3ca4-c17e-46c0-a8b5-d64795c2652a)

### Steps to Reproduce

1. install ubuntu 22.04 LTS desktop x86_64
2. install nvim.appimage v0.9.1
3. install nvim with lazy.nvim, neo-tree.
4. start nvim and open a file.

### Expected Behavior

Opening file without exception.

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {
    { "<Leader>e", "<Cmd>Neotree<CR>" }, -- change or remove this line if relevant.
  },
  opts = {
    -- Your config here
    -- ...
  },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by pysan3** [comment]
Hi, I also do occasionally experience a similar bug once in a while, but I cannot reproduce this with the `# Your Configuration` you provided.

Does this really happen to you with the minimal example?

It would be nice if you could nail down the problem a bit further.

Thanks in advance.

**Comment by linrongbin16** [comment]
Hi, finally I just re-installed my ubuntu VM, and it's all good now.

This is not a neo-tree plugin bug, it should be the installation issue related to ubuntu.
