### ISSUE TITLE
[BUG] Reveal file does not work

### ISSUE THREAD

**Issue by levouh** [nvim-neo-tree/neo-tree.nvim#105]
See below:

https://user-images.githubusercontent.com/31262046/151678010-26a1cb1a-166d-471f-bf04-9268fdefabb6.mp4

where the steps to reproduce would be:

1. Open a file
2. Use `:NeoTreeReveal`
3. Observe that the correct file is not revealed, and instead the tree is simply shrunk

This was introduced via `4787b637895fccfedb813c9bf8926453f187c2e8`, as the same action works (meaning the tree properly focuses the current file) on `751ee6b4e840d36915ab5ac7234e848aa45db1ac`.

**Comment by cseickel** [comment]
I'm not seeing the same issue. Are you currently on the latest release, which is 517cf66523139071df05c45c221b8e186343aeb2?

Can you paste your config here?

**Comment by levouh** [comment]
I am using `59d22bbc767a16ebce4d706e9b5e4be350be9278`, and it happens for me when using a minimal configuration like:

```lua
vim.opt.runtimepath = { vim.env.VIMRUNTIME }

vim.cmd([[
  packadd plenary.nvim
  packadd neo-tree.nvim
]])

require("neo-tree").setup({})
```

and then running `nvim --noplugin -u /tmp/neo-tree.lua` (assuming the file above is at the path mentioned here). Open a path in the same directory as where you ran `nvim`, and run `:NeoTreeReveal`.

**Comment by cseickel** [comment]
Thanks, I see it now. I am pretty sure the first invocation works but the second invocation is messing it up by not having the correct folders open.

**Comment by cseickel** [comment]
@levouh Can you try the latest in **main** and let me know if it works correctly?

**Comment by nyngwang** [comment]
I think this problem still exists.


https://user-images.githubusercontent.com/24765272/153723388-c573129f-8922-4e80-9ddc-5d33fa68506d.mov

**Comment by cseickel** [comment]
> Usually happen after all packages get updated via packer.nvim (while don't restart the session) 

That was the missing detail I needed! I found the bug and am fixing it now.

**Comment by cseickel** [comment]
@nyngwang I think this is fixed now in **mian**.

**Comment by nyngwang** [comment]
> That was the missing detail I needed! [...]

@cseickel Lol, I thought this info was not important days ago so I didn't provide it. Let me check it now!
