### ISSUE TITLE
FEATURE: multiple neotree in different tab 

### ISSUE THREAD

**Issue by qizidog** [nvim-neo-tree/neo-tree.nvim#1053]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

May I have multiple neotree in different nvim tab?

When I open neotree window in tab1 then switch into tab2 and call `Neotree` command, it just get back to neotree window in tab1 which is not what I what.

Perhaps, opening a neotree directly in the second tab would be a more intuitive behavior?

### Describe the solution you'd like.

provid an option to config thsi behavious~

### Describe alternatives you've considered.

neotree window should be handled by each tab independently.

**Comment by cseickel** [comment]
This is actually a core feature that broke somewhere along the way. It should absolutely support a separate instance for each tab. Since I stopped using tabs and sidebars in my daily workflow I didn't notice that this was broken.

I'll take a look and fix it.

**Comment by qizidog** [comment]
@cseickel Sorry for forgetting to mention that the branch I am using is the latest version of 2.x (maintained by LazyVim), this defect also exists on that branch 🤣

**Comment by miversen33** [comment]
@qizidog looks like @cseickel merged a fix for this in main. Can you try out the main branch and verify that it is working "as expected" there?

**Comment by qizidog** [comment]
@miversen33 Sure, I have checked the main branch and it looks very good! 😆

**Comment by miversen33** [comment]
Awesome sauce :)

**Comment by cseickel** [comment]
FYI @qizidog @miversen33 - I was considering `v2.x` as done because we are about to release `v3.0`, but this is a significant bug so I backported it to `v2.x` as well.

**Comment by qizidog** [comment]
> FYI @qizidog @miversen33 - I was considering `v2.x` as done because we are about to release `v3.0`, but this is a significant bug so I backported it to `v2.x` as well.

Thank you for your information!
