### ISSUE TITLE
How to install with lazy

### ISSUE THREAD

**Issue by Hello-LuisWu** [nvim-neo-tree/neo-tree.nvim#1058]
怎么用lazy 安装？？？？

**Comment by miversen33** [comment]
[Did you even bother looking at the lazy documentation](https://github.com/folke/lazy.nvim#-installation)
[There is literally a section detailing how to setup Neo-tree itself in lazy](https://github.com/folke/lazy.nvim#%EF%B8%8F-lazy-key-mappings)
