### ISSUE TITLE
BUG: `require("neo-tree").close_all()` no longer works as its not defined

### ISSUE THREAD

**Issue by felipesere** [nvim-neo-tree/neo-tree.nvim#1063]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.9.1

### Operating System / Version

macOS Ventura 13.4.1

### Describe the Bug

It used to be possible to close `neotree` after opening a file with this  event handler configured
```lua
  event_handlers = {
    {
      event = "file_opened",
      handler = function(file_path)
        --auto close
        neotree.close_all()
      end,
    },
  },
```
As is, its taken directly from the recipes page.

Now, when running I get the following error:

```
Error in event handler for event file_opened[table: 0x01019283c8]: /Users/felipe.sere/.config/nvim/init.lua:188: attempt to call field 'close_all' (a nil value)
```

### Steps to Reproduce

Open neovim
Open neotree
In neotree, try to open any file with `o`

### Expected Behavior

The function should be defined and close the current neotree instance.

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {
    { "<Leader>e", "<Cmd>Neotree<CR>" }, -- change or remove this line if relevant.
  },
  opts = {
  event_handlers = {
    {
      event = "file_opened",
      handler = function(file_path)
        --auto close
        neotree.close_all()
      end,
    },
  },
  window = {
    mappings = {
      ["o"] = "open",
      ["l"] = false,
    },
  },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by miversen33** [comment]
I can verify this issue. I can also confirm that the function exists in neo-tree v2.x, so somewhere in the migration to `main`, this function was dropped off. I am a bit busy this morning so I don't have the time to bisect this.

Tagging @cseickel as they may have quicker access to more details/a solution/workaround

**Comment by cseickel** [comment]
Confirming that this was a deprecated function that was dropped in 3.0. You can use either of these to replace it:

```lua
vimc.cmd("Neotree close")
-- OR
require("neo-tree.command").execute({ action = "close" })
```

**Comment by felipesere** [comment]
Confirmed, works like a charm.

I'll update the recipe.

**Comment by cseickel** [comment]
> I'll update the recipe.

Thanks!

**Comment by rzyanhao** [comment]
I replaced this by
```
require("neo-tree.sources.manager").close_all();
```
