### ISSUE TITLE
Feature request: Add Api for overriding filenames

### ISSUE THREAD

**Issue by hacker-DOM** [nvim-neo-tree/neo-tree.nvim#1069]
Hi there! 

First of all, great job! neo-tree.nvim is great, I'm lovin it! I was wondering if you would be open to add an Api for overriding file names. My use case is:

I work with _a lot_ of projects that I haven't developed (I'm a security auditor), I am not familiar with the physical layout of the code

So I wrote a tool - `sccd` that places a small `.metadata.json` file in each directory. It's very simple; here's an example:

```json
{
  "generators.py": {
    "programmingCode": 192
  },
  "fuzzer.py": {
    "programmingCode": 286
  },
}
```

Then I wrote a Ranger Plugin that shows me that info in Ranger:

<img width="1106" alt="image" src="https://github.com/akinsho/bufferline.nvim/assets/18601956/fec39ec2-732e-4218-804e-f47de04486ad">

It works great but I would love the same functionality in neo-tree :)

**Comment by hacker-DOM** [comment]
Basically all I would need is something like

```lua
opts = {
    filename_override = function(filename)
         -- read from .metadata.json from the same directory
         -- return f"{filename} ({lines_of_code})"
    end
}
```

**Comment by miversen33** [comment]
Consider looking into `:h neo-tree-component-configs`, that may likely get you where you are looking to go.

You would need to use that along with the `filesystem` source. 
The [`doc`](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/doc/neo-tree.txt) has more info on this :)
