### ISSUE TITLE
BUG: deprecated instructions remaining in examples

### ISSUE THREAD

**Issue by pysan3** [nvim-neo-tree/neo-tree.nvim#1080]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.9.0

### Operating System / Version

Linux

### Describe the Bug

@cseickel 

I found out that you deprecated most of the functions in `neo-tree.lua`. But I found one still referenced in `defaults.lua`.

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/7951701fd21291ac473ea92d3fd57ec5c8bf10bb/lua/neo-tree/defaults.lua#L103

`require("neo-tree").close_all()` was deleted with commit https://github.com/nvim-neo-tree/neo-tree.nvim/commit/78d26168e0b4c7c06a0c59b26c2cd305e64f3d12.

This should be changed to the correct API or it would be nice if `close_all` is kept in `neo-tree.lua` since I believe many people still have this exact event. Up to you tho.

Thanks in advance.

### Steps to Reproduce

Uncomment this line in `defaults.lua`.

```lua
    event_handlers = {
      {
        event = "file_opened",
        handler = function(_)
          require("neo-tree").close_all()
        end,
      },
    }
```

### Expected Behavior

Update `defaults.lua`.

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {
    { "<Leader>e", "<Cmd>Neotree<CR>" }, -- change or remove this line if relevant.
  },
  opts = {
    -- Your config here
    -- ...
    event_handlers = {
      {
        event = "file_opened",
        handler = function(_)
          require("neo-tree").close_all()
        end,
      },
    }
  },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by cseickel** [comment]
Oops, I definitely should have removed it from the help file prior to deleting the function. I think what I will do is:

- [ ] Restore the `close_all()` method, but make the implementation call the currently preferred `neo-tree.command` method. Mark it as deprecated in the source.
- [ ] Change the documentation to call that method directly and remove reference to the deprecated function.
- [ ] Delete it again in 4.0
