### ISSUE TITLE
FEATURE: select then move or copy, then paste

### ISSUE THREAD

**Issue by MuhammadSawalhy** [nvim-neo-tree/neo-tree.nvim#1083]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

Select files to move or copy. If a user wants to move or copy single or **multiple** files from different directories to another directory. The same feature is not for files only, the user may select files or directories as well. It will be a UX booster.

### Describe the solution you'd like.

I need to select them first then put the cursor on the destination then I may be able to press some key (<kbd>p</kbd>) to paste these files. This feature exists in my previous file explorer plugin, [chadtree](https://github.com/ms-jpq/chadtree).

**Comment by cseickel** [comment]
This feature exists already. Press `y` to yank (copy) or `x` to cut, the files will be marked. Press `y` or `x` again on the same file to unmark them. Then press `p` to paste them in another location.

**Comment by MuhammadSawalhy** [comment]
Thank you for the clarification. Is it in the documentation? I've read the README multiple times and couldn't find this feature explicitly stated.

**Comment by cseickel** [comment]
Yes:
```
:h neo-tree-file-actions
```

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/1424449bb4fea7a6041a782cfb7ca46156fc358e/doc/neo-tree.txt#L275-L281

**Comment by MuhammadSawalhy** [comment]
I believe that it can be better written like this:

```
 y    = copy_to_clipboard:    Mark file or directory to be copied. 
                              Supports visual selection.~ 
                              Can mark more than a file or a directory.~   

 x    = cut_to_clipboard:     Mark file or directory to be cut (moved). 
                              Supports visual selection.~ 
                              Can mark more than file or directory.~ 
  
 p    = paste_from_clipboard: Copy/move all marked files or directories to the selected folder. 
```

Can I unmark all cut and copy marks?

**Comment by MuhammadSawalhy** [comment]
It is not even in the help window

![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/42011920/88ef266c-2395-4379-9fef-fb6ddd4a7471)

**Comment by cseickel** [comment]
> I believe it should be stated in the README and also can be better written like this:

The clarification doesn't hurt, feel free to submit a PR.

> Can I unmark all cut and copy marks?

There's no command for this yet, you have to toggle them individually.

> It is not even in the help window

It is, your screen just isn't big enough. You need to scroll down to see the rest of the commands.

**Comment by MuhammadSawalhy** [comment]
Excuse me, sir. I have a good suggestion. What about removing the extra keybindings <kbd>x</kbd> and <kbd>y</kbd> to mark files for specific actions and add another keybinding <kbd>m</kbd> to mark files or directories, in general, then the user can select the destination and press <kbd>c</kbd> to copy, <kbd>x</kbd> to move, or <kbd>d</kbd> to delete them.

This is so useful when the user also **_wants to mark multiple files for deletion 💥_** (to avoid the confirmation prompt every time). Another keybinding may be set to unmark all files such as <kbd>M</kbd> (capital s).

So now only one (instead of 6) keybinding is occupied to start the marking (selection) mode, once the user enters this mode he/she can get more keybindings such as <kbd>c</kbd>, <kbd>x</kbd>, <kbd>d</kbd>, and <kbd>M</kbd>.

**Comment by miversen33** [comment]
This is how I handle mass node interaction in Netman, however I don't know that "removing" keybindings is a great idea.

We **must** remember that we cannot just change the default settings "because something is better". Some users rely on the existing keybindings (and in general existing defaults). 

Relevant XKCD
![Spacebar heating workflow](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/2640668/75a07e62-729d-4dd2-9f14-bff7cebbeec5)

**Comment by MuhammadSawalhy** [comment]
> We **must** remember that we cannot just change the default settings "because something is better". Some users rely on the existing keybindings (and in general existing defaults).

I agree. This can be planned for version 4.

**Comment by cseickel** [comment]
Another thing to consider is that someone may want to cut some files and move other files to a common location. That is something that works with the current system but won't work with the proposed one.

I have an alternative for you that is additive and won't break existing workflows:

- Add a new mapping `mm` to `mark` nodes
- Add a new mapping `md` to `marked delete` all marked files
- Add two other new mappings to change marked nodes:
  - `mx` to set `marked to cut`
  - `my` to set `marked to yank`
  - Then you can use `p` as normal to paste

**Comment by LeonB** [comment]
Adding some mapping to mark non-consecutive nodes would be very nice!

**Comment by schroedermatthias** [comment]
> Yes:
> 
> ```
> :h neo-tree-file-actions
> ```
> 
> https://github.com/nvim-neo-tree/neo-tree.nvim/blob/1424449bb4fea7a6041a782cfb7ca46156fc358e/doc/neo-tree.txt#L275-L281

@cseickel agree for yank and move. How about `d`(elete)? The docs say `d` Supports visual selection.~:

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/1424449bb4fea7a6041a782cfb7ca46156fc358e/doc/neo-tree.txt#L270C1-L271C57

But how is this supposed to work when the deletion popup appears on the first hit of `d`?

**Comment by pysan3** [comment]
@schroedermatthias You visually select the nodes i.e. vim's visual selection invoked normally by `v` or `V`.

**Comment by tednaaa** [comment]
Hey guys, is there something like copy files/folders from one project to another?

**Comment by Giessen** [comment]
Any way to clear all the marks, which possibly hard to track the locations one by one? Many thanks.

**Comment by MuhammadSawalhy** [comment]
Many users here request the feature of selecting multiple non-consecutive items to delete them. I know about deleting multiple consecutive items by selecting them using the visual mode.

There is also a request to remove all mark of copying and moving files. How to clear these marks?

So, I suggest reopening this issue.

**Comment by martin-dimi** [comment]
Re: How do I delete multiple files at once?
