### ISSUE TITLE
Undocumented dependency on LuaJIT

### ISSUE THREAD

**Issue by pearzt** [nvim-neo-tree/neo-tree.nvim#1087]
Due to architectural limitations, I am running Neovim using plain Lua, not LuaJIT. Unfortunately, neo-tree imports LuaJIT's foreign-functions interface (FFI) which is not available in plain Lua. IMHO, this dependency should be either documented or removed.
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/38293fe690981aba6cfef5e440f26d8b956d463e/lua/neo-tree/utils.lua#L4

I'm aware of third-party implementations like https://github.com/jmckaskill/luaffi and https://github.com/facebookarchive/luaffifb which I haven't tried in this context yet.

**Comment by pearzt** [comment]
In case somebody has the same problem: The workaround using https://github.com/facebookarchive/luaffifb seems to work for me.

**Comment by cseickel** [comment]
Seeing as though ffi is only used to identify hidden files on windows, I think it should be a soft requirement and gracefully fallback to the old behavior of using *nix rules to identify hidden files if it is not available.

Are you on Windows?

**Comment by pearzt** [comment]
No, I'm on Linux, but on a machine using the POWER ISA which is not supported by LuaJIT.

Making it a soft requirement sounds like a very sensible solution to me.

**Comment by cseickel** [comment]
@pearzt could you try the branch in #1087 and tell me if it works without your workaround?
```
1087-undocumented-dependency-on-luajit
```

**Comment by pearzt** [comment]
I just tested the branch you specified and it seems to fix the problem \o/

However, if have given up trying to make Neovim run on this machine, as this plugin is not the only one that has problems like this. It seems like that parts of Neovim ecosystem implicitly depend on LuaJIT as it is the way how the official binary are built.

**Comment by pearzt** [comment]
I just tested the branch you specified and it seems to fix the problem \o/

However, if have given up trying to make Neovim run on this machine, as this plugin is not the only one that has problems like this. It seems like that parts of Neovim ecosystem implicitly depend on LuaJIT as it is the way how the official binary are built.

**Comment by cseickel** [comment]
Thanks for testing but sorry it didn't work for you.
