### ISSUE TITLE
FEATURE: Dynamic width window

### ISSUE THREAD

**Issue by DanielCardonaRojas** [nvim-neo-tree/neo-tree.nvim#1092]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

It is nice to not have to manually expand the window width  to see a complete file name. Specifying a percentage might result in an excessive window width. 

Note this feature is implemented in nvim-tree I created a similar issue which got implemented. Here it is for reference: 

https://github.com/nvim-tree/nvim-tree.lua/issues/865

### Describe the solution you'd like.

 The proposed feature is to expand the width of the window to fit the largest file name or deepest nested file name.

### Describe alternatives you've considered.

I read through the documentation and found fit_content option but that didn't seem to do what I'm describing.

**Comment by cseickel** [comment]
It actually already exists, it's one of the options that is only mentioned in `defaults.lua`:

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/38293fe690981aba6cfef5e440f26d8b956d463e/lua/neo-tree/defaults.lua#L313

You can toggle it on and off by pressing `e` in the neo-tree window.
