### ISSUE TITLE
Cannot perform search/filter due to errors on "is_active" function

### ISSUE THREAD

**Issue by wookayin** [nvim-neo-tree/neo-tree.nvim#110]
While performing search/filter (`/`) on a neo-tree, I see the following error message:

```
Error executing vim.schedule lua callback: $HOME/.vim/plugged/plenary.nvim/lua/plenary/job.lua:212: bad argument #1 to 'is_active' (Expected uv_handle userdata)
stack traceback:
        [C]: in function 'is_active'
        $HOME/.vim/plugged/plenary.nvim/lua/plenary/job.lua:212: in function 'shutdown'
        $HOME/.vim/plugged/plenary.nvim/lua/plenary/job.lua:334: in function <$HOME//.vim/plugged/plenary.nvim/lua/plenary/job.lua:333>
Press ENTER or type command to continue
Error executing luv callback:
cannot resume dead coroutine
stack traceback:
        [builtin#36]: at 0x55ddd2a41af0
```

neovim version (NVIM v0.7.0-dev+963-g082ff2190, nightly installed few days ago)
neotre version: tag/v1.25

Any ideas why it's happening?

**Comment by cseickel** [comment]
That is a new one to me, but I am a little behind on updates so maybe there is a new breaking change upstream. I'll update tonight and see if it breaks.

**Comment by cseickel** [comment]
It's working fine for me on the latest neovim from git:
```
NVIM v0.7.0-dev+997-g21cdecc8e
Build type: Release
LuaJIT 2.1.0-beta3
```

do you have `fd` or `find` installed? Can you post your neo-tree config?

**Comment by wookayin** [comment]
I was using the empty config:

```
require('neo-tree').setup {         
}                                   
```

I have fd, find, ripgrep installed. Probably it could be a conflict with other plugins..

**Comment by cseickel** [comment]
Is this still happening for you, or have you found the cause? If it still happens, I think the next step is to try it with a minimal config to see if it is an interaction with another plugin.

**Comment by cseickel** [comment]
Closing for now due to lack of activity. Feel free to re-open if you have any new info.
