### ISSUE TITLE
BUG: Line number show in Neotree window when opened via autocmd.

### ISSUE THREAD

**Issue by croyleje** [nvim-neo-tree/neo-tree.nvim#1106]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.9.1

### Operating System / Version

Linux arch 6.4.10-1 x86_64 GNU/Linux

### Describe the Bug

If Neotree is started via an autocmd the Neotree window shows line numbers, both relative and regular.  Once the Neotree window gains focus the line number disapear.

### Steps to Reproduce

This autocmd added to your init.lua should do it.

vim.api.nvim_create_autocmd({ "VimEnter" }, {
	pattern = "*",
	command = ":Neotree show reveal",
})

### Expected Behavior

Neotree should be opened with vim but not have line numbers.  Setting a ftplugin config does not seem to fix the issue

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {
    { "<Leader>e", "<Cmd>Neotree<CR>" }, -- change or remove this line if relevant.
  },
  opts = {
    -- Your config here
    -- ...
  },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here

vim.api.nvim_create_autocmd({ "VimEnter" }, {
	pattern = "*",
	command = ":Neotree show reveal",
})

vim.opt.relativenumber = true
```

**Comment by croyleje** [comment]
Rolling back to release 3.1 does fix the issue it appears to be related to the commit 38293fe but that is only a from looking at the logs.

**Comment by cseickel** [comment]
Using your minimal config I do not see line numbers in the tree.

I would guess that the problem is that you need to enable `nested` autocmds for it to work with the changes that were just made:

```
:h autocmd-nested
```

**Comment by croyleje** [comment]
Thank you and sorry to bother you with this.  That did seem to fix it if anyone else comes acorss this below is a example of how to enabled a nested autocmd via the nvim_api.

```
vim.api.nvim_create_autocmd({ "VimEnter" }, {
	pattern = "*",
	nested = true,
	command = ":Neotree show reveal",
})
```
