### ISSUE TITLE
FEATURE: make `:Neotree toggle` close Neotree if a source other than "filesystem" is selected

### ISSUE THREAD

**Issue by Subjective** [nvim-neo-tree/neo-tree.nvim#1115]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

Currently, the `:Neotree toggle` command only closes Neotree if the filesystem source is selected.

### Describe the solution you'd like.

I think it would be more intuitive for `:Neotree toggle` to close Neotree no matter which source is selected, without having to specify in the command (e.g. `:Neotree toggle source=buffers`). This would be useful for people who have `:Neotree toggle` bound to a keymap.

### Describe alternatives you've considered.

It might be feasible to use the api to check which source is selected and use that to determine how to close Neotree in the callback function for a keymap.

**Comment by cseickel** [comment]
This would be best solved by #1081

**Comment by Subjective** [comment]
While I think that's a great idea, it doesn't fully address the issue I had in mind. Assuming the PR is merged, `:Neotree toggle last` will always close Neotree no matter which source is selected, but this would also mean reopening the same source when toggling it open again, which is not what I want (though I understand some people might). I actually prefer `:Neotree toggle` to always open Neotree with the filesystem source selected. 

In my opinion, the solution that covers both use cases would be to have the `:Neotree toggle` command always close neotree no matter the source if it is already open, while retaining the same default behavior of opening the filesystem source if it is not. Those who want Neotree to reopen the with previously selected source could just use `:Neotree toggle last`.

This way, the toggle command will behave intuitively as the name suggests  – two consecutive uses of a toggle will always result in the original state being restored.

**Comment by cseickel** [comment]
> This way, the toggle command will behave intuitively as the name suggests

I would strongly disagree with the idea that this workflow is intuitive! It's inconsistent and confusing and there's no way that will become the default behavior.

If what you want is to close any Neotree window regardless of source or position, you can use:

```
:Neotree close
```

If you want to create your own function that acts this way, you can just check if any of the visible buffers are Neotree by checking if the filetype == `neo-tree`. If they are, then issue the `:Neotree close` command, else issue `:Neotree filesystem`.

Something like this should work to find a buffer by filetype (this is untested):

```lua
local find_buffer_by_type = function(type)
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    local ft = vim.api.nvim_buf_get_option(buf, "filetype")
    if ft == type then
      return buf
    end
  end
  return -1
end
```

**Comment by hail0hydra** [comment]
> While I think that's a great idea, it doesn't fully address the issue I had in mind. Assuming the PR is implemented correctly and merged, `:Neotree toggle last` will always close Neotree no matter which source is selected, but this would also mean reopening the same source when toggling it open again, which is not what I want (though I understand some people might). I actually prefer `:Neotree toggle` to always open Neotree with the filesystem source selected.
> 
> In my opinion, the solution that covers both use cases would be to have the `:Neotree toggle` command always close neotree no matter the source if it is already open, while retaining the same default behavior of opening the filesystem source if it is not. Those who want Neotree to reopen the with previously selected source could just bind `:Neotree toggle last` to a keymap.
> 
> This way, the toggle command will behave intuitively as the name suggests – two consecutive uses of a toggle will always result in the original state being restored.

Did you find any way to toggle the Neotree with just one keybinding?

**Comment by Subjective** [comment]
@hail0hydra You could try this snippet for lazy:
```lua
keys = function()
  local find_buffer_by_type = function(type)
    for _, buf in ipairs(vim.api.nvim_list_bufs()) do
      local ft = vim.api.nvim_buf_get_option(buf, "filetype")
      if ft == type then return buf end
    end
    return -1
  end
  local toggle_neotree = function(toggle_command)
    if find_buffer_by_type "neo-tree" > 0 then
      require("neo-tree.command").execute { action = "close" }
    else
      toggle_command()
    end
  end

  return {
    {
      "<leader>e",
      function() require("neo-tree.command").execute { toggle = true, dir = vim.uv.cwd() } end,
      desc = "Toggle Explorer (cwd)",
    },
    {
      "<leader>E",
      function() require("neo-tree.command").execute { toggle = true } end,
      desc = "Toggle Explorer (root)",
    },
  }
end
```

**Comment by hail0hydra** [comment]
> @hail0hydra You could try this snippet for lazy:
> 
> ```lua
> keys = function()
>   local find_buffer_by_type = function(type)
>     for _, buf in ipairs(vim.api.nvim_list_bufs()) do
>       local ft = vim.api.nvim_buf_get_option(buf, "filetype")
>       if ft == type then return buf end
>     end
>     return -1
>   end
>   local toggle_neotree = function(toggle_command)
>     if find_buffer_by_type "neo-tree" > 0 then
>       require("neo-tree.command").execute { action = "close" }
>     else
>       toggle_command()
>     end
>   end
> 
>   return {
>     {
>       "<leader>e",
>       function()
>         toggle_neotree(function() require("neo-tree.command").execute { action = "focus", reveal = true, dir = vim.uv.cwd() } end)
>       end,
>       desc = "Toggle Explorer (cwd)",
>     },
>     {
>       "<leader>E",
>       function()
>         toggle_neotree(function() require("neo-tree.command").execute { action = "focus", reveal = true } end)
>       end,
>       desc = "Toggle Explorer (root)",
>     },
>   }
> end
> ```

Thank you for this. I almost went back to [nvim-tree](https://github.com/nvim-tree/nvim-tree.lua)
