### ISSUE TITLE
Trailing slashes on directories

### ISSUE THREAD

**Issue by wookayin** [nvim-neo-tree/neo-tree.nvim#112]
I would like to see trailing slashes on the directories if configured (I think this should be the default behavior), like netrw, NERDTree, nvim-tree.lua, etc.

**Comment by cseickel** [comment]
You can do this by adding or changing components in your directory renderer. I'll post an example later.

**Comment by cseickel** [comment]
Here is how you can add a trailing slash right now:

```lua
require("neo-tree").setup({
  filesystem = {
    components = {
      trailing_slash = function ()
        return {
          text = "/",
          highlight = "NeoTreeDirectoryName",
        }
      end,
    },
    renderers = {
      directory = {
        {"icon"},
        {"name", use_git_status_colors = false},
        {"trailing_slash"},
        {"diagnostics"},
        {"git_status"},
      },
    }
  },
})
```

I'm also going to include some simpler configuration options in the future to accomplish the same thing with less code.

**Comment by nyngwang** [comment]
> I'm also going to include some simpler configuration options in the future to accomplish the same thing with less code.

Waiting for this. Thanks a lot!

**Comment by cseickel** [comment]
I slipped this into 3e1af7a590cf1ac71edffb442618aa890f1cb29e, which is in **main** now and will probably be released today. You can now just add `trailing_slash = true` as a config option on the `name` component.

```lua
require("neo-tree").setup({
  filesystem = {
    renderers = {
      directory = {
        {"icon"},
        {
          "name", 
          use_git_status_colors = true,
          trailing_slash = true
        },
        {"diagnostics"},
        {"git_status"},
      },
    }
  },
})
```

**Comment by nyngwang** [comment]
@cseickel Yes!

**Comment by wookayin** [comment]
@cseickel Thanks for implementing this. Could we use different highlight group for the trailing slashes (e.g., DirectoryIcon rather than DirectoryName) when using such built-in options? Although a very complex renderer would do the job :)

**Comment by cseickel** [comment]
@wookayin I think for that purpose, the original `trailing_slash` example is actually the ideal solution.

**Comment by nyngwang** [comment]
@cseickel: I just added the `trailing_slash = true` but it didn't show the slash?
