### ISSUE TITLE
BUG: `Currently open buffers list` only update if the file has been opened by neotree

### ISSUE THREAD

**Issue by Zeioth** [nvim-neo-tree/neo-tree.nvim#1124]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.9.1

### Operating System / Version

Arch btw

### Describe the Bug

When opening several buffers at the same time with `Rnvimr`, or any other way,  the `Bufs tab` is not updated with the opened buffers.

I've tried with

```lua
  autocmd("BufReadPre", {
    desc = "Refresh Neo-Tree buffers tab when opening a new buffer",
    group = augroup("neotree_refresh", { clear = true }),
    callback = function()
        require("neo-tree.sources.buffers").buffers_changed()
    end,
  })
```

* But this only shows a buffer in the neotree buffers list after I enter the buffer.
* I need the buffers to be added to the neotree buffers list as soon as they are opened.

How can this be done?

### Screenshots, Traceback

You can see items are on the heirline but not on neotree bufs list
![screenshot_2023-08-28_16-41-08_754407908](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/3357792/e3ab048b-50bc-4af7-8ee9-11f3a2732a5a)

### Steps to Reproduce

1. Open Rnvimr and press space to mark several files.
2. Press ENTER to open them

### Expected Behavior

Neotree bufs tree should be updated no matter what or how open the buffers.

### Your Configuration

```Lua
https://github.com/NormalNvim/NormalNvim
```

**Comment by cseickel** [comment]
The buffers in question may not actually be loaded. Try this options:

```lua
require("neo-tree").setup({
  buffers = {
    show_unloaded = true
  }
})
```

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/2c992760f154285dff9f798647954b363cf35963/lua/neo-tree/defaults.lua#L536-L537

**Comment by Zeioth** [comment]
Bull's eye. That fixes it thank you so much @cseickel
