### ISSUE TITLE
Moving files/folders are inconvenient currently

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#114]
For some reason, I have to disable `<Up>`,`<Down>`,`<Left>`,`<Right>` in insert mode. So when I want to rename a file for moving it to another folder, I will have to retyping it's filename:

<img src="https://user-images.githubusercontent.com/24765272/152228253-e80524d6-ea48-4de8-8e40-3be44c6f19fa.png" width="700">

Is it possible to rename the file in the cmdline (using `: ...`) and with the full-path of the file being rename pre-filled? Since I didn't disable the four keys in command mode, this will be convenient for me. (Actually this is the behaviour provided by nvim-tree.lua)

**Comment by cseickel** [comment]
Not right now. If more people were interested I might add the option.

I have to ask, why not fix your problem with using arrow keys in insert mode? That's a pretty basic feature to just live without.

**Comment by nyngwang** [comment]
@cseickel The input method I'm using needs to facilitate these four arrow keys to choose a word from candidates. Inside insert mode, these arrows **move** the insert point which makes typing my mother language in (Neo)Vim impossible. It's OK that you don't want to implement this, but then what I can tell is this indeed an important feature for who need to typing non-english in (Neo)Vim.

**Comment by nyngwang** [comment]
As for other idea: is it possible to simulate `y`(yank) or `d`(delete) and paste the file/folder one needs to move?

**Comment by cseickel** [comment]
If it might affect a large number of people then that makes it a higher priority.

What do mean by simulating yank/delete?

**Comment by nyngwang** [comment]
> If it might affect a large number of people then that makes it a higher priority.

Okay.

> What do mean by simulating yank/delete?

I imagine one can `yy` on the file he/she wants to copy. So just move the cursor to the correct position and then `p`. Same argument for `dd`.

**Comment by cseickel** [comment]
I just pushed this to **main**, add this option to disable the popup inputs:

```lua
      require("neo-tree").setup({
        use_popups_for_input = false, -- If false, inputs will use vim.ui.input() instead of custom floats.
      })
```

**Comment by nyngwang** [comment]
@cseickel: Insane! Really appreciate this option!!
