### ISSUE TITLE
BUG: How do I display relative line numbers?

### ISSUE THREAD

**Issue by whxcode** [nvim-neo-tree/neo-tree.nvim#1140]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.10.0-dev-664+g0ce391086

### Operating System / Version

13.1 (22C65)

### Describe the Bug

When the plug-in is opened; You want to display relative line numbers.

### Screenshots, Traceback

<img width="394" alt="image" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/44012914/b1dcc19a-55e5-44d5-a5f9-3884781a1b22">

### Steps to Reproduce

Open nvim
cmd: Neotree filesystem left reveal dir=./

### Expected Behavior

When the plug-in is opened; You want to display relative line numbers.

### Your Configuration

```Lua
local tree =  {

	-----------------------------------------------------------------------------
	'nvim-neo-tree/neo-tree.nvim',
	dependencies = {
		'MunifTanjim/nui.nvim',
		's1n7ax/nvim-window-picker',
	},
}
```

**Comment by cseickel** [comment]
This is not a bug, it's a how to question. Here is your answer: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/608

**Comment by whxcode** [comment]
> This is not a bug, it's a how to question. Here is your answer: #608

Works like a charm! Thank you!!!
