### ISSUE TITLE
BUG: Failure on verbose mode (`nvim -V1`) due to <afile>

### ISSUE THREAD

**Issue by wookayin** [nvim-neo-tree/neo-tree.nvim#1145]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.8.3, 0.9.2, 0.10.0-nightly

### Operating System / Version

macos 13.5

### Describe the Bug

Use `nvim -V1` (verbose mode).

Then any `WinEnter` autocommand triggered by neo-tree.nvim will hit an error upon expanding `<afile>`

```
Error detected while processing WinEnter Autocommands for "*":
E5108: Error executing lua Vim:E495: no autocommand file name to substitute for "<afile>"               
stack traceback:
        [C]: in function 'expand'
        [string ":lua"]:1: in main chunk
```

The relevant autocmd is:

```
--- Autocommands ---
NeoTreeEvent_vim_win_enter  WinEnter
    *         :lua require('neo-tree.events').fire_event('vim_win_enter', { afile = vim.fn.expand('<afile>') })
```

The error doesn't happen in nvim without the verbose flag, strange. I guess `<afile>` not being expanded might be a bug of neovim core, but it'd be good to make neo-tree not crash for already released neovim versions (0.8.x and 0.9.x).

### Screenshots, Traceback

Also: when using `fzf#run()` (just add junegunn/fzf to `&rtp`):

```
Error detected while processing function fzf#run[81]..function fzf#run[64]..<SNR>162_execute_term[3]..<SNR>162_split[20]..WinEnter Autocommands for "*":
E5108: Error executing lua Vim:E495: no autocommand file name to substitute for "<afile>"^@stack traceback:^@^I[C]: in function 'expand'^@^I[string ":lua"]:1: in main c
hunk
```
But this is not a bug of fzf, it's due to the WinEnter autocmd triggered by neo-tree.

### Steps to Reproduce

1. `nvim -V1`  (or `nvim -V1 -u repro.lu`)
2. `:Neotree`

### Expected Behavior

No error happens

### Your Configuration

[Just use the minimal init.lua](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml). I think this bug is always reproducible.

**Comment by pysan3** [comment]
We have concluded that we won't fix this in issue: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/754

This might be a new motivation to fix it, but I'm not quite familiar with debug mode so I cannot say any conclusion.

**Comment by wookayin** [comment]
This is certainly a bug (or some rare corner case), because per `:help expand()`:

>		When 'verbose' is set then expanding '%', '#' and <> items
>		will result in an error message if the argument cannot be
>		expanded.


So doing some kind of "safe expand" would suffice here:

```
vim.F.npcall(vim.fn.expand, '<afile>') or ''
```

or in a vimescript:

```
function! s:safe_expand(arg) abort
  " When verbose is set, expand("<amatch>"), etc. will throw errors.
  " See vim-patch:8.2.4740 (or neovim a9e6cf0e)
  try
    return expand(a:arg)
  catch   " E495, E496, E497, E498, E1274, etc.
    return ''
  endtry
endfunction
```

Now I've more convinced than I write this issue in September about the behavior of `vim.fn.expand` and that this is a bug, I can write a PR for this.

**Comment by pysan3** [comment]
Thanks for your detailed explanation. Reading your words, I believe we should fix this issue. 

I'd be more than happy if you could work on this since I think you're the one who's most knowledgeable in this case.
