### ISSUE TITLE
BUG: gitignored files aren't marked as such when hide_gitignored = true

### ISSUE THREAD

**Issue by andycarlberg** [nvim-neo-tree/neo-tree.nvim#1152]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.8.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@Monterey

### Operating System / Version

macOS 13.5

### Describe the Bug

I'm not sure if this is a bug or just I haven't figured out how to configure the plugin correctly. With filtered_items not visible (`filesystem.filtered_items.visible = false`) and gitignored items shown (`filesystem.filtered_items.hide_gitignored = false`), I expect to be able to see the gitignored items and that they would be formatted to match their status (by default, grayed out and an appropriate icon to the right).

The actual behavior with these settings is that the gitignored items are visible but they appear as normal files - the same text color as other files and no icon indicating that they are ignored.

### Screenshots, Traceback

With opts:
```
filesystem = {
  filtered_items = {
    visible = false,
    hide_dotfiles = true,
    hide_gitignored = false,
  },
},
```
<img width="294" alt="image" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/7405933/0aa86b59-846f-43bc-adb1-abb5fd87124c">

With opts:
```
filesystem = {
  filtered_items = {
    visible = true,
    hide_dotfiles = true,
    hide_gitignored = true,
  },
},
```
<img width="304" alt="image" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/7405933/4263a22a-52d6-4f25-8bb8-6f1d67c00dc1">

### Steps to Reproduce

Configure neo-tree to hide dotfiles and show gitignored files. The visible setting should be set to false.

### Expected Behavior

- Dotfiles are not visible and neo-tree shows that there are X files not visible (if there are dotfiles in the directory).
- The gitignored files and directories are visible and marked as ignored with text formatting and an appropriate icon.

### Your Configuration

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	{
		"nvim-neo-tree/neo-tree.nvim",
		branch = "v3.x",
		dependencies = {
			"nvim-lua/plenary.nvim",
			"nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
			"MunifTanjim/nui.nvim",
		},
		opts = {
			sources = { "filesystem", "buffers", "git_status", "document_symbols" },
			filesystem = {
				filtered_items = {
					visible = false,
					hide_dotfiles = true,
					hide_gitignored = false,
				},
			},
			default_component_configs = {
				name = {
					use_git_status_colors = true,
					highlight = "NeoTreeFileName",
				},
				git_status = {
					symbols = {
						-- Change type
						added = "",
						modified = "",
						deleted = "✖",
						renamed = "󰁕",
						-- Status type
						untracked = "",
						ignored = "",
						unstaged = "󰄱",
						staged = "",
						conflict = "",
					},
				},
			},
		},
	},
})
```

**Comment by cseickel** [comment]
What you actually want is this:
```
filesystem = {
  filtered_items = {
    visible = true,
    hide_dotfiles = true,
    hide_gitignored = true,
  },
},
```

**Comment by andycarlberg** [comment]
Sorry, there was a typo in my shortened config. The `visible` value is meant to be set to `true`, not `visible`. I will update the issue description.

The config you suggest is the second screenshot where the dotfiles are shown - behavior I do not want.

**Comment by cseickel** [comment]
It's not really meant to work that way. You either show all hidden files or hide them all. There are the "never show" options, but then you would not be able to use the hidden toggle to show them unless you write a custom command to toggle that setting for you.

```
filesystem = {
  filtered_items = {
    visible = true,
    hide_dotfiles = true,
    hide_gitignored = true,
    never_show = { -- uses exact filenames
       ".git"
    }
    never_show_by_pattern = { -- uses glob style patterns
      ".*",
    },
},

```

**Comment by andycarlberg** [comment]
Alright, that's fair.

It still seems a little odd to me that turning off `hide_gitignored` also
turns off the icon and colorscheme for ignored files. Is that correct
behavior?

**Comment by cseickel** [comment]
> It still seems a little odd to me that turning off `hide_gitignored` also turns off the icon and colorscheme for ignored files. Is that correct behavior?

Yes. 

It doesn't have it's own color scheme as it is just a "hidden" file. I can see how still showing the icon without it being hidden would make sense. We don't have that option because your particular variation of desired behavior has not come up before. We have just used this visibility setting as the controlling input for whether to do git ignored checks at all, which are relatively expensive to do. Up until now, the only people that did not want to hide git ignored files are the ones that had such big repos that even doing the checks was too slow.

So, it's not a bug, it's an intentional design decision.  

I think that it is probably just too uncommon of a desire to be worth adding any more complexity to the project. If you want this behavior enough to create the PR though, I may accept it.

**Comment by MunifTanjim** [comment]
Did this behavior changed recently?

I have this config for as long as I can remember...

https://github.com/MunifTanjim/dotfiles/blob/4030c2377b60c065f826b67b8a41184128fac9c0/private_dot_config/nvim/lua/plugins/ui/neo-tree.lua#L107-L111

https://github.com/MunifTanjim/dotfiles/blob/4030c2377b60c065f826b67b8a41184128fac9c0/private_dot_config/nvim/lua/plugins/ui/neo-tree.lua#L149-L158

Previouslyw when I ran `toggle_dotfiles` or `toggle_gitignored`, those files would show up in the tree as grayed out lines.

But recently they are showing up as colored lines. 🤔

**Comment by cseickel** [comment]
> Did this behavior changed recently?

Not _recently_, but it may have been different at some point in the past. Has it been a long time since you upgraded?

**Comment by MunifTanjim** [comment]
> Has it been a long time since you upgraded?

Yeah...

One of my machine has a4660ea5 with the previous behavior (grayed out lines). Another machine has the latest head with the new behavior (colored lines).

**Comment by cseickel** [comment]
It looks like it was changed (by me) on Aug 30 in this PR: https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1127/files#diff-9efe3fdfb62283f6d74a061ad9bb09fe5f40394d60fbe656b84cb430e906ad89

For you @MunifTanjim, I can change this. Let me take a look...
