### ISSUE TITLE
BUG: attempt to concatenate local 'cwd' (a nil value)

### ISSUE THREAD

**Issue by Serranya** [nvim-neo-tree/neo-tree.nvim#1157]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.9.2

### Operating System / Version

Windows 10 Pro 22H2

### Describe the Bug

I get the following error when trying to open neotree the second time in the same directory.

```
E5108: Error executing lua: ...im-data/lazy/neo-tree.nvim/lua/neo-tree/command/init.lua:219: attempt to concatenate local 'cwd' (a nil value)
stack traceback:
	...im-data/lazy/neo-tree.nvim/lua/neo-tree/command/init.lua:219: in function 'handle_reveal'
	...im-data/lazy/neo-tree.nvim/lua/neo-tree/command/init.lua:156: in function 'execute'
	...ers\peter.lamby\AppData\Local\nvim/lua/serra/neotree.lua:29: in function <...ers\peter.lamby\AppData\Local\nvim/lua/serra/neotree.lua:28>
```

Of note:
While `:Neotree current show reveal` fails the second time `:Neotree current show` works just fine.

### Steps to Reproduce

1. Start nvim
2. `:cd ~\dev\inner\de.serra.parent`
3. <leader>e and open a file in the current directory
4. `:vs`
5. <C-w><Right>
6. <leader>e to open another file. (The error occurs here before neotree shows in the buffer)

### Expected Behavior

When opening neotree for the second time it should succeed.

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {
    { "<Leader>e", "<Cmd>Neotree current show reveal<CR>" }, -- change or remove this line if relevant.
  },
  opts = {
    -- Your config here
    -- ...
  },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by chenzhiyuan-dm** [comment]
I encountered the same issue (on Windows 10), and upon inspecting the code in `neo-tree/command/init.lua`, I discovered that in the `handle_reveal` method, `args.reveal_file` uses '/' as the separator, whereas `state.path` uses '\\'. This discrepancy causes `utils.is_subpath` and related path comparison methods to fail. This should be considered a bug. If you're looking to make it work just in your own development environment, you can insert the following line at the beginning of the handle_reveal method: ```args.reveal_file = args.reveal_file:gsub("/", "\\\\")```. However, this isn't the best solution, and I look forward to the author's fix.

**Comment by sRavioli** [comment]
another solution that i found for revealing the current file is the following:

```lua
    {
      "<leader>e",
      "<cmd>Neotree action=focus source=filesystem position=left reveal_file="
        .. vim.fn.expand "%:p"
        .. "<CR>",
      desc = "  Focus Neotree",
    },
```

this is one of the lazy keymaps i have for Neo-Tree.

This does not require you to change the plugin files.

**Comment by sRavioli** [comment]
another solution that i found for revealing the current file is the following:

```lua
    {
      "<leader>e",
      function()
        vim.cmd(
          "Neotree action=focus source=filesystem position=left reveal_file="
            .. vim.fn.expand "%:p"
        )
      end,
      desc = "  Focus Neotree (current file)",
    },
```

this is one of the lazy keymaps i have for Neo-Tree.

This does not require you to change the plugin files.

**Comment by jkeepr** [comment]
As an addition to @sRavioli 's answer. I have something similar. Keep in mind, that this might crash in case your path includes whitespaces.

Also, it might be a good idea to add an extra condition to check if the path your trying to focus does not exists/ is blank (unwritten buffers).

```
function ()
      local p = vim.fn.expand('%:p') -- or :gsub("/", "\\")
      if (not require('neo-tree.utils').truthy(p)) then
        return
      end
      vim.cmd("Neotree action=focus source=filesystem reveal_file=" .. p)
end
```

Looking forward to a permanent fix :)

**Comment by sRavioli** [comment]
further expanding on @jkeepr suggestion, one could use `vim.fn.filereadable()`:

```lua
function()
  local p = vim.fn.expand "%:p"
  if vim.fn.filereadable(p) == 1 then
    vim.cmd(
      "Neotree action=focus source=filesystem position=left reveal_file=" .. p
    )
  end
end,
```

calling my `reveal_file` inside inside the neotree context does not result in an error.

i did not test it for filenames/paths that contain whitespace though.

**Comment by s-cerevisiae** [comment]
Above workarounds won't work if the current buffer *is opened with* Neo-tree: the path would be separated with `/`.

I think the only sane way to fix this is to `vim.fs.normalize` all the paths and use `/` as separator everywhere.

**Comment by bwpge** [comment]
If you are still having this issue, I believe possibly the PR mentioned above could fix it. There were a couple things fixed with Windows paths in the last few merges to `main`.

**Comment by qawdees** [comment]
@bwpge appears to be fixed. I was able to remove the workaround and everything seems to work as expected. Thanks for solving the issue 👍
