### ISSUE TITLE
FEATURE: Add copy Relative/Absolute path like nvim.tree

### ISSUE THREAD

**Issue by hungvx-dev** [nvim-neo-tree/neo-tree.nvim#1163]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

create a mapping to `Copy Relative/Absolute Path`

### Describe the solution you'd like.

example from nvim.tree
![Uploading image.png…]()

**Comment by pysan3** [comment]
https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/370

This might help you :)

**Comment by Crispy13** [comment]
Any update?
