### ISSUE TITLE
FEATURE: Add some additional movement commands

### ISSUE THREAD

**Issue by kmoschcau** [nvim-neo-tree/neo-tree.nvim#1165]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

In some constellations of opened child nodes it is somewhat hard to get to the nodes I want to quickly. For example I'd like to go to the first or last child of an opened node or skip an opened node entirely.

### Describe the solution you'd like.

Add commands for the following:
- next/previous sibling (skips child nodes)
- first/last sibling (jumps to the first or last sibling on the same nesting level)

**Comment by dannywrayuk** [comment]
I'd also like to see this. Though, I think it might be possible using a custom command. I'll reply if I figure it out.

**Comment by miki725** [comment]
Another one I found missing from nvim-tree was to go to the parent node. I have something like:

```lua
parent = function(state)
    local node = state.tree:get_node()
    local parent_path, _ = utils.split_path(node:get_id())
    renderer.focus_node(state, parent_path)
end,
```

**Comment by dannywrayuk** [comment]
I've been using this: 

```lua
local goToParent = function(state)
    local node = state.tree:get_node()
    renderer.focus_node(state, node:get_parent_id())
end

local goToParentAndClose = function(state)
    goToParent(state)
    local node = state.tree:get_node()
    if node:is_expanded() then
        fsc.toggle_node(state)
    end
end
```

**Comment by pysan3** [comment]
I think your snippets are worth a PR ;)

If you have any interests, take a look at https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/lua/neo-tree/sources/common/commands.lua and https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/lua/neo-tree/sources/filesystem/commands.lua.

**Comment by kmoschcau** [comment]
Since we already have this discussion going and I didn't want to create a new issue just for this: Is there a way to get the open commands to NOT automatically expand nested files and instead just open the top level file?

**Comment by pysan3** [comment]
> instead just open the top level file?

Do you mean folder?

**Comment by kmoschcau** [comment]
I mean to have one command that does the following:

1. when run on a closed folder/directory -> expands it
2. when run on a file with other files nested under it -> opens the file without expanding it
3. when run on any other file -> opens the file

Number 2 is not possible right now as far as I know, because the built-in open command will always first expand files with nesting and then open it when you run it again on the same file.

**Comment by pysan3** [comment]
Ok, got it.

Well unfortunately it is now hardcoded to expand the file if it is not expanded so I think you'll need a new feature request for that.
