### ISSUE TITLE
BUG:  Fuzzy Finder not returning hidden files using `find` when filtered_items.visible = true

### ISSUE THREAD

**Issue by anthonymq** [nvim-neo-tree/neo-tree.nvim#1168]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.9.2

### Operating System / Version

MacOS 13.6

### Describe the Bug

When setting filtered items visibility, the fuzzy finder doesn't work anymore. Not returning anything.
``` 
filtered_items = {
                            visible = true,
                            hide_dotfiles = false,
                        --     hide_gitignored = false,
                        },
```

### Screenshots, Traceback

![Capture d’écran 2023-09-29 à 13 22 26](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/1382637/88155f9d-e889-4885-9621-c65b2beb3368)

### Steps to Reproduce

1. Set : ``` filesystem = {
                        filtered_items = {
                            visible = true,
                            hide_dotfiles = false,
                        --     hide_gitignored = false,
                        },```
2. ```/searchforcwdfile```  

### Expected Behavior

The second step should return the files matching the search in the tree.

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {
    { "<Leader>e", "<Cmd>Neotree<CR>" }, -- change or remove this line if relevant.
  },
    opts = {
        -- Your config here
        -- ...
        filesystem = {
            filtered_items = {
                visible = true,
                hide_dotfiles = false,
                --     hide_gitignored = false,
            },
        },
    },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by cseickel** [comment]
If it works when visible items are false but not when true, It could be that there are just too many files in the search results.

Make sure you have `fd` installed, try it in a smaller directory without things like `node_modules` or large git repos, and check the logs for errors: https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Troubleshooting#logs

**Comment by anthonymq** [comment]
Thanks for the quick response.
The directory where I made the test was very small (my .conf/nvim dir).

But while checking the logs I can narrow the issue. The issue seems to be that this is not a git repository. See logs :
```
[TRACE Ven 29 sep 16:00:27 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  filesystem.vim_buffer_enter  for vim_buffer_enter called successfully.
[TRACE Ven 29 sep 16:00:27 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  buffers.vim_buffer_enter  for vim_buffer_enter called successfully.
[TRACE Ven 29 sep 16:00:27 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:181: reset_search
[TRACE Ven 29 sep 16:00:27 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:174: navigate nil nil nil
[TRACE Ven 29 sep 16:00:27 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:112: navigate_internal left nil nil
[DEBUG Ven 29 sep 16:00:27 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:120: navigate_internal: path is nil, using cwd
[TRACE Ven 29 sep 16:00:27 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:151: navigate_internal: position saved
[DEBUG Ven 29 sep 16:00:27 2023] ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:610: Not unwatching folders... use_libuv_file_watcher is  false  and state.tree is  true
[TRACE Ven 29 sep 16:00:27 2023] ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:269: async_scan:  /Users/antmarqu3/.config/nvim
[TRACE Ven 29 sep 16:00:27 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/git/ignored.lua:45: ================================================================================
[TRACE Ven 29 sep 16:00:27 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/git/ignored.lua:46: IGNORED: mark_ignore BEGIN...
[TRACE Ven 29 sep 16:00:27 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/git/ignored.lua:138: IGNORED: Running async git with args:  { "-C", "/Users/antmarqu3/.config/nvim", "check-ignore", "--stdin" }
[TRACE Ven 29 sep 16:00:27 2023] ...share/nvim/lazy/neo-tree.nvim/lua/neo-tree/git/utils.lua:20: GIT ROOT ERROR  { "fatal: not a git repository (or any of the parent directories): .git" }
[TRACE Ven 29 sep 16:00:27 2023] ...hare/nvim/lazy/neo-tree.nvim/lua/neo-tree/git/status.lua:211: status_async: not a git folder:  /Users/antmarqu3/.config/nvim
[DEBUG Ven 29 sep 16:00:27 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/git/ignored.lua:143: Failed to load ignored files for /Users/antmarqu3/.config/nvim : { "fatal: not a git repository (or any of the parent directories): .git" }
[TRACE Ven 29 sep 16:00:27 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/git/ignored.lua:68: IGNORED: Checking types of -0 items to see which ones are directories
[TRACE Ven 29 sep 16:00:27 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/git/ignored.lua:88: IGNORED: Comparing results to mark items as ignored: false
[TRACE Ven 29 sep 16:00:27 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/git/ignored.lua:100: IGNORED: mark_ignored is complete, ignored: -0 , not ignored: 7
[TRACE Ven 29 sep 16:00:27 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/git/ignored.lua:101: ================================================================================
[TRACE Ven 29 sep 16:00:27 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  before_render  with args:  {
  _ready = false,
  async_directory_scan = "auto",
  bind_to_cwd = true,
  bufnr = 5,
  check_gitignore_in_search = true,
  commands = {
    add = <function 1>,
    add_directory = <function 2>,
    cancel = <function 3>,
    clear_filter = <function 4>,
    close_all_nodes = <function 5>,
    clo...
[TRACE Ven 29 sep 16:00:27 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  buffers.before_render  for before_render called successfully.
[TRACE Ven 29 sep 16:00:27 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1159: Force open folders
[DEBUG Ven 29 sep 16:00:27 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:769: Tree already exists and buffer is valid, skipping creation filesystem 1
[DEBUG Ven 29 sep 16:00:27 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:757: Setting expanded nodes
[TRACE Ven 29 sep 16:00:27 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  14  actual width:  37
[TRACE Ven 29 sep 16:00:27 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  3  actual width:  35
[TRACE Ven 29 sep 16:00:27 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  10  actual width:  35
[TRACE Ven 29 sep 16:00:27 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  8  actual width:  35
[TRACE Ven 29 sep 16:00:27 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  14  actual width:  35
```

There is no problem in a git repository directory.

**Comment by cseickel** [comment]
That log snippet is from **after** you've cancelled out of the search, you can tell because the third line says `reset_search`. Also, it's not a problem that the git ignored lookup failed, which is why it is simply a DEBUG level event.

It is interesting that it works in a git directory but not your config, but it could also be coincidence. I know it does not make a difference for me. Can you try again and capture more of the log that includes the search actions?

You could also try a different directory as a test, maybe even one that you create just for the purpose of testing. I can see there being some particular file or directory that is crashing the search because of a special character or permissions issue.

**Comment by anthonymq** [comment]
[TRACE Lun  2 oct 10:46:48 2023] ...tree.nvim/lua/neo-tree/sources/filesystem/lib/filter.lua:103: No search or pre-search folders, recording pre-search folders now
[TRACE Lun  2 oct 10:46:48 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_enter  with args:  {
  afile = "neo-tree filesystem [1]"
}
[TRACE Lun  2 oct 10:46:48 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  neo-tree-win-enter  for vim_win_enter called successfully.
[TRACE Lun  2 oct 10:46:48 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  vim_buffer_enter  with args:  {
  afile = ""
}
[TRACE Lun  2 oct 10:46:48 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  neo_tree_popup_buffer_enter  with args:  nil
[TRACE Lun  2 oct 10:46:48 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_buffer_enter",
  handler = <function 1>
}  for vim_buffer_enter called successfully.
[TRACE Lun  2 oct 10:46:48 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  filesystem.vim_buffer_enter  for vim_buffer_enter called successfully.
[TRACE Lun  2 oct 10:46:48 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  buffers.vim_buffer_enter  for vim_buffer_enter called successfully.
[TRACE Lun  2 oct 10:46:48 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  vim_buffer_modified_set  with args:  {
  afile = ""
}
[TRACE Lun  2 oct 10:46:48 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:67: Seed for vim_buffer_modified_set returned: table: 0x0101bd6480
[TRACE Lun  2 oct 10:46:48 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:685: Redrawing tree filesystem 1
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  14  actual width:  37
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  3  actual width:  35
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  6  actual width:  33
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  8  actual width:  31
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  9  actual width:  31
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  7  actual width:  31
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  7  actual width:  33
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  14  actual width:  31
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  9  actual width:  31
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  20  actual width:  31
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  8  actual width:  31
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  7  actual width:  31
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  11  actual width:  31
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  13  actual width:  31
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  16  actual width:  31
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  12  actual width:  31
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  10  actual width:  35
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  8  actual width:  35
[TRACE Lun  2 oct 10:46:48 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  14  actual width:  35
[TRACE Lun  2 oct 10:46:48 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:691:   Redrawing tree done filesystem 1
[TRACE Lun  2 oct 10:46:48 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  filesystem.vim_buffer_modified_set  for vim_buffer_modified_set called successfully.
[TRACE Lun  2 oct 10:46:48 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  buffers.vim_buffer_modified_set  for vim_buffer_modified_set called successfully.
[TRACE Lun  2 oct 10:46:48 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  git_status.vim_buffer_modified_set  for vim_buffer_modified_set called successfully.
[TRACE Lun  2 oct 10:46:49 2023] ...tree.nvim/lua/neo-tree/sources/filesystem/lib/filter.lua:161: Setting search in on_change to: l
[TRACE Lun  2 oct 10:46:49 2023] ...tree.nvim/lua/neo-tree/sources/filesystem/lib/filter.lua:161: Setting search in on_change to: la
[TRACE Lun  2 oct 10:46:49 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:112: navigate_internal left nil nil
[DEBUG Lun  2 oct 10:46:49 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:120: navigate_internal: path is nil, using cwd
[TRACE Lun  2 oct 10:46:49 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:151: navigate_internal: position saved
[DEBUG Lun  2 oct 10:46:49 2023] ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:610: Not unwatching folders... use_libuv_file_watcher is  false  and state.tree is  true
[INFO  Lun  2 oct 10:46:49 2023] ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:109: No items, skipping git ignored/status lookups
[TRACE Lun  2 oct 10:46:49 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  before_render  with args:  {
  _ready = true,
  async_directory_scan = "auto",
  bind_to_cwd = true,
  bufnr = 5,
  check_gitignore_in_search = true,
  commands = {
    add = <function 1>,
    add_directory = <function 2>,
    cancel = <function 3>,
    clear_filter = <function 4>,
    close_all_nodes = <function 5>,
    clos...
[TRACE Lun  2 oct 10:46:49 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  buffers.before_render  for before_render called successfully.
[TRACE Lun  2 oct 10:46:49 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1162: Preserving expanded nodes
[DEBUG Lun  2 oct 10:46:49 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:769: Tree already exists and buffer is valid, skipping creation filesystem 1
[DEBUG Lun  2 oct 10:46:49 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:757: Setting expanded nodes
[TRACE Lun  2 oct 10:46:49 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  14  actual width:  24
[DEBUG Lun  2 oct 10:46:49 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:668: Restoring position to node_id: /Users/antmarqu3/.config/nvim/lazy-lock.json
[DEBUG Lun  2 oct 10:46:49 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:484: focus_node cannot find node with id  /Users/antmarqu3/.config/nvim/lazy-lock.json
[TRACE Lun  2 oct 10:46:49 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  after_render  with args:  {
  _ready = true,
  async_directory_scan = "auto",
  bind_to_cwd = true,
  bufnr = 5,
  check_gitignore_in_search = true,
  commands = {
    add = <function 1>,
    add_directory = <function 2>,
    cancel = <function 3>,
    clear_filter = <function 4>,
    close_all_nodes = <function 5>,
    clos...
[TRACE Lun  2 oct 10:46:49 2023] ...tree.nvim/lua/neo-tree/sources/filesystem/lib/filter.lua:161: Setting search in on_change to: laz
[TRACE Lun  2 oct 10:46:50 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:112: navigate_internal left nil nil
[DEBUG Lun  2 oct 10:46:50 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:120: navigate_internal: path is nil, using cwd
[TRACE Lun  2 oct 10:46:50 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:151: navigate_internal: position saved
[DEBUG Lun  2 oct 10:46:50 2023] ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:610: Not unwatching folders... use_libuv_file_watcher is  false  and state.tree is  true
[INFO  Lun  2 oct 10:46:50 2023] ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:109: No items, skipping git ignored/status lookups
[TRACE Lun  2 oct 10:46:50 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  before_render  with args:  {
  _ready = true,
  async_directory_scan = "auto",
  bind_to_cwd = true,
  bufnr = 5,
  check_gitignore_in_search = true,
  commands = {
    add = <function 1>,
    add_directory = <function 2>,
    cancel = <function 3>,
    clear_filter = <function 4>,
    close_all_nodes = <function 5>,
    clos...
[TRACE Lun  2 oct 10:46:50 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  buffers.before_render  for before_render called successfully.
[TRACE Lun  2 oct 10:46:50 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1162: Preserving expanded nodes
[DEBUG Lun  2 oct 10:46:50 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:769: Tree already exists and buffer is valid, skipping creation filesystem 1
[DEBUG Lun  2 oct 10:46:50 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:757: Setting expanded nodes
[TRACE Lun  2 oct 10:46:50 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  14  actual width:  23
[DEBUG Lun  2 oct 10:46:50 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:668: Restoring position to node_id: /Users/antmarqu3/.config/nvim
[TRACE Lun  2 oct 10:46:50 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  after_render  with args:  {
  _ready = true,
  async_directory_scan = "auto",
  bind_to_cwd = true,
  bufnr = 5,
  check_gitignore_in_search = true,
  commands = {
    add = <function 1>,
    add_directory = <function 2>,
    cancel = <function 3>,
    clear_filter = <function 4>,
    close_all_nodes = <function 5>,
    clos...
[TRACE Lun  2 oct 10:46:50 2023] ...tree.nvim/lua/neo-tree/sources/filesystem/lib/filter.lua:161: Setting search in on_change to: lazy
[TRACE Lun  2 oct 10:46:50 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:112: navigate_internal left nil nil
[DEBUG Lun  2 oct 10:46:50 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:120: navigate_internal: path is nil, using cwd
[TRACE Lun  2 oct 10:46:50 2023] ...y/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:151: navigate_internal: position saved
[DEBUG Lun  2 oct 10:46:50 2023] ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:610: Not unwatching folders... use_libuv_file_watcher is  false  and state.tree is  true
[INFO  Lun  2 oct 10:46:50 2023] ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:109: No items, skipping git ignored/status lookups
[TRACE Lun  2 oct 10:46:50 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  before_render  with args:  {
  _ready = true,
  async_directory_scan = "auto",
  bind_to_cwd = true,
  bufnr = 5,
  check_gitignore_in_search = true,
  commands = {
    add = <function 1>,
    add_directory = <function 2>,
    cancel = <function 3>,
    clear_filter = <function 4>,
    close_all_nodes = <function 5>,
    clos...
[TRACE Lun  2 oct 10:46:50 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  buffers.before_render  for before_render called successfully.
[TRACE Lun  2 oct 10:46:50 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1162: Preserving expanded nodes
[DEBUG Lun  2 oct 10:46:50 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:769: Tree already exists and buffer is valid, skipping creation filesystem 1
[DEBUG Lun  2 oct 10:46:50 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:757: Setting expanded nodes
[TRACE Lun  2 oct 10:46:50 2023] .../neo-tree.nvim/lua/neo-tree/sources/common/container.lua:309: wanted width:  14  actual width:  22
[DEBUG Lun  2 oct 10:46:50 2023] ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:668: Restoring position to node_id: /Users/antmarqu3/.config/nvim
[TRACE Lun  2 oct 10:46:50 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  after_render  with args:  {
  _ready = true,
  async_directory_scan = "auto",
  bind_to_cwd = true,
  bufnr = 5,
  check_gitignore_in_search = true,
  commands = {
    add = <function 1>,
    add_directory = <function 2>,
    cancel = <function 3>,
    clear_filter = <function 4>,
    close_all_nodes = <function 5>,
    clos...
[TRACE Lun  2 oct 10:46:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_closed  with args:  {
  afile = "1200"
}
[DEBUG Lun  2 oct 10:46:57 2023] ...hare/nvim/lazy/neo-tree.nvim/lua/neo-tree/setup/init.lua:728: VIM_WIN_CLOSED: disposing state for window 1200
[TRACE Lun  2 oct 10:46:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_win_closed",
  handler = <function 1>
}  for vim_win_closed called successfully.
[TRACE Lun  2 oct 10:46:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_closed  with args:  {
  afile = "1201"
}
[DEBUG Lun  2 oct 10:46:57 2023] ...hare/nvim/lazy/neo-tree.nvim/lua/neo-tree/setup/init.lua:728: VIM_WIN_CLOSED: disposing state for window 1201
[TRACE Lun  2 oct 10:46:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_win_closed",
  handler = <function 1>
}  for vim_win_closed called successfully.
[TRACE Lun  2 oct 10:46:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:97: Firing event:  vim_win_closed  with args:  {
  afile = "1202"
}
[DEBUG Lun  2 oct 10:46:57 2023] ...hare/nvim/lazy/neo-tree.nvim/lua/neo-tree/setup/init.lua:728: VIM_WIN_CLOSED: disposing state for window 1202
[TRACE Lun  2 oct 10:46:57 2023] ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/events/queue.lua:81: Handler  {
  event = "vim_win_closed",
  handler = <function 1>
}  for vim_win_closed called successfully.

**Comment by anthonymq** [comment]
I can also add that the current working dir is `~/.config/nvim`.

**Comment by cseickel** [comment]
I see from the logs that there is no error at all, you are just getting back zero search results. The problem will be with the search utility on your computer or the settings you have applied. I'm guessing it has to do with the fact that you are searching within a hidden folder.

It will use `fd` if available, then fallback to `fdfind` and then `find`. Can you tell me which if these are installed, and what the version is?

**Comment by cseickel** [comment]
Sorry I forgot to follow up. My guess is that there is just a problem with how the find command is built in this situation. It could be that the syntax is wrong for your particular version. 

I don't have a lot of time to debug this. Would you mind trying to install `fd` and seeing if it works better? If `fd` is installed then neo-tree will use that instead.

**Comment by mPyKen** [comment]
Without having investigated too much into this, I can confirm it works on my end after installing `fd`. I am mostly using the default settings. With `find (GNU findutils) 4.9.0`, I was unable to get hidden files even if they were toggled on with `["H"] = "toggle_hidden"`.

**Comment by viz404** [comment]
I might be too late and I don't see this anywhere, how can I ignore a specific directory while doing fuzzy_find I don't want to search in the node_modules.
