### ISSUE TITLE
Disable winbar when opening neo-tree by command

### ISSUE THREAD

**Issue by serhez** [nvim-neo-tree/neo-tree.nvim#1170]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

At the moment, the source selector being enabled/disabled is a global option that applied to all windows/commands.

### Describe the solution you'd like.

It would be great to have the option of disabling the winbar source selector (and perhaps also the statusline, for consistency, or simply the source selector alltogether) when calling the neo-tree command. E.g.: `Neotree source=document_symbols position=right winbar=false`. This would allow having different usages for neo-tree, e.g., having a command to open the file tree + git tree on the left position with the source selector enabled, as well as having another command to open the document symbols of the left position with the source selector disabled.

**Comment by pysan3** [comment]
Related: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/895
