### ISSUE TITLE
FEATURE: Allow short msg when 'use_popups_for_input = false' #1167

### ISSUE THREAD

**Issue by jonahfang** [nvim-neo-tree/neo-tree.nvim#1172]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

The msg before new filename is too long:

<img width="892" alt="image" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/16301509/5b8ef5fc-ed86-4b74-9ebc-7d23d1c149cb">

### Describe the solution you'd like.

Provide option to setup short msg content.

**Comment by pysan3** [comment]
What do you think would be a good message? @jonahfang

**Comment by jonahfang** [comment]
I like the NERDTree ui:

<img width="620" alt="image" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/16301509/fff5b88f-60a9-44e1-b201-9e4a24c91958">
