### ISSUE TITLE
BUG: Open file in the first always open vsplit

### ISSUE THREAD

**Issue by sownteedev** [nvim-neo-tree/neo-tree.nvim#1175]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.10.0-dev-ac1c234

### Operating System / Version

Arch Linux

### Describe the Bug

When I first open a file, it always opens vsplit.

### Screenshots, Traceback

https://github.com/nvim-neo-tree/neo-tree.nvim/assets/90148193/e7b1dd93-3a1f-40c0-876d-82c9ec48c4f4

### Steps to Reproduce

1. Open Neovim
2. Open Neotree
3. Open a file

### Expected Behavior

Dont open with vsplit

### Your Configuration

```Lua
vim.g.neo_tree_remove_legacy_commands = 1

vim.fn.sign_define("DiagnosticSignError",
	{ text = " ", texthl = "DiagnosticSignError" })
vim.fn.sign_define("DiagnosticSignWarn",
	{ text = " ", texthl = "DiagnosticSignWarn" })
vim.fn.sign_define("DiagnosticSignInfo",
	{ text = " ", texthl = "DiagnosticSignInfo" })
vim.fn.sign_define("DiagnosticSignHint",
	{ text = " ", texthl = "DiagnosticSignHint" })

require("neo-tree").setup({
	close_if_last_window = true,
	popup_border_style = "rounded",
	enable_git_status = true,
	enable_diagnostics = true,
	open_files_do_not_replace_types = { "terminal", "trouble", "qf" },
	sort_case_insensitive = false,
	default_component_configs = {
		container = { enable_character_fade = true },
		indent = {
			indent_size = 2,
			padding = 1,
			with_markers = false,
			indent_marker = "│",
			last_indent_marker = "└",
			highlight = "NeoTreeIndent",
			with_expanders = true,
			expander_collapsed = "",
			expander_expanded = "",
			expander_highlight = "NeoTreeIndent",
		},
		icon = {
			folder_closed = "",
			folder_open = "",
			folder_empty = "",
		},
		modified = {
			symbol = "●",
			highlight = "NeoTreeModified",
		},
		git_status = {
			symbols = {
				added = "",
				modified = "",
				deleted = "",
				renamed = "",
				untracked = "",
				ignored = "",
				unstaged = "",
				staged = "",
				conflict = "",
			},
		},
	},
	commands = {},
	window = {
		position = "left",
		width = 33,
		mappings = {
			["o"] = "open",
			["<c-x>"] = "open_split",
			["<c-v>"] = "open_vsplit",
		},
	},
	filesystem = {
		filtered_items = {
			visible = false,
			hide_dotfiles = false,
			hide_gitignored = false,
			never_show = { ".git" },
		},
		follow_current_file = { enabled = true },
		use_libuv_file_watcher = true,
		components = {
			name = function(config, node, state)
				local cc = require("neo-tree.sources.common.components")
				local result = cc.name(config, node, state)
				if node:get_depth() == 1 then
					result.text = string.gsub(state.path, "(.*[/\\])(.*)", "%2")
				end
				return result
			end,
		},
	},
	source_selector = {
		winbar = false,
		sources = {
			{ source = "filesystem", display_name = "  Files " },
			{ source = "buffers", display_name = "  Bufs " },
			{ source = "git_status", display_name = "  Git " },
		},
	},
	event_handlers = {
		-- {
		-- 	event = "file_opened",
		-- 	handler = function()
		-- 		vim.cmd("wincmd |")
		-- 	end,
		-- },
	},
})
```

**Comment by sownteedev** [comment]
Solved!

**Comment by bew** [comment]
> Solved!

how?

**Comment by sownteedev** [comment]
> > Solved!
> 
> how?

Remove line `open_files_do_not_replace_types = { "terminal", "trouble", "qf" },`

**Comment by erlonbie** [comment]
I was facing the same issue and just came to the same fix as you dit, but, I would not consider this problem as finished. This is a bug that happens in any type of file that I open. Removing the line ou commenting won't fix for other people.

**Comment by cseickel** [comment]
The problem here seems to be that you have a configuration problem or a misbehaving plugin that is setting the buffer or file type of the empty buffer incorrectly. That's the only explanation for why removing the type check would have any effect on a buffer that should not match any of the listed types.

To test it you can try these two commands when focused on the empty buffer:
```
:echo &buftype
```

and
```
:echo &ft
```

The results of both commands should be empty. If you get anything else then you have a problem elsewhere.

**Comment by sownteedev** [comment]
> I was facing the same issue and just came to the same fix as you dit, but, I would not consider this problem as finished. This is a bug that happens in any type of file that I open. Removing the line or commenting it won't fix the bug itself.

U can use my config then see that
