### ISSUE TITLE
BUG: Fix shortcut or give easy options to use a completely different set

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [nvim-neo-tree/neo-tree.nvim#1177]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

v0.10.0-dev-1327+gf79052fae

### Operating System / Version

macOs 13.5

### Describe the Bug

I honestly don't know why but why are shortcuts so edgy and literally go against:
- vim principles: enter is insanely far on the keyboard what's the point of using vim if my finger has to travel more than 2 cm when digging thru files....
- shortcuts of other tree plugs: how can you literally throw away the most important shortcut 'o' and assign it to so crazy order-by

### Steps to Reproduce

open it up

### Expected Behavior

have an option for shortcuts of popular vim plugins like:
- nerdtree
- nvim-tree

I know this might be opinionated but there is no better shortcuts than that of nerd-trees'. I've tested a lot of tree plugins...

### Your Configuration

```Lua
does not apply...
```

**Comment by cseickel** [comment]
If you don't like the shortcuts, just change them.

**Comment by ZeChArtiahSaher** [comment]
Was expecting this sort of comment. Well, it's not really something that is helpful given the amount of code duplication for shortcut definitions for... umm. window, buffer? Plus fact of the matter being any such drift is almost always a lack in cohesive user interface. I guess props on make yet another dead in 2 years tree plug then igs \_○_○_/
