### ISSUE TITLE
File Nesting a la JetBrains

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#118]
### Discussed in https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/117

<div type='discussions-op-text'>

<sup>Originally posted by **bennypowers** February  3, 2022</sup>
Jetbrains (webstorm, etc) has a feature where file entries in the tree can collapse into one another. For example, a user can configure the tree to show `*.ts` files as a subtree, with siblings matching `$1.d.ts` `$1.js` and `$1.js.map` as the subtree's children:

![example of nesting](https://resources.jetbrains.com/help/img/idea/2021.3/nesting-rules-on-off.png)

This would be a cool feature in neo-tree. I'm wondering if maintainers and contributors think this could be easily accomplished in userland?</div>

**Comment by lopi-py** [comment]
I'm trying to get it 👍 
![image](https://user-images.githubusercontent.com/70210066/156054909-7e325df2-2296-490d-9305-11ca1d40faff.png)

**Comment by nyngwang** [comment]
Waiting for this one~
