### ISSUE TITLE
BUG: Setting some window keys breaks help (?)

### ISSUE THREAD

**Issue by miki725** [nvim-neo-tree/neo-tree.nvim#1180]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.9.4

### Operating System / Version

Arch Linux

### Describe the Bug

When assigning some keys for the global window it seems to break the help command (pressing `?`). Weird that it only happens on non-filesystem sources such as git or buffers. It doesnt not happen on filesystem source. 

I was able to narrow down to these 2 keys consistently break help for me:

```lua
        opts = {
            window = {
                mappings = {
                    ["u"] = "navigate_up",
                    ["F"] = "fuzzy_finder",
                },
            },
        },
```

`u` -> `navigate_up` only breaks git status source whereas `F`->`fuzzy_finder` breaks both git status and buffers.

### Screenshots, Traceback

<img width="815" alt="image" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/932940/637f3e70-b3ff-4216-adb1-fd5e30e405af">

Exception:

```
E5108: Error executing lua: /root/.repro/plugins/nui.nvim/lua/nui/line/init.lua:22: attempt to index local 'block' (a nil value)
stack traceback:
        /root/.repro/plugins/nui.nvim/lua/nui/line/init.lua:22: in function 'append'
        ...ugins/neo-tree.nvim/lua/neo-tree/sources/common/help.lua:62: in function 'show'
        ...s/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:865: in function 'func'
        ...repro/plugins/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:843: in function <...repro/plugins/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:841>
```

### Steps to Reproduce

1. Open nvim with minimal config:

   ```sh
   ➜ nvim -u minimaltree.lua
   ```
1. Open tree with `:Neotree`
1. Open help with `?` (it should work with filesystem source)
1. Go to another source with `>`
1. Open help with `?` which 💥 

### Expected Behavior

Should see regular help popup

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    { "folke/tokyonight.nvim", lazy = false },
    {
        "nvim-neo-tree/neo-tree.nvim",
        branch = "v3.x",
        dependencies = {
            "nvim-lua/plenary.nvim",
            "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
            "MunifTanjim/nui.nvim",
        },
        cmd = { "Neotree" },
        opts = {
            window = {
                mappings = {
                    ["u"] = "navigate_up",
                    ["F"] = "fuzzy_finder",
                },
            },
        },
    },
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

**Comment by miki725** [comment]
also here is my lock file:

```
➜ cat .repro/config/nvim/lazy-lock.json
{
  "lazy.nvim": { "branch": "main", "commit": "33c447b96e1cb1a5a2be87982d5d32bb5054079d" },
  "neo-tree.nvim": { "branch": "v3.x", "commit": "6f8c49956c89e9fefae6acdfe1d57c6293b0a03d" },
  "nui.nvim": { "branch": "main", "commit": "c0c8e347ceac53030f5c1ece1c5a5b6a17a25b32" },
  "nvim-web-devicons": { "branch": "master", "commit": "a1e6268779411048a87f767a27380089362a0ce2" },
  "plenary.nvim": { "branch": "master", "commit": "50012918b2fc8357b87cff2a7f7f0446e47da174" },
  "tokyonight.nvim": { "branch": "main", "commit": "dce0ab49ae751f4f3617ab42d6f20c72369c7cb1" }
}
```

**Comment by cseickel** [comment]
The problem there is that not all commands work for all sources, and the global `window.mappings` should only contain mappings that are available in all of the sources that you use.

All search related command sonly work in the filesystem source, and the git_status source does not support anything related to changing cwd.

You should set these mappings within the `filesystem.window.mappings` section instead.

**Comment by miki725** [comment]
👍 thanks for quick response. closing as it was my bad. thanks for the explanation!

oh and thank you for the plugin!!! 🎉  I just switched today and I find it a lot more intuitive. amazing job!
