### ISSUE TITLE
BUG:  When I set vim.opt.cmdheight=0, the prompt (add new file when use_popups_for_input = false) disappears (v3.10)!

### ISSUE THREAD

**Issue by jonahfang** [nvim-neo-tree/neo-tree.nvim#1197]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.9.1

### Operating System / Version

MacOS Monterey

### Describe the Bug

After adding newline when use_popups_for_input = false by @pysan3, when I set `vim.opt.cmdheight=0` the add new file or directory prompt does not show, only one line to input the new file name or directory.

### Screenshots, Traceback

When vim.opt.cmdheight not set:

<img width="601" alt="image" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/16301509/92d34fd7-cb15-4e37-8434-9774e1b32710">

When vim.opt.cmdheight set to 0:

<img width="482" alt="image" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/16301509/32523470-7f7d-466f-9a2c-082caa63ff4f">

**Comment by pysan3** [comment]
Hmm, I usually use `nightly` so I thought that was the difference but even when I downgrade to `v0.9.1` I still cannot reproduce the issue.

Here are my screenshots.

- `vim.opt.cmdheight = 0`
![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/41065736/ece8758e-600e-4f0e-866b-03f5d729b397)

- `vim.opt.cmdheight = 1`
![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/41065736/2c4494db-bdfe-4852-9ca6-6cf1a38f3e21)

- `vim.opt.cmdheight = 2`
![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/41065736/13cb62bf-b584-45bd-8b46-3dcf846d410c)

The following code is what neo-tree is basically doing in the back. Could you execute this code in your environment?

> Open neovim
> Create a file named `test.lua`
> Copy the following code
> Run `:so` once

```lua
vim.keymap.set("n", "<Leader>r", "<Cmd>source<CR>", {})
vim.cmd("language en_US.utf8")

local opts = {
  prompt = "Question: foo bar" .. "\n",
  default = "~/",
}

vim.ui.input(opts, function(msg)
  vim.print(string.format([[msg: %s]], vim.inspect(msg)))
end)
```

- `:lua vim.opt.cmdheight = 0`
- `<Leader>r`
- See what happens
- `:lua vim.opt.cmdheight = 1`
- `<Leader>r`
- See what happens
- `:lua vim.opt.cmdheight = 2`
- `<Leader>r`
- See what happens

**Comment by pysan3** [comment]
Ok, I was able to reproduce inside neo-tree but I'm now confused that the above code does work despite both should be doing the exact same thing.

I think I'll deal this with a workaround.

**Comment by jonahfang** [comment]
It works! @pysan3 Thank you very much!
