### ISSUE TITLE
FEATURE: keep git source node open-close state 

### ISSUE THREAD

**Issue by coffebar** [nvim-neo-tree/neo-tree.nvim#1202]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

When i `git add` something from Neo-tree source `Git`, it refreshes afterward and auto open all nodes.

### Describe the solution you'd like.

I want to keep closed all nodes that I manually closed at least until I close Neo-tree.

**Comment by pysan3** [comment]
Duplicate: #717

We are aware but it's pretty difficult to solve this issue in an elegant way...
Stay tuned in the linked issue until I can get some spare time to tackle this.
