### ISSUE TITLE
feature request: disable or configure escape to close floating window

### ISSUE THREAD

**Issue by BerkeleyTrue** [nvim-neo-tree/neo-tree.nvim#123]
I find myself accidentally closing the floating window often and I find it pretty annoying. I'd like to be able to turn of this feature and just use `:q` or autclosing on open instead.

P.S. Nice work! I've just switched from Defx and what a night and day difference it makes. Not only being way more configurable than Defx, but much easier to reason about.

**Comment by cseickel** [comment]
Sure, I can make this an option. I'll probably do it this weekend.

**Comment by cseickel** [comment]
This is in **main** and will probably be relased to **v1.x** in a day or two. I also added a built-in "close_window" command:

```lua
require("neo-tree").setup({
  close_floats_on_escape_key = false,
  filesystem = {
    window = {
      mappings = {
        ["q"] = "close_window",
      },
    },
  }
})
```

**Comment by cseickel** [comment]
Sorry, I just realized I forgot to push that one! It is in main **now**.

**Comment by nyngwang** [comment]
I like this one!

**Comment by nyngwang** [comment]
@cseickel: btw is it possible to use `q` for __both__ clearing the filter and closing the window? I just feel like using two different keys to do the same thing: leaving, is not necessary.

**Comment by cseickel** [comment]
You can also replace the `close_window` command with one that takes both actions:

```lua
      require("neo-tree").setup({
        filesystem = {
          commands = {
            close_window = function (state)
              -- clear filter
              require("neo-tree.sources.filesystem").reset_search(state, true)
              -- close the current window
              require("neo-tree.ui.renderer").close(state)
            end,
          }
        }
      })
```

**Comment by BerkeleyTrue** [comment]
@cseickel you are awesome! Thanks a lot!
