### ISSUE TITLE
FEATURE: follow_current_file should support floating neotree as well

### ISSUE THREAD

**Issue by wookayin** [nvim-neo-tree/neo-tree.nvim#1246]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

Currently, following the current file in the neo-tree filesystem explorer does not work when neo-tree is positioned on a floating window. Floating neo-tree should also be support follow_current_file.

See https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/lua/neo-tree/sources/filesystem/init.lua#L39-L41

Reproduce:

- Open any file
- `:Neotree toggle float`
- this file is not followed in the neo-tree

But if it were not a floating window, e.g `:Neotree toggle left`, neo-tree will show the path of the opened file correctly.

Config:

```
neotree.setup {
  follow_current_file = {
    enabled = true,
  },
}
```

### Describe the solution you'd like.

We can consider removing the following check in https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/lua/neo-tree/sources/filesystem/init.lua#L39-L41
:

```
  if state.current_position == "float" then
    return false
  end
```

### Describe alternatives you've considered.

-

### Additional Context

-

**Comment by cseickel** [comment]
I think what you are looking for is
```
:Neotree float reveal
```

It doesn't make sense for the float to `follow_current_file` because the float should not be open long enough for it to matter.
