### ISSUE TITLE
FEATURE: Recycle bin; Accidently delete files.

### ISSUE THREAD

**Issue by abcdefg233** [nvim-neo-tree/neo-tree.nvim#1263]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

I deleted a important file accidently. and I couldn't find it in my system Recycle bin : `trash:///`.

### Describe the solution you'd like.

Move deleted file to system Recycle bin.

### Describe alternatives you've considered.

Use a unique Recycle bin for the plugin its own.

## System `Recycle bin`.
![图片](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/32760059/63c91baa-0ef5-4256-a9c9-48d76305f844)

## Trying to recovery
![图片](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/32760059/781f3805-ffb7-4408-a58c-7f6ff6bdb13a)

**Comment by miversen33** [comment]
Closing as duplicate is #202
