### ISSUE TITLE
Opening a file in Neo-tree window without jumping into it.

### ISSUE THREAD

**Issue by 6H075T2** [nvim-neo-tree/neo-tree.nvim#1266]
It gets tedious when I have many files in the same directory and needs to open them all I always jump back and forth between Neo-tree and the buffer created by Neo-tree? How do I add some option to solve this.

How do I make cursor stays on Neo-tree when I open a file with <CR>?

**Comment by miversen33** [comment]
Almost certainly related to #996

**Comment by cseickel** [comment]
> Almost certainly related to #996

I don't think so. I think OP just wants this: https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Tips#open-file-without-losing-sidebar-focus

**Comment by 6H075T2** [comment]
Thanks @cseickel for answering my question it works well now I'm really glad.
