### ISSUE TITLE
BUG: Neotree (on the left), moves to the right by pressing "<space> ["

### ISSUE THREAD

**Issue by strahinjapetrovic** [nvim-neo-tree/neo-tree.nvim#1267]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

2.1.1700008891

### Operating System / Version

Linux

### Describe the Bug

I am using which-keys and have <Space> set as a leader.

I have mapped both <Space>[ and <Space>] to move buffers left and right using :previous and :next accordingly.

When I have that enabled in which-keys configuration, Neotree (on the left), moves to the right by pressing <Space>[

### Steps to Reproduce

1. Map <Space>[ and <Space>] to move buffers left and right using :previous and :next accordingly
2. Set Neotree to left side
3. Switch focus to Neotree and press <Space>[

### Expected Behavior

It should stay at the same place

### Your Configuration

```Lua
return {
    "nvim-neo-tree/neo-tree.nvim",
    branch = "v3.x",
    -- event = "VeryLazy",
    opts = {
        disable_netrw = false,
        hijack_netrw = false,
    },
    filesystem = {
        filtered_items = {
            visible = false, -- when true, they will just be displayed differently than normal items
            hide_dotfiles = true,
            hide_gitignored = true,
            hide_hidden = true, -- only works on Windows for hidden files/directories
            hide_by_name = {
                --"node_modules"
            },
            hide_by_pattern = { -- uses glob style patterns
                --"*.meta",
                --"*/src/*/tsconfig.json",
            },
            always_show = { -- remains visible even if other settings would normally hide it
                --".gitignored",
            },
            never_show = { -- remains hidden even if visible is toggled to true, this overrides always_show
                --".DS_Store",
                --"thumbs.db"
            },
            never_show_by_pattern = { -- uses glob style patterns
                --".null-ls_*",
            },
        },
        follow_current_file = {
            enabled = false,              -- This will find and focus the file in the active buffer every time
            --               -- the current file is changed while the tree is open.
            leave_dirs_open = false,      -- `false` closes auto expanded dirs, such as with `:Neotree reveal`
        },
        group_empty_dirs = false,         -- when true, empty folders will be grouped together
        hijack_netrw_behavior = "open_default", -- netrw disabled, opening a directory opens neo-tree
        -- in whatever position is specified in window.position
        -- "open_current",  -- netrw disabled, opening a directory opens within the
        -- window like netrw would, regardless of window.position
        -- "disabled",    -- netrw left alone, neo-tree does not handle opening dirs
        use_libuv_file_watcher = false, -- This will use the OS level file watchers to detect changes
        -- instead of relying on nvim autocmd events.
    },
    window = {
        position = "left",
        width = 31,
        mapping_options = {
            noremap = true,
            nowait = true,
        },
    },

    dependencies = {
        "nvim-lua/plenary.nvim",
        "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
        "MunifTanjim/nui.nvim",
        -- "3rd/image.nvim", -- Optional image support in preview window: See `# Preview Mode` for more information
        --
    },
}
```

**Comment by cseickel** [comment]
I'm sorry, but that is an unreasonable expectation. You should not be trying to switch buffers from the Neo-tree window when Neo-tree was opened as a sidebar. You need to first focus the window that you expect the buffer to show in. That is how `:previous` and `:next` work.

What is technically happening is that there is something going awry with focus stealing prevention. If it weren't for that focus stealing prevention, you would get the desired buffer in Neo-tree's window. I can't see how that makes any sense at all.

Do not try to load other buffers in Neo-tree's window when it is opened as a sidebar. If you want to be able to reuse Neo-tree's window, you should manage the windows yourself open it with `position=current`.
