### ISSUE TITLE
BUG: Not opening .tex files when opened via the file tree.

### ISSUE THREAD

**Issue by rafaelferracini** [nvim-neo-tree/neo-tree.nvim#1270]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM 0.9.4

### Operating System / Version

Windows 11

### Describe the Bug

When I try to open a .tex file through the file tree (using NeoTreeShowToggle), the file appears empty. No pop-up error message when opening

Although when trying to save this empry file it shows de following error message: 

`E212: Can't open file for writing: no such file or directory`

Moreover, if I open a file like 'nvim main.tex' and switch files through the File Tree. When I return to main.tex, this error doesn't occur

### Screenshots, Traceback

Original file:
![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/121617955/16f8edd6-addf-488c-bdca-af16bd9335cd)

When opening via Tree:
![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/121617955/3e19954f-46d3-4ee3-848a-e2b3f8320849)

### Steps to Reproduce

1. In a directory with .tex files Open nvim
2. Open Tree with NeoTreeShowToggle
3. Open a .tex file
4. Save file to pop-up the error E212

### Expected Behavior

The file opens without any content

### Your Configuration

```Lua
-
```

**Comment by cseickel** [comment]
`NeoTreeShowToggle` was removed in 3.0, so you must be on old version. Can you try updating to the latest version (which is 3.14) and seeing if that fixes it?

**Comment by rafaelferracini** [comment]
It's already updated and even other commands to open neotree shows the same problem

**Comment by bwpge** [comment]
@rafaelferracini unless you are using a different Neovim config than what's public in your [dotfile](https://github.com/rafaelferracini/dotfile) repository, you are not on the latest stable branch. Check out your `nvim-tree` plugin spec, it is using `2.x`: https://github.com/rafaelferracini/dotfile/blob/e5d8da0292de20b53d3a5e4f52cbfcaebbf2f8a1/nvim/lua/plugins.lua#L36-L44

You need to change this to `3.x` and have `packer` update your Neo-tree plugin. I suspect you're having issues with the spaces in your path and the buffer is being opened to a non-existent file. The escaping issue was fixed 8 months ago in https://github.com/nvim-neo-tree/neo-tree.nvim/commit/7f6fa04dbd8e8c79d1af33bc90e856b65d8641da, but this is only on `3.x` (it was not merged into `2.x`).

**Comment by pysan3** [comment]
This should be fixed with the latest branch. Closing.

Please reopen and ping me if you still experience this issue.
