### ISSUE TITLE
BUG: previously revealed file incorrectly focused on all future renders

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#1279]
> Sorry for mentioning that this pr seems breaking the `open` action in `Neotree reveal`.
> 
> Open one file and run `Neotree reveal`, then run `<cr>` to `open` the directory of that file.
> 
> After running `<CR>`, it jumps to the file location not toggle the directory.

That is true. Beyond that, any action you take will result in the previously revealed file being focused. That includes opening other files. Whatever the last revealed file is will be permanently stuck and refocused after every render.

I will make this a new issue.

_Originally posted by @cseickel in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1274#issuecomment-1872982362_

**Comment by cseickel** [comment]
Can you take a look at this @georgeguimaraes?

**Comment by georgeguimaraes** [comment]
Sure, I'll take a look.
