### ISSUE TITLE
How do I open nodes in document_symbols to reveal nested symbols?

### ISSUE THREAD

**Issue by adambarjo** [nvim-neo-tree/neo-tree.nvim#1282]
Hello, in `:Neotree document_symbols` I can't seem to open the nodes with nested symbols. Please see pic below. There is an indication that the symbol has nested symbols since it has a ">" icon, but how do I reveal them? I can't find anything in `?` which seems to do the job. Any ideas? Thanks

![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/47948089/7e242fbc-5e04-4a36-a7c7-ddde074ec628)

**Comment by DDGRCF** [comment]
same question

**Comment by pysan3** [comment]
Whatever key you register to `"toggle_node"` command.

By default it is `<Space>`. Keep in mind that this might only be triggered after `:h timeoutlen` if you have any other keybinds colliding.

**Comment by pysan3** [comment]
Please reopen and ping me if it is not working :)
