### ISSUE TITLE
BUG: attempt to index field 'text' (a nil value)

### ISSUE THREAD

**Issue by kawre** [nvim-neo-tree/neo-tree.nvim#1290]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

v0.10.0-dev-2022+ga064ed6229

### Operating System / Version

6.6.8-arch1-1

### Describe the Bug

[Neo-tree WARN] Error rendering component diagnostics: ...neo-tree.nvim/lua/neo-tree/sources/common/components.lua:91: attempt to index field 'text' (a nil value)
One fix i found is to set update_in_insert to true as i showcased in the video.
Also at 0;25 you can see that the filename changed to that error

### Screenshots, Traceback

https://github.com/nvim-neo-tree/neo-tree.nvim/assets/69250723/706a396d-51d6-47cf-ae47-21eed9dba4c5

### Steps to Reproduce

1. open `.lua` file
2. type anything that will trigger diagnotic errors once `lua_ls` loads
3. wait and stay in insert mode
4. once `lua_ls` loads it should give an warning

### Expected Behavior

not throw an error?

### Your Configuration

I don't think reproducing this is needed but if it is tell me 

lspconfig - https://github.com/kawre/nvim/tree/master/lua/plugins/lsp/config

```Lua
local M = {
    "nvim-neo-tree/neo-tree.nvim",
    dependencies = {
        "nvim-lua/plenary.nvim",
        "nvim-tree/nvim-web-devicons",
        "MunifTanjim/nui.nvim",
    },
    lazy = false,
    enabled = true,
}

M.keys = {
    { "<leader>e", "<cmd>Neotree left toggle<cr>", desc = "Toggle Neotree" },
}

M.init = function()
    vim.g.loaded_netrw = 1
    vim.g.loaded_netrwPlugin = 1

    vim.cmd([[hi link NeoTreeGitAdded String]])
end

M.opts = {
    window = {
        position = "left",
        width = 60,
    },
    default_component_configs = {
        indent = {
            indent_size = 3,
            highlight = "Comment",
        },
        icon = {
            folder_closed = "",
            folder_open = "",
            folder_empty = "󰜌",
            -- The next two settings are only a fallback, if you use nvim-web-devicons and configure default icons there
            -- then these will never be used.
            default = "*",
            highlight = "NeoTreeFileIcon",
        },
        modified = {
            symbol = "",
            highlight = "NeoTreeModified",
        },
        git_status = {
            symbols = {
                -- Change type
                added = "+", -- or "✚", but this is redundant info if you use git_status_colors on the name
                modified = "", -- or "", but this is redundant info if you use git_status_colors on the name
                deleted = "✖", -- this can only be used in the git_status source
                renamed = "󰁕", -- this can only be used in the git_status source
                -- Status type
                untracked = "",
                ignored = "",
                unstaged = "󰄱",
                staged = "",
                conflict = "",
            },
        },
        -- indent = {
        -- 	indent_size = 1,
        -- 	padding = 0,
        -- 	indent_market = "",
        -- },
    },
    filesystem = {
        use_libuv_file_watcher = true,
        group_empty_dirs = true,
        follow_current_file = { enabled = true, leave_dirs_open = true },
        filtered_items = {
            visible = false, -- when true, they will just be displayed differently than normal items
            hide_dotfiles = true,
            hide_gitignored = false,
            hide_hidden = true, -- only works on Windows for hidden files/directories
            hide_by_name = {
                "node_modules",
            },
            hide_by_pattern = { -- uses glob style patterns
                --"*.meta",
                --"*/src/*/tsconfig.json",
            },
            always_show = { -- remains visible even if other settings would normally hide it
                --".gitignored",
            },
            never_show = { -- remains hidden even if visible is toggled to true, this overrides always_show
                --".DS_Store",
                --"thumbs.db"
            },
            never_show_by_pattern = { -- uses glob style patterns
                --".null-ls_*",
            },
        },
        hijack_netrw_behavior = "open_default",
    },
}

return M
```

**Comment by kawre** [comment]
Also if you keep typing while in insert mode your screen will get spammed with these notifications. They will go away only if you enter normal mode and then go back to insert

**Comment by kawre** [comment]
Apparently it's an `neovim` issue.
https://github.com/neovim/neovim/pull/26927

**Comment by gpanders** [comment]
I don't think https://github.com/neovim/neovim/pull/26927 is the right solution, because even then it's not guaranteed that `vim.diagnostic.config().signs.text` will be non-nil.

Is your issue resolved if you apply the following patch to `neo-tree.nvim`?

```diff
diff --git a/lua/neo-tree/sources/common/components.lua b/lua/neo-tree/sources/common/components.lua
index e4443ba..9595b06 100644
--- a/lua/neo-tree/sources/common/components.lua
+++ b/lua/neo-tree/sources/common/components.lua
@@ -87,8 +87,9 @@ local function get_defined_sign(severity)
       if identifier == "H" then
         identifier = "N"
       end
+      local text = signs_config.text or {}
       defined = {
-        text = signs_config.text[vim.diagnostic.severity[identifier]],
+        text = text[vim.diagnostic.severity[identifier]],
         texthl = "DiagnosticSign" .. severity,
       }
     end
```

**Comment by kawre** [comment]
@gpanders i've forked `neotree` and tried doing exactly this but while it works if user has custom icons defined then `neotree` will not display those and fallback to the default icons like 'E' for error.

**Comment by kawre** [comment]
@gpanders Also there might be more plugins expecting `signs.text` to be defined so thats why i opened the issue on `neovim` rather than making it a fix local to `neotree`

**Comment by gpanders** [comment]
Regardless of what is changed in Neovim itself, it is still the case that `signs_config.text` may be `nil`, so neotree needs to check for that case.

https://github.com/neovim/neovim/pull/26927 only affects how legacy signs are translated into the new diagnostic config format. However, I don't use any legacy signs at all, so https://github.com/neovim/neovim/pull/26927 has no effect for me, and yet `vim.diagnostic.config().signs.text` is still `nil`.

**Comment by kawre** [comment]
@gpanders You're right, I wrongly assumed that `vim.diagnostic.config().signs.text` should never be `nil`.

I think we can move the further conversation to https://github.com/neovim/neovim/pull/26927 as i still think it's an issue worth fixing.
