### ISSUE TITLE
Feature request: customizable tree layout

### ISSUE THREAD

**Issue by wookayin** [nvim-neo-tree/neo-tree.nvim#130]
![image](https://user-images.githubusercontent.com/1009873/152696425-e98cd7f6-04da-42bd-8b59-9166c0c2a6e5.png)

**Left**: NERDTree,  **Mid**: nvim-tree.lua,   **Right**: NeoTree

It would be great if neotree can support customization tree layout. For example, I personally prefer the style of nvim-tree.lua (or coc-explorer) where a fancy unicode characters is used to denote the expanded tree. Compared to that, the style of NERDTree and NeoTree seem less intuitive for me.

NeoTree follows the default style of NERDTree, but it has another problem: the indent align is not proper. This is more noticable when one has some [indent level guide plugin](https://github.com/lukas-reineke/indent-blankline.nvim).  I have a tabsize of 4 (`&sw = 4`) in this example -- somehow it was supposed to be `2` but I just did not have such config (although the plugin itself might want to add buffer-specific options). Please compare with that of NERDTree. It might be fixed either if (i) there is no a padding (in one space character) on the left, (ii) if no space/tab is used with different tree drawing style (like nvim-tree), or (iii) I just don't use the indent-blankline plugin.

**Comment by wookayin** [comment]
In my opinion, adding some configurable option/feature to choose which tree drawing style to be used would be great, but even if an user chooses the current default style the misaligned indentation would need to be fixed.

**Comment by cseickel** [comment]
For the folder icons, that is configurable by setting the `folder_open` and `folder_closed` properties on the icon component, see: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/caa64cf0e43cf141bc6d34ff6216c1ab2611d75c/lua/neo-tree/defaults.lua#L140

The problem with the indent alignment is that I pad the window with 1 space because I don't show indent lines on the tree and to me it looks better with the padding. I can certainly make that configurable. There is also a PR that is almost complete to add indent guides. I think that is stalled but I'll finish it up and get it merged.

**Comment by cseickel** [comment]
This should be handled with the changes in #131  which are now in the latest release. You should be able to get what you want with this config:

```lua
      require("neo-tree").setup({
        default_component_configs = {
          indent = {
            indent_size = 2,
            padding = 0, -- extra padding on left hand side
            with_markers = true,
            indent_marker = "│",
            last_indent_marker = "└",
            highlight = "NeoTreeIndentMarker",
          },
          icon = {
            folder_closed = "",
            folder_open = "",
            trailing_slash = true,
            default_icon = "*",
          },
          ...
```

If you have the `icon` component configured in your renderers as well, those settings will merge and take precedence over the default_component_configs where they conflict.

The indent component is brand new.

**Comment by wookayin** [comment]
Thanks, the new feature works very well for me. 

One minor issue: Has the default_icon changed? It was `*` previously, and now it is just a blank, which confuses indent guide again.

**Comment by cseickel** [comment]
I moved the default settings from the individual renderers to the `global_component_config` section, so you may have lost it in the transition. If you use the config I posted above then it should still apply as "*". Of course, even without that the true default is a space `" "` anyhow, so the spacing should be preserved.

I never actually saw the default icon getting used on my computer, `web-devicons` has always supplied an icon for every file. I'm suprised to see that your Makefile used the default in the screenshot above.

**Comment by wookayin** [comment]
Ok so this seems to be a typo. You probably have meant

```diff
 icon = {             
-  default_icon = "",
+  default = "",
 },                   
```

in the config (README, docs, etc.)

**Comment by cseickel** [comment]
🤦‍♂️ Good catch, thanks for finding that!

**Comment by nyngwang** [comment]
While it works, I would like to know why `with_markers = true,` is needed? It took me some time to realize that I have to also set this option to `true` to show the markers.

**Comment by cseickel** [comment]
@nyngwang Indent makers are just one of the possible features of indent. The other configurations exposed here are how many spaces to indent and how much padding to add. 

Not everyone likes have indent markers so the default is false.

**Comment by nyngwang** [comment]
Got it!
