### ISSUE TITLE
FEATURE: Not a strict search

### ISSUE THREAD

**Issue by mr-scrpt** [nvim-neo-tree/neo-tree.nvim#1304]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

For example in telescope I can search for files by non-strict match, for example if I am looking for a file with the word "action" in its name but it should be in the folder "src" - I can just write "src action" and I will get the desired result. And in neo tree I can search only by strict match using "/" or by directories using "D", but sometimes I need to search in the way it is implemented in telescope. Is it possible to do it in neotree?

### Describe the solution you'd like.

We type "action src" and get all files with these words in their name or paths

**Comment by cseickel** [comment]
It already has these options. See:

```
:h neo-tree-filter
```

You will also get the specific effect you are looking for by enabling this option:
``` lua
    require("neo-tree").setup({
      filesystem = {
        find_by_full_path_words = false,  
      }
    })
```

I think that the `fuzzy_sorter` method will also do this naturally, which is mapped to `#` by default.
