### ISSUE TITLE
FEATURE: Allow changing the `git_root` using `dir` for `git_status`

### ISSUE THREAD

**Issue by pdgendt** [nvim-neo-tree/neo-tree.nvim#1309]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

Opening a `Neotree git_status` when there are multiple `git` directories in `cwd` this will result in no files being listed. This can happen, for example using `git submodule`.

### Describe the solution you'd like.

When setting `dir` this should be considered the `git_root` instead of cwd.

**Comment by konosubakonoakua** [comment]
@pdgendt could you please try this PR? I have tested it on my laptop. :D

**Comment by pdgendt** [comment]
> @pdgendt could you please try this PR? I have tested it on my laptop. :D

Works like a charm! Thanks
