### ISSUE TITLE
BUG: Neotree can't get icon for Diagnostic

### ISSUE THREAD

**Issue by sownteedev** [nvim-neo-tree/neo-tree.nvim#1311]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.10.0-dev

### Operating System / Version

Arch Linux / 6.7.0

### Describe the Bug

I have added these properties but it doesn't show up on Neotree
`vim.fn.sign_define("DiagnosticSignError",
	{ text = " ", texthl = "DiagnosticSignError" })
vim.fn.sign_define("DiagnosticSignWarn",
	{ text = " ", texthl = "DiagnosticSignWarn" })
vim.fn.sign_define("DiagnosticSignInfo",
	{ text = " ", texthl = "DiagnosticSignInfo" })
vim.fn.sign_define("DiagnosticSignHint",
	{ text = "󰌵", texthl = "DiagnosticSignHint" })`

### Screenshots, Traceback

![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/90148193/9e8e69b1-3b7d-4230-bf7e-47d7401bcd59)

### Steps to Reproduce

.

### Expected Behavior

.

### Your Configuration

```Lua
local status_ok, tree = pcall(require, "neo-tree")
if not status_ok then
	return
end

vim.g.neo_tree_remove_legacy_commands = 1

vim.fn.sign_define("DiagnosticSignError",
	{ text = " ", texthl = "DiagnosticSignError" })
vim.fn.sign_define("DiagnosticSignWarn",
	{ text = " ", texthl = "DiagnosticSignWarn" })
vim.fn.sign_define("DiagnosticSignInfo",
	{ text = " ", texthl = "DiagnosticSignInfo" })
vim.fn.sign_define("DiagnosticSignHint",
	{ text = "󰌵", texthl = "DiagnosticSignHint" })

tree.setup({
	close_if_last_window = true,
	open_files_do_not_replace_types = { "terminal", "Trouble", "trouble", "qf", "Outline" },
	popup_border_style = "rounded",
	enable_git_status = true,
	enable_diagnostics = true,
	sort_case_insensitive = false,
	default_component_configs = {
		container = { enable_character_fade = true },
		indent = {
			indent_size = 2,
			padding = 1,
			with_markers = false,
			indent_marker = "│",
			last_indent_marker = "└",
			highlight = "NeoTreeIndent",
			with_expanders = true,
			expander_collapsed = "",
			expander_expanded = "",
			expander_highlight = "NeoTreeIndent",
		},
		icon = {
			folder_closed = "",
			folder_open = "",
			folder_empty = "",
		},
		modified = {
			symbol = "●",
			highlight = "NeoTreeModified",
		},
		git_status = {
			symbols = {
				added = "",
				modified = "",
				deleted = "",
				renamed = "",
				untracked = "",
				ignored = "",
				unstaged = "",
				staged = "",
				conflict = "",
			},
		},
	},
	commands = {},
	window = {
		position = "left",
		width = 35,
		mappings = {
			["o"] = "open",
			["<c-x>"] = "open_split",
			["<c-v>"] = "open_vsplit",
		},
	},
	filesystem = {
		filtered_items = {
			visible = false,
			hide_dotfiles = false,
			hide_gitignored = false,
			never_show = {},
		},
		follow_current_file = { enabled = true },
		group_empty_dirs = true,
		bind_to_cwd = false,
		use_libuv_file_watcher = true,
		components = {
			name = function(config, node, state)
				local cc = require("neo-tree.sources.common.components")
				local result = cc.name(config, node, state)
				if node:get_depth() == 1 then
					result.text = string.gsub(state.path, "(.*[/\\])(.*)", "%2")
				end
				return result
			end,
		},
	},
	source_selector = {
		winbar = false,
		sources = {
			{ source = "filesystem", display_name = "  Files " },
			{ source = "buffers", display_name = "  Bufs " },
			{ source = "git_status", display_name = "  Git " },
		},
	},
})
```

**Comment by mehalter** [comment]
You should probably move to configuring diagnostic signs using the new API if you are using neovim 0.10 nightly: https://github.com/neovim/neovim/pull/26193

**Comment by sownteedev** [comment]
Solved ! Thanks guy

**Comment by 0xJWLabs** [comment]
How do you solve it? @sownteedev

**Comment by sownteedev** [comment]
> How do you solve it? @sownteedev 

Change to new config lsp

**Comment by PriyobrotoKar** [comment]
> > How do you solve it? [@sownteedev](https://github.com/sownteedev)
> 
> Change to new config lsp (icon)

Can you show your new config? I'm facing the same error

**Comment by bombsimon** [comment]
Maybe obvious to most, but the linked PR doesn't mention it in the use of the constants in the description so you'd have to read the changes or the [neovim docs](https://neovim.io/doc/user/diagnostic.html#_signs) to find it. Just using the keys (`["WARN"]` etc) didn't work for me so I ended up with this:

```lua
vim.diagnostic.config({
    signs = {
        text = {
            [vim.diagnostic.severity.ERROR] = "❌ ",
            [vim.diagnostic.severity.WARN] = "⚠️",
            [vim.diagnostic.severity.INFO] = "ℹ️",
            [vim.diagnostic.severity.HINT] = "📎",
        },
    },
})
```

Should the docs for `neo-tree` be updated to include this? Neovim 0.10 has been stable since May last year.

**Comment by stevenxxiu** [comment]
@bombsimon you have a trailing space in `vim.diagnostic.severity.ERROR` which causes an error.
