### ISSUE TITLE
FEATURE: Focus newly created file

### ISSUE THREAD

**Issue by ls-devs** [nvim-neo-tree/neo-tree.nvim#1315]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

Hi,
After research I cannot find a way to focus a newly created file.
Could you provide solution to this ?

### Describe the solution you'd like.

Open neo-tree (float), add a file, neo-tree instantly focus the newly created file.

**Comment by ls-devs** [comment]
Actually I managed to make it work by creating a custom command and mapping `["a"]` to this command.
I would appreciate an easier way to do this if possible.

Anyway, here's how I did it : 

`COMMAND` :
```lua
      create_and_focus = function(state)
        local fs = require("neo-tree.sources.filesystem")
        local fs_actions = require("neo-tree.sources.filesystem.lib.fs_actions")

        local function get_folder_node(nodeState)
          local tree = nodeState.tree
          local node = tree:get_node()
          local last_id = node:get_id()

          while node do
            local insert_as_local = nodeState.config.insert_as
            local insert_as_global = require("neo-tree").config.window.insert_as
            local use_parent
            if insert_as_local then
              use_parent = insert_as_local == "sibling"
            else
              use_parent = insert_as_global == "sibling"
            end

            local is_open_dir = node.type == "directory" and (node:is_expanded() or node.empty_expanded)
            if use_parent and not is_open_dir then
              return tree:get_node(node:get_parent_id())
            end

            if node.type == "directory" then
              return node
            end

            local parent_id = node:get_parent_id()
            if not parent_id or parent_id == last_id then
              return node
            else
              last_id = parent_id
              node = tree:get_node(parent_id)
            end
          end
        end

        local function get_using_root_directory(rootState)
          local using_root_directory = get_folder_node(rootState):get_id()
          local show_path = rootState.config.show_path
          if show_path == "absolute" then
            using_root_directory = ""
          elseif show_path == "relative" then
            using_root_directory = rootState.path
          end
          return using_root_directory
        end

        local function add(addState, callback)
          local node = get_folder_node(addState)
          local in_directory = node:get_id()
          local using_root_directory = get_using_root_directory(addState)
          fs_actions.create_node(in_directory, callback, using_root_directory)
        end

        add(state, function(destination)      -- callback to cc.add, destination is the new file/dir path
          fs.show_new_children(state, destination) -- lazily update neo-tree to show created item
          vim.cmd.edit(destination)
        end)
      end,
```

`MAPPING` : 
```lua
        ["a"] = {
          "create_and_focus",
          config = {
            show_path = "relative",
          },
        },
```

**Comment by cseickel** [comment]
I have to say, I don't get why you need to go through all of this trouble. When a new file is created, it already focuses that file. Then you just need to hit enter (or whatever your `open` mapping is) to edit it. Why do you need another mapping to remove one extra keypress for this action?

**Comment by ls-devs** [comment]
@cseickel Actually when I'm creating a file, neo-tree dont focus it. That's why I go through all of this trouble. 
Even with the default setup provided, it doesn't work.

**Comment by ls-devs** [comment]
@cseickel I think you misunderstood what I was talking about. My problem is not about auto entering the new created file but more about focusing it when its's created. Actually in a long directory (about 20 files) if I'm at the top and I created a file named `x` for example, neo-tree do not focus the bottom of the directory, and so, the file.

**Comment by cseickel** [comment]
Strange. For me, it auto focuses the newly added file in every situation, even if the directory contents are longer than the screen height and I add something that requires scrolling to focus it.

It sounds like you should close this feature request (because the feature already exists) and open a bug report which has steps to recreate the issue with a minimal config.
