### ISSUE TITLE
BUG:  Re-opening any file lefts `untitled` buffer opened

### ISSUE THREAD

**Issue by Rid1-fz-06** [nvim-neo-tree/neo-tree.nvim#1322]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.9.5

### Operating System / Version

Fedora 39 (Workstation)

### Describe the Bug

If I open any file from neo-tree and if there is no buffer/file opened except `Untitled` buffer, neo-tree replaces that buffer with the opened file's buffer. But doing this again (i.e: closing that file, and trying to re-open that) lefts that `Untitled` buffer opened.

### Screenshots, Traceback

[Screencast from 2024-01-25 10-47-02.webm](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/92540820/b2f451fa-ea64-4378-9759-4cc49634d854)

### Steps to Reproduce

1. Open any file from neo-tree in an empty neovim session
2. Close that file
3. Try to re-open the same file from neo-tree

### Expected Behavior

The `Untitled` buffer should have been closed.

### Your Configuration

```Lua
I am using [AstroNvim](https://astronvim.com)
```

**Comment by cseickel** [comment]
This is not a neo-tree responsibility at all, it is a built-in behavior of neovim to have an an empty buffer when no other buffer is open. If you wanted neovim to close after deleting the last buffer, you should use a "quit" command instead of a delete buffer command.

**Comment by Rid1-fz-06** [comment]
@cseickel I didn't mean that. I don't want to close neovim. Yes, neovim will always create an empty buffer when there is no buffer opened. But when I open any file from neo-tree (when there is no buffer opened but the empty `Untitled` buffer), neo-tree should have closed that empty `Untitled` buffer (not neovim), and open the file I tried to open. In other words, that `Untitled` buffer should be replaced by the file's buffer I was trying to open.

**Comment by Rid1-fz-06** [comment]
@cseickel this doesn't happen if I open any file first time after opening neovim. It only happens when I close that file, and try to re-open that file.

**Comment by Rid1-fz-06** [comment]
@cseickel thanks. I found that this issue is still there if I use the `:edit` command. It is not a bug of neo-tree. Sorry for wasting you time sir. Thanks
