### ISSUE TITLE
Help: how can i remove the "padding" colors round the boder?

### ISSUE THREAD

**Issue by zsmatrix62** [nvim-neo-tree/neo-tree.nvim#1323]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.8.0

### Operating System / Version

Mac

### Describe the Bug

Im new to neovim and i want ot rmeove those kind of "padding" around the floating borders, how can i made it?

<img width="1010" alt="图片" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/2951879/7e303e5f-2b5d-4738-bc5d-f3036ed7bb13">

### Steps to Reproduce

None

### Expected Behavior

None

### Your Configuration

```Lua
None
```

**Comment by cseickel** [comment]
You need to set the `FloatBorder` or `NeoTreeFloatBorder` highlight group to something where the background color is either not set or is the same color as your Normal background. Something like this in vimscript:

``` vim
highlight FloatBorder guifg=#b8b8e6
```
