### ISSUE TITLE
Conflict with plugin `romgrk/nvim-treesitter-context`: E5601: `Cannot close window, only float window would ...`

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#133]
![image](https://user-images.githubusercontent.com/24765272/152911174-6cd9b7f3-81d8-4c3a-bfba-5ecc17c212ab.png)

**Comment by nyngwang** [comment]
I rollback to on master cbe2121 then the problem disappear.

**Comment by cseickel** [comment]
@nyngwang Can you try the latest in **main** and tell me if it fixes that error?

**Comment by nyngwang** [comment]
@cseickel  It did :) Thank you!

**Comment by cseickel** [comment]
@nyngwang I see the issue with being unable to close the tree or neovim if it is the last buffer, I'm working on that.

> I have to run <C-f> on any non-neo-tree buffer to trigger another plugin's behavior(grep files).

I don't understand that one, can you provide more details on what <C-f> should do and what is does now?

> I probably want to open dashboard(a plugin, which enable me to open old files) on any non-neo-tree buffer.

That sounds like a new feature request.

**Comment by nyngwang** [comment]
> > I have to run  on any non-neo-tree buffer to trigger another plugin's behavior(grep files).
> 
> I don't understand that one, can you provide more details on what should do and what is does now?
> 
> > I probably want to open dashboard(a plugin, which enable me to open old files) on any non-neo-tree buffer.
> 
> That sounds like a new feature request.

You can safely ignore these two. They're just some consequences caused by the OP.

**Comment by cseickel** [comment]
@nyngwang I've cleaned this up in the latest commit on main, let me know if it works better now.

**Comment by nyngwang** [comment]
<img src="" width="500">

![Uploading image.png…]()

**Comment by cseickel** [comment]
@nyngwang It is true that neovim will throw that error if you try to close the last non-floating window in a way that would leave only floating windows open. That's not really an issue as long as you can close the floating Neo-tree window without issue and you can close a normal Neo-tree window when there are no floats open.

I think I have fixed all problems with the hijack netrw functionality now and I'll be releasing this to v1.x soon. Let me know if I missed anything.
