### ISSUE TITLE
Neo-tree hijacks netrw, which causes cascading issues for other plugins

### ISSUE THREAD

**Issue by grem11n** [nvim-neo-tree/neo-tree.nvim#135]
First of all, thank you for a great project!

### Description

Now, here is the issue. It looks like `neo-tree` hijacks `netrw`. At least, I found [this function](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/1bfd7d171934e8dd248b0d7850d5bada23372d3f/lua/neo-tree.lua#L84), which has a related name. Or `neo-tree` conflicts with `netrw` in some other way. I'm not very good in Lua and I cannot trace it down to a specific function.

Since `netrw` is eventually disabled, one cannot use any of its functions. For example: `call netrw#BrowseX('https://...', 0)` returns: `E117: Unknown function: netrw#BrowseX`.

This causes issues for other plugins. For example, https://github.com/tpope/vim-rhubarb. This plugin depends on the `netrw` functions. Thus, it is incompatible with `neo-tree`.

[`nvim-tree.lua`](https://github.com/kyazdani42/nvim-tree.lua), for instance, provides an [ability to enable `netrw` in the configuration](https://github.com/kyazdani42/nvim-tree.lua/pull/195). With this configuration `nvim-tree.lua` doesn't conflict with `netrw` and do not create issues for other plugins.

Notice, when `neo-tree` is not loaded, all the `netrw` commands work as expected.

### Steps to reproduce

1. Create NeoVim configuration with `neo-tree` enaabled.
2. Try to call any `netrw` function. For example, `call netrw#BrowseX('https://google.com', 0)`

**Expected results**: Spcified link is opened in a browser.
**Actual result**: `E117: Unknown function: netrw#BrowseX`

Thank you!

**Comment by cseickel** [comment]
I was actually waiting to see if anyone requested this to be turned off, I wasn't sure when I added it if there would be anyone that wants to use Neo-tree and netrw at the same time. Now I know!

The plumbing was just added yesterday to make this an optional feature. I'll finish that off now.

**Comment by cseickel** [comment]
@grem11n I have made this an option that is disabled by default in the `135-optional-netrw-hijack` branch. If you want to switch to that now you can try it out and see if it works as expected. I still need to document, add tests, and leave some time for discussion before this is released.

**Comment by grem11n** [comment]
Thank you so much, @cseickel !

Works like a charm. I've tried both direct call with `call netrw#BrowseX(...)` and Tpope's plugins. Everything looks good so far.

**Comment by cseickel** [comment]
@grem11n This is close to being merged. When it does, the default behavior will be to continue to hijack netrw and disable it, but there will be an option to disable the hijack behavior. **You should add this to your config:**

```lua
    require("neo-tree").setup({
      filesystem = {
        hijack_netrw_behavior = "disabled",
    })
```
