### ISSUE TITLE
Question: Does Neo-tree support symbolic link display? 

### ISSUE THREAD

**Issue by rltyty** [nvim-neo-tree/neo-tree.nvim#1358]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.9.5

### Operating System / Version

macOS 12.7

### Describe the Bug

With default settings, a normal file and a symbolic link to a file look the same, a symbolic directory does look different (italic and highlight) , but no target is shown (even in File details, it shows the type is normal directory or file) .

E.g. 
> tree
.
├── a
├── alink -> a
├── b
├── c
├── etc -> /etc
├── pf.os -> /etc/pf.os
└── x

6 directories, 2 files

In Neo-tree, 
<img width="345" alt="Screen Shot 2024-02-20 at 18 15 28" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/98961340/6444dbb8-3e88-4c18-961f-be6636dc1e8a">

In Nerdtree
<img width="271" alt="Screen Shot 2024-02-20 at 18 16 29" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/98961340/7024570d-7c6c-4588-a58a-03908955ca36">

Is there any way Neo-tree can
1. show the difference between a link and a normal file;
2. show the target for both a directory link and a file link.

Thanks in advance.

### Steps to Reproduce

N/A

### Expected Behavior

As above

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {
    { "<Leader>e", "<Cmd>Neotree<CR>" }, -- change or remove this line if relevant.
  },
  opts = {
    -- Your config here
    -- ...
  },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by pysan3** [comment]
Yes, and it is changed to show the linked destination just like your image by default in a relative recent change. 

I wonder why you don't see it. Do you really use the stock config without any modifications? As you didn't put anything in repro.lua

**Comment by rltyty** [comment]
My configuration about Neo-tree,

    -- neo-tree
    {
        "nvim-neo-tree/neo-tree.nvim",
        branch = "v3.x",
        dependencies = {
          "nvim-lua/plenary.nvim",
          "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
          "MunifTanjim/nui.nvim",
        },
        keys = {
          { "<c-n>", "<cmd>Neotree<cr>", desc = "neo-tree" }, -- `q` to exit
          { "<leader>ev", "<cmd>Neotree" .. conf_root .. "/lua<cr>",
            desc = "open nvim configuration" }
        },
        config = {
        },
        enabled = true,
        -- enabled = false,
    },

Btw, I just revised my main post to make my question clear.

**Comment by pysan3** [comment]
Oh my bad, it might not be my default.

Try `config.default_component.configs.symlink_target.enabled = true`, and you should get something like this.

![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/41065736/650e7a55-b471-405a-941f-9e98a9495cc8)

**Comment by rltyty** [comment]
@pysan3 After add the option to enable symlink_target, everything works great! Many thanks!
Here is my current configuration:

```lua
    -- neo-tree
    {
        "nvim-neo-tree/neo-tree.nvim",
        branch = "v3.x",
        dependencies = {
          "nvim-lua/plenary.nvim",
          "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
          "MunifTanjim/nui.nvim",
        },
        keys = {
          { "<c-n>", "<cmd>Neotree<cr>", desc = "neo-tree" }, -- `q` to exit
          { "<leader>ev", "<cmd>Neotree" .. conf_root .. "/lua<cr>",
            desc = "open nvim configuration" }
        },
        opts = {
          default_component_configs = {
            symlink_target = { enabled = true },
          },
        },
        enabled = true,
        -- enabled = false,
    },
```

**Comment by pysan3** [comment]
Glad to hear that :)

Sorry for lying that it was the default. Somewhere in my brain tricked me lol.
