### ISSUE TITLE
Can't figure out how to make <CR> open the file but at the same time close the sidebar

### ISSUE THREAD

**Issue by joaqo** [nvim-neo-tree/neo-tree.nvim#1359]
Read through the doc and tried changing the <CR> mapping to 'focused' and 'open_drop' but that didn't work. Any suggestions? Sorry to create an issue about this, but I really couldn't figure it out.

**Comment by pysan3** [comment]
Keep it mapped to "open" but add this instead. 

https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#auto-close-on-open-file

I'd prefer to ask these kinda questions in [discussions](https://github.com/nvim-neo-tree/neo-tree.nvim/discussions) but you are nothing wrong to ask here as well ;)

**Comment by cseickel** [comment]
You should also consider that if you want to auto close the sidebar every time you open a file, maybe you don't really want to use a sidebar at all. The "current" or "float" positions might be better suited to your workflow.

**Comment by joaqo** [comment]
Thanks @pysan3, thats perfect! I'll post these kinds of things to discussions in the future.

@cseickel Great suggestion! You actually made me change my mind, I ended up using the "float" position, thanks.

Closing, issue.
