### ISSUE TITLE
[QUESTION] I try to add the root path from neo-tree to cokline sep

### ISSUE THREAD

**Issue by bbidds** [nvim-neo-tree/neo-tree.nvim#1360]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

- My question is how to grab the root path from neo tree and place it in the cokeline separator so that the path in the cokeline updates itself at any time.
- And disable the root path at the top in neo-tree.

If anyone knows how, please tell.

ty

### Describe the solution you'd like.

I like the api in nvim-tree. I would be happy about an api and a api documentation.

**Comment by pysan3** [comment]
These lines might be useful for you.

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/7d3b02073e59ed9ef271795787de76d0de8f5294/lua/neo-tree/defaults.lua#L12
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/7d3b02073e59ed9ef271795787de76d0de8f5294/lua/neo-tree/defaults.lua#L31-L33

Regarding cokeline, may I ask what you've got so far? There are various degrees that needs to be explained so I'd like to know that you don't understand.

Have you read the [sidebar section](https://github.com/willothy/nvim-cokeline?tab=readme-ov-file#sidebars)?

**Comment by cuattoo** [comment]
yes, I had read many pages of code and issues to find that, what I need. So that was my first question/comment on github.

I have a sidebar for coke but only a normal text and I wish so cool functions.

```lua
    sidebar = {
        filetype = {'NvimTree', "neo-tree"},
        components = {
            {
                text = 'File Explorer',
                fg = title,
                bg = bg,
                style = 'bold',
            },
        },
    },

```

Idk, I would like to add some code for the empty line so that if I want a new file or something with a keybind to write in the blank line instead of a popup, for a new file. That would be nice. 
and then add an integration for cokeline.

I find my idea useful
pls give feedback.

**Comment by pysan3** [comment]
I don't quite understand what you want but I think this will help you.

Could you give me your nvim-tree example (as you said you liked the nvim-tree api)?
I don't fully understand what your goal looks like.

```lua
        {
          text = function(buffer)
            local mgr = require("neo-tree.sources.manager")
            if not vim.api.nvim_buf_is_valid(buffer.number) then
              return "File Explorer"
            end
            local winid = vim.b[buffer.number].neo_tree_winid
            local state = mgr.get_state_for_window(winid)
            if not state then
              return "File Explorer"
            end
            return state.path
          end,
          style = "bold",
        },
```

**Comment by pysan3** [comment]
Mate, you might be interested in `config.source_selector.show_scrolled_off_parent_node` with a combination of this trick.

- https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1368

**Comment by pysan3** [comment]
If you are satisfied, plz close this issue @cuattoo

**Comment by cuattoo** [comment]
Ik, can I edit the gui like this?
![preview](https://raw.githubusercontent.com/cuattoo/arcdic.nvim/main/.screenshots/2024-03-03_09-47-27.png)

I find this important because otherwise my GUI doesn't match up.

**Comment by pysan3** [comment]
I don't understand what you mean.

**Comment by cuattoo** [comment]
The borders

**Comment by pysan3** [comment]
Did you check the `config.source_selector.show_scrolled_off_parent_node` option?

I don't think it has any borders at all, so I don't know what you are talking about.

If you want to modify the borders in the winbar selector, please read the help file. You've got options like `config.source_selector.separator / separator_active / highlight_tab` etc

Do you know how to decorate tabline without any plugin? As you can see in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1368#issuecomment-1970678429, you can decorate the `raw` field as muchas you like.

```lua
          raw = "<decorate-here>%{%v:lua.__get_selector()%}<and-here>",
```

**Comment by cuattoo** [comment]
I don't quite understand how it works,
I am using cokeline and I am trying to implement this.
Idk how. My brain is dead now ^ ^

**Comment by cseickel** [comment]
Just to clarify, the "scrolled off parent node" stuff only applies when the window is scrolled down. In that situation, it proves the parent path of the node which is at the top of the visible screen. It really only makes sense to place this in the winbar of neo-tree.

If you haven't changed any of the default settings regarding paths, the root path of neo-tree is just going to be the current working directory of the neovim tab. That means all you need to do is to use a generic "current working directory" component, which is a question for the cokeline project. If you want a raw statusline code, I use this:

```
%#StatusLineCwd#  %{fnamemodify(getcwd(), ":~")}/%*
```

There is a config option in neo-tree to hide the root folder, just set `hide_root_node = true` in your config.
