### ISSUE TITLE
BUG: Floating  neo-tree moves upon toggling file preview

### ISSUE THREAD

**Issue by escapingSamsara** [nvim-neo-tree/neo-tree.nvim#1362]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

lts

### Operating System / Version

linux debian bookworm lts

### Describe the Bug

When using the toggle preview command on a file within a floating neotree over and over, the neotree window and the preview window move up until they hit the top window border, cant really explain myself why

### Screenshots, Traceback

[Screencast from 2024-02-24 00-54-00.webm](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/111993187/d0d736af-6fb2-47d1-84bf-3700caab8c5b)

### Steps to Reproduce

use this settings for neotree : position = "float", popup = {size = {height ="80%, width="50%"}}, mappings = {["P"] = {"toggle_preview", config = {use_float = true, use_image_nvim = true}}

open neotree and use toggle command repeatetly

### Expected Behavior

i guess it should stay centered at ?

### Your Configuration

```Lua
lazyvim.starter
```

**Comment by pysan3** [comment]
Dup: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/782
