### ISSUE TITLE
How to quit Neovim if Neotree is the last remaining window?

### ISSUE THREAD

**Issue by mrjones2014** [nvim-neo-tree/neo-tree.nvim#137]
Hi, just switched from nvim-tree, really impressed so far.

The one thing I'm not seeing that nvim-tree had built in is an option to quit Neovim if the only remaining buffer is the Neotree buffer?

**Comment by mrjones2014** [comment]
I've done it with this but it'd be cleaner to have a built-in option IMO: 

```VimL
autocmd WinEnter * if winnr('$') == 1 && getbufvar(winbufnr(winnr()), "&filetype") == "neo-tree" | q | endif
```

**Comment by mrjones2014** [comment]
actually I guess what I want is to quit if Neo-tree is the last _window,_ not just buffer. the above doesn't do that.

**Comment by cseickel** [comment]
OK, I can see how to do this right. It should be easy so I'll add it soon.

**Comment by mrjones2014** [comment]
@cseickel I'm getting the following error when I set the new option:

```
[neo-tree.nvim] [ERROR 14:21:02] ...packer/start/neo-tree.nvim/lua/neo-tree/events/queue.lua:144: Error in event handler for event vim_win_enter[neo-tree-win-enter]: ...im/site/pack/packer/start/neo-tree.nvim/lua/neo-tree.lua:410: Vim:E444: Cannot close last window
```

**Comment by mrjones2014** [comment]
This is still not working for me. I've set the option in config, but Neo-tree still remains open for me when it's the last window.

**Comment by cseickel** [comment]
It is working for me right now. One thing that may affect you is that the setting only applies if the last window was opened as a sidebar. 

Can you share your config and an example of what steps will recreate the issue?

**Comment by mrjones2014** [comment]
My Neo-tree config, installed with packer:

```lua
return {
  'nvim-neo-tree/neo-tree.nvim',
  requires = { 'MunifTanjim/nui.nvim' },
  config = function()
    require('neo-tree').setup({
      close_if_last_window = true,
      popup_border_style = 'rounded',
      enable_git_status = true,
      enable_diagnostics = true,
      default_component_configs = {
        indent = {
          indent_size = 2,
          padding = 1, -- extra padding on left hand side
          with_markers = true,
          indent_marker = '│',
          last_indent_marker = '└',
          highlight = 'NeoTreeIndentMarker',
        },
        icon = {
          folder_closed = '',
          folder_open = '',
          default = '',
        },
      },
      filesystem = {
        follow_current_file = true,
        use_libuv_file_watcher = true,
        filters = {
          show_hidden = true,
          respect_gitignore = true,
        },
        window = {
          position = 'right',
          mappings = {
            f = 'none',
          },
        },
      },
    })
  end,
}
```

To reproduce:

1. Open a file, then open Neo-tree (or vice versa, order does not matter)
2. Close the window with the file buffer
3. Neo-tree should close, but it sometimes doesn't (I just noticed the issue seems to be intermittent)

**Comment by cseickel** [comment]
I'm just guessing because it always works for me, but I added a filter when counting windows to exclude floating windows, and maybe that will fix the issue for you. Let me know if this helps.

**Comment by mrjones2014** [comment]
Works for me on branch `main`!
