### ISSUE TITLE
FEATURE: Add 'refresh' command to force Neo-tree refresh

### ISSUE THREAD

**Issue by linrongbin16** [nvim-neo-tree/neo-tree.nvim#1381]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

Sometimes, neo-tree won't refresh the git status & lsp diagnostics in time. So I have to first type `<C-w>` to navigate to neo-tree window, then press `R` key to refresh it, then press `<C-w>` to navigate back to the buffer I'm editing.

### Describe the solution you'd like.

Can we create a `refresh` command? So I could create a key mapping to invoke `Neotree refresh` to refresh neo-tree.

**Comment by linrongbin16** [comment]
thank you for teaching !

**Comment by GNRSN** [comment]
Also thankful for this explainer. For my usecase I'm opening lazygit within a neovim floating terminal and I find that the git state in neo-tree doesn't update after closing the terminal. 

With this I was able to add a callback to refresh after exiting lazygit.

**Comment by kreeger** [comment]
> With this I was able to add a callback to refresh after exiting lazygit.

@GNRSN Sorry for the necropost on this a year later, but how did you manage to accomplish this? I can't find any built-in close callback on `kdheepak/lazygit.nvim`.

**Comment by GNRSN** [comment]
> [@GNRSN](https://github.com/GNRSN) Sorry for the necropost on this a year later, but how did you manage to accomplish this? I can't find any built-in close callback on `kdheepak/lazygit.nvim`.

I was just opening lazyvim through a nvim-native float term (Terminal:new({ direction = "float" })) which takes an `on_close` callback. Hope this helps 😄
