### ISSUE TITLE
BUG: Error while focusing Neotree window on insert mode

### ISSUE THREAD

**Issue by luisjakon** [nvim-neo-tree/neo-tree.nvim#1383]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.10.0-dev-2292+g0db6946b3-Homebrew

### Operating System / Version

MacOS 14.3.1

### Describe the Bug

When focusing the neo-tree window while on ```insert mode```, get an msg ```E21: Cannot make changes, 'modifiable' is off```.

Forces a hit to ```<Esc``` to enter ```normal mode``` in order to continue with normal operations.

### Steps to Reproduce

1. Open nvim
2. Open neotree
3. Open any file
4. Change to insert mode on file
5. hit ```<C-o><C-h>``` to focus the neotree window on left side

### Expected Behavior

Focusing the neotree window while on ```insert mode``` should trigger a change to ```normal mode``` in order to carry out actions.  

Same behavior happens if clicking on the neotree window while on ```insert mode```. 

```<LeftRelease>``` should also trigger a change to ```normal mode``` automatically.

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {
    { "<Leader>e", "<Cmd>Neotree<CR>" }, -- change or remove this line if relevant.
  },
  opts = {
    -- Your config here
    -- ...
  },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by pysan3** [comment]
Are you sure you want a plugin to mess around with your mode automatically?

**Comment by luisjakon** [comment]
Hi! thnxs @pysan3. Good point.

Perhaps it could be temporarily store the current mode when focus is moved to the neotree window and restore it when it leaves.  

Otherwise, having focus while on insert mode has no value...adding an extra unnecessary keystroke to exit to normal mode and do something with it.  Makes sense?

**Comment by cseickel** [comment]
I don't think it is the place of any plugin to control the mode. Here's what I would suggest:

1. If you are insert mode and done with your edits, exit insert mode. Always.
2. If you have a mapping that allows you to switch windows while still in insert mode, you should update that mapping to leave insert mode before switching windows.
3. Clicking with a mouse: 😱
4. ...but seriously, see 1.

All that being said, the best solution is to create an autocmd to run `stopinsert` when you switch windows:
``` vim
augroup ForgetfulMe
  autocmd!
  autocmd WinEnter * :stopinsert
augroup end
```

If someone wanted to put up a PR that does that autocmd specifically for neo-tree windows, I would probably accept it.

**Comment by pysan3** [comment]
If you enter help page I think you'll get the same error. I don't think that is a bug but a feature so same for us.

**Comment by luisjakon** [comment]
Ok. Thanks for the response! 

I'm pretty new at this so I thought I'd follow up with your suggestion with something like this, but somehow it is not triggering on neovim...may need to spend more time with it...Thnks!

```lua
vim.g.forgetfulme = "n"

vim.api.nvim_create_augroup("ForgetfulMe", { clear = true })

vim.api.nvim_create_autocmd({ "BufEnter", "FocusGained" }, {
  group = "ForgetfulMe",
  pattern = { "neo-tree" },
  callback = function()
    vim.g.forgetfulme = vim.api.nvim_get_mode().mode
    if vim.g.forgetfulme == "i" then
      vim.cmd "stopinsert"
    end
  end,
})

vim.api.nvim_create_autocmd({ "BufLeave", "FocusLost" }, {
  group = "ForgetfulMe",
  pattern = { "neo-tree" },
  callback = function()
    if vim.g.forgetfulme == "i" then 
      vim.cmd "startinsert" 
    end
  end,
})
```

**Comment by pysan3** [comment]
Use neo-tree's event handlers instead of autocmds. 

`:h neo-tree-events`

**Comment by luisjakon** [comment]
Hi, Just here in case anyone else is having similar issues with switching and restoring user state for command modes when going in and out of neo-tree with a mouse clicker or other means...

Thnxs!

```lua
-- initialize user command-mode state (just for neo-tree)
vim.g.forgetfulme = "n"

return {
  "nvim-neo-tree/neo-tree.nvim",
  config = function()
    require("neo-tree").setup {
      ...
      -- Set-up event handlers to manage and restore user command-mode state
      event_handlers = {
        {
          event = "neo_tree_buffer_enter",
          handler = function()
            vim.g.forgetfulme = vim.api.nvim_get_mode().mode
            if vim.g.forgetfulme == "i" then vim.cmd "stopinsert" end
          end,
        },
        {
          event = "neo_tree_buffer_leave",
          handler = function()
            if vim.g.forgetfulme == "i" then vim.cmd "startinsert" end
            vim.g.forgetfulme = vim.api.nvim_get_mode().mode
          end,
        },
      },
    }
  end,
}

```
