### ISSUE TITLE
`:NeoTreeReveal!` to skip prompt for changing the cwd

### ISSUE THREAD

**Issue by Neelfrost** [nvim-neo-tree/neo-tree.nvim#139]
Is it possible to add `:NeoTreeReveal!` such that the user is not prompted to switch the cwd i.e., the cwd is switched automatically and the file is focused?

**Comment by nyngwang** [comment]
? cwd is not supposed to be changed by _ant_ file-tree plugin IMOO.

**Comment by nyngwang** [comment]
Sounds like a `autocmd BufEnter * ...`?

**Comment by cseickel** [comment]
That sounds like a good idea. I'll add it.
