### ISSUE TITLE
Do not close popup with <Esc> in INSERT mode

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#1396]
Also with this new suggested event:
```lua
{
  event = "neo_tree_popup_input_ready",
  ---@param input NuiInput
  handler = function(input)
    vim.cmd("stopinsert") -- Enter normal mode
  end,
}
```
I am unable to enter normal mode after manually entering insert mode with `i`, since pressing esc even in insert mode just closes the input. Is there a way to make it so that I need to press `esc` from within normal mode only to exit the input box, as I believe it used to be before?

_Originally posted by @uthmanmoh in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1371#issuecomment-1998578046_

**Comment by pysan3** [comment]
@uthmanmoh I've updated the help page and it should be more helpful for you this time.

And of course you can combine the two into one handler (tbh I recommend registering only one handler for this event).

```lua
    {
      event = "neo_tree_popup_input_ready",
      handler = function()
        -- enter input popup with normal mode by default.
        vim.cmd("stopinsert")
      end,
    },
    {
      event = "neo_tree_popup_input_ready",
      ---@param args { bufnr: integer, winid: integer }
      handler = function(args)
        -- map <esc> to enter normal mode (by default closes prompt)
        -- don't forget `opts.buffer` to specify the buffer of the popup.
        vim.keymap.set("i", "<esc>", vim.cmd.stopinsert, { noremap = true, buffer = args.bufnr }) 
      end,
    }
```

BTW if you have something like `nnoremap jk <esc>` globally, you don't need to remap `<esc>` for the popup but use `jk` to get out of insert mode OOTB.
