### ISSUE TITLE
Creating a new file fails when trying to create a new directory and file in that directory in one go

### ISSUE THREAD

**Issue by mrjones2014** [nvim-neo-tree/neo-tree.nvim#140]
For example, say you have the tree:

```
nvim/
-- lua/
---- init.lua
```
if you put your cursor over `lua/` and press `a` to add a new file, and for the file path you enter `snippets/rust.lua` to create the `snippets/` dir and a file called `rust.lua` inside the new `snippets/` folder, it should be able to create the directory and file in one shot.

Currently it fails because the `snippets/` directory does not exist.

**Comment by nyngwang** [comment]
This is a serious one IMOO. I did want to report this days ago but forgot.

**Comment by cseickel** [comment]
This is in **main** now. If you have time to try it out, please let me know if you run into any issues or not.

**Comment by nyngwang** [comment]
@cseickel: It works perfectly. I think we can close this one  :)
