### ISSUE TITLE
FEATURE: NvChad style

### ISSUE THREAD

**Issue by FormalSnake** [nvim-neo-tree/neo-tree.nvim#1404]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

Neo tree looks ugly and out of place in my setup.

### Describe the solution you'd like.

My telescope looks like this
<img width="1920" alt="Screenshot 2024-03-17 at 10 13 49" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/90651091/52450f6b-1c54-4a5b-ab9b-9201c7248cbc">
And it would be cool if neotree also looked like it.
<img width="1920" alt="Screenshot 2024-03-17 at 10 14 12" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/90651091/54d4bca9-668f-47ae-8de2-4308b28e6b53">

### Describe alternatives you've considered.

i've considered nvim tree but it doesnt work as nicely.

**Comment by cseickel** [comment]
You have two options:

1. Read the docs and style it any way you like: `:h neo-tree-highlights`
2. Open an issue in the NvChad repo asking them to style neo-tree way you want.

Neo-tree doesn't really force any style on the user, it just uses whatever styles are set by your theme. I think what you are looking to change is just these highlights:

```
NeoTreeFloatBorder
NeoTreeFloatTitle
```

If they are not enough and there's something else you want to be able to style that you cannot, open an issue asking for that thing to have a dedicated highlight group.
