### ISSUE TITLE
Incorrect bg color on rename

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#141]
As title. I suppose that the it should have the same color as I set:

```lua
au ColorScheme * hi NeoTreeNormal guibg=NONE
au ColorScheme * hi NeoTreeNormalNC guibg=NONE
```

<img src="https://user-images.githubusercontent.com/24765272/153726553-83d001a4-7972-45bb-9ab1-dc57554eb00d.png" width="500">

**Comment by cseickel** [comment]
Do you mean the `lua` part? It looks like that may be a left over search from vim's built-in `/` search command.

**Comment by nyngwang** [comment]
> Do you mean the lua part?

No. I mean the background of all files and folders.
