### ISSUE TITLE
BUG: Buffer with this name already exists after manually closing neo-tree

### ISSUE THREAD

**Issue by idanarye** [nvim-neo-tree/neo-tree.nvim#1415]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.9.5

### Operating System / Version

Arch Linux 6.7.0-arch3-1

### Describe the Bug

This looks similar to #1365, but since I don't use sessions (the discussion there is mostly about how fix it by fixing session management with a new `)auto_restore_session_experimental = true` setting) and since I've only started experiencing this a couple of days ago (that ticket is almost a month old), I suspect it may be a different bug.

When closing the Neo-tree panel using Vim commands (like `:quit` or like running `:only` from another window), another attempt to open the Neo-tree panel will result in a `Buffer with this name already exists` error.

Note that when I close the panel using Neo-tree (e.g. - by hitting `q` inside it) this problem does not occur.

### Screenshots, Traceback

```
[Neo-tree ERROR] debounce  filesystem_navigate  error:  ...e-bug/plugins/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1036: Vim:E95: Buffer with this name already exists
```

### Steps to Reproduce

1. Run `:Neotree` to open the Neo-tree panel.
2. Run `:close` inside the Neo-tree panel to close it (don't use any of Neo-tree's shortcuts/commands for closing the panel - use Vim's window management commands)
3. Run `:Neotree` again.

### Expected Behavior

I'd expect the Neo-tree panel to just open again.

### Your Configuration

```Lua
local lazypath = "/tmp/reproduce-bug/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

require"lazy".setup({
    {
        "nvim-neo-tree/neo-tree.nvim",
        branch = "v3.x",
        dependencies = {
            "nvim-lua/plenary.nvim",
            "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
            "MunifTanjim/nui.nvim",
            -- "3rd/image.nvim", -- Optional image support in preview window: See `# Preview Mode` for more information
        }
    }
}, {
    root = "/tmp/reproduce-bug/plugins",
})
```

**Comment by idanarye** [comment]
Note that I've managed to workaround this problem by adding this event handle:

```lua
{
    event = 'neo_tree_buffer_leave',
    handler = function()
        local shown_buffers = {}
        for _, win in ipairs(vim.api.nvim_list_wins()) do
            shown_buffers[vim.api.nvim_win_get_buf(win)] = true
        end
        for _, buf in ipairs(vim.api.nvim_list_bufs()) do
            if not shown_buffers[buf] and vim.api.nvim_buf_get_option(buf, 'buftype') == 'nofile' and vim.api.nvim_buf_get_option(buf, 'filetype') == 'neo-tree' then
                vim.api.nvim_buf_delete(buf, {})
            end
        end
    end,
},
```

But this, of course, is an ugly hack.

**Comment by nmfirdausw** [comment]
@idanarye  Its working, haha... Will use this for a while

**Comment by chaozwn** [comment]
Regarding how to reproduce the issue: `<C-w>o`, then open neo-tree.

**Comment by rodhash** [comment]
> Regarding how to reproduce the issue: `<C-w>o`, then open neo-tree.

+1 same here, error persists even after adding the above function into `event_handlers`
