### ISSUE TITLE
FEATURE: Enhancement for the `set_root` command

### ISSUE THREAD

**Issue by xvzc** [nvim-neo-tree/neo-tree.nvim#1419]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like.

Hi, I've been using my custom command called "sync_root" which looks like below.
```lua
  commands = {
    sync_root = function(state)
      if state.search_pattern then
        fs.reset_search(state, false)
      end

      local node = state.tree:get_node()
      local id = node.type == "directory" and node.id or node._parent_id
      fs._navigate_internal(state, id, nil, nil, false)
    end,
  },
```
While the built in `set_root` command allows us to run it only when the neovim cursor is pointing to directories, the `sync_root` function above allows us to set the current directory as root regardless of the location of cursor.

So my question is, would you be interested if i make a PR that enhances the `set_root` commands for `filesystem` and `buffer`?

**Comment by cseickel** [comment]
Sure, I don't see how it can hurt.
