### ISSUE TITLE
Rename file with `$` will cause error

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#142]
As title. You probably need to escape it.

**Comment by cseickel** [comment]
I'm not having this issue. What OS are you on?

**Comment by nyngwang** [comment]
macOS 12.2. To be clear I mean renaming an existing file with a new name like `foo$bar` to reproduce this bug.

**Comment by nyngwang** [comment]
No error, but the `$` is substituted to something else, like a random substring. So `foo$bar` will become `fooX2f4bar`

**Comment by cseickel** [comment]
I remember you mentioning before that you used multiple languages for input, maybe it's related to that?

**Comment by nyngwang** [comment]
@cseickel I think you could put this one with very low priority since most of the time I won't name a file containing a `$`. That I opened this issue is I just accidentally encountered it this morning, in case I will forget.

**Comment by cseickel** [comment]
I'm going to close this one. Since it does happen for me there's really nothing i can do. 

Besides, it seems pretty unusual to have a dollar sign in a file name. I'd say if this affects you and you don't want to submit a PR that fixes it, just rename those files in another way.
