### ISSUE TITLE
BUG: Maps to '<C-W>' don't work while fuzzy finding, moving, etc.

### ISSUE THREAD

**Issue by wtaranto** [nvim-neo-tree/neo-tree.nvim#1421]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.9.5

### Operating System / Version

Fedora 39

### Describe the Bug

I have `vim.keymap.set('!', '<M-BS>', '<C-W>')` in my configs. However, while fuzzy finding, moving, etc., it doesn't delete the previous word like expected, but instead does escapes and moves to the parent node. This appears to be a problem whenever mapping to `<C-W>`. For example, `vim.keymap.set('!', 'a', '<C-W>')` just does nothing when a is pressed in a fuzzy find.

### Steps to Reproduce

1. Put `vim.keymap.set('!', '<M-BS>', '<C-W>')` in config
2. Open neo-tree
3. Start a fuzzy find
4. Type `foo bar`
5. Press `<M-BS>`

### Expected Behavior

The last word should be deleted similarly to how `<C-W>` works in neovim's default insert mode by deleting the previous word. 

### Your Configuration

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  -- add any other plugins here
}

local neotree_config = {
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-tree/nvim-web-devicons", "nvim-lua/plenary.nvim" },
  cmd = { "Neotree" },
  keys = {
    { "<Leader>e", "<Cmd>Neotree<CR>" }, -- change or remove this line if relevant.
  },
  opts = {
    -- Your config here
    -- ...
  },
}

table.insert(plugins, neotree_config)
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
vim.keymap.set('!', '<M-BS>', '<C-W>')
```

**Comment by pysan3** [comment]
If I'm not mistaken, please enable remap = true.

**Comment by wtaranto** [comment]
Thank you, this worked: `vim.keymap.set('!', '<M-BS>', '<C-W>', { remap = true })`

I assume this is because the small popup buffers have to manually map `<C-W>` to delete the previous word, correct?

**Comment by pysan3** [comment]
That's my understanding but I'm not sure. At least I know that `<C-W>` is registered here and if I delete this line, `<C-w>` doesn't delete a word anymore. 

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/16d1b194376bf1fc2acd89ccb3c29ba8315bfcea/lua/neo-tree/ui/inputs.lua#L30

I assume it's something related with NuiInput.
