### ISSUE TITLE
Feature Request: Option to disable "Neo-tree Popup" text in prompt

### ISSUE THREAD

**Issue by kevintraver** [nvim-neo-tree/neo-tree.nvim#1426]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

No, this is a new opt-in config option.

### Describe the solution you'd like.

When using `use_popups_for_input = false`, it would be nice to be able to customize or disable the "Neo-tree Popup" text.

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/16d1b194376bf1fc2acd89ccb3c29ba8315bfcea/lua/neo-tree/ui/inputs.lua#L69

**Comment by pysan3** [comment]
Dup
- https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1222

We will accept PR to fix the problem but will not add an option.
