### ISSUE TITLE
FEATURE: Relative line number 

### ISSUE THREAD

**Issue by hrai** [nvim-neo-tree/neo-tree.nvim#1446]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

It would be much easier to navigate the panel if there were relative line numbers

### Describe the solution you'd like.

If there's a config setting that can be used to leverage this feature, that'd be great.

**Comment by pysan3** [comment]
Unfortunately no. 

- https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1320

As I described in this issue, if you know a way to get the actual window width, PR is definitely very welcomed.

**Comment by pysan3** [comment]
Closing this as duplicate.
