### ISSUE TITLE
Neo-tree can't correctly get diagnostic sings for Neovim 0.10.0-dev-3097+g064f3e42e-dirty

### ISSUE THREAD

**Issue by atchim** [nvim-neo-tree/neo-tree.nvim#1465]
In the code snippet bellow, Neo-tree assumes that for Neovim >= 0.10, `vim.diagnostic.config().signs` is a table. But in my case, using Neovim 0.10.0-dev-3097+g064f3e42e-dirty, the value is a boolean (`true`, to be more specific). I don't know if this is the source of my problems, but Neo-tree just can't use the symbols defined via `vim.fn.sign_define`. 

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/25bfdbe802eb913276bb83874b043be57bd70347/lua/neo-tree/sources/common/components.lua#L77-L114

The following screenshot shows the behavior reported.

![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/56227607/86fb4eaf-114a-4c12-8004-47f5b7d5ca36)

**Comment by johnend** [comment]
Is this fixed? I'm still seeing similar issues: 
![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/3886057/39576dc3-cf84-49f3-bfc2-da036aae784b)

Also if there are three signs the last is also rendered smaller than the others

**Comment by atchim** [comment]
@johnend, previously I was using the now deprecated function `vim.fn.sign_define()`. By switching the signs definition to a modern approach via `vim.diagnostic.config()`, Neo-Tree just started properly displaying the signs. You can learn more about the new way of setting signs via `:h diagnostic-signs`.

**Comment by johnend** [comment]
Yep this works thanks! Docs should be updated on the repo, as it's still pointing to the deprecated `sign_define()` method.
