### ISSUE TITLE
Add option to show git ignored files with indicator

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#148]
One more idea (let me know if it is better to open a new issue):
For the gitignored files, how about adding an option to show them with a symbol like `[I]`, or hide them directly?
E.g., 
```lua
require("neo-tree").setup({
	filesystem = {
		filters = {
			respect_gitignore = true,
			gitignore_treatmente = 'symbol'	-- can be 'hidden' or 'symbol'
		}
	}
})
```

For the symbols, `nvim-tree` uses symbols for different status of files
<img width="152" alt="image" src="https://user-images.githubusercontent.com/11582667/154361528-7b6f5e34-2610-4d4a-ad56-75f24fb43ecf.png">

I think this is a good addition to `neo-tree`

_Originally posted by @yanzhang0219 in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/147#issuecomment-1042335204_

**Comment by cseickel** [comment]
I think this is a good idea @yanzhang0219, I personally like to show any "hidden" files in a different highlight group as well. I'll add both options.

**Comment by cseickel** [comment]
Anyone interested in this feature, please see the discussion at: #171

**Comment by cseickel** [comment]
This has been partially implemented in a new **v2.x** branch. The way it works now, if you show hidden files, git ignored files will be marked with it's own highlight group (grey) and use the `[!!]` marker. I'll also update or add a new component that can replace these codes with symbols in a future update.

**v2.x** has breaking changes to the filters config. These options have been completely changed:

```lua
    require("neo-tree").setup({
      filesystem = {
        filtered_items = {
          visible = false, -- when true, they will just be displayed differently than normal items
          hide_dotfiles = true,
          hide_gitignored = true,
          hide_by_name = {
            ".DS_Store",
            "thumbs.db"
            --"node_modules"
          },
          never_show = { -- remains hidden even if visible is toggled to true
            --".DS_Store",
            --"thumbs.db"
          },
        },
      }
    })
```

WARNING: **v2.x** is brand new and far from release. It will have many breaking changes, although I will alert you to these changes and try to auto migrate your existing config options.

**Comment by cseickel** [comment]
I've added my own set of symbols that I like better:

![image](https://user-images.githubusercontent.com/5160605/157349462-656caef3-bc97-4663-b685-0762ee5c9dfc.png)

![image](https://user-images.githubusercontent.com/5160605/157349649-4f8c7c05-d7d9-49b9-9355-63d986110b18.png)


This will be merged to 2.x soon, I''m not sure when 2,x will be released. Let me know if you have any feedback.

**Comment by nyngwang** [comment]
I want this cool feature AS SOON AS POSSIBLE.
