### ISSUE TITLE
BUG: v3.x not updated to latest release

### ISSUE THREAD

**Issue by metalinspired** [nvim-neo-tree/neo-tree.nvim#1483]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.11.0-dev

### Operating System / Version

Kubuntu 23.10

### Describe the Bug

It seems that v3.x branch is still on version 3.25 instead of 3.26

### Steps to Reproduce

Use the configuration for Lazy from README.

### Expected Behavior

Version 3.26 should be installed.

### Your Configuration

```Lua
{
    'nvim-neo-tree/neo-tree.nvim',
    branch = 'v3.x',
    dependencies = {
      'nvim-lua/plenary.nvim',
      { 'nvim-tree/nvim-web-devicons', enabled = vim.g.have_nerd_font },
      'MunifTanjim/nui.nvim',
    },
}
```

**Comment by pysan3** [comment]
Dang it. You are right. 

Please wait a few days.

**Comment by cseickel** [comment]
@pysan3 there is a release script in the root of the repo that I always used if you don't want to do all of this by hand.

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/release.sh

**Comment by pysan3** [comment]
Thanks but I wanted to add a bit of announcement to the release note so I did it manually and totally forgot to update 3.x branch. 

https://github.com/nvim-neo-tree/neo-tree.nvim/releases/tag/3.26

**Comment by pysan3** [comment]
I should have updated `v3.x` branch if not mistaken.

Could you check if it's working @metalinspired?
And if yes, please close this issue.

Thanks a lot for notifying me!
