### ISSUE TITLE
Exclude files/dirs by pattern

### ISSUE THREAD

**Issue by rockyzhang24** [nvim-neo-tree/neo-tree.nvim#149]
How about adding an option to exclude some files/directories based on a pattern to make them being hidden?

E.g., 
```lua
require("neo-tree").setup({
	filesystem = {
		filters = {
			respect_gitignore = true,
			exclude_pattern = { 'node-module', '.DS_Store' }
		}
	}
})
```

Thanks.

**Comment by cseickel** [comment]
I'm not seeing a situation where someone would want to hide a file in Neo-tree without actually making it hidden at the OS level or putting it in a gitignore file. In your example, `node_modules` should be in .gitignore and `.DS_Store` is already hidden and won't be shown by default.

**Comment by cseickel** [comment]
I just realized that there is no way to rename `node_modules`, and therefore no way to hide it outside of windows if it's not in a repo. Just another reason to hate the nodejs ecosystem...

I can add something. I am considering adding a more generic `process_item` option that is a function to be called on every item before it is added. That way it could be used for other purposes, one of which being returning `nil` to exclude it from the results.

**Comment by yanzhang0219** [comment]
Thanks. 

> I'm not seeing a situation where someone would want to hide a file in Neo-tree without actually making it hidden at the OS level or putting it in a gitignore file

Not really. For example, sometimes I want to see the whole contents (including hidden ones) in a certain directory that is not a git repo, but only hide `.DS_Store` that exists in each folder on macOS. In this situation, I cannot put it into `.gitignore` and all hidden files need be shown other than `.DS_Store`. So we need an extra option for such a file. `nvim-tree` has this, it is `filter.custom`.

**Comment by nyngwang** [comment]
Waiting for this. I'm working on a python project where I need to ignore folder like `__pycache__/`.

**Comment by cseickel** [comment]
I'm going to work on this now. Since it seems like all examples so far are exact names and not patterns, I plan on implementing it as an exact match which will be much faster. Let me know if anyone sees the need for patterns.

**Comment by cseickel** [comment]
Anyone interested in this feature, please see the discussion at: #171

**Comment by cseickel** [comment]
This has been added to a new **v2.x** branch, along with breaking changes to the filters config. These options have been completely changed:

```lua
    require("neo-tree").setup({
      filesystem = {
        filtered_items = {
          visible = false, -- when true, they will just be displayed differently than normal items
          hide_dotfiles = true,
          hide_gitignored = true,
          hide_by_name = {
            ".DS_Store",
            "thumbs.db"
            --"node_modules"
          },
          never_show = { -- remains hidden even if visible is toggled to true
            --".DS_Store",
            --"thumbs.db"
          },
        },
      }
    })
```

WARNING: **v2.x** is brand new and far from release. It will have many breaking changes, although I will alert you to these changes and try to auto migrate your existing config options.

**Comment by nyngwang** [comment]
> [...] Since it seems like all examples so far are exact names and not patterns, I plan on implementing it as an exact match which will be much faster. [...] [link to comment](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/149#issuecomment-1053690076)

This must be a good idea. I prefer clearly specify any file I want to ignore, so I won't accidentally ignore some files in the future. The speed should have the highest priority, too.

**Comment by nyngwang** [comment]
It's a little bit unclear for me: If I set both `hide_dotfiles/gitignored` to `true` and have `visible = true`, are these "hidden" files got shown/visible?

**Comment by cseickel** [comment]
> > [...] These options have been completely changed: [...] [link](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/149#issuecomment-1059987718)
> 
> It's a little bit unclear for me: If I set both `hide_dotfiles/gitignored` to `true` and have `visible = true`, are these "hidden" files got shown/visible?

If `visible = true`, then all filtered_items are visible, but will be highlighted differently, like this:
![image](https://user-images.githubusercontent.com/5160605/157719347-3eee98c7-dbaf-47cf-a0f2-2f7414883a61.png)

In that screenshot, `doc/tags` is a gitignored file, and the rest are just dotfiles. The `H` mapping now toggles the visibility of all these files at once.

**Comment by nyngwang** [comment]
I'm on the `v2.x`-branch and tried this option:

```
          filtered_items = {
            hide_dotfiles = false,
            hide_gitignored = false,
            never_show = {
              '.DS_Store',
              '__pycache__/'
            }
          },
```

but the folder is still shown :(
