### ISSUE TITLE
Disable relative line numbers

### ISSUE THREAD

**Issue by onneva** [nvim-neo-tree/neo-tree.nvim#15]
Great plugin - thank you!

Is there a way to disable relative line numbers from appearing within the neo-tree window automatically?

**Comment by cseickel** [comment]
Definitely. I didn't have that turned on by default so I didn't realize that it was not being explicitly turned off for the tree window like normal line numbers were. This will be fixed in the next release.

**Comment by cseickel** [comment]
Fixed in [Release v1.6](https://github.com/nvim-neo-tree/neo-tree.nvim/releases/tag/v1.6)
