### ISSUE TITLE
Ability to use system open on a file

### ISSUE THREAD

**Issue by wavded** [nvim-neo-tree/neo-tree.nvim#150]
Thanks for the great plugin. Coming from NerdTree and NvimTree, it would be great to add a command to open the file with the system (e.g. `open` on macOs).

**Comment by cseickel** [comment]
This is not something I will be adding personally because I would never use it, but I'd be happy to merge a PR if someone else wants to add it. It's also a good candidate for a custom command. See `:help neo-tree-custom-commands` or https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#commands

**Comment by wavded** [comment]
This worked for me, thx for the pointers. I personally use this a lot (for binary or previewing files):

```lua
require("neo-tree").setup({
  filesystem = {
    window = {
      mappings = {
        ["o"] = "system_open",
      },
    },
    commands = {
      system_open = function(state)
        local node = state.tree:get_node()
        if node and node.type == "file" then
          local file_path = node:get_id()
          vim.api.nvim_command("silent !open -g " .. file_path)
        end
      end,
    },
  },
})
```

**Comment by cseickel** [comment]
Thanks for sharing! If you don't mind, I'd like to add this to the [Recipes](https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#commands) section of the Wiki. I'll also leave the issue open in case someone wants to add in all the cross platform parts needed for a built-in command.

**Comment by wavded** [comment]
Sure thing 👍🏻

**Comment by nyngwang** [comment]
@wavded  This one is cool. Can this be able to open finder when the cursor is hovered on a folder?

**Comment by wavded** [comment]
Yeah, that is a useful idea. This will open up directories as well now.

```
require("neo-tree").setup({
  filesystem = {
    window = {
      mappings = {
        ["o"] = "system_open",
      },
    },
    commands = {
      system_open = function(state)
        local node = state.tree:get_node()
        local path = node:get_id()
        -- macOs specific -- open file in default application in the background
        vim.api.nvim_command("silent !open -g " .. path)
      end,
    },
  },
})
```

**Comment by nyngwang** [comment]
@wavded Awesome! Now I'm sure this tree is absolutely a replacement of the nvim-tree.lua :) (which has this ability too.)

**Comment by nyngwang** [comment]
@wavded Just test it and it works nicely. Have a nice day!
