### ISSUE TITLE
BUG: Can't unbind actions

### ISSUE THREAD

**Issue by ic-768** [nvim-neo-tree/neo-tree.nvim#1537]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

NVIM v0.11.0-dev-475+g5fc25ecc7

### Operating System / Version

Linux

### Describe the Bug

After mapping an action such as `fuzzy_finder` or `set_root` to a certain key, the default key isn't cleared.
I would like to clear `fuzzy_finder` off of `/` so that I can use vim's native visual search. 

### Steps to Reproduce

In config:

```
mappings = {
		["F"] = "fuzzy_finder",
		["/"] = nil,
					}
```

### Expected Behavior

Unbind `/`

### Your Configuration

```Lua
It's a very straightforward issue and my config is complicated please don't make me fill this out :(
```

**Comment by soifou** [comment]
Are you sure you read the doc? You need to set either `none` or `noop`. 
See `:h neo-tree-custom-mappings`

**Comment by ic-768** [comment]
Yep, missed that. Thanks!
