### ISSUE TITLE
FEATURE: disable fuzzy_finder

### ISSUE THREAD

**Issue by nagy135** [nvim-neo-tree/neo-tree.nvim#1543]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

I like to search my buffer using the same way neovim does everywhere

### Describe the solution you'd like.

boolean flag that disables this fuzzy_searching entirely, in config. Maybe i just missed this somewhere i just dont see any mention in readme

**Comment by pysan3** [comment]
Sorry I'm on my phone and can't give detailed explanation. 

You can map `["/"] = "noop"` to revive the simple vim `/` keybind to search.

**Comment by nagy135** [comment]
well that works, should have thought about that ...but at least we gave a clear path for anyone searching this as well i guess
