### ISSUE TITLE
FEATURE: Git status for submodules

### ISSUE THREAD

**Issue by tomkimsour** [nvim-neo-tree/neo-tree.nvim#1555]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

I have a project with many submodules. When neotree is set a higher level than a git repo, then it would not display git changes for the child directories.

### Describe the solution you'd like.

Always see git status for files in subdirectories, even if there is multiple projects

**Comment by jdeamicis** [comment]
Possibly related to #1394

**Comment by tomkimsour** [comment]
completely related to it. I'll close that one
