### ISSUE TITLE
Add event `VIM_COLORSCHEME`

### ISSUE THREAD

**Issue by lopi-py** [nvim-neo-tree/neo-tree.nvim#156]
Useful to update neo-tree highlights when changing neovim colorscheme. Also should add internal `require("neo-tree.ui.highlights").setup` handler

I have this by now
```lua
autocmd("ColorScheme", require("neo-tree.ui.highlights").setup)
```

**Comment by cseickel** [comment]
Interesting. I didn't realize that would be needed. What highlights are an issue without this autocmd?

**Comment by lopi-py** [comment]
I'm just getting highlight for devicons (without autocmd)
![image](https://user-images.githubusercontent.com/70210066/155785045-6210aceb-b298-4e35-9618-d566758a5be3.png)
