### ISSUE TITLE
FEATURE: allow Tab to autocomplete the file name on add command

### ISSUE THREAD

**Issue by srghma** [nvim-neo-tree/neo-tree.nvim#1565]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

suppose I am in a dir with already existing file `mkInitDbScript.sh`

![2024-09-19_15-18-10](https://github.com/user-attachments/assets/6e117d10-8f56-43c8-a99e-5cb4bc1820e8)

I want to add to this dir also a file `mkInitDbScript.nix`

I press `a`, I write `mk`, I press `<tab>` but it doesnt autocomplete

![2024-09-19_15-18-25](https://github.com/user-attachments/assets/fd1eb13d-c653-4493-9c99-5df21d42d6e3)

### Describe the solution you'd like.

I want it to autocomplete

**Comment by miversen33** [comment]
Duplicate request to #1167
