### ISSUE TITLE
FEATURE: Needs to be adapted to Neovim 0.11

### ISSUE THREAD

**Issue by Zeioth** [nvim-neo-tree/neo-tree.nvim#1588]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

We are using some functions that are deprecated on nvim 0.11, causing a warning when the user open neotree.
![screenshot_2024-10-16_13-41-46_450235378](https://github.com/user-attachments/assets/cefe6776-878c-4f3a-9697-637d1eb3fc10)

### Describe the solution you'd like.

Replace the deprecated functions by the new ones.

### Additional Context

More or less high prio, as more people are starting to use nvim 0.11

**Comment by Zeioth** [comment]
Lines that need to be updated.

![screenshot_2024-10-16_14-06-33_394569830](https://github.com/user-attachments/assets/f34f3a49-49e5-4388-bbf8-201aec04a06c)

**Comment by pynappo** [comment]
I don't see a use of `islist` anywhere in neo-tree and it seems to have been fixed in plenary since may, closing this https://github.com/nvim-lua/plenary.nvim/commit/ce8556de8fa51c783bee6304cbe012407ea413b9are
