### ISSUE TITLE
FEATURE: mini.icons support

### ISSUE THREAD

**Issue by Zeioth** [nvim-neo-tree/neo-tree.nvim#1589]
### Did you check the docs?

- [X] I have read all the docs.

### Is your feature request related to a problem? Please describe.

Icons are displayed correctly when using `nvim-web-devicons`, buf fallback to a default icon when using `mini.icons`.

### Describe the solution you'd like.

Support mini.icons, as it's reduced complexity is less likely to run into bugs and regressions.

**Comment by pynappo** [comment]
related: https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1527

So far since it's just mini.icons and nvim-web-devicons maybe we could add a preset for those... will see if adoption for mini.icons keeps increasing and see what to do from there.

**Comment by Zeioth** [comment]
Thank you for pinging me @pynappo 
closed by #1527
