### ISSUE TITLE
Disable Completions in neotree

### ISSUE THREAD

**Issue by Muizzyranking** [nvim-neo-tree/neo-tree.nvim#1626]
I am using blink cmp and I get completions when I try to create a new file or rename a file, this is really annoying. What is the input filetype so I can add it to the list of filetype I do not want completions? I thought it was prompt, but it wasn't it. i have also tried neo-tree as filetype and it is not working still.

**Comment by miversen33** [comment]
Please don't spam your question. 

#1625

I believe the file type is `neotree`. Try that and see if it works

**Comment by Muizzyranking** [comment]
Appologies, I have tried both neotree and neo-tree, none of them works. I even tried prompt, it doesn't work still.

**Comment by miversen33** [comment]
Doing a quick check with `set filetype?` in nvim
![image](https://github.com/user-attachments/assets/c5b61c73-4df4-4822-a247-375dad7c3077)


The filetype is `neo-tree`. [Indeed, the source reflects this](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/ecf9ba5d017bb80d859124388a32313c7ee423e9/lua/neo-tree/ui/renderer.lua#L936)

If you are having issues with blink showing up when its not supposed to, I would reach out to the developers of blink. I suspect you aren't the first person to have this issue, they are likely flooded with interest right now

**Comment by Muizzyranking** [comment]
It's the input window and the file type is not neotree. Thank you, I'll report to blink.

**Comment by Muizzyranking** [comment]
I have been able to fix this, disabling blink in `neo-tree-popup` will stop autocompletion while creating/renaming a file in neotree.
