### ISSUE TITLE
BUG: Widths of components with header can not be changed with configurations

### ISSUE THREAD

**Issue by Kaiser-Yang** [nvim-neo-tree/neo-tree.nvim#1638]
### Did you check docs and existing issues?

- [X] I have read all the docs.
- [X] I have searched the existing issues.
- [X] I have searched the existing discussions.

### Neovim Version (nvim -v)

0.10.1

### Operating System / Version

WSL2 + Ubuntu 22.04 LTS

### Describe the Bug

I want to change the width of a components like: file_size. But this will not work.

This is caused by the fixed size when calling `get_header`:

![image](https://github.com/user-attachments/assets/aeaeba9b-208e-4b0b-9003-3ed08d4e0550)

This will cause a problem when I set width smaller than `12`, it will stay the width with `12`.

![image](https://github.com/user-attachments/assets/225ce30a-8cad-48e7-9d58-0a8ce90d8d26)

### Steps to Reproduce

None.

### Expected Behavior

Update the code calling get_header to make them respect the configurations.

### Your Configuration

```Lua
None
```

**Comment by Kaiser-Yang** [comment]
BTW, these should be updated with `%s` to make `fit_content` work.

![image](https://github.com/user-attachments/assets/672837ca-5433-4f0e-9f91-f973613497b7)

**Comment by pynappo** [comment]
Already implemented on `main` @ https://github.com/nvim-neo-tree/neo-tree.nvim/commit/395ce4675a54828f9fd730d78f7910c114ab0a49, I'll merge the recent fixes into branch 3.x soon, sorry about the wait.
