### ISSUE TITLE
NeoTree <args>

### ISSUE THREAD

**Issue by wookayin** [nvim-neo-tree/neo-tree.nvim#167]
It would be great if `:NeoTreeReveal`, `:NeoTreeShow`, etc. commands are accepting path as the argument to open a specific directory. If one is using a netrw-hijacking mode, `:e <args>`, etc. would work for this, but there are some rare cases more direct API or command would be needed not assuming the hijacking behavior.

For example:

```
:NeoTreeShow /some/path/to/open
:NeoTreeFloat /some/path/to/open
```

In addition to command, it would be even better if there is a equivalent Lua API to open a new neo-tree window (with some options).

**Comment by wookayin** [comment]
It is already there:

```
command! -nargs=? NeoTreeFloat         lua require("neo-tree").float("<args>")       
command! -nargs=? NeoTreeFocus         lua require("neo-tree").focus("<args>")       
command! -nargs=? NeoTreeShow          lua require("neo-tree").show("<args>", true)  
```

But this gives me an error:

```
:NeoTreeShow /

E5108: Error executing lua /Users/wookayin/.vim/plugged/neo-tree.nvim/lua/neo-tree.lua:80: bad argument #2 to 'error' (number expected, got string)
stack traceback:
        [C]: in function 'error'
        /Users/wookayin/.vim/plugged/neo-tree.nvim/lua/neo-tree.lua:80: in function 'check_source'
        /Users/wookayin/.vim/plugged/neo-tree.nvim/lua/neo-tree.lua:456: in function 'show'
        [string ":lua"]:1: in main chunk
```

**Comment by wookayin** [comment]
BTW, command completions could be added for all the commands.

**Comment by cseickel** [comment]
The args in this case are just the source to show, such as `filesystem`, `'buffers`, or `git_status`. There is an open issue to revamp the Command to use a single command with arguments that would cover all possible actions. That is stalled right now but I might pick it up and get that done soon. #31 #61

**Comment by wookayin** [comment]
So how to achieve this exactly?

**Comment by cseickel** [comment]
```
:Neotree show /some/path/to/open
:Neotree float /some/path/to/open
```

See https://github.com/nvim-neo-tree/neo-tree.nvim/tree/v2.x#the-neotree-command for a complete description

**Comment by wookayin** [comment]
Thanks, they are working. I reported another bug about this #186.

It would be nice to have a lua API -- I looked at the code and it currently lacks modularity so I have to make some list of argument and pass directly to `M._command` or something. We could consider adding this feature at a later point.

**Comment by cseickel** [comment]
> It would be nice to have a lua API -- I looked at the code and it currently lacks modularity so I have to make some list of argument and pass directly to `M._command` or something. I am opposed to deprecating lua functions corresponding to each Neotree subcommand. We could consider adding this feature back at a later point.

You are actually expected to use `neo-tree.commands.execute()` if you want to use the lua API. Having the separate functions was a mistake and it was impossible to model all of the possible variations that people wanted in a clean way with separate commands. Having a single command that takes an object as an argument also makes it much easier to add new arguments later in a backwards compatible way without creating a mess.
