### ISSUE TITLE
[Suggestion] Use default highlight group for diagnostic icons

### ISSUE THREAD

**Issue by AndreAugustoAAQ** [nvim-neo-tree/neo-tree.nvim#170]
The plugin can use custom diagnostic icons
By default `nvim` already has the `DiagnosticSign*` highlight group
But currently the plugin uses `LspDiagnosticsSign`, as seen [here][0]
It would be interesting to change the origin of the icons to the `nvim` default

A plugin that would be useful for this is [ray-x/navigator.lua][1], which sets icons using the default highlight group
This would make it easier to define icons, and also more practical to have uniform icons in `nvim`
If the person already uses [ray-x/navigator.lua][1], the icons will be taken from there, or if not, you can set the icons as it is currently done, just changing the name of the highlight used.

The [function where the severity is obtained][severity] is also necessary to change, changing Warning to Warn and Information to Info

<details>
<summary>Severity function code</summary>

Current code:
```lua
local diag_severity_to_string = function(severity)
  if severity == vim.diagnostic.severity.ERROR then
    return "Error"
  elseif severity == vim.diagnostic.severity.WARN then
    return "Warning"
  elseif severity == vim.diagnostic.severity.INFO then
    return "Information"
  elseif severity == vim.diagnostic.severity.HINT then
    return "Hint"
  else
    return nil
  end
end
```

Modified code:
```lua
local diag_severity_to_string = function(severity)
  if severity == vim.diagnostic.severity.ERROR then
    return "Error"
  elseif severity == vim.diagnostic.severity.WARN then
    return "Warn"
  elseif severity == vim.diagnostic.severity.INFO then
    return "Info"
  elseif severity == vim.diagnostic.severity.HINT then
    return "Hint"
  else
    return nil
  end
end
```

</details>

If the suggestion is accepted, I can make these changes

[0]: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/0fd720115887f006fe4867e65c68ab24d95b51dd/lua/neo-tree/sources/common/components.lua#L60
[severity]: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/0fd720115887f006fe4867e65c68ab24d95b51dd/lua/neo-tree/utils.lua#L11-L23
[1]: https://github.com/ray-x/navigator.lua "ray-x/navigator.lua"

**Comment by cseickel** [comment]
I think I had the Lsp* hl groups because that was the standard in earlier versions and I never saw the change. I think it would be good to move to the standard names, but this is a breaking change so some care would need to be taken to ensure that the old LspDiagnostic* groups would still work the same if anyone had defined their own settings for those groups.

> It would be interesting to change the origin of the icons to the nvim default

Are there default icons that I can be using?

**Comment by AndreAugustoAAQ** [comment]
> I think I had the Lsp* hl groups because that was the standard in earlier versions and I never saw the change. I think it would be good to move to the standard names, but this is a breaking change so some care would need to be taken to ensure that the old LspDiagnostic* groups would still work the same if anyone had defined their own settings for those groups.

Yes, Lsp* are the past versions, and from what we find in these [PR][nvim pull] that the group names have been changed

One way to maintain compatibility is to use the [solution] used in [ray-x/navigator.lua][navigator commit]
It checks if vim.diagnostic exists, which was implemented along with the name change, if it returns false it uses the old nomenclature

> Are there default icons that I can be using?

I particularly use these icons
error '' | nf-mdi-close_circle
warn '' | nf-mdi-alert
info '' | nf-mdi-information
hint '' | nf-mdi-lightbulb

[nvim pull]: https://github.com/neovim/neovim/pull/15585
[navigator commit]: https://github.com/ray-x/navigator.lua/commit/79fee5dda81bef29fac7604d7f61e8e529418015
[solution]: https://github.com/ray-x/navigator.lua/blob/3adbbaf5098dae1db8b370f5f28f7b242348d272/lua/navigator/lspclient/highlight.lua#L26-L57

**Comment by cseickel** [comment]
With the highlight groups, it's not that I care what version of nvim the user is one so much as I care about whether or not they are defining the old style of highlight groups themselves, either before or after the Neo-tree config runs. If they do, and we switch to using the new style internally, then their carefully selected colors will suddenly stop being used.

I think the answer right now, in v1.x, is that when we check for the existence of those groups in setup, if they don't yet exist we will try to link them to the new style if that exists before defining them with our default values. Of course, if someone defines them later after our config runs, it could cause an error if they don't first unlink that group, so it could still be a breaking change.

I think this is a good idea, but it should wait for 2.x, which is coming soon.


On the icons issue, it doesn't sound like there are any default icons at all, so we will need to stick with the current strategy of telling users how to define their own in the docs. Maybe that should be elevated to the Quickstart in the readme.

**Comment by gsalvatella** [comment]
I second this change for 2.x. As I changed `DiagnosticSign*` for the LSP diagnostics I quickly noticed that the ones in NeoTree had not been changed and thought initially that it may have been a problem with NeoTree itsellf. Elevating to Quickstart would be helpful. In the end the aren't that many configuration parameters, and these will become more relevant as nvim users migrate to LSP.

**Comment by AndreAugustoAAQ** [comment]
+1 for the 2.x
The icons for those who have not defined can be the letters (E I W H) as is already done.
A deprecation notice would be great too.
