### ISSUE TITLE
Open parent directory of currently open file when invoking `NeoTreeRevealInSplit`

### ISSUE THREAD

**Issue by strange** [nvim-neo-tree/neo-tree.nvim#175]
`nvim-tree` and `vinegar` both do this and I really like the behavior. If `NeoTreeRevealInSplit` is called and the current buffer is:

- `nofile`: just open the current working directory (current behavior).
- An existing file: open the parent directory (as opposed to the working directory today).
- A directory: go up one level (current behavior).

**Comment by cseickel** [comment]
I think a good solution for this is to add the ability to specify the working directory as an argument to the command, then you can create your mapping with the behavior you are looking for. I'll include this in the work for #31.

**Comment by strange** [comment]
That should work just fine!

**Comment by marcuscaisey** [comment]
I think this behaviour was already implemented, there was just a bug. https://github.com/nvim-neo-tree/neo-tree.nvim/pull/178 fixes

**Comment by strange** [comment]
I just tried it again (`main`) and now it seems to work exactly the way I want it to.

I found the following commit that is related to handling paths when revealing in split:

https://github.com/nvim-neo-tree/neo-tree.nvim/commit/6c84fef01e600dc4cd2db8151ca86737f4130ec9

**Comment by cseickel** [comment]
I think you're right! This was actually just a bug and I didn't realize it.
