### ISSUE TITLE
Some issues with :Neotree <cmd> <args>: 

### ISSUE THREAD

**Issue by wookayin** [nvim-neo-tree/neo-tree.nvim#186]
Command: `:Neotree show /`

It seems that this command hasn't gained much test, so I ran into some issues when running the command (#167). Those commands would need more comprehensive testing involving several corner cases.

(1) Bug: It raises an error:
```
[neo-tree.nvim] [ERROR 17:29:21] ...plugged/neo-tree.nvim/lua/neo-tree/sources/common/file-items.lua:67: bad argument #1 to 'sub' (string expected, got nil)
```

The line is `elseif f.hide_dotfiles and string.sub(item.name, 1, 1) == "." then`. I wonder if it's just a mistake: I might work around as `item.name or {}` but you could have meant `item.path` or something.

(2) Bug: Even if I work around this, I do see a weird error
```
 is not accessible by the current user!
```
Perhaps the directory `/` (or anything else) is something that I don't own. But it should still show the tree as read-only mode. I guess this is related to git status stuff.

(3) When running `:Neotree show|reveal` while having a neotree open, the explorer will close and then be re-opened.

(4) The following also do not work:
```
:Neotree show ls/
-> Invalid argument: ls/

:Neotree show README.md        " (which is an invalid usage)
-> it just shows the previous or current directory?
```
where `ls/` is expected to be interpreted as an argument which does not exist, but the parser is trying to recognize them as some subcommand argument.

(5) Suggestion: I am trying to do something like `:NeotreeShowInSplit /some/path/to/open`, but I don't understand how it can be translated to `:Neotree show current`. The meaning of this optional attribute or semantics of this command doesn't seem intuitive enough; and documentation could be better in clarifying the command arguments.

I could do like `:Neotree reveal current /some/path/too/open`, but this syntax sounds really strange to me, as options and arguments are ambiguous for the parser (#31). As another example, if I would want to open a directory named `current` then how can I do this?

**Comment by cseickel** [comment]
> Command: `:Neotree show /`

That's an obvious test I should have done... I would never browse from root so it never occurred to me. 🤷‍♂️  I'll fix that.


> Perhaps the directory `/` (or anything else) is something that I don't own. But it should still show the tree as read-only mode. I guess this is related to git status stuff.

There's no issue with browsing read only files. It's probably just using a bad path due to the first error.


> (3) When running `:Neotree show|reveal` while having a neotree open, the explorer will close and then be re-opened.

I think I just introduced that bug when fixing a problem with the float option not closing other windows. I'll fix that too.


> (4) The following also do not work:
> 
> ```
> :Neotree show ls/
> -> Invalid argument: ls/
> 
> :Neotree show README.md        " (which is an invalid usage)
> -> it just shows the previous or current directory?
> ```
> 
> where `ls/` is expected to be interpreted as an argument which does not exist, but the parser is trying to recognize them as some subcommand argument.

If `ls` was a folder in the current working directory, it _should_ be recognized as such. You can get autocomplete on folder names if you start with a `/` for absolute paths or `./` for relative ones. Same with the README.md argument, that would reveal the file if it was in the working directory.


> (5) Suggestion: I am trying to do something like `:NeotreeShowInSplit /some/path/to/open`, but I don't understand how it can be translated to `:Neotree show current`. The meaning of this optional attribute or semantics of this command doesn't seem intuitive enough; and documentation could be better in clarifying the command arguments.
> 
> I could do like `:Neotree reveal current /some/path/too/open`, but this syntax sounds really strange to me, as options and arguments are ambiguous for the parser (#31). As another example, if I would want to open a directory named `current` then how can I do this?

Looks like you figured it out. My goal is to be as open ended as flexible as possible. If it seems to verbose, I think the solution is to create your own command that embeds whatever default values that make sense to you, such as:

```
command! -nargs=1 NeoTreeShowInSplit Neotree reveal current dir=<args>
```

If you want to open a directory that happens to be an argument, prefix it with `./` or 'dir='. I would personally recommend always starting path arguments with `./` so you can get tab completion. This is really the solution to many of the issues you are having.

I'll improve the documentation around the dir and reveal_path arguments.

**Comment by cseickel** [comment]
Also, I really should have mentioned somewhere that the command has tab completion, which makes it easier to discover valid options. That's another thing to add to the documentation.

**Comment by wookayin** [comment]
Regarding (1-2), `Neotree show /` still doesn't work for me. I see `item.name` is still `nil`.

(4-5): The current behavior is very confusing and **ambigious**. So the command we have now `:Neotree show [current] dir=/the/path/you want`. But do you think this is a good design or API?  In my view, this is somewhat like a mess from users' perspective. Will you assign a new subtoken if you need to extend something in the future? For the sake of backward compatibility, I would suggest something like`:Neotree show --current /the/path/you...` which is closer to GNU's cmdline convention. As some vim/neovim plugins are using such approaches, I would find this more intuitive, and a safer option taking some future changes/extensions into consideration.

I think there is a smell in `:Neotree show current something` working *implicitly* like `... dir=something` if `something` is a file/directory.

**Comment by cseickel** [comment]
> Will you assign a new subtoken if you need to extend something in the future?

Yes, that's the idea.

> So the command we have now :Neotree show [current] dir=/the/path/you want

Just to be clear, every argument is optional, not just `[current]`. If you run `:Neotree` by itself it will just take default values for every argument, just like the old `:NeoTreeFocus`.

> For the sake of backward compatibility, I would suggest something like`:Neotree show --current /the/path/you...` which is closer to GNU's cmdline convention.

The `--` just seems like extra work to me, and why is there a `--` in front of `current` but not `show`? If you find it ambiguous, you can use the key=value notation instead:

```
:Neotree action=show position=current dir=/some/path
```

> I think there is a smell in :Neotree show current something working implicitly like ... dir=something only if something is a file/directory.

It's just a convenience, I personally hate unnecessary typing. If you want to type more, go ahead and enjoy the key=value notation instead! Also, if you start all relative paths with `./`, that' enough to distinguish it as a path without all the extra typing.

Can you describe what your ideal command syntax would be? Is it just that you'd like everything to be in `--argument=value` form except for the dir?

**Comment by cseickel** [comment]
@wookayin I expanded on the Neotree command section of the readme and enabled offering the key=value form in tab completions of the command. Let me know if that makes it any more intuitive.

**Comment by wookayin** [comment]
@cseickel Sorry, I was occupied for the last few days and checked in this now. It's unfortunate to see that you already went through it, but I still don't like the form of the current command arguments. For example, as I said earlier, it is **ambiguous by nature**. In the command `Neotree show current`, we cannot easily tell `show` or `current` is a directory or a directive. My preference/suggestion was like having all arguments `--argument=value` --- think about how POSIX `ls` (or other shell commands) command is written; IMHO in this way we could make it more flexible and intuitive, and open to future extension with less breaking changes. 

But given that `key=value` syntax are supported, users might feel it's reasonable enough and OK. At least other actions or behaviors I wanted to achieve can be implemented using the current ~API~ command. Although I personally don't like such a convention and cannot tell it's better, I respect your decision about the current command and will just use as-it-is. Thanks for the consideration.
