### ISSUE TITLE
Error caused by async git_status

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#187]
Probably related to this, at the current `main` branch:

sometimes it correctly show the folder structure, sometimes it shows an error:

```
Error executing vim.schedule lua callback: ...k/packer/start/neo-tree.nvim/lua/neo-tree/git/status.lua:58: atte
mpt to index local 'line' (a nil value)
stack traceback:
        ...k/packer/start/neo-tree.nvim/lua/neo-tree/git/status.lua:58: in function 'parse_git_status_line'
        ...k/packer/start/neo-tree.nvim/lua/neo-tree/git/status.lua:141: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

__Update__: I just switch to the `v2.x`-branch and the bug is gone :) And I found the `:Neotree migrations` guide really helpful and easy to follow!

https://user-images.githubusercontent.com/24765272/159196193-a2db7814-eae1-4232-b442-827eeab5a172.mov

_Originally posted by @nyngwang in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/184#issuecomment-1073412394_

**Comment by cseickel** [comment]
@nyngwang This isn't happening to me so I can't be sure it's fixed, but the latest commit on main should deal with the error in your video. Can you try it out and let me know how it goes?

**Comment by nyngwang** [comment]
@cseickel Fixed confirmed.
