### ISSUE TITLE
`<esc>` to close input leaves window in insert mode

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#189]
hi @cseickel I just ran into this issue. I try to hit `<esc>` to close the `popup inputs`. The popup was closed, the window is still in `insert` mode. Is this a bug? or we need to add a custom keymap to also switch to normal mode?

_Originally posted by @sandangel in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/21#issuecomment-1074662177_

**Comment by sandangel** [comment]
thanks for creating this issue. 😀😀

**Comment by cseickel** [comment]
Of course, when I got to fix it, it just completely stops happening! It may be because I upgraded to a new nightly neovim. Do you still have this issue @sandangel ?
