### ISSUE TITLE
Binding to close current node

### ISSUE THREAD

**Issue by levouh** [nvim-neo-tree/neo-tree.nvim#19]
Say that I am in a node like this:

![image](https://user-images.githubusercontent.com/31262046/148649981-aa597bb5-dd81-4f1d-8ee2-553a1e501e13.png)

Being able to press a key and change the tree to this:

![image](https://user-images.githubusercontent.com/31262046/148649998-9ca9aa1a-c514-4426-b629-f897254dc206.png)

(so close the node that the cursor is currently inside of) would be a nice feature to have, similar to how `nvim-tree.lua` has `close_node`.

**Comment by cseickel** [comment]
Interesting. That is easy enough to add.

**Comment by cseickel** [comment]
@levouh Question: If a directory is currently focused, should it collapse that currently focused directory, or it's parent? 

In your example, what happens when you execute `close_node` in the pack directory in your second screenshot?

**Comment by levouh** [comment]
Apologies for the delay; it would close the focused node if it was open, otherwise close the parent of the current node.

**Comment by levouh** [comment]
@cseickel thanks for the addition!

Messing with what you pushed on `main` and is works great, however I _sometimes_ run into this issue where closing a node changes the directory of the window and goes to the wrong parent:

https://user-images.githubusercontent.com/31262046/148656119-370545bd-33a7-40f1-9327-9546ff47ba54.mp4

Note that the starting directory (and the one that contains the file) is `~/dots`, then after closing a node within `~/dots` my directory (both global and tab-local) is changed to `~/`

**Comment by cseickel** [comment]
I just opened up a bug that I think is the real cause of this issue: #22 
Basically, it is not using your custom mappings, and backspace is still running the default command of navigating up. Upper case `C` should give you the behavior you are looking for right now.

**Comment by cseickel** [comment]
Actually, I already figured it out! change your mapping to lower case. My default config merging is case sensitive.

`<bs>` instead of `<BS>`

I'll fix that of course, but this will get you working immediately.

**Comment by levouh** [comment]
Awesome, I will give it a try. Thanks for the notes.
