### ISSUE TITLE
Custom command for creating Directory?

### ISSUE THREAD

**Issue by sandangel** [nvim-neo-tree/neo-tree.nvim#192]
Hi, I would like to use a separated command/keymap to create folder. Like mapping `A` to create folder only, no need backslash at the end. This feels more natural to me. When I think about creating a folder, I hit keymap, then think about the name of the folder. 

The current way of doing it doesn't feel good to me, when I think of creating a folder, I hit a keymap, think of a name, then realize this is a folder name so it should have `/`

Is there a way for adding that custom command and leverage existing neo-tree code? Thanks for an excellent plugin

**Comment by cseickel** [comment]
Yes, but there is really a lot going on there so it's a little complicated for a function defined in a config table. The code for the existing command stats here:https://github.com/nvim-neo-tree/neo-tree.nvim/blob/2152f18291ced01f255ee7f5c121cf3bdba216e0/lua/neo-tree/sources/filesystem/commands.lua#L14

The way to change this is to add an argument to specify that a directory is being created at that point, which will be passed down through to: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/2152f18291ced01f255ee7f5c121cf3bdba216e0/lua/neo-tree/sources/filesystem/lib/fs_actions.lua#L116

So you would have to copy all of that, collapse it to one function, and make it directory only.

I can also add in that in to the built-in commands. That might take me a week or so to get to.

**Comment by sandangel** [comment]
Thank you very much. I love that we can have it as a builtin command. Fantastic!!! 😊
