### ISSUE TITLE
never_show not working in 2.x

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#194]
I'm on the `v2.x`-branch and tried this option:

```
filtered_items = {
  hide_dotfiles = false,
  hide_gitignored = false,
  never_show = {
    '.DS_Store',
    '__pycache__/'
  }
},
```

but the folder is still shown :(

_Originally posted by @nyngwang in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/149#issuecomment-1073414599_

**Comment by cseickel** [comment]
Sorry, I almost forgot about this @nyngwang.

**Comment by nyngwang** [comment]
Roger that :) I'm still busy with some stuff.
