### ISSUE TITLE
($) Dollar sign in file names

### ISSUE THREAD

**Issue by crxo** [nvim-neo-tree/neo-tree.nvim#197]
You'll be aware of a rename issue with dollar signs in file names as per #142

I've noticed something possibly related when opening files.

For example, if you create a file "MyTest$File.ts" and try to open it through neo-tree, the actual file path it will open is MyTest.ts - ignoring everything after the dollar sign.

I've only recently come across this with the Remix framework, which uses a $ for naming files with [dynamic route parameters](https://remix.run/docs/en/v1/api/conventions#dynamic-route-parameters).

If you don't think it's important, I'll eventually get around to submitting a PR as this is my favourite Nvim tree plugin. Great job to the authors :)

**Comment by cseickel** [comment]
@crxo I actually would have fixed it if I could recreate the problem, but I have no issues with files that have dollar signs in them on my computer. Are you on a Mac?

**Comment by crxo** [comment]
Thanks for that. Yeah, on a Mac (12.2.1). How odd. I'll have a closer look and see if I can uncover anything.

**Comment by crxo** [comment]
Haven't tested this on other systems, but for me, it's the nvim edit command.

For example, `:e $test.tsx` opens a buffer for ".tsx"

Escaping the path in utils.lua fixes it for me:

```lua
vim.cmd(open_cmd .. " " .. vim.fn.fnameescape(path))
```

**Comment by cseickel** [comment]
I think that last commit fixes it, can you confirm?

**Comment by crxo** [comment]
Confirmed working 👍 Thanks so much.
