### ISSUE TITLE
can we get some config to show nested files even if they're hidden and hidden files aren't shown?

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#199]
can we get some config to show nested files even if they're hidden and hidden files aren't shown?

e.g. yes hide `node_modules`, but don't hide `index.js.map`, even though they're both gitignored.

_Originally posted by @bennypowers in https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/191#discussioncomment-2434030_

**Comment by cseickel** [comment]
_moving this replay from the discussion..._

> can we get some config to show nested files even if they're hidden and hidden files aren't shown?
> 
> e.g. yes hide node_modules, but don't hide index.js.map, even though they're both gitignored.

Would that only be for specific named files, or for any file that is nested? Would this only apply to gitignored and never the

**Comment by bennypowers** [comment]
I think it should apply to any hidden file that is also nested under another file

The reason being that nesting already hides the file in question, but also makes it available for inspection, whereas showing all hidden files is way too much information

**Comment by cseickel** [comment]
> The reason being that nesting already hides the file in question, but also makes it available for inspection, whereas showing all hidden files is way too much information

I definitely agree with that. My thoughts are that it should be that:

- `dotfiles` are always shown in a nesting, regardless of any other settings
- same with `gitignored`
- same with `hide_by_name`
- `never_show` files are the one thing that are not shown

Would you agree with that?

The next question is, does that need to be optional? Would anyone ever say that hidden files should also be hidden in nestings?

**Comment by bennypowers** [comment]
That sounds reasonable. I'm not sure how a user would end up nesting dotfiles, but that's fine, in mostly interested in build artifacts like .d.ts

What you described looks good, and if a user had more specific needs they could open an issue
