### ISSUE TITLE
Allow :NeoTreeFloat to toggle the floating window

### ISSUE THREAD

**Issue by jemag** [nvim-neo-tree/neo-tree.nvim#20]
Currently calling :NeoTreeFloat twice in a row will try to render it again. I think it would make a lot more sense if it just toggled the floating tree, especially considering the fact that you cannot close it directly with either "Ctrl+w_c" or "Ctrl+w_q" as this results in the following:
Initial state:
![image](https://user-images.githubusercontent.com/7985687/148651374-bef6ba19-fe34-4f21-b3ce-5d8258516180.png)
After "Ctrl+w_c" or "Ctrl+w_q"
![image](https://user-images.githubusercontent.com/7985687/148651388-344444fc-9963-46d5-9a9d-96c9e110e706.png)

**Comment by cseickel** [comment]
Hit Escape to close the window, or focus another window. I am planning on adding some new Toggle commands that will have the behavior you are looking for.

Also, I notice the border is showing up correctly for you, you may want to switch to `popup_border_style = "rounded"` in your config.
