### ISSUE TITLE
`netrw` opening by default instead of `neo-tree`?

### ISSUE THREAD

**Issue by ok-nick** [nvim-neo-tree/neo-tree.nvim#200]
Hi, I'm new to neovim and just got most of my config setup. `neo-tree` was working fine for me yesterday, although today it doesn't seem to open by default when I open a directory?

I'm using `packer` and my config looks like this,
```lua
use({
	"nvim-neo-tree/neo-tree.nvim",
	branch = "v2.x",
	requires = {
		"nvim-lua/plenary.nvim",
		"kyazdani42/nvim-web-devicons",
		"MunifTanjim/nui.nvim",
	},
	config = function()
		-- remove legacy commands
		vim.cmd([[ let g:neo_tree_remove_legacy_commands = 1 ]])

		-- diagnostic errors
		vim.fn.sign_define("DiagnosticSignError", { text = " ", texthl = "DiagnosticSignError" })
		vim.fn.sign_define("DiagnosticSignWarn", { text = " ", texthl = "DiagnosticSignWarn" })
		vim.fn.sign_define("DiagnosticSignInfo", { text = " ", texthl = "DiagnosticSignInfo" })
		vim.fn.sign_define("DiagnosticSignHint", { text = "", texthl = "DiagnosticSignHint" })

		require("neo-tree").setup({})
	end,
})
```

I disabled all my other plugins, settings, keymaps, etc to no avail. I've also tried explicitly setting `hijack_netrw_behavior = "open_default"`, however that doesn't seem to work either. I've also tried going back to the `v1.x` branch and it still doesn't work. Any ideas?

Edit: and yes I'm positive it's installed. I could call commands via `:Neotree`.

**Comment by ok-nick** [comment]
Oh wow, I spent so long trying to fix this and I just got it. I changed my `compile_path` for `packer` to,
`util.join_paths(vim.fn.stdpath("data"), "site", "pack", "compiled.lua")`
Using this setting seems to cause the issue above.

**Comment by cseickel** [comment]
Very weird. I've never set that option so I'm not sure what it does, but if it's working now then I'll close this issue.

**Comment by ok-nick** [comment]
It's only a patch, I want to set the `compile_path` but in doing so I break `neo-tree`. Actually, I break every plugin. It seems like this is more of an issue with `packer` than `neo-tree`.
