### ISSUE TITLE
Missing APIs for dealing with nested files

### ISSUE THREAD

**Issue by bennypowers** [nvim-neo-tree/neo-tree.nvim#201]
we could also use a `toggle_children` next to `toggle_directory` in commands.lua

_Originally posted by @bennypowers in https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/191#discussioncomment-2434101_

An example of how this is missing, from my config which adds [special toggling rules to the `hjkl` mappings](https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/163):

```lua
["h"] = function(state)
  local node = state.tree:get_node()
    if node.type == 'directory' and node:is_expanded() then
      require'neo-tree.sources.filesystem'.toggle_directory(state, node)
    else
      require'neo-tree.ui.renderer'.focus_node(state, node:get_parent_id())
    end
  end,
["l"] = function(state)
  local node = state.tree:get_node()
    if node.type == 'directory' then
      if not node:is_expanded() then
        require'neo-tree.sources.filesystem'.toggle_directory(state, node)
      elseif node:has_children() then
        require'neo-tree.ui.renderer'.focus_node(state, node:get_child_ids()[1])
      end
    end
  end,
```
I think what's needed is changes to `node:has_children()` (or some new `node:has_expander()` and also changes to `toggle_directory` or some new `toggle_nested`

**Comment by cseickel** [comment]
Yeah, you're right. I hadn't actually used it until now and we need commands to open/close nested files.

I think we should add a separate `"toggle_node"` command that toggles any container open/closed, which I would map to space by default.

In that case, I would stop the deafult `"open"` command from expanding nested files at all so that it just opens the file.

Does that sound right to you?

**Comment by bennypowers** [comment]
Yeah, spot on. Don't forget the has_children method, so I can guard against calling toggle_node on a plain file

**Comment by cseickel** [comment]
There is this:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/45c724f9c5c4b5267a08a4d91913a8d391377a72/lua/neo-tree/utils.lua#L526

that may be what you are looking for.

**Comment by bennypowers** [comment]
Yup that's the one. As long as it works on expandable nodes.

**Comment by bennypowers** [comment]
Nice. Here are the new functions for replication atom tree-view behviour:

```lua
-- ascend to the parent or close it
local function float(state)
  local node = state.tree:get_node()
  if (node.type == 'directory' or node:has_children()) and node:is_expanded() then
    commands.toggle_node(state)
  else
    renderer.focus_node(state, node:get_parent_id())
  end
end

-- toggle a node open or descend to it's first child
local function dive(state)
  local node = state.tree:get_node()
  if node.type == 'directory' or node:has_children() then
    if not node:is_expanded() then
      commands.toggle_node(state)
    elseif node:has_children() then
      renderer.focus_node(state, node:get_child_ids()[1])
    end
  end
end
```
