### ISSUE TITLE
Directories starting with uppercase letters are sorted first (not respecting `$LC_COLLATE` ?)

### ISSUE THREAD

**Issue by xfzv** [nvim-neo-tree/neo-tree.nvim#203]
The directories (and probably the files too, I didn't try) starting with uppercase letters are sorted first, which isn't supposed to happen on my system considering the `$LC_COLLATE` value I'm using.

A quick test with some directories containing lowercase and uppercase letters:

- `% exa -l --no-user --no-time`:
![1](https://user-images.githubusercontent.com/78810647/160198644-c4ce9cc9-a0e9-4974-b677-cd66dc24bf37.png)

- Dolphin:
![image](https://user-images.githubusercontent.com/78810647/160201310-f9ee6cd6-334c-471c-93cb-cb0644a957f3.png)

---

![2](https://user-images.githubusercontent.com/78810647/160198646-221ea5fb-bd96-427b-9d78-5cf15aa8887e.png)
| Side | Plugin | Remark |
| ---- | ------------- | ------ |
| Left | Neo-tree | :negative_squared_cross_mark:  wrong sorting, directories with uppercase letters are sorted first |
| Right | nvim-tree | :heavy_check_mark: right sorting 

Can this be changed? I cannot see any relevant pref in [defaults.lua](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/defaults.lua)

Cheers

**Comment by cseickel** [comment]
It's just doing a natural string sort in lua. TBH, it never occurred to me that someone would want to sort another way.

I can certainly add this in, I'm sure it simple enough to just read your env variables and sort accordingly.

**Comment by cseickel** [comment]
This was just added to **main** and will go out in the next release. Interpreting LC_COLLATE turned out to be more complicated than I originally expected, so I just added a `sort_case_insensitive` option:

```lua
  require('neo-tree').setup({
    sort_case_insensitive = true,
  })

```
