### ISSUE TITLE
Multi-select items then delete/copy/cut

### ISSUE THREAD

**Issue by svermeulen** [nvim-neo-tree/neo-tree.nvim#207]
Not sure if this would be too much scope or not for this plugin, but one feature I really miss from [defx](https://github.com/Shougo/defx.nvim) is the ability to select multiple files/directories then delete/copy/cut them all at once

**Comment by cseickel** [comment]
If I am understanding the request properly, we do have that in the `*-clipboard` commands:
```
            ["y"] = "copy_to_clipboard",
            ["x"] = "cut_to_clipboard",
            ["p"] = "paste_from_clipboard",
```

The `y` and `x` commands are how multi-select happens, and `p` to apply those yank/cuts to a destination.


...and btw, thanks so much for the easyclip/cutlass plugins! They are must haves for me!

**Comment by svermeulen** [comment]
Ohhh I see.  Sorry, I should have actually tried it first before assuming the behaviour from the docs.  Works well now that I get it

Also glad that my work is useful to you as well!  :)
