### ISSUE TITLE
Add Container Component for more complex layouts

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#208]
This is to cover situations where we want:
- overlapping components where there is a priority order to what gets displayed
- components that are aligned to the right of the window

Here's what I'm thinking:

```lua
local config = {
  renderers = {
    {
      "container",
      width = "fit_content", --<-- default value for width
      content = {
        {
          "indent",
          zindex = 10,
          indent_size = 2,
          padding = 1, -- extra padding on left hand side,
        },
        { "indent_guide", enabled = true, zindex = 10, align = "right", ... }, -- `...` = the config itself
        { "collapser_icon", enabled = true, zindex = 20, align = "right", ... }, -- `...` = the config itself
      }
    }
  },
  {
    "container",
    width = 2,
    content = {
      { "icon", zindex = 10 },
      { "diagnostics", zindex = 20, show_errors_only = true },
    }
  },
  {
    "container",
    width = "100%", -- <-- means 100% of what's left from the current column to the window width
    content = {
      { "name", trailing_slash = false, zindex = 5 },
      { "git_status", enabled = true, zindex = 10, align = "right", symbols = { ... } },
    }
  }
}
```

_Originally posted by @cseickel in https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/191#discussioncomment-2419067_

**Comment by cseickel** [comment]
I had some performance issues today and I suspect it may be this feature. If anyone else experiences performance issues with this feature, please let me know.

**Comment by ghillb** [comment]
No performance issues, but on the main branch I get this message when opening neo-tree:
`container_width:  35 max_width:  nil `

(without `renderers` key in the `config` table)

**Comment by cseickel** [comment]
Thanks. I'll take out that debug statement. I think this is solid now and I'll be releasing it soon.
