### ISSUE TITLE
nvim-tree feature migration

### ISSUE THREAD

**Issue by axieax** [nvim-neo-tree/neo-tree.nvim#211]
Hi, I'm currently migrating from nvim-tree and was wondering whether the following features are supported (feature requests if not):

- [ ] group empty directories (compact folders that only contain a single folder into one node in the file tree)
- [x] vim.ui.input instead of popup for creating files etc. (like nvim-tree)
- [x] netrw_hijack behaviour of open_default but for full-width window instead of the side panel (open_current replaces current, which isn't ideal)

**Comment by cseickel** [comment]
> [ ] group empty directories (compact folders that only contain a single folder into one node in the file tree)

This feature does not exist.

**Comment by cseickel** [comment]
> * vim.ui.input instead of popup for creating files etc. (like nvim-tree)

Yes, add this to your config:
```lua
  use_popups_for_input = false, -- If false, inputs will use vim.ui.input() instead of custom floats.
```

**Comment by cseickel** [comment]
> [x] netrw_hijack behaviour of open_default but for full-width window instead of the side panel (open_current replaces current, which isn't ideal)

If you want to open Neotree in a split, but not the current one, you can use the `"open_current"` behavior but use `:split .` and `:vsplit .` to open it.

**Comment by axieax** [comment]
Thanks for the quick response and help! For the netrw_hijack behaviour, I was more describing the following scenario:
- User opens Neovim to a directory
- neo-tree automatically opens as a full width buffer (which can be closed, unlike `open_current`)
- Selecting a file from the neo-tree buffer will close the buffer and open the file

Running `<ctrl-w>o` after loading seems to be closer to this behaviour than `:split .` and `:vsplit .`.

**Comment by cseickel** [comment]
> * User opens Neovim to a directory
> * neo-tree automatically opens as a full width buffer (which can be closed, unlike `open_current`)
> * Selecting a file from the neo-tree buffer will close the buffer and open the file

Sorry but I think I am confused, what you describe above is the current behavior if you specify `hijack_netrw_behavior = "open_current"` and you open nvim to a directory. Does it not work that way for you?

**Comment by axieax** [comment]
`open_current`'s behaviour is pretty much what I would like. Only thing is that when that buffer is active, it pretty much "consumes" my buffers and I cannot move to my other tabs without using my mouse for some reason. It works fine if neo-tree is opened as a separate buffer though.

https://user-images.githubusercontent.com/62098008/160290759-93787595-73ce-4ff6-88c5-9efdf4da7ee9.mp4

**Comment by cseickel** [comment]
In the video above you opening nvim with two buffers, one is a file and one is a dir. The strange behavior you are experiencing is due to these facts:

- **You are using a plugin that displays buffers as tabs**
- The buffer with a file starts out as the "active" buffer in this situation
- The hijack does not happen until you actually show the directory buffer
- Once the directory buffer is hijacked and turned into a "neo-tree" buffer, it becomes unlisted and your bufferline plugin stops showing a tab for it.

I am still confused as to why you would open a file and directory at the same time. Did you want them to open in splits like the `-o` option would do with two files?

**Comment by axieax** [comment]
Thanks for the followup. I guess the question is more whether it's possible to make the hijacked buffer "listed" rather than "unlisted". 

> I am still confused as to why you would open a file and directory at the same time.

For my workflow, I like to open nvim with the files/directories which I will be working on, then further selecting the files within directories to open (eliminates the need to find and search for the subfiles). In this case, I would like the directory listing to be treated as an "active" buffer (like for a normal file opened to the full-width of the editor). Sorry for the confusion!

**Comment by cseickel** [comment]
OK, in that case all you need is the ability to override the local options with a `setlocal buflisted`. This is related to #155.

**Comment by axieax** [comment]
Oo I just tried adding `vim.cmd("au! FileType neo-tree setlocal buflisted")`, and it seems like the buffer becomes active before quickly becoming inactive again. I am doing this incorrectly lol.

https://user-images.githubusercontent.com/62098008/160352046-c433ce07-ae93-45e0-b3c2-92288e3ded1a.mp4

**Comment by cseickel** [comment]
Because I use my own event system, the timing can be a little off. This will work around that:
```
autocmd Filetype neo-tree lua vim.schedule(function() vim.cmd("setlocal buflisted") end)
```

**Comment by axieax** [comment]
Works perfectly now. Thank you so much for the followup help!

**Comment by cseickel** [comment]
I think you may have a timing issue @gegoune. I'm not sure the name is applied before those events fire.

I think it will be faster for me to just do #155 than to work this out. I'll do that tonight.

**Comment by cseickel** [comment]
@gegoune, see https://github.com/nvim-neo-tree/neo-tree.nvim/issues/155#issuecomment-1081338852

That code is in main right now, I will probably release it to 2.x tomorrow.

**Comment by gegoune** [comment]
@cseickel Perfect, that's working as expected now, thanks!

**Comment by cseickel** [comment]
@axieax I just added the group empty directories option: #216
