### ISSUE TITLE
Invalid default mapping for sources buffers and git_status

### ISSUE THREAD

**Issue by axieax** [nvim-neo-tree/neo-tree.nvim#212]
Is it intended that these default mapping warnings appear for the buffers and git_status sources? I haven't edited the default mappings so it seems quite unexpected that these warnings come up.

`:Neotree source=buffers`

![image](https://user-images.githubusercontent.com/62098008/160268554-d9cecb07-707d-456e-826c-ed70333ab717.png)

`:Neotree source=git_status`

![image](https://user-images.githubusercontent.com/62098008/160268578-2b0e9e38-147e-45bc-90a1-d75021a7b3e9.png)

**Comment by tsakirist** [comment]
I'm still getting this kind of errors/warnings in the mentioned sources:

![Screenshot from 2022-04-03 05-55-39](https://user-images.githubusercontent.com/20475201/161429152-38c542ae-0549-475a-b8d3-1021608e0676.png)

**Comment by cseickel** [comment]
Can you provide your config and confirm you are up to date on v2.x?

**Comment by tsakirist** [comment]
Yes I can confirm that I have the latest commits.
My config, is the one provided by the [README.md](https://github.com/nvim-neo-tree/neo-tree.nvim#quickstart)

**Comment by tsakirist** [comment]
![Screenshot from 2022-04-03 06-39-31](https://user-images.githubusercontent.com/20475201/161430799-272c8d5d-804a-45c9-94b7-714255fefd37.png)

**Comment by cseickel** [comment]
Thanks, now I see that the README is wrong. I'll fix that right now.

**Comment by cseickel** [comment]
If you update your config to what is in the README now then it should work without errors.
