### ISSUE TITLE
Don't override <space> key

### ISSUE THREAD

**Issue by zeitchef** [nvim-neo-tree/neo-tree.nvim#213]
I use `<space>` as my leader key, as I'm sure a lot of people do. Unfortunately, I can't use my normal key mapping for toggling the filesystem tree (`<leader>e`) because you've hijacked the space key for `toggle_node`. Is it possible to turn off that default behavior, or override this override? Thanks.

**Comment by cseickel** [comment]
`<space>` is being used as the mapping for toggling a node open/closed. There is a problem with the mapping functionality where it swallows any mapped keys and prevents existing multi-key combos that start with a mapped key from firing. I am going to work on fixing that now.

For right now, you can map to `"none"` to remove a default mapping:

```lua
      require("neo-tree").setup({
        window = {
          mappings = {
            ["<space>"] = "none",
          }
        }
      }

```

**Comment by zeitchef** [comment]
Great! Thanks for the tip, and cheers for the awesome plug-in!
