### ISSUE TITLE
Add window picker for open command

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#221]
Example: https://github.com/idanarye/vimConfig/blob/091574f7163d79fc7d31b74d1ea4625064b8842b/0my-configurations/plugin/config_neo_tree.lua#L24-L35

**Comment by s1n7ax** [comment]
I externalized window picker from nvim-tree if anyone finds that's helping to add it here you can check that out

https://github.com/s1n7ax/nvim-window-picker

**Comment by cseickel** [comment]
That is an awesome idea @s1n7ax! It Looks like a well thought out configuration too. I'll probably just add a recipe to hook into that or maybe add your project as a dependency and provide a built-in command.

**Comment by cseickel** [comment]
This will be an official command soon, but here's how to use it right now:

```lua
  require('neo-tree').setup({
    window = {
      mappings = {
        w = function (state)
          local node = state.tree:get_node()
          local success, picker = pcall(require, "window-picker")
          if not success then
            print("You'll need to install window-picker to use this command: https://github.com/s1n7ax/nvim-window-picker")
            return
          end
          local picked_window_id = picker.pick_window()
          if picked_window_id then
            vim.api.nvim_set_current_win(picked_window_id)
            vim.cmd("edit " .. vim.fn.fnameescape(node.path))
          end
        end
      }
    },
  })
```
