### ISSUE TITLE
Copy dialog backspace stuck

### ISSUE THREAD

**Issue by nagy135** [nvim-neo-tree/neo-tree.nvim#223]
Hello, I just noticed this little bug, where when I wanna copy a file but edit previous name "from middle" (requiring cursor movement).
Example:
```
file1.entity.ts => file2.entity.ts
```
You move cursor after "1" and backspace.

How it behaves on my setup is, it lets me move cursor (inside that nui input) but sometimes i cannot backspace. Its hard to describe when, but when you hold "left arrow" and then try to backspace, it doesnt do anything, until you "type a letter" and start backspacing from there.

If more info is needed to detect this, I ll gladly provide whats needed, just checking if anyone noticed this or if its some other plugin of mine that breaks it

**Comment by lukamanitta** [comment]
I also have this issue, but also with Telescope, so could be an issue with Neovim's popup / float windows rather than a specific plugin.

**Comment by nagy135** [comment]
@lukamanitta hmm didnt notice this in telescope ever, but you are right ...that one behaves the same. So probably sharing version where this happens would be good idea. Feel free to close if this isnt relevant to this repository (mr maintainer)
```
❯ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by cseickel** [comment]
I don't have this problem on my computer, but I am running a recent nightly. Can someone that does has this problem now can try it on a nightly version and let us know if it works?
