### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by rlch** [nvim-neo-tree/neo-tree.nvim#224]
Hey! First of all I'd like to say thanks for this fantastic plugin. I've been trying it for the past couple days and it looks and feels beautiful, and I hope to use + contribute to it in the future.

I've been experiencing a memory leak (climbs to 500mb+ after causing a few errors in the repository, and continues to the GB's before crashing). I've singled this plugin out as the cause, and have noticed that disabling diagnostics makes it chill out at 250mb. 

For context, my memory rests at ~130mb using`nvim-tree` under the same conditions; the LSP I'm using is `dartls` _(note, feverishly slow),_ and SLOC is ~100k.

Sorry for the lack of reproducibility; I'm more than happy to provide any extra context or information. 
Thanks again for the plugin, I really hope I can fully replace `nvim-tree` in the near-future!

**Comment by cseickel** [comment]
> Hey! First of all I'd like to say thanks for this fantastic plugin. I've been trying it for the past couple days and it looks and feels beautiful, and I hope to use + contribute to it in the future.

Thanks!



> I've been experiencing a memory leak (climbs to 500mb+ after causing a few errors in the repository, and continues to the GB's before crashing). I've singled this plugin out as the cause, and have noticed that disabling diagnostics makes it chill out at 250mb.

Does each new edit eat up a bit more memory, or does it start to climb on its own at some point? How long does it take to climb to 500+ mb? Is it like this at the end of the day or does it get there quickly?

I'll definitely keep an eye on this as I use it today.

**Comment by rlch** [comment]
It climbs to 500mb+ in ~2-3 minutes I would say. Each new edit eats up a bit more memory, and it's definitely exponential. Also, I did some simple debugging on a local fork, and found that the `diagnostics` function in `components.lua` is called even when I'm just moving my cursor. Perhaps the diagnostics reported by the LSP are being staggered when affecting multiple files in the workspace?

**Comment by cseickel** [comment]
It's based on the built-in `DiagnosticChanged` event which I think will fire on every edit. It is debounced to only run once per 500ms by default,  but you can alter that value in your fork to see if it helps:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/b500daadd5ff0cce16c2a8e827b6d08a8b16357d/lua/neo-tree/setup/init.lua#L47

**Comment by rlch** [comment]
Sorry to make this issue even more vague, but I can confirm that enabling diagnostics just seems to speed the problem up. Even with it disabled, my memory usage still gets to the 500mb+ range.

Also, increasing the debounce to 2s+ made no tangible difference.

Here's my config if it helps at all:
```lua
vim.cmd [[ let g:neo_tree_remove_legacy_commands = 1 ]]

require('neo-tree').setup {
  close_if_last_window = false, -- Close Neo-tree if it is the last window left in the tab
  popup_border_style = 'rounded',
  enable_git_status = true,
  git_status_async = true,
  enable_diagnostics = true,
  default_component_configs = {
    indent = {
      indent_size = 2,
      padding = 1, -- extra padding on left hand side
      -- indent guides
      with_markers = true,
      indent_marker = '│',
      last_indent_marker = '└',
      highlight = 'NeoTreeIndentMarker',
      -- expander config, needed for nesting files
      with_expanders = nil, -- if nil and file nesting is enabled, will enable expanders
      expander_collapsed = '',
      expander_expanded = '',
      expander_highlight = 'NeoTreeExpander',
    },
    icon = {
      folder_closed = '',
      folder_open = '',
      folder_empty = 'ﰊ',
      default = '*',
    },
    name = {
      trailing_slash = false,
      use_git_status_colors = true,
    },
    git_status = {
      symbols = {
        -- Change type
        added = '✚',
        deleted = '✖',
        modified = '',
        renamed = '➜',
        -- Status type
        untracked = '★',
        ignored = '◌',
        unstaged = '',
        staged = '✓',
        conflict = '',
      },
    },
  },
  window = {
    position = 'left',
    width = 35,
    mappings = {
      ['<space>'] = 'toggle_node',
      ['<Tab>'] = 'toggle_node',
      ['<2-LeftMouse>'] = 'open',
      ['<cr>'] = 'open',
      ['s'] = 'open_split',
      ['v'] = 'open_vsplit',
      ['C'] = 'close_node',
      ['<bs>'] = 'navigate_up',
      ['.'] = 'set_root',
      ['H'] = 'toggle_hidden',
      ['R'] = 'refresh',
      ['/'] = 'fuzzy_finder',
      ['f'] = 'filter_on_submit',
      ['<c-x>'] = 'clear_filter',
      ['a'] = 'add',
      ['A'] = 'add_directory',
      ['d'] = 'delete',
      ['r'] = 'rename',
      ['y'] = 'copy_to_clipboard',
      ['x'] = 'cut_to_clipboard',
      ['p'] = 'paste_from_clipboard',
      ['c'] = 'copy', -- takes text input for destination
      ['m'] = 'move', -- takes text input for destination
      ['q'] = 'close_window',
    },
  },
  nesting_rules = {
    ['dart'] = { 'config.dart', 'pearl_config.dart', 'g.dart', 'model.dart' },
  },
  filesystem = {
    filtered_items = {
      visible = false, -- when true, they will just be displayed differently than normal items
      hide_dotfiles = true,
      hide_gitignored = false,
      hide_by_name = {
        '.DS_Store',
        'thumbs.db',
        --"node_modules"
      },
      never_show = { -- remains hidden even if visible is toggled to true
        ".DS_Store",
        "thumbs.db"
      },
    },
    follow_current_file = true, -- This will find and focus the file in the active buffer every
    -- time the current file is changed while the tree is open.
    hijack_netrw_behavior = 'open_default', -- netrw disabled, opening a directory opens neo-tree
    -- in whatever position is specified in window.position
    -- "open_current",  -- netrw disabled, opening a directory opens within the
    -- window like netrw would, regardless of window.position
    -- "disabled",    -- netrw left alone, neo-tree does not handle opening dirs
    use_libuv_file_watcher = false, -- This will use the OS level file watchers to detect changes
    -- instead of relying on nvim autocmd events.
  },
  buffers = {
    show_unloaded = true,
    window = {
      mappings = {
        ['bd'] = 'buffer_delete',
      },
    },
  },
  git_status = {
    window = {
      position = 'float',
      mappings = {
        ['A'] = 'git_add_all',
        ['gu'] = 'git_unstage_file',
        ['ga'] = 'git_add_file',
        ['gr'] = 'git_revert_file',
        ['gc'] = 'git_commit',
        ['gp'] = 'git_push',
        ['gg'] = 'git_commit_and_push',
      },
    },
  },
}

vim.api.nvim_set_keymap('n', '\\', '<cmd>Neotree reveal<cr>', { silent = true })
vim.api.nvim_set_keymap('n', '<leader>o', '<cmd>Neotree reveal<cr>', { silent = true })
vim.api.nvim_set_keymap('n', '<leader>to', '<cmd>Neotree reveal toggle<cr>', { silent = true })
```

Thanks!

**Comment by cseickel** [comment]
It is possible it's the interaction of neo-tree with another plugin that is causing the leak, or it can be your specific version. Can you test these situations:

1. Running the nightly version of neovim (unless you already are, what version are you on?)
2. Removing all other plugins except for neo-tree

If you are in the root of the repo, you can run a minimal init with:
```
nvim --noplugin -u tests/mininit.lua
```

**Comment by nagy135** [comment]
not sure if this is related, but today I had this manual "task" where i was editing json files in like 90 separate folders ...so each time I opened folder in neo-tree, opened json file, edited it, navigated back to neo-tree, closed node and moved to another one. After like 50 folders I realized my pc fan spins like crazy and neovim uses 40% of my 16gb ram (according to htop). I will try to localize if this is another plugin issue, but definitely something leaks

**Comment by andersevenrud** [comment]
I just experienced this as well. I was working with neo-tree open and edited ~20 files. Suddenly everything started slowing to an absolute crawl. Checked memory usage, and all of my 32G were used. Then neovim just crashed and left this in my terminal:

```
[neo-tree.nvim] [ERROR 15:32:15] ...packer/start/neo-tree.nvim/lua/neo-tree/events/queue.lua:144: Error in event handler for event vim_diagnostic_changed[filesystem.vim_diagnostic_changed]: ...im/site/pack/packer/start/nui.nvim/lua/nui/tree/init.lua:365: Vim:E315: ml_get: invalid lnum: 2%
```

Not sure if that is of use. I will do some more investigation on this. This seems to happen when neo-tree is open only.

**Comment by cseickel** [comment]
I've discovered that the leak happens in NuiTree's render method and opened an issue there: https://github.com/MunifTanjim/nui.nvim/issues/117

The trick to force it to happen is to just keep refreshing the tree repeatedly. That's why the diagnostics made the leak worse, it will refresh the tree every 500 ms when you are actively editing because the diagnostic messages are constantly changing.

**Comment by cseickel** [comment]
@MunifTanjim was able to fix the memory leak we found in NuiTree. Hopefully that's the only one in play here but we'll see...

Can you please update your plugins, including `nui.nvim`, and tell me if that fixes the memory leak issue?

**Comment by ndom91** [comment]
@cseickel Updated and have no longer seen any memory leaks in the past ~24hrs :+1:

**Comment by andersevenrud** [comment]
I might be a bit premature in writing this...but I've updated everything today and still experience some mild slowdowns with neo-tree open (and only when open) still. It doesn't seem to suck up all of my memory, but there's still something going on :thinking:

**Comment by cseickel** [comment]
I have noticed that having a neo-tree window open seems to utilize 3 - 5 % of my cpu. I have been tryimng to figure out why but I haven't come up with any explanation yet. Maybe that issue affects you as well and that is the "mild slowdown" you are experiencing.

**Comment by nyngwang** [comment]
Wowowow, it seems like I've missed out on some serious bug discussed here. I hope this problem can be addressed soon! (I have to go back to work with my typescriptbabelwebpackpolyfill stuff, which is another tragedy)

**Comment by cseickel** [comment]
> I have noticed that having a neo-tree window open seems to utilize 3 - 5 % of my cpu. I have been trying to figure out why but I haven't come up with any explanation yet. Maybe that issue affects you as well and that is the "mild slowdown" you are experiencing.

I've addresses this issue in **main**, it will be released in the next day or two. It turns out it was just the overhead of using the resize timer. I adjusted it from a default of every 50ms to 500ms, with a temporary speed up after a resize is detected. That reduces the cpu to an average of 0.5% when idle.

68b3f8f04f34fef1d5192a1028dfdf45a21cce2d

If you still have a slowdown after receiving this update, please open a new issue.
