### ISSUE TITLE
Handle files in .git/info/exclude like files .gitignore

### ISSUE THREAD

**Issue by ghillb** [nvim-neo-tree/neo-tree.nvim#226]
Currently neo-tree doesn't include files in `.git/info/exclude`  if `hide_gitignored=true`.

Proposal:
neo-tree should respect `.git/info/exclude`, like nvim-tree does.

**Comment by cseickel** [comment]
This is the first I have heard about this feature, it's amazing how much you learn when you respond to issues in an open source project!

That being said, I think nvim-tree showing files that were in the `exclude` list was a bug. If it's in the exclude list, isn't thatjust a personal `.gitgnore`, meaning that the files mentioned there should be ignored by git? If my understanding is correct, then they should be hidden when `hide_gitignored=true`.

**Comment by ghillb** [comment]
You are correct that's what its is and the way it should be handled, but currently is not.
Maybe my wording was confusing. Files in `.git/info/exclude` are displayed in neo-tree, when `hide_gitignored=true`.

**Comment by cseickel** [comment]
> Maybe my wording was confusing. Files in `.git/info/exclude` are displayed in neo-tree, when `hide_gitignored=true`.

Sorry, that's on me, I'm not sure why I misunderstood that. I'll give it a try later and figure out what's wrong

**Comment by cseickel** [comment]
If you want to try out **main**, this should be fixed in that branch.

**Comment by cseickel** [comment]
That's a new error message for me, I'm surprised to see a path ending in `..`. Could you walk me through all the steps you took to get to that error, starting with the `nvim` command used to open nvim?

**Comment by ghillb** [comment]
It is not much:
1. cd into repo `cd ~/code/tmp/neo-tree-test/`
2.  open file in repo: `nvim .gitignore`
3.  open neo-tree: `:Neotree toggle reveal`

I re-checked and the error is not present in the 2.x branch.

**Comment by cseickel** [comment]
I'm going to start tracking this new bug in #232

**Comment by ghillb** [comment]
Reporting in that on the latest commit on main branch (same settings as above) it is like this for me:
![Screenshot 2022-04-03 104536](https://user-images.githubusercontent.com/35503959/161419651-c35ec705-d5e3-4f33-96c2-8b3fc720dbff.png)

**Expected behavior:**
The `.file_in_gitignore` (`.gitignore`) should have the same style as `file_in_gitexclude` (`.git/info/exclude`) in the drawer.

**Comment by cseickel** [comment]
That is working for me:
![image](https://user-images.githubusercontent.com/5160605/161430359-5595defc-097e-42f5-8c84-0fa80632d279.png)

Looking at your screenshot, it appears that the `.gitignore` entry is indented, and those spaces are included in the pattern and make it not match.

**Comment by ghillb** [comment]
That white space is part of the numbers column caused by (`vim.opt.number = true`  & `vim.opt.relativenumber = true`):
![image](https://user-images.githubusercontent.com/35503959/161432320-dfc3a9e2-420d-4ae0-94cf-54e7ff31b2c2.png)
There is no additional white space in the buffer.

**Comment by cseickel** [comment]
> That white space is part of the numbers column caused by (`vim.opt.number = true` & `vim.opt.relativenumber = true`):

Oh I see. There's still something else different for you than what I have because it works fine for me. Can you confirm that `.file_in_gitignore` was not accidentally added to the index? Could you try adding another normal file and a dotfile to `gitignore` and see if they display properly?

**Comment by ghillb** [comment]
![image](https://user-images.githubusercontent.com/35503959/161434380-24b87c33-0a37-4ed1-bce0-57d9a54bb3eb.png)
I have created a new file `.another_file`, same behavior. Maybe an util thats differently configured and not part of nvim causes the divergence?

**Comment by cseickel** [comment]
The fact that you got that [error](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/226#issuecomment-1085988486) is probably why this isn't working for you. I'll need to rewrite that in a way that's not dependent on the local shell.

**Comment by cseickel** [comment]
Can you try out the `226-handle-files-in-gitinfoexclude-like-files-gitignore` branch and tell me how it works?

**Comment by ghillb** [comment]
This seems to work like expected, when opening the project from within the folder:
![image](https://user-images.githubusercontent.com/35503959/161533296-57bc9c84-5ae9-4dc4-8d02-5bf7c9f3db8b.png)

However I noticed that when I open project files from outside the project folder, lets say I am in `../project`, open a file within `nvim project/file_in_project` and change the working dir to the project root after opening, all files seem to be interpreted as ignored:
![image](https://user-images.githubusercontent.com/35503959/161533970-161e7696-e2b5-4bde-bef4-76e86783c922.png)

-> files are grayed out and have ignored symbol (in case of `tracked_file`)

**Comment by cseickel** [comment]
I think the highlight problem is fixed now, can you try the latest on that branch?

**Comment by jose4125** [comment]
I used the `v2.x` and `main` branch. but the ignore files are not gray
<img width="571" alt="Screen Shot 2022-04-05 at 12 09 12 AM" src="https://user-images.githubusercontent.com/1216119/161685217-9ce25a19-2a5c-436e-848b-fb0369ca8e19.png">

**Comment by ghillb** [comment]
> I think the highlight problem is fixed now, can you try the latest on that branch?

The only thing amiss is on the 226 branch is that `tracked_file` should not be grayed out and should not have the ignored symbol:
![image](https://user-images.githubusercontent.com/35503959/161708887-b4d9aabb-e1a5-4de7-8584-e5b8b3dd3095.png)

The cause could be that `~/` is a git repo with a wild card ignore on everything and that when switching nvims working dir to the git repo in `~/code/tmp/neo-tree-test`, the highlights / git file status don't get cleared properly.

**Comment by cseickel** [comment]
> The cause could be that `~/` is a git repo with a wild card ignore on everything and that when switching nvims working dir to the git repo in `~/code/tmp/neo-tree-test`, the highlights / git file status don't get cleared properly.

Yup, I'm sure that's it! I'll test that situation.

**Comment by cseickel** [comment]
@ghillb I've updated that branch to handle the repo in a repo situation correctly. Please give it a try when you get a chance and let me know how it goes.
