### ISSUE TITLE
netrw hijack changes to cwd

### ISSUE THREAD

**Issue by axieax** [nvim-neo-tree/neo-tree.nvim#230]
Hi, I did not have this issue before since I was using `hijack_netrw_behavior = "open_default"`, but now with `open_current`, it seems that opening nvim to a directory will use the cwd instead (sounds like expected behaviour?). The main reason I'm using a different hijack_netrw_behavior is because I've customised my default right sidebar tree view to be a float popup, but I want my netrw-hijacked behaviour to be the normal full sized window (as can be seen from the video below).

https://user-images.githubusercontent.com/62098008/161254500-7d224569-5b08-4d9a-9f5a-2dd64683f439.mp4

Sorry for the many tickets, but here's my config:
```lua
require("neo-tree").setup({
  use_popups_for_input = false,
  -- popup_border_style = "rounded",
  default_component_configs = {
    indent_size = 1,
    name = {
      trailing_slash = true,
    },
  },
  window = {
    position = "float",
    width = "30%",
    popup = {
      position = { col = "100%", row = "2" },
      size = function(state)
        local root_name = vim.fn.fnamemodify(state.path, ":~")
        local root_len = string.len(root_name) + 4
        return {
          width = math.max(root_len, 50),
          height = vim.o.lines - 6,
        }
      end,
    },
  },
  filesystem = {
    hijack_netrw_behavior = "open_current",
    use_libuv_file_watcher = true,
    filtered_items = {
      hide_dotfiles = false,
      never_show = { ".git" },
    },
  },
  event_handlers = {
    {
      -- auto close
      event = "file_opened",
      handler = function(file_path)
        require("neo-tree").close_all()
      end,
    },
    {
      -- show netrw hijacked buffer in buffer list
      event = "neo_tree_buffer_enter",
      handler = function()
        vim.schedule(function()
          local position = vim.api.nvim_buf_get_var(0, "neo_tree_position")
          if position == "current" then
            vim.cmd("setlocal buflisted")
          end
        end)
      end,
    },
  },
})
```

**Comment by cseickel** [comment]
It works correctly for me when I try it with your config.

If you look closely, at 3 seconds into the video, it did open correctly to the desired folder, but then it changes to the global working directory. I think the problem here is that another plugin or an autocmd you have in your config is changing the working directory for the window, which neo-tree then responds to.

**Comment by axieax** [comment]
Ahh yeah I had a suspicion - most likely [project.nvim](https://github.com/ahmedkhalf/project.nvim) which updates the cwd to the project scope based on LSP. I'm not sure if there's a way to get it to not switch though, like "open_default" does.

**Comment by cseickel** [comment]
I'm not quite sure why it doesn't happen the same for both settings. I have two thoughts:

1. You can try opening nvim with the direct command instead relaying through a netrw hijack:

**Comment by axieax** [comment]
Disabling `bind_to_cwd` fixes this. Thanks!
