### ISSUE TITLE
Combining hide_dotfiles and hide_gitignored

### ISSUE THREAD

**Issue by kristijanhusak** [nvim-neo-tree/neo-tree.nvim#231]
Hi,

Today I switched from nvim-tree, and things are working great!

One thing that is not working as I would expect is combination of `hide_dotfiles` and `hide_gitignored`.
I tried combination of `hide_dotfiles = false` and `hide_gitignored = true` to hide dotfiles that are part of gitignore, and show dotfiles that are not part of gitignore. Currently, with this setting, all dotfiles are shown, no matter if they are part of gitignore or not.
For example, I have `.env.something` files that are git ignored as `.env*`, but they still show.

Steps to reproduce:
1. Use this configuration:
```lua
require('neo-tree').setup({
  filesystem = {
    filtered_items = {
      hide_dotfiles = false,
      hide_gitignored = true,
    }
  }
})

```
2. Create .gitignore file with `.env*` in it
3. Create file `.env.test`
4. Create file `.somefile`
5. Open Neotree, see that both `.env.test` and `.somefile` are visible

Expectation:

Expected to see only `.somefile`, since `.env.test` is gitignored

**Comment by cseickel** [comment]
Thanks for the great bug report. I do think this has been handled in #226. That fix is currently in the **main** branch. Can you try that out and let me know if it works as expected?

**Comment by kristijanhusak** [comment]
Yeah, it works as expected on main branch. Thanks!
