### ISSUE TITLE
ignored files error: is outside repository at…

### ISSUE THREAD

**Issue by gegoune** [nvim-neo-tree/neo-tree.nvim#232]
On main, after some of the recent updates I am getting following error when opening filesystem tree:

```
[neo-tree.nvim] [ERROR 20:31:34] .../packer/start/neo-tree.nvim/lua/neo-tree/git/ignored.lua:25: Failed to load ignored files for  /Users/gegoune/repos/test :  { "fatal: /Users/gegoune/repos/test/..: '/Users/gegoune/repos/test
/..' is outside repository at '/Users/gegoune/repos/test'" }
```

Something straight forward or would you like me to find exact commit introducing that error?

**Comment by cseickel** [comment]
@ghillb is also having this issue but I am not. Something just occurred to me, when you run `git ls-files *` does that show dotfiles by default? Do you have `shopt -s dotglob` somewhere in a bashrc or something?

**Comment by gegoune** [comment]
> `git ls-files *`

does not show dotfiles. There are some tracked dotfiles in repository I tested.

> Do you have shopt -s dotglob somewhere in a bashrc or something?

I am using zsh, but have `shell` set to `/bin/sh` in neovim.

But! I did update to latest main just now and you latest commit seems to have fixed it, did not get the error while opening tree, but that's all I tried so far.

**Comment by cseickel** [comment]
> But! I did update to latest main just now and you latest commit seems to have fixed it, did not get the error while opening tree, but that's all I tried so far.

I'm actually just ignoring that error, which I hate doing but it seems like it's still getting all of the ignored files anyhow. I think the issue might be that I am relying on an actual shell with glob expansion to do this work, and that can have different results on different computers. The **right** thing to do is to rewrite this to not be dependent on the local shell (sh/bash/zsh/cmd/etc). One day I will, but if this works for both of you then that day is not today.
