### ISSUE TITLE
Error rendering component container

### ISSUE THREAD

**Issue by axieax** [nvim-neo-tree/neo-tree.nvim#234]
Hi, I encountered this error when opening `/home/axie/.local/share/nvim/site/pack/packer/start/neo-tree.nvim/lua/neo-tree/ui/highlights.lua`. Perhaps this is due to the text being too long (cannot fit in the container?)

![image](https://user-images.githubusercontent.com/62098008/161372880-b2b80f6b-9980-4578-bff6-506cc7c9215c.png)

```
[neo-tree.nvim] [WARN  18:48:11] .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:198: Error rendering component container: ...acker/start/neo-tree.nvim/lua/neo-tree/ui/highlights.lua:40: bad argument #2 to 'format' (num
ber expected, got nil)
```

**Comment by cseickel** [comment]
Can you tell me what is set for the Normal and NeoTreeRootName highlight groups?
```
:hi Normal
:hi NeoTreeRootName
```

**Comment by cseickel** [comment]
Actually, never mind. After some testing I'm sure that you have an empty `Normal` highlight group, and that is what caused that error. I added in code to figure out what the default foreground and background colors should be in that situation. Should be fixed now.

**Comment by axieax** [comment]
Ahh no wonder. Thanks for fixing this :))
