### ISSUE TITLE
Neo-tree window waits next key for some inapplicable actions

### ISSUE THREAD

**Issue by alefbragin** [nvim-neo-tree/neo-tree.nvim#242]
E.g. I have binding for `dm` in some pluggin, and this action (delete mark) is not make sense for Neo-tree window. But when `d` was pressed Neo-tree waits for a next key instead of immediately execute delete file action (which binds for `d` by default), and then the next key was pressed it appears in Nui window, that is janky behavior i think :)

May be it is can be fixed by allowing `nowait` mapping options for some keybindings.

**Comment by cseickel** [comment]
> May be it is can be fixed by allowing `nowait` mapping options for some keybindings.

Yes, that's the key. In the past I actually had all mappings created with `nowait` but that caused a different set of issues. I guess it really just needs to be configurable somehow.

Maybe the "right hand side" mapping can be optionally specified as an table in addition to the existing options of using a string or a function. That table would look like:

```lua
...
  mappings = {
      ["d"] = {
        target = "name_of_command", -- or function
        options = { nowait = true }
      }
   
    }
  }
...
```

What do you think about that?

**Comment by alefbragin** [comment]
> What do you think about that?

I think this do the trick :)
But i'm not sure if this is the most elegant way; and i can't realize better way currently

**Comment by cseickel** [comment]
> I'm not sure if this is the most elegant way; but i can't realize better way currently

Sometimes that's the hardest part of making the plugin. Especially because once I add this in, it can't be changed without breaking someones's setup. Let me know if you come up with anything better. It will probably be a few days before I get to it.

**Comment by lopi-py** [comment]
I suggest handle it like [packer](https://github.com/wbthomason/packer.nvim)
```lua
...
  mappings = {
      -- can be a table (in this case the command itself is `[1]`)
      ["d"] = {
        "name_of_command", -- or function
        nowait = true
      },
      -- or just a string/function
      ["D"] = "name_of_other_command" -- or function
    }
  }
...
```

**Comment by cseickel** [comment]
This is in **main** now and will be released soon. See the `help` changes in the commit for details.

**Comment by gegoune** [comment]
I would argue that `nowait` should be added by default to 'known' offenders. `d` is one of them as there is vim's `dd` which in neo-tree context is useless hence user will most likely always mean 'just do `d`' when pressing `d`. What do you think?

**Comment by cseickel** [comment]
> I would argue that `nowait` should be added by default to 'known' offenders. `d` is one of them as there is vim's `dd` which in neo-tree context is useless hence user will most likely always mean 'just do `d`' when pressing `d`. What do you think?

Yes, I suppose you are right. Strange how I never even noticed that until you pointed it out. I would actually want `nowait` on all of my mappings.

I think the better thing to do is add a `mapping_options` property just above `mappings` which is the default options that apply to all mappings. Then I can `nowait = true` in my config at that level and maybe override that on one or two mappings if needed.

**Comment by cseickel** [comment]
Done:

```lua
 require("neo-tree").setup({
   window = {
     mapping_options = {
        noremap = true,
        nowait = true,
     },
     mappings = {
       ["d"] = "whatever", -- this will have `nowait` applied
       ["<space>"] = { "other_command", nowait = false }, -- this will be normal
       ...
```

**Comment by alefbragin** [comment]
There are no new `mapping_options` in default config when do `:lua require("neo-tree").paste_default_config()`.

**Comment by cseickel** [comment]
It wasn't in the default config when this was closed, but it is there now in `main`. It will be included in the next release. In the meantime, it's still available for use if you add this into your own config.
