### ISSUE TITLE
Context/help menu with ?

### ISSUE THREAD

**Issue by zeitchef** [nvim-neo-tree/neo-tree.nvim#245]
I've fully migrated to `neo-tree` and absolutely love it! One feature that I'm really missing however is a context/help menu listing available keybindings. Either I'm getting old or switch plugins too often - I can't remember what does what :)

`nvim-tree` offers `g?` (per my suggestion) and `coc-explorer` implemented this even better IMHO with `?` - do you think we could get something like that for `neo-tree`?

Many thanks for this awesome plugin!

**Comment by cseickel** [comment]
> `nvim-tree` offers `g?` (per my suggestion) and `coc-explorer` implemented this even better IMHO with `?` - do you think we could get something like that for `neo-tree`?

Yes, I've been meaning to do that for a long time, I just haven't gotten around to it because there have been so many other things to do. This is definitely on the list though.


> Many thanks for this awesome plugin!

You're very welcome!

**Comment by nyngwang** [comment]
To @zeitchef:

> [...] Either I'm getting old or switch plugins too often - I can't remember what does what :)

No worries. I have the same problem, lol. I'm also looking forward to this feature!

**Comment by cseickel** [comment]
This was just added to the `main` branch. Please give it a try and let me know what you think.

**Comment by zeitchef** [comment]
@cseickel Just tested and works great!

**Comment by nagy135** [comment]
also can confirm that works as expected, on my setup
