### ISSUE TITLE
Cannot set git status colors

### ISSUE THREAD

**Issue by zeitchef** [nvim-neo-tree/neo-tree.nvim#251]
I've set `use_git_status_colors` in my config, but it still uses the fallback icons. How can I properly set this?

<img width="767" alt="Screen Shot 2022-04-08 at 16 58 15" src="https://user-images.githubusercontent.com/6670659/162467221-c0f6aeba-7711-4aca-95d6-267020b62fd9.png">

**Comment by cseickel** [comment]
The colors are not directly related to the icons. To change the icons used, you want to change the `symbols` of the `git_status` config:

```lua
      require("neo-tree").setup({
        default_component_configs = {
          git_status = {
            symbols = {
              -- Change type
              added     = "", -- or "✚", but this is redundant info if you use git_status_colors on the name
              modified  = "", -- or "", but this is redundant info if you use git_status_colors on the name
              deleted   = "✖",-- this can only be used in the git_status source
              renamed   = "",-- this can only be used in the git_status source
              -- Status type
              untracked = "",
              ignored   = "",
              unstaged  = "",
              staged    = "",
              conflict  = "",
            }
          },
        },

```

If you want to remove them, you can either set the symbols to empty strings, or define custom  `renderers` that omit the `git_status` component.
