### ISSUE TITLE
Netrw `open_current` issues

### ISSUE THREAD

**Issue by lopi-py** [nvim-neo-tree/neo-tree.nvim#254]
* [doesn't align right the icons](https://gyazo.com/fc07481a9efa359b0981a776b904d8f1)
* [will let you open another neo-tree filesystem instance](https://gyazo.com/042f22680dc69f40f30956b8a72e6115)(is this intended?)
* [not restoring state after opening a file](https://gyazo.com/1e925d868b74699843840bab44b5fc47)

### Steps to reproduce:
1. Setup neo-tree with:
```lua
local utils = require "neo-tree.utils"

...
  event_handlers = {
    {
      event = "file_opened",
      handler = utils.wrap(require("neo-tree").close_all, nil),
    },
  }
  filesystem = {
    hijack_netrw_behavior = "open_current", -- if "open_default", all works as expected
  }
...
```
2. exit from neovim and `nvim .`
3. **optional:** `:Neotree toggle`(with "open_default" it's closed but with "open_current", opens a new tree)
4. **optional:** `:Neotree toggle`(again, it should close the new tree)
5. expand a folder and open a file from the current tree(it should close the current tree)
6. `:Neotree toggle`(not restoring the previous state of the expanded folder)

**Comment by cseickel** [comment]
This is all working as expected, I think you are just working under different assumptions than me. A tree that is opened in the "current" position is different from a sidebar. 

There is only one **sidebar per tab**, and if you change the position then the state of that sidebar will travel with it. You can only have one sidebar (or float) per source per tab.

**A "current" tree, however, is bound to the _window_** it was opened in, so each "current" will track its own state and not affect any others. You can have infinite "current" trees. You can also have zero or one sidebars at the same time.

My usage is that I will generally have a sidebar open as long as I have the space, but when I switch files I usually open a tree in the current window where I want to open that file to do so. If your expectation is that you will only have one tree at all times, you should not use the "current" position at all.

**Comment by cseickel** [comment]
> * doesn't align right the icons

This is also by design. They should be aligned together in a column, but not all the way to the right of the window because that would be too far away to be useful. They should be just far enough away from the longest filename that it creates a column.
![image](https://user-images.githubusercontent.com/5160605/162576716-0808201b-ae7f-4608-8e44-d81a75ab4b2e.png)

**Comment by lopi-py** [comment]
ah thanks, I'll use open_default then
