### ISSUE TITLE
ignored files should have gray color and ignored icon

### ISSUE THREAD

**Issue by jose4125** [nvim-neo-tree/neo-tree.nvim#256]
the following is my neo tree setup, I want that the ignored and dotfiles will be visible
<img width="367" alt="Screen Shot 2022-04-09 at 4 41 35 PM" src="https://user-images.githubusercontent.com/1216119/162592525-6e8c4a34-ad78-4bb5-8959-0fb5c3990282.png">
it is working. but the ignored files like `node_modules` and `.env` files are not gray.
would be nice if the ignored files are gray with ignored icon 
<img width="571" alt="Screen Shot 2022-04-05 at 12 09 12 AM" src="https://user-images.githubusercontent.com/1216119/162592523-b0e203dc-72b3-484a-b444-408b93c8f37c.png">

**Comment by cseickel** [comment]
What you actually want is this:

```lua
      filtered_items = {
        visible = true,
        hide_dotfiles = true,
        hide_gitignored = true,
      },
```

That will show them because of `visible = true`, but still mark them because of `hide_gitignored = true`.
