### ISSUE TITLE
Make 'toggle_node' act like 'close_node' if on a file

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#260]
`close_node` will close node when cursor is on file within that node. `toggle_node` has to be on directory itself. Could `toggle_node` also toggle node if cursor is on file within that node?

_Originally posted by @gegoune in https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/258#discussioncomment-2540781_

**Comment by cseickel** [comment]
It could, but is that an intuitive behavior? I'm not quite sure if it is or not. Does anyone else have any opinions on that?

If you want to have this functionality now, you can use this custom command:

```lua
    require("neo-tree").setup({
      window = {
        mappings = {
          ["<space>"] = function (state)
            local node = state.tree:get_node()
            if require("neo-tree.utils").is_expandable(node) then
              state.commands["toggle_directory"](state)
            else
              state.commands["close_node"](state)
            end
          end,
    ...
```

**Comment by gegoune** [comment]
Actually, that made me think and I double checked what it is like in nvim-tree. And I am actually not using toggle at all, so close_node and open will do for me. Apologies about the noise, and since you questioned it straight away you are probably right and issue can be closed.
