### ISSUE TITLE
Happy news: Speed boosted confirmed

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#261]
Tested with my holding on `NeoTreeFloat`(while it seems that this has been deprecated?):

https://user-images.githubusercontent.com/24765272/162727170-bb2f9812-db2f-42bc-b6dd-77093e9ac465.mov

**Comment by nyngwang** [comment]
I remembered I opened an issue about I experienced some lag when I was trying this. Now I can do this smoothly :)

**Comment by cseickel** [comment]
> Tested with my holding on `NeoTreeFloat`(while it seems that this has been deprecated?):

Yes, the `NeoTreeFloat` command is replaced by `Neotree float`.
