### ISSUE TITLE
Ignore pattern possible?

### ISSUE THREAD

**Issue by DianeOfTheMoon** [nvim-neo-tree/neo-tree.nvim#266]
I was wondering if there was any config for ignoring patterns in neo-tree?  I'm working in Unity and generally don't want to see *.meta and *.prefab files, but it seemed like the config was full filename only.

**Comment by cseickel** [comment]
No, but the `nesting` feature may work for you if they are just compiled artifacts of other files. See:
```
:h neo-tree-file-nesting
```

**Comment by DianeOfTheMoon** [comment]
Not entirely because Unity creates .meta files for things like directories, too, which the file nesting doesn't seem to handle.  Can you do directory level nesting?  The help didn't indicate that you could.

**Comment by cseickel** [comment]
> Can you do directory level nesting?

No, that can't really work from a UI perspective. 

I will add the ability to hide with a pattern as well.

**Comment by cseickel** [comment]
I just pushed an update to the `main` branch that adds this feature. Can you give it a try and let me know if it works for you?

```lua
    require("neo-tree").setup({
      filesystem = {
        filtered_items = {
          visible = false, -- when true, they will just be displayed differently than normal items
          hide_dotfiles = true,
          hide_gitignored = true,
          hide_by_name = {
            ".DS_Store",
            "thumbs.db",
            --"node_modules",
          },
          hide_by_pattern = {
            "*.meta",
            "*.prefab"
          },
        },
      }
    })

```
