### ISSUE TITLE
Error: no file '../packer_hererocks/2.1.0-beta3/lib/lua/5.1/neo-tree.so'

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#271]
![image](https://user-images.githubusercontent.com/24765272/163089616-17c7c694-1078-45f1-a0c8-0c4b38e40cbe.png)

I don't know how to fix this.

## Debug Info.

```
NVIM v0.7.0-dev+1446-g18152cf6f
Build type: Release
LuaJIT 2.1.0-beta3
```
(link: [18152cf6](https://github.com/neovim/neovim/commit/18152cf6f17fb4fd6dc6194bad33a971fc985b75))

And I just upgrade my macOS to the latest version `12.3.1 (21E258)`.

neo-tree branch cf819084.

## What's wrong?

Neo-tree didn't show those git status signs:

<img src="https://user-images.githubusercontent.com/24765272/163100641-8d546715-d0d1-489e-9e1b-df9fab27e79d.png" width="400">

**Comment by nyngwang** [comment]
Rolling back to 6da5c910 saves this problem. So it's probably these commits that cause this, and probably not upstream issue:

<img src="https://user-images.githubusercontent.com/24765272/163103867-7e8311e6-ca00-4a58-b768-5fe422e4de21.png" width="700">

**Comment by cseickel** [comment]
There may be more to that error message. Can you run 
```
:messages
```

and copy the rest of it if there are related errors leading up to that final error?

**Comment by nyngwang** [comment]
@cseickel I just go back to the latest commit and the error disappears! (was sleeping sorry for my late reply)
