### ISSUE TITLE
Source filesystem setup failed

### ISSUE THREAD

**Issue by gegoune** [nvim-neo-tree/neo-tree.nvim#272]
Latest commit, 2a42aff on main, causes following error to be printed during `setup()` call:

```
[neo-tree.nvim] [ERROR 10:32:22] ...ker/start/neo-tree.nvim/lua/neo-tree/sources/manager.lua:510: Source filesystem setup failed: ...t/neo-tree.nvim/lua/neo-tree/sources/filesystem/init.lua:263: module 'neo-t
ree.sources.filesystem.lib.globtopattern' not found:
[neo-tree.nvim] ^Ino field package.preload['neo-tree.sources.filesystem.lib.globtopattern']
```
(followed by list of search paths).

Reverting back to b049969 fixes the issue

**Comment by cseickel** [comment]
This is fixed now. I forgot to add a new module when committing.
63ddbd8c1036f7186eec10654f5ddef4febb5338

**Comment by gegoune** [comment]
All working now, thank you!
