### ISSUE TITLE
Git status is rendered despite being explicitly disabled in renderer

### ISSUE THREAD

**Issue by ioreshnikov** [nvim-neo-tree/neo-tree.nvim#28]
Hey, guys!

First, many thanks for your work on this plugin. I am a big fan: this is perhaps the most fluid and intuitive tree plugin to date.

Second, I've noticed that git status next to a file is being rendered despite being explicitly disabled by me in the config. Please see the screenshot attached:
![git_status](https://user-images.githubusercontent.com/1098912/148700735-cd4ac524-4afc-4259-a9a4-a7c75a6aea79.png)

On the right you can see the relevant part of my config. As you can notice, I explicitly restrict file renderer to being an icon and a name only. However, in the left panel I see that my config was modified. I believe this is an inconsistency of some sorts.

Best,
Ivan

**Comment by ioreshnikov** [comment]
One more thing: when I start neovim and open `neo-tree`, then I also see additional highlighting of the file names (notice the color of `init.vim`):
![Снимок экрана от 2022-01-09 21-52-28](https://user-images.githubusercontent.com/1098912/148701158-7c7029b5-82a0-48ac-ae6e-b976174cdda2.png)
When I evaluate the whole config with `source`, the additional highlighting is gone and all the file names are rendered with the usual `Normal` highlight group.

**Comment by levouh** [comment]
Not that this directly answers your question, but you can also skip the (potentially costly) operation of loading the `git` information by just defining your own custom `before_render` function, and removing the `git` portion entirely. For example, the default has:

```lua
    before_render = function(state)
      -- This function is called after the file system has been scanned,
      -- but before the tree is rendered. You can use this to gather extra
      -- data that can be used in the renderers.
      local utils = require("neo-tree.utils")
      state.git_status_lookup = utils.get_git_status()
    end,
```

and you can just set it to:

```lua
    before_render = function(_)
      return
    end,
```

and then there won't be any state to render in the first place.

**Comment by cseickel** [comment]
I would definitely recommend @levouh 's suggestion of overriding before_render. But also, I just pushed an update to main that I believe fixes the underlying issue.

**Comment by levouh** [comment]
@cseickel bisecting a bit, highlights show up (for directories) in `f4ae153b467e5fb716cca114ad4f374d7e54943c`, but do not in `bda5eaeb0d2ec1fbadf7ed691973f082030af2d2`.

Respective pictures:

![image](https://user-images.githubusercontent.com/31262046/148708594-5bcff788-e47e-4109-8f94-d9f026a22a00.png)

![image](https://user-images.githubusercontent.com/31262046/148708585-02a538f8-79a3-4f0d-9dc8-5d50afb05f6e.png)

**Comment by levouh** [comment]
Might be something due to the fact that I have my own directory renderer actually, as the files work just fine. Ignore for now.

**Comment by ioreshnikov** [comment]
@cseickel Thanks! That have fixed the first issue. The problem with highlight is still there though.

**Comment by cseickel** [comment]
@ioreshnikov The highlight for the name is built in to the default "name" component. There are two ways to disable that now:

1. Override the `before_render` function and leave out the utils.get_git_status() call. This is the best way if you are not going to use the `git_status_lookup` it at all.
2. Override the built-in name component with your own version.

**Comment by cseickel** [comment]
FYI, a better solution for this will becoming in #37.
