### ISSUE TITLE
Directories are not getting diagnostics icons?

### ISSUE THREAD

**Issue by lopi-py** [nvim-neo-tree/neo-tree.nvim#280]
(capture from #268)
![image](https://user-images.githubusercontent.com/70210066/163290165-4b166344-effb-4b51-afb0-d3f0011c0747.png)
(my capture)
![image](https://user-images.githubusercontent.com/70210066/163291133-a5c1c08f-8a89-4613-b80d-a95a68445882.png)

is intended that directories should not get diagnostics icons? (note that with git it works)

neo-tree config:
```lua
local directory = {
  { "indent" },
  { "icon" },
  { "current_filter" },
  {
    "container",
    width = "100%",
    content = {
      { "name", zindex = 40 },
      { "diagnostics", zindex = 30 },
      { "clipboard", zindex = 20 },
      { "git_status", zindex = 10, align = "right" },
    },
  },
}
local file = {
  { "indent" },
  { "icon" },
  {
    "container",
    width = "100%",
    content = {
      {
        "name",
        use_git_status_colors = true,
        zindex = 100,
      },
      { "modified", zindex = 50 },
      { "diagnostics", zindex = 40 },
      { "bufnr", zindex = 30 },
      { "clipboard", zindex = 20 },
      { "git_status", zindex = 10, align = "right" },
    },
  },
}

...
  filesystem = {
    renderers = {
      directory = directory,
      file = file,
    },
  },
...
```
as I see in [defaults.lua](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/lua/neo-tree/defaults.lua#L133), I think it is not intended

**Comment by cseickel** [comment]
In the default config, diagnostics are shown for directories, but only the error status.

Your config is off because you are using the `zindex` wrong. It looks like you are using it as an `index` that would signify the order, but the order is implied by the order you specifiy the components in. The `zindex` property signifies what **layer** a component is on. If you want components to render inline, one after the other, then they all need to have the same `zindex` value. You only want to use different `zindex` values if the components are supposed to overlap and replace each other. For what I believe you are trying to do, they should all have the same `zindex`. 

The exception would be that the right aligned `git_status` should have a higher `zindex` if you want it on top of the other components when there is not enough space, or a lower `zindex` if you want the left aligned components to render over top of it.

**Comment by lopi-py** [comment]
still is not working
```lua
local directory = {
  { "indent" },
  { "icon" },
  { "current_filter" },
  {
    "container",
    width = "100%",
    content = {
      -- { "name", zindex = 10 },
      { "diagnostics", zindex = 10 },
      -- { "clipboard", zindex = 10 },
    },
  },
}
```

![image](https://user-images.githubusercontent.com/70210066/163313458-279a8413-42aa-4325-b048-0e6601ac387c.png)
maybe is not working on Windows

**Comment by cseickel** [comment]
It's not related to Windows. There is something else wrong with your config that is not included here. Can you show the entire setup call?

**Comment by lopi-py** [comment]
I made a minimal config
```lua
local on_windows = vim.loop.os_uname().version:match "Windows"

vim.cmd "set runtimepath=$VIMRUNTIME"

local function join_paths(...)
  return table.concat({ ... }, on_windows and "\\" or "/")
end

local temp_dir = vim.loop.os_getenv "TEMP" or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "jose-elias-alvarez/null-ls.nvim",
      "nvim-neo-tree/neo-tree.nvim",
      "muniftanjim/nui.nvim",
      "nvim-lua/plenary.nvim",
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  require("null-ls").setup {}
  require("null-ls").register {
    method = require("null-ls").methods.DIAGNOSTICS,
    filetypes = { "text" },
    generator = {
      fn = function(params)
        local diagnostics = {}
        for i, line in ipairs(params.content) do
          table.insert(diagnostics, {
            row = i,
            col = 1,
            end_col = #line,
            source = "test",
            message = "Error!'",
            severity = vim.lsp.protocol.DiagnosticSeverity.Error,
          })
        end
        return diagnostics
      end,
    },
  }

  local renderer = {
    { "indent" },
    { "icon" },
    {
      "container",
      width = "100%",
      content = {
        { "name", zindex = 10 },
        { "diagnostics", zindex = 10 },
      },
    },
  }

  require("neo-tree").setup {
    filesystem = {
      renderers = {
        file = renderer,
        directory = renderer,
      },
    },
  }
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path }
  load_plugins()
  require("packer").sync()
  vim.cmd "autocmd User PackerComplete ++once lua load_config()"
else
  load_plugins()
  require("packer").sync()
  _G.load_config()
end
```
still is not working
![image](https://user-images.githubusercontent.com/70210066/163469891-7026511e-f2e4-4521-bb07-5695316e808f.png)

### Steps to reproduce
1. `mkdir dir`
2. `nvim -u minimal.lua dir/file.txt`
4. `:Neotree toggle`
5. focus the previous window(file.txt)
6. append some lines and save(`:write`)
7. `:Neotree focus` and expand `dir`

**Comment by lopi-py** [comment]
I printed the diagnostics lookup
![image](https://user-images.githubusercontent.com/70210066/163480762-9fcadd7e-7341-4d3f-a394-2d24a5e0cb07.png)
in directories, `\` is added at begin

**Comment by cseickel** [comment]
I guess you were right, it is a windows thing!
