### ISSUE TITLE
Custom Sorting

### ISSUE THREAD

**Issue by theduke** [nvim-neo-tree/neo-tree.nvim#282]
Is there some way to customize the sorting behaviour?
Maybe a custom function that can be specified for sorting a level?

In particular, I would like to improve the Rust and Javascript/Typescript experience by always showing `mod.rs` or `index.rs` files as the first item.

I'd potentially also like to show files before subdirectories.

**Comment by cseickel** [comment]
No, there is no way to do that. It does internally choose from two different sorters based on whether it should sort case insensitive, so it wouldn't be that difficult to add a custom sort option if you or someone else wants to submit a PR.

**Comment by danilshvalov** [comment]
If I understood the question correctly now it can be done as follows:

<details>
<summary>Code</summary>

```lua
local priorities = {
    ["index.rs"] = 6,
    ["mod.rs"] = 5,
    ["b.txt"] = 4,
}

require("neo-tree").setup({
    sort_function = function(a, b)
        -- show files before subdirectories
        if a.type ~= b.type then
            return a.type == "file"
        end
        -- sort by priority if it possible
        if priorities[a.name] and priorities[b.name] then
            return priorities[a.name] > priorities[b.name]
        end
        -- if the priority is set for only one, then the
        -- one who has it set will be the first
        if priorities[a.name] or priorities[b.name] then
            return priorities[a.name] ~= nil
        end
        -- default path sort
        return a.path < b.path
    end,
})
```
</details>

It looks something like this:
<details>
<summary>Screenshot</summary>

![Screenshot 2022-07-02 at 01 32 33](https://user-images.githubusercontent.com/57654917/176974479-32f0c18a-7f52-4e58-9326-de3ea8acfa84.png)
</details>

**Comment by cseickel** [comment]
Closing this now because custom sorting was added in #377 and @danilshvalov example should work.
