### ISSUE TITLE
Focus newly created file

### ISSUE THREAD

**Issue by axieax** [nvim-neo-tree/neo-tree.nvim#283]
Hi, just wondering if it's possible to automatically place the cursor on the new file after creation? Also, it seems that there is quite a bit of delay when trying to delete a file with `d`. Is it possible to make this `nowait` so it doesn't wait for a text object?

**Comment by gegoune** [comment]
You can use functionality from that https://github.com/nvim-neo-tree/neo-tree.nvim/blob/a1f5f4b15cec517d632e7335d20400cb3f410606/doc/neo-tree.txt#L319.

**Comment by cseickel** [comment]
> Hi, just wondering if it's possible to automatically place the cursor on the new file after creation?

I don't know why that never occurred to me! Yes, that is a good idea.

**Comment by cseickel** [comment]
This is in `main` now and will be included in the next release.

**Comment by axieax** [comment]
Works like a charm, thanks!
