### ISSUE TITLE
`async scan` does not work properly if there is expanded files

### ISSUE THREAD

**Issue by lopi-py** [nvim-neo-tree/neo-tree.nvim#286]
https://gyazo.com/b36f7910199b4795341c599d2ea9cd74
when file is collapsed, it works as expected, but if you expand it and create another file(that updates async with `filesystem. async_directory_scan = true`), neo-tree will not get updated, then if you close and open neo-tree, it will be updated(because opening the tree is sync scan)

**Comment by cseickel** [comment]
Before I make this sync, I want to fix the async scan. Just to clarify, when you say:

> when file is collapsed, 

are you talking about nested files?

**Comment by lopi-py** [comment]
Yes

**Comment by cseickel** [comment]
It's not an issue for me, but it could just be a timing issue that runs differently on your computer. I'll look for logical errors in the async code.

**Comment by lopi-py** [comment]
I'm getting this error with `fix-asyncs-scan-issues` branch
![image](https://user-images.githubusercontent.com/70210066/163686735-3a22d555-a0d1-4bbb-8bc7-35313fa5c98f.png)

**Comment by cseickel** [comment]
This should be fixed on `main`
