### ISSUE TITLE
Custom name modifier

### ISSUE THREAD

**Issue by lopi-py** [nvim-neo-tree/neo-tree.nvim#296]
![image](https://user-images.githubusercontent.com/70210066/163686779-19cfa641-1b57-4a94-b481-0c7dfeb4e000.png)
I don't wan't the tree to show `~`, so I suggest allow to set custom name modifiers like nvim-tree

**Comment by cseickel** [comment]
In this case, the suggested solution is to use a custom "name" component. You can resuse and extend upon the builtin one like this:

```lua
  require('neo-tree').setup({
    filesystem = {
      components = {
        name = function(config, node, state)
          -- first call the default name component
          local cc = require("neo-tree.sources.common.components")
          local result = cc.name(config, node, state)
          -- if it is root, customize the name how you want
          if node:get_depth() == 1 then
            result.text = state.path
          end
          return result
        end
      }
    },
  })
```

**Comment by lopi-py** [comment]
Thanks!, feel free to close
