### ISSUE TITLE
Root directory not expanding if empty and creating node

### ISSUE THREAD

**Issue by lopi-py** [nvim-neo-tree/neo-tree.nvim#297]
(sorry if you feel I'm spamming issues)
https://gyazo.com/b6132ba68fd554585baa4e959831f24f
Is this intended?

**Comment by cseickel** [comment]
It's not intended, but I have never set an empty directory as root so that situation wasn't tested.

**Comment by cseickel** [comment]
I finally tested this and I didn't experience this issue. Maybe it was fixed along the way. Can you give it another try and let me know if it is still an issue?

**Comment by lopi-py** [comment]
It seems to be fixed, I can't reproduce
