### ISSUE TITLE
Toggle requires two key presses after hiding with <Esc>

### ISSUE THREAD

**Issue by levouh** [nvim-neo-tree/neo-tree.nvim#30]
Using the `float` implementation, if I open the tree using something like `:NeoTreeFloatToggle` it will open with the current buffer focused, as expected. If I hit `<Esc>` to close the _NeoTree_ window, I then have to use `:NeoTreeFloatToggle` twice to get it to show up again.

Here is an example:

https://user-images.githubusercontent.com/31262046/148704793-2162b88a-6150-4d83-8894-edd108b9cead.mp4

If using `:NeoTreeFloatToggle` when the window is visible to hide the the window, it opens on the first repeat of this command as expected.

**Comment by levouh** [comment]
A small bit of debugging, the problem is with the call to `renderer.close_floating_window(source_name)`. After using `<Esc>` to close the window, it returns `true` so we just bail out of the `M.float` function early rather than showing the window.

**Comment by levouh** [comment]
It works to check `vim.api.nvim_win_is_valid` in the loop inside of `M.close_floating_window` for `renderer.lua`; however editing a list while iterating it is always a fun time.

It might be a good time to do some cleanup though either way, so saving off a list of invalid windows and removing them might be a fine price to pay (multiple iterations of the loop in some cases).

**Comment by levouh** [comment]
At this point actually, the window is closed, so `nui` takes care of setting the `win.winid` to `nil`, so that can be used as the check (perhaps along with `vim.api.nvim_win_is_valid`).

**Comment by cseickel** [comment]
Thanks for the information, I think I've got the optimal solution after reading all of this...

**Comment by cseickel** [comment]
Check that commit and let me know what you think.

**Comment by levouh** [comment]
I've messed something up with the highlights along the way so ignore that (or from switching from `1.x` to `main`), but it works perfectly:

https://user-images.githubusercontent.com/31262046/148708461-febc361c-44d9-435d-a5e4-86e0cf3a2ed7.mp4
