### ISSUE TITLE
Use default icon from `nvim-web-devicons` instead of own default one (`*`)

### ISSUE THREAD

**Issue by alefbragin** [nvim-neo-tree/neo-tree.nvim#301]
If no icon fetched from `nvim-web-devicons` default icon from config will be used. AFAIK there no ability to choose separate color for that default icon. Instead of it i suggest use default icon from `nvim-web-devicons` which in turn can be changed in `nvim-web-devicons` config.

I suppose this can be achieved by changing line https://github.com/nvim-neo-tree/neo-tree.nvim/blob/ada6a3dbb95e7cf33b8356756bd56849525d66a4/lua/neo-tree/sources/common/components.lua#L249 like in https://github.com/kyazdani42/nvim-web-devicons/blob/09e62319974d7d7ec7e53b974724f7942470ef78/README.md?plain=1#L60

Currently it is possible to globally enable default icons in `nvim-web-devicons` and it will be shown in file tree.

**Comment by cseickel** [comment]
I realize it isn't documented anywhere, but there is a `highlight` config option on the icon component that will be used if the `nvim-web-devicon` lookup fails. As a generally rule of thumb, every component has a `highlight` config option that it falls back to if all else fails. The `default` and `highlight` options are mainly there for people that do not have `nvim-web-devicons` installed.

I personally have the `default` option configured in `nvim-web-devicons`. I would definitely recommend configuring icons there if you use that plugin, as it will then be used by other plugins with icons.

**Comment by msva** [comment]
@cseickel sorry for necroposting, but can you advice, why can `default` icon from neo-tree be used despite of me having
```lua
require("nvim-web-devicons").set_default_icon('', '#6d8086')
```
and even such hack as
```lua
         override = {                                                                                                                                                                                                                                                         
           default = {                                                                                                                                                                                                                                                        
             icon = "kk",                                                                                                                                                                                                                                                     
             color = "#428850",                                                                                                                                                                                                                                             
             name = "default"
           }                                                                                                                                                                                                                                                                  
         };
```

in devicons config?

**Comment by cseickel** [comment]
> @cseickel sorry for necroposting, but can you advice, why can `default` icon from neo-tree be used despite of me having

It should use the default icon if you specify it in your `nvim-web-devicons` config:

```lua
require'nvim-web-devicons'.setup {
 -- globally enable default icons (default to false)
 -- will get overriden by `get_icons` option
 default = true;
}
```
