### ISSUE TITLE
cwd not updating when changed by neo-root plugin

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#304]
@cseickel: I'm still keeping this option on :) OK, but there is a problem I have experienced for two months(or more?) I'm using a plugin I made for myself to change the current working directory. It seems that the tree would not get updated when this option is on and the current directory did change via my plugin. (Maybe I should open a standalone issue for this though.) Regarding the possible reason: it seems that either NeoVim or the `libuv` would treat manual `cd` and lua-command-`cd`(quoted below) differently. When doing things manually it can be successfully detected, but programmatically it would have some problems. (i.e. the first attempt was ignored)

https://github.com/nyngwang/NeoRoot.lua/blob/3c391852bc7bb4e5bc7c0fdae8632194d4ac3587/lua/neo-root.lua#L55

The current flow: (for "change the `cwd`" I mean programmatically via `vim.cmd('cd ' ...)`, as the link)

1. I change the `cwd` to A, but the tree didn't reflect the change.
2. I change the `cwd` to B.
3. I change the `cwd` to A. The tree now does reflect the change.

expected flow:

1. I change the `cwd` to A. The tree now does reflect the change.

_Originally posted by @nyngwang in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/188#issuecomment-1101030310_

**Comment by cseickel** [comment]
@nyngwang I'm guessing the issue is is related to the fact that neo-tree does not follow `cd` (global workinng directory), it follows `tcd` (tab working directory). The two will sometimes be the same, particularly if there is no tab working directory set. Once a tab cwd is set however, the two are different.

This applies to sidebars. If you open netrw style, that used the `lcd`, or window local working directory.

The simplest way to fix this is probably to have your plugin set the tab working directory instead of the global one.

**Comment by nyngwang** [comment]
Great, let me try it now! I will report it back soon!

**Comment by nyngwang** [comment]
@cseickel: I think this is the solution :) it does get updated after I changed to `tcd`. But now another problem is that giving the current file is in the nested folder of the new `cwd`, the tree didn't expand the folder, which contains the target file, by default.

**Comment by nyngwang** [comment]
I think this can be safely closed now. The problem I found can be fixed in my plugin.
