### ISSUE TITLE
Update file handler/buffer after move/rename

### ISSUE THREAD

**Issue by gegoune** [nvim-neo-tree/neo-tree.nvim#308]
Currently renaming `a.lua` to `b.lua` leaves me with open buffer named `a.lua` (saving which recreates `a.lua` on filesystem) and no `b.lua` gets opened.

Expected behaviour is such that a.lua buffer gets removed and b.lua is opened in its place (not with the same buffer number, but 'instead').

_Originally posted by @gegoune in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/47#issuecomment-1085097404_

**Comment by nyngwang** [comment]
There is also a related error message shown upon that the neo-tree got closed and the cursor went back to the no-longer-exist buffer(i.e. `a.lua` in the example). While it is not harmful but definitely related so I provided this info here.

**Comment by gegoune** [comment]
Without checking, afair, it's regular (neo)vim's messages saying that file for that buffer no longer exists. It's not an issue in itself as much as it is product of not updating/removing that buffer by neo-tree (which this ticket is about).

**Comment by cseickel** [comment]
This is now working in `main` and will be in the next release.

**Comment by nyngwang** [comment]
@cseickel: This causes an error:

```
E5108: Error executing lua: /Users/ningwang/.config/nvim/init.lua:35: Vim(write):E13: File exists (add ! to override)
stack traceback:
        [C]: in function 'cmd'
        /Users/ningwang/.config/nvim/init.lua:35: in function </Users/ningwang/.config/nvim/init.lua:35>
Press ENTER or type command to continue
```

**Comment by nyngwang** [comment]
:( waiting for the fix.

**Comment by cseickel** [comment]
I'll fix it, but to be clear it's still writable and not a fake buffer at all. You just have to add the `!` to your write the command the first time you write it.

```
:w!
```

**Comment by cseickel** [comment]
So the E13 error issue is resolved, and I also realized that previously there was no handling for renaming buffers in a directory that was renamed, that was fixed too.

I did find a new bug related to cut/pasting files. I'm not sure if it's related to this or not but I'm investigating that right now.

**Comment by Gelio** [comment]
FYI I was able to implement this functionality for `tsserver`. I added the following handler https://github.com/Gelio/ubuntu-dotfiles/blob/d5f693db0e5afd10efacb3269f3a96bf3bade834/install/neovim/stowed/.config/nvim/lua/plugins.lua#L116-L134 for the rename and move neo-tree events https://github.com/Gelio/ubuntu-dotfiles/blob/d5f693db0e5afd10efacb3269f3a96bf3bade834/install/neovim/stowed/.config/nvim/lua/plugins.lua#L176-L183

It may be worth adding this snippet to the documentation or the codebase so others can easily copy/require it and use it themselves.

With this snippet, renaming/moving a file or directory in neo-tree automatically updates import paths in TypeScript.

**Comment by cseickel** [comment]
> FYI I was able to implement this functionality for `tsserver`.

🤯 You are amazing @Gelio! Thanks for sharing this! I'll link to his comment in the wiki for now.

**Comment by 9mm** [comment]
Is this still an issue? After renaming something I often get this problem after saving, requiring me to hit enter a second time:

![](https://user-images.githubusercontent.com/1386207/274132841-17e7f1a9-72c6-46a6-b45e-39ee0491149e.png)

**Comment by Gelio** [comment]
@9mm I don't experience this. This seems like a candidate for a separate issue if you are sure this happens because of neo-tree.

Did you try disabling neo-tree, renaming, and then saving the file again? Let this be the deciding factor for you whether to create a separate issue
