### ISSUE TITLE
Add more variations for open commands

### ISSUE THREAD

**Issue by levouh** [nvim-neo-tree/neo-tree.nvim#31]
If I open the tree with `:NeoTreeFloatToggle`, it will show the current file (which I'm not sure if is intended or not). If I move somewhere else in the tree, hide the tree, then show it again, I am returned to where the file that was focused when first opening the tree rather than the file that I had previously navigated to before closing it.

For example:

https://user-images.githubusercontent.com/31262046/148704967-ad40a77b-dfcb-40af-92ae-f5094721fc35.mp4

where I first open the tree and it focuses the current buffer (whether or intended or not). I then change it to focus on another node, close the tree, then when I re-open it the focus is not on the same node as I closed it with

**Comment by cseickel** [comment]
That is the intended behavior, but I can see how not everyone would want that. The question is, do i just keep adding more commands to cover every variation, or something else? To keep with the current conventions, I should add:
```
NeoTreeFloatFocus = the behavior you are looking for
NeoTreeFloatShow = keep the state and show it, but don't focus it
NeoTreeFloatReveal = the current behavior of NeoTreeFloat, but explicitly named
NeoTreeFloatFocusToggle
NeoTreeFloatShowToggle
NeoTreeFloatRevealToggle = the current behavior of NeoTreeFloatToggle, but explicitly named
```

**Comment by levouh** [comment]
Yea I can see how that start to get a little bit ridiculous. You could try to do what _Fugitive_ and _Telescope_ do and just use a single command that takes arguments that are like `key` or `key=value` so that you can extend it however you need to.

This is basically a "complication layer" on top of a command, but makes it a lot easier (at least before `vim.keymap`) to map.

**Comment by levouh** [comment]
Would this be a good time to expand and support the "any tree" model, such that the commands would be something like:

```
NeoTree filesystem reveal
NeoTree filesystem show
```

as well? The plugin could handle parsing the first argument to direct the rest to the proper tree, then the tree would have to handle what remains?

**Comment by cseickel** [comment]
I think that's the way to go. I haven't heard of "any tree", is that a design pattern or a vim specific api?

**Comment by levouh** [comment]
No, just echoing what the `README` notes about:

>browse the file system and other tree like structures in a sidebar or floating window

and the top level keys to `setup`, referencing that really you can render "any tree-like structure" with this plugin.

**Comment by cseickel** [comment]
Oh right, that's obvious now! I guess I was hoping there some utility to make this task easier.

**Comment by levouh** [comment]
I'm happy to take a stab at it as well, just let me know. Implementing it would be easy enough, then "just" have to plug it in to the functions that already exist and take arguments.

**Comment by cseickel** [comment]
I do think I want to deprecate all of the current commands, to be removed in 2.x, and switch to a new single command system of the form:

NeoTree <action> <source> <position> <toggle>

example: `NeoTree focus filesystem float toggle`
or is it easier to use this? `example: `NeoTree action=focus source=filesystem position=float toggle=true`

Where **action** is one of:

- show = show the window, keeping previous state, without focusing
- focus = show and focus, keeping previous state
- reveal = focus and find current file in tree 

and **source** is any available source:

- filesystem
- buffers
- git_status

and **position** is a valid position:

- left
- right
- float

and **toggle** is a boolean flag, which is true if present and false otherwise

**Comment by cseickel** [comment]
I just saw your offer to take a stab at it, that would be great! The biggest complication would be that the float methods are currently built around always revealing, so they need to be refactored a little.

**Comment by cseickel** [comment]
@levouh Just so I know how to categorize this on the new project board, are you working on this?

If you are, be warned we added stylua to the project which made minor changes to every file. It can be a merge nightmare you probably want to get ahead of before making too many changes.

**Comment by levouh** [comment]
Everything I've added so far is in new files, so as soon as you push I can go from there. Having `stylua` will be nice! Also something like `luacheck` would be cool.

FYI as well, I added testing using the module that `plenary` provides in my branch.

**Comment by cseickel** [comment]
Adding tests would be great, thanks!

luacheck style warning are already running from something in my config, maybe the language server. Feel free to open a PR for  a config or an action if you want.

**Comment by levouh** [comment]
@cseickel wanted to double check with you, but right now there isn't a way to "get the previous state from a tree", right?

Specifically consider the case where I reveal a file and close the tree. The tree itself has a state, but so does the cursor. If I then `action=focus` the tree again, the current action only makes an attempt to open and then focus the tree window. The cursor is left alone at the top of the buffer, rather than placed in the same place as it was when the window was previously closed.

I have a relatively simple way to handle this that I use in my own current configuration (basically tracking `Win{Leave,Enter}` for all `neo-tree` buffers and keep track of the cursor state), but wanted to make sure there isn't something that already exists first. The aforementioned method could break in the case that the tree state changes without one of those events firing (not a common thing as far as I'm aware).

Wanted to get your feedback before going any further with this.

**Comment by cseickel** [comment]
I always use Reveal so I never noticed that the cursor location is lost. That is not the intended behavior.

Something should be done to store that piece of state and restore when creating a new window. I think that event could be subscribed in the renderer using Nui methods to record the cursor position on WinLeave.

I would say this is a separate issue, I'd call it a bug on the Show/Focus behavior.
