### ISSUE TITLE
/ Search doesn't find any results

### ISSUE THREAD

**Issue by s1n7ax** [nvim-neo-tree/neo-tree.nvim#310]
I have the following configuration. Everything is up to date

```lua
    use({
        'nvim-neo-tree/neo-tree.nvim',
        requires = {
            'nvim-lua/plenary.nvim',
            'kyazdani42/nvim-web-devicons',
            'MunifTanjim/nui.nvim',
        },
        config = function()
            require('nvim.plugins.nvim-neo-tree')
        end,
    })
```
#### nvim.plugins.nvim-neo-tree.lua
```lua
require('neo-tree').setup({
    filesystem = {
        window = {
            mappings = {
                ['o'] = 'open',
            },
        },
        renderers = {
            directory = {
                {
                    'icon',
                    default = '',
                    folder_closed = ' ',
                    folder_open = ' ',
                    padding = ' ',
                },
                { 'current_filter' },
                { 'name' },
                {
                    'clipboard',
                    highlight = 'NeoTreeDimText',
                },
                { 'diagnostics', errors_only = true },
            },
        },
    },
})
```

When something is searched in the window, there are no results found. (Seems like the popup windows are broken too)

![image](https://user-images.githubusercontent.com/18459807/163892409-eddabde9-f400-4616-951e-7ca20af5ac09.png)
![image](https://user-images.githubusercontent.com/18459807/163892425-711df6a4-a9c9-4a24-bce3-2a85c06a0107.png)

**Comment by cseickel** [comment]
Does that last screenshot show a floating window with no borders? If so, are all your popups like that, such as with add/rename prompts?

Can you tell me what OS you are using, and what versions of `fd` and `find` you have installed?

**Comment by s1n7ax** [comment]
I think I found the issue. I'm using `oh-my-zsh`.  It apparently adds `fd` alias to `find . -type d -name`. I think it is better to add requirements section in the README.md and add `find` and `fd`.

There is an issue with all popups including the `:NeoTreeFloatToggle`. It's not showing border nor it's content. It's just a invisible floating window without any content.

https://user-images.githubusercontent.com/18459807/163992841-a3844e15-2a15-4519-9fca-0e364ccf7cb5.mp4

I don't think it is a nui issue because nvim-lsp-install also using nui and :LspInstallInfo floating window works fine

**Comment by cseickel** [comment]
So does it work when you remove that alias? If you don't have `fd` installed, I would highly recommend it because it works better than `find`.

I don't think I need to list `find` as a requirement because it really is universal. Maybe I should add that `fd` is recommended though.

As for the popup issue. It could just be that there is an issue with your default highlight groups. Try setting the `NeoTreeFloatBorder` highlight group to something. If there really is no content at all, then there is something else wrong with your config. Maybe also set `NeoTreeNormal` if your standard `Normal` group is transparent or soemthing.

**Comment by s1n7ax** [comment]
Yes. I removed the alias. Find is working. Well, some

It was working few days ago. An update broke it. I don't know which package.

```
:hi NeoTreeFloatBorder
NeoTreeFloatBorder xxx links to FloatBorder

:hi FloatBorder
FloatBorder    xxx links to WinSeparator

:hi WinSeparator
WinSeparator   xxx links to VertSplit

:hi VertSplit
VertSplit      xxx cterm=reverse ctermfg=235 ctermbg=240 gui=reverse guifg=#1b2b34 guibg=#4f5b66
```


```
:hi NeoTreeNormal
NeoTreeNormal  xxx links to Normal

:hi Normal
Normal         xxx ctermfg=253 ctermbg=235 guifg=#d8dee9 guibg=#1b2b34
```

**Comment by cseickel** [comment]
> It was working few days ago. An update broke it. I don't know which package.

Well, the highlight groups look fine. If there is a certain version of Neovim that it breaks on, then I can fix that. If it is an interaction with another plugin then I would need you to  identify which one, and ideally give me a minimal config to recreate it.

**Comment by s1n7ax** [comment]
Found the issue. plugin called Shade.nvim was messing up all neo-tree popups.
