### ISSUE TITLE
Faded highlights get broken after changing the color scheme

### ISSUE THREAD

**Issue by atchim** [nvim-neo-tree/neo-tree.nvim#311]
Faded highlights doesn't work as expected after a color scheme change. Also, I think it would be nice to have an option to disable faded highlights.

**Comment by ryoppippi** [comment]
Me too
But I also found this issue on Fern. 
I guess this issue is not came from neo-tree

**Comment by ryoppippi** [comment]
@cseickel Thanks!

**Comment by ryoppippi** [comment]
@atchim 
This can happen everywhere.
If you want to set colorscheme in autocmd, add nested option( like `++nesed` or `nested = true`
