### ISSUE TITLE
split_with_window_picker

### ISSUE THREAD

**Issue by nagy135** [nvim-neo-tree/neo-tree.nvim#314]
Hello, I m curious if this feature would be possible (or is already?).

Basically `w` (default bind) allows us to select where the window opens, but if I want it to appear in split, I have to create split, then close neo-tree, open it again (because that way the last split that had focus is that new split ...or simply make sure that I get to neo-tree from that new split) and then use `w` to place new file there.

Those are many steps I do quite often. Is there a better way? I would even suggest to take approach that nvim-tree took, and basically defaulting to pick destination every time when destination is not 100% determined, when you have more than one split opened.

The same thing should apply to vsplit.

Subjective opinion:
I understand that it has some advantages to have this picker as a optional dependency, but imho this should be default because the way it "chooses" where to open is something I have to keep in mind every time I open split. I even made `open_with_window_picker` my default opener, because that does exactly what I m proposing here with splits.

**Comment by cseickel** [comment]
I think it would actually be a simple change to create a "split from chosen window" command. I'll put it on the list. There's probably enough information in the wiki to build one in your config as well if you want to take a shot at it.
