### ISSUE TITLE
[Cross-Plugin Bug] If a buffer is opened via the other plugins(fzf-lua), it will not be a listed buffer, thus cannot be shown by bufferline.nvim

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#321]
Continued from https://github.com/nvim-neo-tree/neo-tree.nvim/issues/305#issuecomment-1102065752. While the double-`[No Name]` has been resolved, I forgot to test the interaction between neo-tree and fzf-lua. I found that:

1. If the buffer is opened via fzf-lua, the result of command `set buflisted?` is `nobuflisted`. This means that the problem is not from bufferline.nvim, it is working correctly: ignore not-listed buffers.
2. It only happened when I started a new `nvim` process and wanted to create the first window/buffer for the file selected via fzf-lua, as the two DEMO below. No such problem if there is already a buffer loaded/listed in the background.
3. By testing without neo-tree.nvim, I cannot reproduce this bug using fzf-lua's minimal config.

So it seems that the interaction between neo-tree.nvim and fzf-lua will somehow cause a buffer loaded with `nobuflisted`, thus the buffer is not displayed by bufferline.nvim.

---

**UPDATE**:

In my experiments, these combinations didn't work as expected: (all testings use `hijack_netrw_behavior = 'open_default'`, if I change it to `'open_current'` the problem of 2. will disappear, i.e. the buffer from fzf-lua selection will get listed.)

1. `position = 'float'` + fzf-lua selection: While the file did get listed, the current buffer becomes (the only) `[No Name]`.

https://user-images.githubusercontent.com/24765272/165285068-929b783a-4eed-4f40-ac48-947840134d07.mov

2. `position = 'left' / 'right'` + fzf-lua selection: The current buffer did load the file content, but its `set buflisted?` returns `nobuflisted`.

https://user-images.githubusercontent.com/24765272/165284741-68ccbfc1-093c-4678-a3c8-1c771fb5898a.mov

**Comment by cseickel** [comment]
I have two comments:

1. Can you please provide a minimal init that includes Neo-tree? It could still be the interaction from another plugin that is causing your issue.
2. The combination of using a netrw hijack along with position="float" and then opening a fzf window is a little ridiculous. Just don't do that. The "float" position is really for using Neotree as a fuzzy finder, it shouldn't be left open all the time or used as part of a netrw hijack.
3. In the second video, was Neotree the focused window when you initiated fzf? If it was, try focusing the other window first and then initiating fzf.

I find it very unlikely that Neo-tree could be affecting whether or not another buffer is listed or not. There is a slim possibility that it could affect which buffer is focused though, especially if Neo-tree was the focused window when you tried to open a new buffer.

**Comment by nyngwang** [comment]
> 1. Can you please provide a minimal init that includes Neo-tree? It could still be the interaction from another plugin that is causing your issue.

Can. But it takes some time since my config is a little bit messy. I might post it and tag you later.

> 2. [...] The "float" position is really for using Neotree as a fuzzy finder, it shouldn't be left open all the time or used as part of a netrw hijack.

Got it.

> 3. In the second video, was Neotree the focused window when you initiated fzf? If it was, try focusing the other window first and then initiating fzf.

Wow, this fixes this problem!

**Comment by Shatur** [comment]
Have the same behavior with Telescope.

**Comment by cseickel** [comment]
I was able to recreate this with Telescope with `:Neotree buffers` to show me what is listed, and files opened via Telescope when I am currently on a Neo-tree window will have this problem. I can fix this now.

**Comment by cseickel** [comment]
This should be fixed now in `main`

**Comment by Shatur** [comment]
Works for me.

**Comment by nyngwang** [comment]
@cseickel I think the bug has not been fixed?

**Comment by cseickel** [comment]
@nyngwang It works fine for me. I am testing with Telescope instead of fzf, but I wouldn't expect that to make a difference. Are you still having a problem opening files as listed when a Neotree float was the prior window?

**Comment by nyngwang** [comment]
@cseickel Sorry for my late reply, sleeping. I have tested removing these checks but the results are the same as the video in this thread. Let me test it again now.
