### ISSUE TITLE
Unable to create directory of name starting with number

### ISSUE THREAD

**Issue by lorefnon** [nvim-neo-tree/neo-tree.nvim#323]
In the sidebar treeview when I try to create a directory named `04` entering `a` and then `04/` creates a file named `04` even though a trailing slash is present. This seems to happen whenever filename starts with a number.

**Comment by cseickel** [comment]
Actually, for me the trailing slash to add a directory is not working for any file name.  I'll fix that.

**Comment by nyngwang** [comment]
@cseickel: I just experienced this too, and thanks for your upcoming fix!
