### ISSUE TITLE
Unable to disable hijack_netrw_behavior

### ISSUE THREAD

**Issue by yesean** [nvim-neo-tree/neo-tree.nvim#324]
## Description
I've been trying to disable `hijack_netrw_behavior` (setting it to `disabled`) but it doesn't seem to be working. `neo-tree` does indeed prevent itself from opening, but instead of getting the usual `netrw` screen, I'm getting a blank buffer. I'm expecting 
![correct-netrw](https://user-images.githubusercontent.com/20366175/165269436-0e84fd06-7d33-42fc-a025-ca3ca33adafa.png)
but I'm getting
![incorrect-netrw](https://user-images.githubusercontent.com/20366175/165269487-0dfd0c22-2348-45f3-b3ef-f76be80fbf6b.png)
instead.

## Steps to Reproduce
minimal config:
```lua
    require("neo-tree").setup({
      filesystem = {
        hijack_netrw_behavior = "disabled",
      }
    })
```

## Steps Taken
I dug around a bit and commenting out [this line](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/116ffb05accc9f1a3d0954ed8f90c618d548b145/lua/neo-tree/setup/init.lua#L479) seems to properly enable netrw which I guess relies on the `FileExplorer` augroup? Furthermore, the config check in the line above calls `netrw.get_hijack_netrw_behavior()` which, in my testing, was returning `'open_default'` instead of `'disabled'`. I think what's happening is that when `get_hijack_netrw_behavior()` is called in `merge_config()`, `nt.config` hasn't been initialized yet since it relies on the return value of `merge_config()`, so `nt.config` is `nil` causing `utils.get_value()` to set `hijack_behavior` as the fallback value of `'open_default'` instead of `'disabled'` in this [line](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/116ffb05accc9f1a3d0954ed8f90c618d548b145/lua/neo-tree/setup/netrw.lua#L16). This is roughly what I found in my experimenting and I'm not too familiar with the other parts of the plugin's setup, but I'm happy to provide any more info.

Thanks for creating this plugin, I've really enjoyed using it!

**Comment by cseickel** [comment]
Thanks for taking the time to debug this for me, I'll fix it soon.

> Thanks for creating this plugin, I've really enjoyed using it!

You're very welcome!
