### ISSUE TITLE
window picker on directory

### ISSUE THREAD

**Issue by nagy135** [nvim-neo-tree/neo-tree.nvim#326]
As I said in issue before, I think this window picking behavior should be default and I binded it like that (having option to do that is good UX). Issue I m facing now is that I basically always use window_picker even on `<CR>` and i m unable to hide/show directories with the same key.

So what I m proposing is that `window_picker_open` should act like regular open on directory nodes. 
I would implement it, just asking if it is desired behavior. Basically, is there any reason to ever *pick location with window picker to open directory*? It even changes working directory.

**Comment by cseickel** [comment]
No, there's no reason to ever try to open a directory with a window picker. I'm looking at teh code now and I see exactly where to make this change so I'll do it.

**Comment by cseickel** [comment]
This is in `main` now.

**Comment by nagy135** [comment]
Works as expected, good job!
