### ISSUE TITLE
The current file is not highlight in neo-tree if it's in a floating window

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#327]
As title. See this image: my current is at a floating window(the right one), but the highlight of neo-tree is at the wrong file. 

<img src="https://user-images.githubusercontent.com/24765272/165484377-7f285b98-865b-47eb-8af6-b897ccad8b01.png" width="700">

**Comment by cseickel** [comment]
That is by design. `follow_current_file` does not apply to floating windows, because floating windows are normally for extra information, previews, or other utility functions. 

I don't think it is reasonable to edit files in a floating window so this is not a use case that I will support.
