### ISSUE TITLE
NeoVim 0.7 superseded VertSplit with WinSeparator

### ISSUE THREAD

**Issue by m-lima** [nvim-neo-tree/neo-tree.nvim#328]
This means that https://github.com/nvim-neo-tree/neo-tree.nvim/blob/01d54bdc316aa36b4eefc8cc456f605cd2e267cc/lua/neo-tree/setup/init.lua#L77 does not work as intended with `VertSplit`.
A new (maybe transitional) hl needs to be created to work as an override of `WinSeparator`

**Comment by cseickel** [comment]
Do you happen to have a link to any official documentation about this? I see it mentioned in the help but nothing about deprecation period or similar.

**Comment by m-lima** [comment]
> Do you happen to have a link to any official documentation about this? I see it mentioned in the help but nothing about deprecation period or similar.

I don't have anything besides the help.
What I can add is that 0.7 added the `laststatus = 3` mode, which allows a single statusline. Because of this, the separators are not only vertical anymore, they can also be horizontal. Therefore, they needed a more fitting name for the hl
See also `fillchars` to see the new characters added for the horizontal split and the intersections
