### ISSUE TITLE
Toggling neotree two times in a row puts it in a broken state

### ISSUE THREAD

**Issue by ioreshnikov** [nvim-neo-tree/neo-tree.nvim#33]
Hi!

The steps to reproduce are the following:
1. Open a file in a git directory.
2. Call `:NeotreeShowToggle` to reveal `neo-tree`.
3. Call it one more time to hide it.
4. From now on calling it will give you a stack trace below.

![Снимок экрана от 2022-01-10 11-09-56](https://user-images.githubusercontent.com/1098912/148749140-6d38114b-16ab-4630-826d-436172fe67f0.png)

I am using the latest `main` branch.

Best,
Ivan

**Comment by cseickel** [comment]
Thanks for reporting! It should be fixed now in both **main** and **1.x**.

**Comment by ioreshnikov** [comment]
@cseickel yep, fixed, thanks!
