### ISSUE TITLE
Add the ability to disable buffer modification tracking 

### ISSUE THREAD

**Issue by Shatur** [nvim-neo-tree/neo-tree.nvim#331]
I would like to suggest to add an option to toggle modification tracking like `enable_diagnostics` or `enable_git_status`. Because modification tracking sometimes causes slowdown.

**Comment by cseickel** [comment]
Before I do that, I'd rather try to fix whatever the slowdown is. If it works correctly, it should not have a meaningful overhead.

If the event is just firing too often, it would be a 3 character change to add a debounce to that event. 

If it is just an error in the component that renders the change, I can check that for errors or come up with a more efficient strategy to track that state. You can also set a custom renderer that omits that component.

If you don't might troubleshooting this with me, sharing your logs from a short session that has slowdowns would be helpful:
https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Troubleshooting

**Comment by Shatur** [comment]
I have a delay when I changing a file / undoing all changes which results in sign adding / removal. Here is the log:
[neo-tree.nvim.txt](https://github.com/nvim-neo-tree/neo-tree.nvim/files/8585377/neo-tree.nvim.txt)
.

**Comment by cseickel** [comment]
May be fixed by #336

**Comment by Shatur** [comment]
But can we also have an ability to disable this feature? I don't think I need it.

**Comment by cseickel** [comment]
Sure

**Comment by cseickel** [comment]
This done in `main`. The modified flag should be much faster now, and it can be disabled entirely with:
```lua
    require("neo-tree").setup({
      enable_modified_markers = false,
    })

```

**Comment by Shatur** [comment]
Thanks! I disable all markes but still have a little delay on modifications if neo-tree is open.

**Comment by Shatur** [comment]
And on save.

**Comment by cseickel** [comment]
@Shatur I noticed an extra "modified" event subscription that I missed the first time which has now been removed. Can you give it another try now?

**Comment by Shatur** [comment]
Hm... Still exists.

**Comment by Shatur** [comment]
Here is the updated log when I trigger mentioned delays multiply times: [neo-tree.nvim.txt](https://github.com/nvim-neo-tree/neo-tree.nvim/files/8597397/neo-tree.nvim.txt)

**Comment by cseickel** [comment]
OK, I found another thing that shouldn't be there. The "buffer_changed" event was firing in response to the `BufModifiedSet` event, and that really shouldn't be happening any more.

Now it is probably done, for real this time...

**Comment by Shatur** [comment]
Now it's smooth even with all markes, thank you!
