### ISSUE TITLE
File nesting problem

### ISSUE THREAD

**Issue by Muslik** [nvim-neo-tree/neo-tree.nvim#334]
File nesting not working properly if i am adding multiple file types.

```lua
  nesting_rules = {
    tsx = { "module.css", "module.scss", "scss" },
    jsx = { "module.css", "module.scss", "scss" },
  },
```

[Here](https://ibb.co/8DQMn1B) you can see that it's working properly for typescript files, but not for javascript.
If i'll remove tsx key, [jsx working properly](https://ibb.co/DkDtQ2h):
```lua
  nesting_rules = {
    jsx = { "module.css", "module.scss", "scss" },
    -- tsx = { "module.css", "module.scss", "scss" },
  }
```

**Comment by cseickel** [comment]
I don't think that was an expected scenario when this was added so I can see why it doesn't work with multiple rules for the same child file types. 

This is a lower priority for me relative to some of the other open issues, but it will get done eventually.

**Comment by nyngwang** [comment]
@cseickel Since #392 is merged (thanks to @danilshvalov) I think this can be closed!
