### ISSUE TITLE
Refreshing or adding files reset the root dir to cwd

### ISSUE THREAD

**Issue by jaekyeom** [nvim-neo-tree/neo-tree.nvim#339]
Hi again,

I think that refreshing (which also seems to happen after renaming, etc.) or adding files set the root directory of neo-tree.nvim to the current working directory of nvim (e.g., [1](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/sources/filesystem/commands.lua#L12), [2](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/sources/filesystem/init.lua#L242) pass `nil` instead of `state.path`?).

As a user who uses `bind_to_cwd = false`, I believe maintaining the root directory of neo-tree.nvim would be a more intuitive behavior.
If this was intentional, could you reconsider it, please?

Thanks!

**Comment by cseickel** [comment]
That was just an oversight, it is fixed now in `main` and will be part of tonight's release.
