### ISSUE TITLE
NeoTreeGitConflict highlight is used for unstaged symbol

### ISSUE THREAD

**Issue by s1n7ax** [nvim-neo-tree/neo-tree.nvim#343]
Seems like his symbol is highlighted using `NeoTreeGitConflict` color reflects in `unstaged` symbol.

```
        git_status = {
            symbols = {
                -- Change type
                added = '', -- or "✚", but this is redundant info if you use git_status_colors on the name
                modified = '', -- or "", but this is redundant info if you use git_status_colors on the name
                deleted = '✖', -- this can only be used in the git_status source
                renamed = '', -- this can only be used in the git_status source
                -- Status type
                untracked = '',
                ignored = '',
                unstaged = '',
                -- ^^^^^^^^^^^^ Seems like his symbol is highlighted using NeoTreeGitConflict highlight group because when I change NeoTreeGitConflict to guifg=#7e73ff, that symbol color is changed.
                staged = '',
                conflict = '',
            },
        },
```

**Comment by cseickel** [comment]
That is intentional that they use the same color by default, the only difference in the highlight groups are that conflicts are also `bold`. If you want them to be different, you'll need to set the `NeoTreeGitUntracked` highlight group.

**Comment by s1n7ax** [comment]
I have all the `NeoTreeGit` highlight overridden. Does it mean it the unstated show `NeoTreeGitUntracked` color? BTW, why `NeoTreeGitConflict` to `ustaged` sign highlight match? Seems like a weird combination for me. Just saying, it would be awesome if they just had separate highlights just for git signs. `NeoTreeGitSignUntracked` or something.

![image](https://user-images.githubusercontent.com/18459807/166605777-64016819-d6c3-4e09-b070-43d9c5c8e83d.png)
![image](https://user-images.githubusercontent.com/18459807/166605925-1ab47378-5c6b-4f56-83bc-0f2f6579d507.png)

**Comment by cseickel** [comment]
> I have all the `NeoTreeGit` highlight overridden. Does it mean it the unstated show `NeoTreeGitUntracked` color?

Yes, unstaged uses `NeoTreeGitUntracked`, both words are used by git in different places to mean the same thing.

> BTW, why NeoTreeGitConflict to ustaged sign highlight match? 

In my mind, they are both errors that need to be resolved, so it makes sense to me. I can disambiguate the type of error by the icon, but in reality I already know which files are new and which would likely have a conflict.

I see in your screenshot that you have set separate colors for untracked vs conflict, does it show the correct colors in that case?

Its also kinda funny that you reused a color between modified and untracked! I can see the logic, but to me that is way crazier than conflict and untracked sharing a color.

**Comment by s1n7ax** [comment]
> Yes, unstaged uses NeoTreeGitUntracked, both words are used by git in different places to mean the same thing.

I don't think it's the same. Untracked means repository will not track any changes. Unstaged means, tracked or untracked changes are not added to the stage to be committed.

> I see in your screenshot that you have set separate colors for untracked vs conflict, does it show the correct colors in that case?

I expected it to show purple color and it does in a merge conflict.
![image](https://user-images.githubusercontent.com/18459807/166610435-bef5eac0-8b8d-48cc-83d6-ffbffb0c8a6f.png)



> Its also kinda funny that you reused a color between modified and untracked!

According to README, `NeoTreeModified` means you have edited something but NOT saved. I don't think it has anything to do with git.

```
modified = {
  symbol = "[+]",
  highlight = "NeoTreeModified",
}
```

Here, I have used red color for `NeoTreeModified` and `NeoTreeGitUntracked` because it's dangerous. In case if I forgot to save `NeoTreeModified` the file and close the terminal, I'm not getting them back. If I ran `git clean -fd` while there are `NeoTreeGitUntracked`, I'm not getting them back either.

However, `NeoTreeGitConflict` as much as it's important to resolve them, it not possible to mess up something by the user. You always can start over the merge or rebase or whatever.  Hen the purple color.

But the fact that untracked sign uses the `NeoTreeGitConflict`, which is less significant (to me at least), is confusing to me.

**Comment by s1n7ax** [comment]
> I see in your screenshot that you have set separate colors for untracked vs conflict, does it show the correct colors in that case?

If there a merge conflict? Yes
![image](https://user-images.githubusercontent.com/18459807/166611511-77b5033a-07bc-4c73-8560-69fc6a83c1bb.png)

If there a untracked modification? No,
![image](https://user-images.githubusercontent.com/18459807/166611492-bdc821b8-bc9e-4462-a685-287cdea7fd89.png)

**Comment by s1n7ax** [comment]
I think someone else could come up with some other argument to justify some other color scheme so that's why I though having separate highlight for git signs and files would be nice.

**Comment by cseickel** [comment]
> I don't think it's the same. Untracked means repository will not track any changes. Unstaged means, tracked or untracked changes are not added to the stage to be committed.

Oh yeah, you are absolutely right. I don't know what I was thinking, just tired I guess. To get back to your original question, unstaged does use the `NeoTreeGitConflict` highlight and staged uses the `NeoTreeGitAdded` highlights. I saw this in my mind as just negative and positive. I'm sorry I didn't understand the original request, but I get it now. **I should add separate `NeoTreeGitUnstaged` and `NeoTreeGitStaged` highlight groups.**

> According to README, NeoTreeModified means you have edited something but NOT saved. I don't think it has anything to do with git.

Right again. I'm really tired...

> But the fact that untracked sign uses the NeoTreeGitConflict, which is less significant (to me at least), is confusing to me.

I see it a little differently. Untracked to me is just as bad as Conflict, both mean I'm not ready to submit a PR. Untracked files should either be added or gitignored. I can certainly see how your concern is more about unsaved changes, but that's just not an issue for me because I obsessively hit the `wa` mapping every minute.

**Comment by cseickel** [comment]
I just added this in `main`, you now have `NeoTreeGitStaged` and `NeoTreeGitUnstaged` that you can use to set the colors for those symbols.

**Comment by s1n7ax** [comment]
looking gorgeous

![image](https://user-images.githubusercontent.com/18459807/166625230-f2aed76d-12d2-40f0-b341-a184d5e87cdb.png)
