### ISSUE TITLE
Delay on the text input window

### ISSUE THREAD

**Issue by rockyzhang24** [nvim-neo-tree/neo-tree.nvim#346]
Hi, 
I noticed that there is a delay around 1 second for opening the text input window when I execute commands like `copy`, `move` or something like that. For example, when I press `c` (default mapped to `copy`), the text input window won't be shown immediately and instead there is a very short but noticeable delay before displaying the input window. Is this the normal behavior by design or a bug? 

Thank you.

**Comment by cseickel** [comment]
It's not normal. It could be that the `nowait` option isn't being applied for some reason, and it is waiting to see if you are going to enter a mapping that starts with `c`, like `ciw`. 

This is the default settings, have you changed anything?

```lua
    mapping_options = {
      noremap = true,
      nowait = true,
    },
    mappings = {
```

**Comment by rockyzhang24** [comment]
So if I disabled all default mappings by `use_default_mappings = false`, in addition to explicitly setting `window.mappings`, I should set `window.mapping_options` as well, right?

**Comment by cseickel** [comment]
> So if I disabled all default mappings by `use_default_mappings = false`, in addition to explicitly setting `window.mappings`, I should set `window.mapping_options` as well, right?

Yes.

**Comment by rockyzhang24** [comment]
Got it. Thank you.
