### ISSUE TITLE
Filter as typed invisible cursor

### ISSUE THREAD

**Issue by treatybreaker** [nvim-neo-tree/neo-tree.nvim#347]
Really appreciate the plugin here, but I've had an issue with the "filter as you type" functionality where my cursor disappears.

![NTInvisible](https://user-images.githubusercontent.com/58627896/166978450-9276996e-f5b9-4b8d-899d-69b1ba46f8cc.gif)

I've attempted to set my cursorline & all Neotree highlight groups to 100% white (#ffffff) and have had no luck. I'm on the `2.x` branch. Content of my neotree setup is 100% minimal currently:

```lua
vim.g.neo_tree_remove_legacy_commands = 1
neotree.setup({})
```

My full configuration can be viewed [here](https://gitlab.orion-technologies.io/philler/dot-files/-/tree/Development/.config/nvim). 

Any pointers on what I may have missed or is this intended and I simply misunderstand?

**Comment by cseickel** [comment]
> Any pointers on what I may have missed or is this intended and I simply misunderstand?

It's definitely not intended and it doesn't happen for me. There are a lot of rapid fire screen updates during the "filter as you type" action, maybe that is why you see the issue there.

Do you have any autocmds or plugins that change the cursorline in response to any events?

**Comment by treatybreaker** [comment]
Found the issue, related to a plugin I use: `modes.nvim`. That plugin modifies the cursorline in response to events -- totally forgot about it. So it's not neo-tree's problem, it's `modes.nvim`. Thanks for mentioning the events on cursorline, completely slipped my mind 😅.

**Comment by nyngwang** [comment]
@treatybreaker I recommend removing (some to all) fancy plugins until all utilities plugins got stable. I have experienced with this kind of bug from another plugin and it was really time-consuming to solve.
