### ISSUE TITLE
Support horizontal scrolling in neo-tree window?

### ISSUE THREAD

**Issue by joshuali925** [nvim-neo-tree/neo-tree.nvim#348]
Hi thanks for the plugin, recently updated it and found file name rendering logic changed. 
<img width="451" alt="image" src="https://user-images.githubusercontent.com/28062824/167025533-db2c4a15-a12b-4e52-a6bb-544cca4b537c.png">
if filename is very long, it only partially renders. users can't see it even after pressing `zl` to scroll. This also prevents searching, for example the file name is `completion.lua`, but `/completion.lua` doesn't have any matches because the rendered text is `comple`.

Is there any plans to support these? thanks

**Comment by cseickel** [comment]
You'll want to remove the containers from the default renderers. See https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/267#discussioncomment-2547669

**Comment by joshuali925** [comment]
that worked, thanks!
