### ISSUE TITLE
[Feature Request] File nesting for filename patterns

### ISSUE THREAD

**Issue by akinsho** [nvim-neo-tree/neo-tree.nvim#349]
In some languages, for example in go identifying a test or other related file might use a different filename pattern e.g. a go file ends with `file.go` and its test will end with `file_test.go` I believe this is also a pattern used in several other languages e.g. `_spec.blah` etc. I see from the original issue/PR that the decision was to go with the simplest solution, however I think there are a bunch of use cases in other languages that would be served by allowing nesting based on filename patterns.

Any thoughts on having file nesting work for these use cases as well?

**Comment by RaafatTurki** [comment]
I've got an another face to this issue, I couldn't nest the file pattern below as
```lua
js = { 'js.map', 'd.ts' }
```

![image](https://user-images.githubusercontent.com/16624558/184757077-7836829b-9862-4094-8118-7720817d6754.png)

**Comment by Teddytrombone** [comment]
I just want to add another example:

```lua
["package.json"] = { "package-lock.json", "yarn.lock" }
``` 

which would nest `package-lock.json` and `yarn.lock` below/inside a `package.json` ;-)
