### ISSUE TITLE
Notification shows twice when I rename a file

### ISSUE THREAD

**Issue by thieung** [nvim-neo-tree/neo-tree.nvim#350]
After rename a file, the popup show 2 messages saying that I renamed successfully. I think we should notify only one message in this case?
 
<img width="502" alt="image" src="https://user-images.githubusercontent.com/79964592/167160945-fa87b528-de63-4ac0-ab67-304e82044d28.png">

**Comment by cseickel** [comment]
It definitely should only be once. I hadn't noticed because I don't use the notify plugin, but it seems like the extra notification is the original name. I'll fix it.
