### ISSUE TITLE
Feature: Be able to use native confirm() as inputs.confirm implementation

### ISSUE THREAD

**Issue by williamboman** [nvim-neo-tree/neo-tree.nvim#351]
I've disabled `use_popups_for_input`, and I also use https://github.com/stevearc/dressing.nvim which changes `vim.ui.*` to floating-style elements (effectively voiding the disabled `use_popups_for_input`).

I'd like for the confirm action to actually prompt me vim-style á la `confirm()`. Would this make sense to add into neo-tree core, or should I overwrite the module myself, like:

```lua
local inputs = require("neo-tree.ui.inputs")
inputs.confirm = function (...) confirm(...) end
```

edit: Maybe neovim needs a `vim.ui.confirm()` component 😄

**Comment by cseickel** [comment]
> edit: Maybe neovim needs a `vim.ui.confirm()` component 😄

💯 In the absence of that, I'd say just overwrite the module because I assume most people that use dressing.nvim for inputs would probably want to use dressing for confirms as well.

**Comment by williamboman** [comment]
Cool! Here's how I did it, for reference:

```lua
require("neo-tree.ui.inputs").confirm = function(message, callback)
    callback(vim.fn.confirm(message, "&Yes\n&No") == 1)
end
```

**Comment by cseickel** [comment]
Thanks for sharing the solution!
