### ISSUE TITLE
feature request: search by / only search in top level entries.

### ISSUE THREAD

**Issue by tristone13th** [nvim-neo-tree/neo-tree.nvim#354]
when search with /, all nested directory will be opened to match the result, is there any method to just search in the top level entries rather than all the files?

**Comment by cseickel** [comment]
You can add your own arguments to the `find`/`fd` command being used: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/a917174b38b065b5fc01c89709cfc31fbe6917db/lua/neo-tree/defaults.lua#L297

I think this will do what you want: 
```lua
    ...
    find_args = {  -- you can specify extra args to pass to the find command.
      fd = {
        "--max-depth", "1",
      },
      find = {
        "-maxdepth", 0
      }
    },
    ...
```

**Comment by tristone13th** [comment]
Many thanks to you! A small fix:

    ...
    find_args = {  -- you can specify extra args to pass to the find command.
      fd = {
        "--max-depth", "1",
      },
      find = {
        "-maxdepth", 1
      }
    },
    ...
