### ISSUE TITLE
How change background highlight color?

### ISSUE THREAD

**Issue by sinetodev** [nvim-neo-tree/neo-tree.nvim#355]
First of all, thanks for this great plugin.

I want to do on my nvim config something like this:
https://i.redd.it/3xpcwmnr47y81.png
See how the left-side window background is different from the main window.

How can I do config this? I saw the docs but I don't get it yet.

Thanks in advance for the help.

**Comment by sinetodev** [comment]
I've try to do that, but didn't work at all. What I'am doing wrog?

The snippet on my setup
https://github.com/sineto/nvim/blob/dbdf7c79c13c265a3cf59ae36e896e25593b631b/lua/specs/neotree/init.lua#L73

**Comment by cseickel** [comment]
I would guess that your colorscheme is being applied after this code runs and is overriding the groups. If that's true, the solution is to either change that order or reapply the highlight groups in response to the `ColorScheme` event:

```
:h ColorScheme
```

**Comment by sinetodev** [comment]
I found a workaround for this use case. Seems not a great solution but worked. I will place here a code snippet of the solution.
```lua
local M = {'sainnhe/sonokai'}

M.config = function()
  vim.cmd([[
    function! s:sonokai_custom() abort
      let s:configuration = sonokai#get_configuration()
      let l:palette = sonokai#get_palette(s:configuration.style, s:configuration.colors_override)

      call sonokai#highlight('NeoTreeNormal', l:palette.fg, l:palette.black)
      call sonokai#highlight('NeoTreeNormalNC', l:palette.fg, l:palette.black)
      call sonokai#highlight('NeoTreeSignColumn', l:palette.fg, l:palette.black)
      call sonokai#highlight('NeoTreeEndOfBuffer', l:palette.black, l:palette.black)
    endfunction
    
    augroup SonokaiCustom
      autocmd!
      autocmd ColorScheme sonokai call s:sonokai_custom()
    augroup END
  ]])

  vim.g.sonokai_style = 'shusia'

  vim.cmd([[colorscheme sonokai]])
end

return M
```
