### ISSUE TITLE
[Question] How to open automatically on startup and get relativenumbers

### ISSUE THREAD

**Issue by mark-ruddy** [nvim-neo-tree/neo-tree.nvim#357]
Hi - thanks for making neo-tree its a great plugin! I've been struggling to implement the below functionality though that would usually be in a tree-view plugin:

- `open_on_setup` - when you open `nvim` the tree will open at the current directory
- `relativenumber` - show relative number lines in the neo-tree buffer, just like setting `set relativenumber` manually

I'm sure there would be some way to hack this in through auto-commands(I've tried a few which haven't worked, see below) - but it would be nice to see it documented or these options exposed by neo-tree itself. 

Please let me know if this already is and I'm missing something!
```
-- doesn't work
vim.api.nvim_exec([[au VimEnter * NeoTreeShow]], false)
vim.api.nvim_exec([[au VimEnter * wincmd p]], false)
```

**Comment by cseickel** [comment]
Your autocmd _should_ work, but it does use the old commands which you may have disabled (which is what is suggested in the README). I should also point out that it is a bad idea to create autocmds outside of an `augroup` like that. This is tested and will work even with plugins that auto restore sessions:

```lua
  vim.cmd[[
    augroup NEOTREE_AUGROUP
      autocmd!
      au VimEnter * lua vim.defer_fn(function() vim.cmd("Neotree show left") end, 10)
    augroup END
  ]]
```

For the line numbers, you can use this:

```lua
require("neo-tree").setup({
  event_handlers = {
    {
      event = "neo_tree_buffer_enter",
      handler = function(arg)
        vim.cmd [[
          setlocal relativenumber
        ]]
      end,
    }
  },
  ... the rest of your config ...
```

**Comment by mark-ruddy** [comment]
Hi @cseickel - Thanks! 

I used your code snippets exactly as shown and they worked perfectly. `neo-tree` now opens on startup in the CWD and has relative line numbers in the buffer that don't go away when you switch buffers.
