### ISSUE TITLE
Ability to remap keys in Insert mode while in Fuzzy Finder

### ISSUE THREAD

**Issue by ziontee113** [nvim-neo-tree/neo-tree.nvim#358]
Thank you for the awesome plugin!

I'm trying to remap `<C-j>` and `<C-k>` to `<Down>` and `<Up>`, only when Fuzzy finding with `/`.
The purpose is to moving / selecting through search results.
It'd be nice not having to reach for the arrow keys while in insert mode :)

Is there a way that I can do that? Thank you very much!

**Comment by cseickel** [comment]
There's no configuration for that, but you can currently use `<C-n>` and `<C-p>`, does that work?

**Comment by ziontee113** [comment]
Oh wow thank you, it worked!
