### ISSUE TITLE
Add a shortcut to copy filename

### ISSUE THREAD

**Issue by Shatur** [nvim-neo-tree/neo-tree.nvim#359]
In https://github.com/kyazdani42/nvim-tree.lua you can copy filename (example: `foo.lua`) and file path relative to the opened root folder (example: `folder1/folder2/foo.lua`).
It's very convenient feature and it would be nice to have something like this.

I would suggest to use `Y` to copy filename and `<C-y>` to copy  relative to opened root path.

**Comment by cseickel** [comment]
You can do that with `c`, mapped to the `copy` command. It takes text input for the destination and you can enter a path relative to its current location, just like if you were at the command line. You could, for example, menter `../../file.txt` to move it up two folders.

**Comment by Shatur** [comment]
@cseickel no, no, I don't want to copy or move files. The idea is to copy **filename** to the default register.

**Comment by cseickel** [comment]
Oh ok. This is a good use for custom mappings:

```lua
        ["Y"] = function(state)
          local node = state.tree:get_node()
          vim.fn.setreg('*', node.name, 'c')
        end,
        ["<C-y>"] = function(state)
          local node = state.tree:get_node()
          local full_path = node.path
          local relative_path = full_path:sub(#state.path + 2)
          vim.fn.setreg('*', relative_path, 'c')
        end,
```

**Comment by Shatur** [comment]
Thank you a lot, will use!

**Comment by nyngwang** [comment]
@cseickel Why `viw*y` doesn't work?

**Comment by cseickel** [comment]
@nyngwang That would work only if you haven't remapped any of those keys within the neo-tree window. It's also much longer than the requested `Y`. The other problems are:

- that would only work for the name by itself, and 
- if that name is clipped you'd only get what is visible
- it does not help with the request to copy the relative path of the file

**Comment by cseickel** [comment]
You can get taht by creating custom commands and then mapping to that command name instead of to an anonymous function:

```lua
   require("neo-tree").setup({
     filesystem = {
       commands = {
         copy_file_name =  function(state)
          local node = state.tree:get_node()
          vim.fn.setreg('*', node.name, 'c')
        end
       },
       window = {
           mappings = {
             ["Y"] = "copy_file_name"
           }
       }
     }
   })
```

Note that while you can define mappings globally for all sources, commands need to be defined within the sources (i.e. "filesystem").

**Comment by zeitchef** [comment]
That's awesome @cseickel - thanks so much! Testing this, it seems the second function will return the full path relative to the current working directory. Would there be an easy way to calculate the path relative to the current buffer? 

Working with big Vue projects, I'm constantly forced to construct import paths that look like '../../../path/file' and I would love an easy way to get this from the file tree. Happy to create a feature request if you prefer. Thanks again!

**Comment by cseickel** [comment]
> That's awesome @cseickel - thanks so much!

No problem, happy to help!

> Working with big Vue projects, I'm constantly forced to construct import paths that look like '../../../path/file' and I would love an easy way to get this from the file tree.

Not really. To execute the mapping, you need to be in the neo-tree buffer, so it wouldn't know which buffer you want to create a relative path for. My suggestion would be to just use your completion plugin to help you type out the paths. Most of them support completing relative sources.
