### ISSUE TITLE
Handle rapid changes gracefully (the curse of vim-rooter)

### ISSUE THREAD

**Issue by ioreshnikov** [nvim-neo-tree/neo-tree.nvim#36]
Hey!

First of all, thanks for lightning-fast bugfixes! I have another one for you: `neo-tree` behaves inconsistenly when I switch the project using `Telescope project`. How to reproduce:

1. Open any file in a git directory, for example, your neovim config and toggle `neo-tree`.
2. Lauch `Telescope proejct`. As you start typing, `Telescope` will bring the closest matching project as the current selection under the cursor and `neo-tree` will detect this change and will automatically switch the root directory _on the fly_ (WOW!)
3. Select a new project and then a file in this project by pressing `Enter`. This confuses `neo-tree` for some reason an it displays the old project root but without any content of the old project directory (screenshot below).

![Снимок экрана от 2022-01-10 13-26-01](https://user-images.githubusercontent.com/1098912/148765691-87e58184-919b-419e-9778-341a9fe6c8fa.png)

Best,
Ivan

**Comment by ioreshnikov** [comment]
Thinking of it, root directory detection might be due to `vim-rooter`, but in any case `neo-tree` reflects the change seamlessly. Big fan!

**Comment by cseickel** [comment]
Neo-tree does have a `bind_to_cwd` that is turned on by default, which will automatically respond to changes in cwd, and likewise will change the cwd in vim if you change it in Neo-tree.

I haven't used Telescope projects, but I do have it installed so I will test it out.

**Comment by cseickel** [comment]
It works fine for me, although the cwd does not change as I type in the Telescope window. Can you try removing vim-rooter to see if that is part of the issue?

**Comment by ioreshnikov** [comment]
@cseickel I was wrong about chaning on typing, actually, it only happens when you select a new project.

Removing rooter does help. Switching to a new project then leaves me with the correct project-specific tree.

With the rooter though, after switching a project I can confirm that `pwd` is set correctly. It looks like `neo-tree` seems to get stuck in some intermediate state when switching. I have no idea why is it like that, maybe there is a race condition of some sorts somewhere. You can try to reproduce it yourself, it's `airblade/vim-rooter` and it's a no-configuration plugin.

**Comment by cseickel** [comment]
> I have no idea why is it like that, maybe there is a race condition of some sorts

That's probably it. I see that the DirChanged event is not debounced and it probably should be. I'll install vim-rooter later and test it out.

**Comment by cseickel** [comment]
I can't recreate it, but I put in a possible fix. Can you update to the latest in **main** and tell me if it works better?

**Comment by ioreshnikov** [comment]
@cseickel unfortunately it's still there. Is there some sort of logging I can enable to help debug this?

**Comment by cseickel** [comment]
There's no logs. I should probably add a log system with log levels that can be adjusted though, right now I just add and remove print statements when I hit a difficult problem.

When I think about this, the filesystem is scanned async but there is no lock mechanism on the renderer.  I definitely need to add one, and that may fix the problem.

**Comment by ioreshnikov** [comment]
@cseickel it's ok, I can probably just install a logger plugin globally (my config needs one anyway). Can you please point me to a place in code where you listen for the directory changes?

**Comment by cseickel** [comment]
Sure, this code get's called on the DirChanged event: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/517dd67b4cb44ea419f46070a81d1662fbf08669/lua/neo-tree/sources/filesystem/init.lua#L68

The autocmd is setup here: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/517dd67b4cb44ea419f46070a81d1662fbf08669/lua/neo-tree/sources/filesystem/init.lua#L268

**Comment by ioreshnikov** [comment]
@cseickel actually, I'm and idiot and completely missed that I was cloning branch `1.x` instead of `main`. It's still broken but in a weird way: now it switches to the new directory, but not immediately. There's now a lag of about one second. And it's not guaranteed to work either. Sometimes it's still stuck in the old directory.

I will try to collect the log.

**Comment by cseickel** [comment]
The delay makes sense. I added a big debounce of 1 second on DirChanged just to be extra safe. Maybe it could still be multiple tree renders clobbering each other, but I have no idea if nvim does or does not have any built-in locks when writing to buffers. If it does not, I need to add my own.

**Comment by ioreshnikov** [comment]
So this is what I got. At this point I am in Telescope and switching from `.config/nvim` to `neo-tree` source directory. The new project is already selected and the cursor is on `README` file. When I press enter, those are the calls that I see:

```
1641938055 1.225193 dir_changed: cwd=`/home/me/.config/nvim` in bufname=`init.vim`
1641938055 1.225291 dir_changed_internal: cwd=`/home/me/.config/nvim` in bufname=`init.vim`
1641938055 1.268188 dir_changed: cwd=`/home/me/.local/share/nvim/plugged/neo-tree.nvim` in bufname=`README.md`
1641938055 1.27574 dir_changed: cwd=`/home/me/.local/share/nvim/plugged/neo-tree.nvim` in bufname=`README.md`
1641938056 1.295665 dir_changed_internal: cwd=`/home/me/.local/share/nvim/plugged/neo-tree.nvim` in bufname=`README.md`
```

It looks to me as if for a split second after closing Telescope vim switches to the old buffer `init.vim` before it is being replaced by the `README`. This split second is enough for `vim-rooter` to switch `cwd`  to `.config/nvim`. Then the new buffer is loaded and `vim-rooter` reports the new `cwd` twice for some reason. And since the old `cwd` is reported first, the correct new `cwd` is being debounced and this is why I see the delay.

I don't see any of this when I disable `vim-rooter`.

Honestly, at this point it looks like we should just acknowledge that `vim-rooter` is way too agressive. I would rather remove it from my configuration since I am using Telescope to navigate anyway, than have you to try to figure out how to work-around this behaviour.

**Comment by cseickel** [comment]
This bugs me and I am still going to leave this open until I fix what I think is the problem. Feel free to uninstall rooter though!

**Comment by cseickel** [comment]
Last try and then we just close it. At the very least I feel like the code is better now because of this investigation. If you wouldn't mind, can you test on more time with the latest in main?

**Comment by ioreshnikov** [comment]
I guess this is as good as it gets. I still can see it switching to the old root for a split second before drawing the new one, but otherwise it works. We should probably add a note to the documentation somewhere so people do not report this blinking as a bug.

**Comment by cseickel** [comment]
Awesome! 

To me, it's working exactly as it should. It faithfully follows the DirChanged event, drops intermediate events when they are being fired quickly, and then ends up where it should at the end. The important thing is that it ends up where it should at the end of the storm.

We could certainly delay the first event as well which would look nicer in this particular situation, but then all actions would have that delay and the interface would feel slugish. In most cases there is nothing that needs to be debounced, so I let the first one through in real time.

Thanks for working on this with me!

**Comment by ioreshnikov** [comment]
BTW, yesterday I switched Telescope to a different layout (it's `bottom_pane` now) and the problem completely disappeared even when I install `vim-rooter` back. Go figure.

**Comment by cseickel** [comment]
Very weird. Software makes no sense sometimes.
