### ISSUE TITLE
I'm taking a short break.

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#361]
This is probably better as a discussion, but I figure less people would read it there.

I've decided I want to focus on my missing formal education and practice some coding challenges for a little while. I'll be using my free time to read and do leetcode/hacker rank challenges for the next month or two, so I won't be personally adding any new features to Neo-tree during that time. I will gladly review and merge PRs though! I'll also keep responding to new issues and discussions to help people out and fix any bugs that come up.

**Comment by nyngwang** [comment]
Hi, @cseickel:

Not very good at expressing but really thank you for being so responsive on resolving all the issues I have these months and this plugin is really a big thing for me in 2022. I really wish you have a good luck on your upcoming leetcode/hacker journey, and possibly become the next tourist in the future.

Forgive me spamming my ricing here, but let's see how awesome the thing you have done:

<img src="https://user-images.githubusercontent.com/24765272/169928201-06e19f78-4686-404e-8c99-17db1d1189af.png" width="600">

**Comment by cseickel** [comment]
OK, break over.
