### ISSUE TITLE
Error whenever cursor enters neo-tree buffer because of WinSeparator:NeoTreeWinSeparator

### ISSUE THREAD

**Issue by rickyelopez** [nvim-neo-tree/neo-tree.nvim#365]
Hey, loving this plugin so far!

I'm getting this:
```
[Neo-tree ERROR] Error in event handler for event vim_buffer_enter[table: 0x7f941ef539e0]: ...e/nvim/plugged/neo-tree.nvim/lua/neo-tree/setup/init.lua:96: Vim(setlocal):E474: Invalid argument: winhighlight=Normal:NeoTreeNormal,NormalNC:NeoTreeNormalNC,SignColumn:NeoTreeSignColumn,CursorLine:NeoTreeCursorLine,FloatBorder:NeoTreeFloatBorder,StatusLine:NeoTreeStat
usLine,StatusLineNC:NeoTreeStatusLineNC,VertSplit:NeoTreeVertSplit,EndOfBuffer:NeoTreeEndOfBuffer,WinSeparator:NeoTreeWinSeparator
```

Whenever I launch or otherwise interact with Neo-tree. I've gone through and removed those options one-by-one until figuring out that `WinSeparator:NeoTreeWinSeparator` (the last one I tried, naturally) is the one causing the error. No idea what this does. Is anybody else getting this? I can fix locally by just removing this for now.

Happy to put up a PR to remove it if that's the correct resolution, but otherwise, no idea what the correct fix is.

**Comment by cseickel** [comment]
That's it, I checked and this was added in 0.7.0. The correct thing is to either:

- Specify that neovim 0.7.0 is the minimum supported version
- add a version check in the code that will use `VertSplit` instead for neovim versions < 0.7.0.

If that's the only problem with 0.6.1, adding the version check is probably the better solution. If you are willing to put in a PR for that, that'd be great.

**Comment by rickyelopez** [comment]
Ahhh rip ok gotcha. How does one check neovim version in lua? I can maybe take a stab at adding a check

**Comment by miversen33** [comment]
@rickyelopez `vim.version()`

**Comment by cseickel** [comment]
Here's an example: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/a917174b38b065b5fc01c89709cfc31fbe6917db/lua/neo-tree/setup/init.lua#L42-L50
