### ISSUE TITLE
Pressing <C-w> causes input to switch window

### ISSUE THREAD

**Issue by yujinyuz** [nvim-neo-tree/neo-tree.nvim#366]
I always use `<C-w>` in insert mode to erase input text. But when I do it in neo-tree when moving files, it just switches windows

[![asciicast](https://asciinema.org/a/5gNLURaPax3Yi5S2FAjYQPUWd.svg)](https://asciinema.org/a/5gNLURaPax3Yi5S2FAjYQPUWd)

**Comment by cseickel** [comment]
I have no idea why that is (yet), but I've confirmed I have the same behavior.
