### ISSUE TITLE
Feature Request: Having <C-W> delete a word in /search functionality

### ISSUE THREAD

**Issue by ziontee113** [nvim-neo-tree/neo-tree.nvim#372]
Hi, the current behavior when pressing `<C-W>` when using the /search functionality won't delete a word (default behavior in Insert Mode).

Is there a way that I can configure this by my own? Or is there some difficulty that makes `<C-W>` not usable as word delete? Thank you :)

**Comment by ziontee113** [comment]
Hi my solution is:
```lua
vim.cmd([[ autocmd FileType neo-tree-popup inoremap <silent> <buffer> <C-W> <Esc>ciw ]])
```

**Comment by cseickel** [comment]
This was added in #376
