### ISSUE TITLE
Mappings aren't case-normalized, leading to ambiguity/failure to override

### ISSUE THREAD

**Issue by danielwe** [nvim-neo-tree/neo-tree.nvim#378]
I habitually capitalize special key identifiers when defining vim mappings, so I did this:

```lua
require('neo-tree').setup({window = {mappings = {['<BS>'] = 'close_node'}}})
```

This results in the following neo-tree help window:

```
         KEY(S)    COMMAND
           ...
           <BS> -> close_node
           <bs> -> navigate_up
           ...
```

This leads to unpredictable behavior of the backspace key. (What seems to end up happening is that the default `'navigate_up'` takes precedence when first opening nvim, but if I re-source my `init.lua` it changes to my custom `'close_node'`.)

Would be good to normalize the case internally to ensure that custom overrides work as expected.

Thanks for the great plugin, and I know you're on hiatus but figured I'd make sure this issue is in the catalog. I may get around to submitting a PR later.

**Comment by cseickel** [comment]
There is actually code to normalize the mappings, there's just some sort of glitch with the setup function that's letting this slip by.

**Comment by cseickel** [comment]
This is fixed in main and will be released in the next few days.

**Comment by nyngwang** [comment]
Nice question and thanks for the quick fix!
