### ISSUE TITLE
Error executing lua ...cker/start/neo-tree.nvim/lua/neo-tree/command/parser.lua:167: attempt to index local 'stat' (a nil value)

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#379]
desc:

Got the error as title after the update. It seems that some of my config is wrong, but I'm not sure where I should modify it.

<img src="https://user-images.githubusercontent.com/24765272/174234342-77dc7a8a-7ac1-43e0-9075-8112b1f09ec2.png" width="700">

config:

```lua
  vim.keymap.set('n', ';', function ()
    if vim.bo.filetype ~= 'neo-tree' then
      win_prev = vim.api.nvim_get_current_win()
      vim.cmd('Neotree focus reveal_force_cwd dir=' .. vim.fn.getcwd())
    else
      vim.api.nvim_set_current_win(win_prev)
    end
  end, NOREF_NOERR_TRUNC)
```

**Comment by nyngwang** [comment]
Remove the `dir= .. vim.fn.getcwd()` part seems to suppress the error. But I remember I put this with purpose. It seems that something about the command has been updated?

**Comment by cseickel** [comment]
The error would seem to indicate to me that `vim.fn.getcwd()` is not providing a valid path. I would echo that out to see what it is. I should also a more graceful check on this parameter to let you know the path was invalid.

I'm not sure why it would be needed. The default behavior is to use the current working directory anyhow. It could be that it was not choosing the scope that you wanted, i.e. global vs tab vs window working directory.

**Comment by cseickel** [comment]
It's also possible that your cwd requires escaping if the path has special characters or spaces.

**Comment by nyngwang** [comment]
I think we can safely close this one since I have no problem after removing it.
