### ISSUE TITLE
cursor in float

### ISSUE THREAD

**Issue by mbriggs** [nvim-neo-tree/neo-tree.nvim#38]
Love the plugin :) 

When I open the float panel in a buffer not pointing to a file, the popup will show with an invisible cursor

![image](https://user-images.githubusercontent.com/89260/148785752-c2c624cb-3221-4ddf-98e0-efab9d57f193.png)

I can move around, open and close folders, but cursor is hidden.

You can see here, when I open on a file that exists on the fs, the cursor exists (over the icon of snippets.lua)

![image](https://user-images.githubusercontent.com/89260/148786046-e2fdd373-97c1-456d-a0a5-5323656c40d5.png)

However, in the above case, cursorline does not seem to be set (you can see cursorline highlight in the window the float popped over.

**Comment by danilshvalov** [comment]
Which terminal do you use?

**Comment by cseickel** [comment]
Can you check (and possibly set) the value for NeoTreeCursorLine?
```
:hi NeoTreeCursorLine
```

**Comment by mbriggs** [comment]
> Which terminal do you use?

Alacritty compiled from source in the last few months. But `cursorline` works fine

**Comment by mbriggs** [comment]
> Can you check (and possibly set) the value for NeoTreeCursorLine?
> 
> ```
> :hi NeoTreeCursorLine
> ```

![image](https://user-images.githubusercontent.com/89260/148822217-1cc23531-e208-41e1-953e-ac50188630b2.png)

that appears to be the problem! I was under the impression that cursorline is copied by default

![image](https://user-images.githubusercontent.com/89260/148822297-7ca0b84a-bd21-42f9-956d-45127d05ad45.png)

but that does not appear to be the case

**Comment by cseickel** [comment]
Curious, that should have linked to CursorLine. I run some tests and see if I can recreate the issue.

**Comment by mbriggs** [comment]
I tried adding the highlight explicitly, and still see the same behaviour

![image](https://user-images.githubusercontent.com/89260/148848719-baf16247-95f4-46a4-aa7c-b4d8b3460e76.png)
![image](https://user-images.githubusercontent.com/89260/148848747-c8a4357a-f7fa-4002-be6e-5a8ebd42cef7.png)

my relevent configs are here https://github.com/mbriggs/nvim/blob/main/lua/mb/explorer.lua but I am largely just copy/pasta from the README

**Comment by cseickel** [comment]
I'm sorry, there is absolutely a problem with CursorLine in the floating window, I'm not sure how I never noticed this. I'll fix that soon.

**Comment by mbriggs** [comment]
working, thank you @cseickel :)
