### ISSUE TITLE
Search folder only feature

### ISSUE THREAD

**Issue by ying234** [nvim-neo-tree/neo-tree.nvim#381]
Request a new feature to search folder only. When hit <cr> in search view, it will move the cursor to that folder. 
And an improvement request: for current search, it also show folders. If hit <cr> on the folder node, it would be great if the cursor move to that folder node.  Thanks.

**Comment by cseickel** [comment]
I think it would be a good idea to have a folder search vs a file search, as you would usually know which one you are searching for. There are two ways to do this:

1. Have three separate commands with separate mappings, one for folder search, one for file search, and one for both.
2. Add a special syntax to the single search prompt that distinguishes, like starting a search with `d:` or `f:`
3. Add a toggle command with instructions in the header to switch between the different modes in the middle of a search.

Anyone have any opinion on the best option?

**Comment by ying234** [comment]
I vote the first one as the best option.

**Comment by cseickel** [comment]
This is in `main` right now and I'll probably release it to `v2.x` tonight. If you get a chance, please try it out and let me know if you see any issues with the new command. Here is the updated documentation:

```help
FILTER                                                        *neo-tree-filter*

NOTE: All of the below commands are affected by the `find_by_full_path_words`
option:
>
    require("neo-tree").setup({
      filesystem = {
        find_by_full_path_words = false,  
      }
    })
<
`false` means it only searches the tail of a path and is the default.
`true` will change the filter into a full path search with space as an implicit
`".*"`, so `fi init` will match: `./sources/filesystem/init.lua`


/ = fuzzy_finder:           Filter the tree recursively, searching for
                            files and folders that contain the specified term as
                            you type. This will use fd if it is installed, or 
                            find, or which if you are on Windows.

                            As of v1.28, this acts like a fuzzy finder,
                            meaning that pressing up/down while the filter
                            window is open will move the cursor up and down in
                            the tree, and pressing `<enter>` will open that
                            item and clear the filter. Any other method of
                            closing the filter window will also clear the
                            filter.

D = fuzzy_finder_directory: Like fuzzy_finder above, but only shows directories.
                            Pressing <enter> on a directory will clear the
                            search and set the focus on that directory.
                            Requires `fd` or `find` to be installed~

f = filter_on_submit:       Same as above, but does not search until you hit
                            enter. Useful if filter_as_you_type is too slow.
                            Also useful if you want to leave the tree
                            filtered.

<C-x> = clear_filter:       Removes the filter.
```

**Comment by cseickel** [comment]
I'm not seeing this behavior, it always focuses the node I was on in the search when I hit enter. Maybe I am just not doing exactly what you are doing, or maybe our settings are changing the result. Can you share your neo-tree config and provide more details on what does and does not work?

**Comment by ying234** [comment]
The folders and files are:
├───folder1
│          │   a.txt
│          └───subfolder
└───folder2
             │   b.txt
             └───subfolder

Search "sub", and ctrl+n navigate to second subfolder, press `<enter>`, focus one is b.txt which should be the second subfolder node.
![image](https://user-images.githubusercontent.com/59452354/177474932-cec925bf-b7b2-4116-9f60-96d727abf359.png)

If I open all the folder before the search:
![image](https://user-images.githubusercontent.com/59452354/177475080-1758113f-ffa2-4cee-be03-e4e4b39b5e59.png)

when press enter on the second subfolder when search "sub", the focus one is folder2:

![image](https://user-images.githubusercontent.com/59452354/177475150-e818297c-c3f8-45a6-bb16-27cb353e644f.png)

if you cannot reproduce it, I'll share the config. Thanks.

**Comment by cseickel** [comment]
That works fine for me. Can you share your config?

**Comment by ying234** [comment]
some log messages:
```
[TRACE 7/6/2022 6:41:20 AM] ...ck\packer\opt\neo-tree.nvim/lua/neo-tree/ui/renderer.lua:861: Force open folders
[DEBUG 7/6/2022 6:41:20 AM] ...ck\packer\opt\neo-tree.nvim/lua/neo-tree/ui/renderer.lua:587: Setting expanded nodes
[DEBUG 7/6/2022 6:41:20 AM] ...ck\packer\opt\neo-tree.nvim/lua/neo-tree/ui/renderer.lua:508: Restoring position to node_id: C:\Users\john\source\repos\test\folder2\subfolder\
[DEBUG 7/6/2022 6:41:20 AM] ...ck\packer\opt\neo-tree.nvim/lua/neo-tree/ui/renderer.lua:329: focus_node cannot find node with id  C:\Users\john\source\repos\test\folder2\subfolder\
[TRACE 7/6/2022 6:41:20 AM] ...k\packer\opt\neo-tree.nvim/lua/neo-tree/events/queue.lua:213: Firing event:  after_render  with args:  {
  async_directory_scan = "auto",
  bind_to_cwd = true,
  bufnr = 3,
  commands = {
    add = <function 1>,
    add_directory = <function 2>,
    clear_filter = <function 3>,
    close_all_nodes = <f...
[DEBUG 7/6/2022 6:41:20 AM] ...ck\packer\opt\neo-tree.nvim/lua/neo-tree/ui/renderer.lua:329: focus_node cannot find node with id  C:\Users\john\source\repos\test\folder2\subfolder\
```

**Comment by cseickel** [comment]
AHA! I see what the problem is. I have to remove the slash from the end of the folder when translating from search results to the normal browse results, but I forgot to do this in a way that supports windows. I'll fix this tonight.

**Comment by cseickel** [comment]
It should work now, can you pull the latest and give it a try?

**Comment by ying234** [comment]
@cseickel Thank you! Works well now.
