### ISSUE TITLE
Pressing `<Esc>` in the tree acts like it has been mapped to perform `navigate_up` when not using default mappings

### ISSUE THREAD

**Issue by atchim** [nvim-neo-tree/neo-tree.nvim#383]
When I have the tree opened and focused, every time a press `<Esc>` the tree performs the same action as the `navigate_up` command, even not having any mappings for `<Esc>` in the buffer of Neo-Tree. This seems to only happen when `use_default_mappings` is set to `false`.

**Comment by cseickel** [comment]
I would guess that for some reason outside of Neo-tree's control, pressing `<Esc>` is changing your working directory, and Neo-tree is following the change.

What does it say when you issue this command?
```
:nmap <esc>
```

**Comment by atchim** [comment]
@cseickel, it was my bad... I've mapped `<C-[>` to `navigate_up` but reading about `:h keycodes` I saw that `<C-[>` is equivalent to `<Esc>`. I didn't know about that. Well, at least I learned something new.
