### ISSUE TITLE
Empty changelist for a file when opened using `:e` while being on Neotree

### ISSUE THREAD

**Issue by ajitid** [nvim-neo-tree/neo-tree.nvim#384]
**Steps to reproduce**:
- Make sure to disable any plugin first that restores cursor position (like [vim-lastplace](https://github.com/farmergreg/vim-lastplace)). Also make sure that Neotree doesn't open by default when nvim is opened. You should also have [persistent undo](https://gist.github.com/ajitid/382304f8cc000ce4ebec1c0007410196) present.
- On a file, make some changes and save. Now close nvim.
- Open nvim again. This time open the file using `:e path/to/file`. Do `g;` to jump to last position using changelist. You would notice that the cursor's position would change to  where you made the edit. Now close nvim.
- Open nvim again. This time open Neotree using `:Neotree`. Now while your cursor is on Neotree buffer, open that file again using `:e path/to/file`. Do `g;`. You would notice that nvim errors saying "At start of changelist". Close nvim.
- Open nvim. Directly go to  `:e path/to/file` and do `g;`. Your cursor will jump to last edited position as normal.

**Expected behavior**: Changelist shouldn't be shown as empty if the file is opened using `:edit` and we have made few changes to the file already 

**Environment**:
nvim version: NVIM v0.8.0-dev+448-g7b2b44bce (it's a nightly release)
OS: Fedora 36

https://user-images.githubusercontent.com/26769888/174766502-270c1b67-a9f6-4586-92ae-273d5465418a.mp4

(I am performing the same steps in the video that I've mentioned above.)

**Comment by ajitid** [comment]
Hey, I just tried on a fresh nvim docker image (`docker run -it --rm --init anatolelucet/neovim:nightly ash`) and I can still reproduce the issue. This is the config I used:


```vim
call plug#begin()
Plug 'nvim-lua/plenary.nvim'
Plug 'MunifTanjim/nui.nvim'
Plug 'nvim-neo-tree/neo-tree.nvim'
call plug#end()
 
if has("persistent_undo")
  let target_path = stdpath('data') . '/.undodir'
 
  if !isdirectory(target_path)
    call mkdir(target_path, "p", 0700)
  endif
 
  let &undodir=target_path
  set undofile
endif
```

**Comment by cseickel** [comment]
I ran the docker container but it had no config and just copying the config you provided into a file and using it does not work because plug is not installed. Did you also mount your home directory when you ran it? if not, can you provide all of the commands you executed to reproduce the issue?

**Comment by ajitid** [comment]
Oh okay:
- Use [this dockerfile](https://gist.github.com/ajitid/3d0063233c7a0aa2d96335616c89cc95#file-dockerfile). Build and run the image as described in the readme 
- Now while in the container, run `nvim`
- Do `:e $MYVIMRC`
- Replace its content with the one mentioned in my previous comment
- Do `:so %`  followed by `:PlugInstall`
- Reopen nvim

**Comment by cseickel** [comment]
OK, thanks, I have reproduced the issue now. The interesting thing is that even though the mark is missing to jump to, you can still undo in that situation.

**Comment by ajitid** [comment]
No, this is not the behavior I want; on opening the file while being on Neotree the cursor moves to the last edited position. The default behaviour of vim is for the cursor to be in the very first line and at the very first column when a new file is opened.

**Comment by cseickel** [comment]
What about if you press `gg0` after opening the file, is it then in the desired state? If it is, then I can just add that to the existing command.

**Comment by ajitid** [comment]
I am using neotreee in netrw fashion, so I'm not facing the issue that I described above. On the matter of adding `gg0`, I would rather prefer to revert the [changes you made here](https://github.com/nvim-neo-tree/neo-tree.nvim/commit/3a79350af79acc3cce359b140d7be03f2bc550ee) as it doesn't feels an actual solution. We can always reopen this ticket if other users also face this issue.

**Comment by ajitid** [comment]
> You mean you changed to using it that way, but when you opened the issue originally you were using it as a sidebar, correct?

Yep, you understood it correctly.

> That sounds good...  not try to open a file in a Neo-tree sidebar window!

Mm hmm. Let's close this issue once you revert the changes.
