### ISSUE TITLE
`git mv` support

### ISSUE THREAD

**Issue by tombh** [nvim-neo-tree/neo-tree.nvim#386]
The move and rename commands don't seem to have Git counterparts? Sorry if I've missed it in the docs.

To be clear: can we assume that if neo-tree detects that it's in a Git repo it can also just internally replace `mv` with `git mv`?

**Comment by cseickel** [comment]
I don't personally use the `git mv` command and tbh I never really understood why it exists. 

From what I understand, which may be wrong, it is a combination of the physical move and updating the git index, which would be undesirable for me. I don't update the index until I am ready to commit.

**Comment by tombh** [comment]
That's totally understandable, just good to know this project's position on it more than anything.

Personally, I sometimes find that if I just use plain `mv` then Git doesn't pick up on the fact that it's the same file, and so sees the move as a deletion and a creation. I don't understand the specifics of it, but it does at least make sense to me that Git would do that if too much editing happens to the file after a plain `mv`.

**Comment by kapral18** [comment]
@tombh not entirely sure if this is properly setup but this is my attempt at overriding rename

```lua
return {
  "nvim-neo-tree/neo-tree.nvim",
  lazy = false,
  opts = {
    window = {
      mappings = {
        ["r"] = "git_rename",
      },
    },
    commands = {
      git_rename = function(state)
        local node = state.tree:get_node()
        if node.type == "message" then
          return
        end

        local cmds = require("neo-tree.sources.filesystem.commands")
        local has_git = vim.fn.finddir(".git", ";") ~= ""

        if not has_git then
          return cmds.rename(state)
        end

        local path = node:get_id()
        local name = node.name
        local events = require("neo-tree.events")
        vim.ui.input({ prompt = "New name: " .. name }, function(new_name)
          if new_name == "" then
            return
          end

          local base_path = vim.fn.fnamemodify(path, ":h")
          local cmd = { "git", "mv", path, base_path .. "/" .. new_name }
          vim.fn.system(cmd)
          events.fire_event(events.GIT_EVENT)
        end)
      end,
    },
  },
}
```

**Comment by cseickel** [comment]
> the only problem is after rename when I try to save the renamed file from inside the buffer it asks me to confirm whether I want to overwrite it under the new name, which is weird since commands.refresh has clearly worked.

That is because vim still has it open under the old name. There is a helper function to deal with this situation:

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/230ff118613fa07138ba579b89d13ec2201530b9/lua/neo-tree/sources/filesystem/lib/fs_actions.lua#L78

It will update the path in any open buffers for the given file.

It's not in the public API, so no guarantee that it won't be changed, but you can use it or just copy it.

**Comment by kapral18** [comment]
@cseickel thanks for the hint

**Comment by tombh** [comment]
And thanks for the snippet!
