### ISSUE TITLE
Open file in external app

### ISSUE THREAD

**Issue by afdallah** [nvim-neo-tree/neo-tree.nvim#389]
Hi, thanks for making neo-tree
is there any way to open the selected file with an external app (e.g finder, chrome)?

**Comment by cseickel** [comment]
Yes, you can use a custom command for this. Here is an example for MacOS: https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#open-with-system-viewer

If you are on another system, just change the command as appropriate for your OS.

**Comment by afdallah** [comment]
Wow, nice. thanks!
