### ISSUE TITLE
Feature Request: Expand all Folders

### ISSUE THREAD

**Issue by ziontee113** [nvim-neo-tree/neo-tree.nvim#399]
Hi, so the current behavior of `<cr> = "open"` will open the file and jump the cursor to that window.
Is there an already existing command that open file without moving the cursor to the target window? I plan to map it to `l` for previewing purposes.

Also is there a command for expanding all folders? I only follow the default commands in README.md and idk if there's more commands that is undocumented.

**Comment by cseickel** [comment]
You can use a custom command for this, here's an example: https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Tips/#open-file-without-losing-sidebar-focus

**Comment by ziontee113** [comment]
Thank you very much @cseickel :+1: Thank you!

**Comment by ziontee113** [comment]
Hi man, `z` works, but `Z` neo-tree says `Invalid mapping for Z: nil`.

**Comment by cseickel** [comment]
This has not yet been released to the default branch, which is `v2.x`, but it is in `main`. Have you switched your branch to `main` to try it out?

**Comment by ziontee113** [comment]
Oh sorry about that. Will do :)

**Comment by ziontee113** [comment]
Hi @cseickel , I'm using the main branch right now, and the `expand_all_nodes` functionality works fine. The feature I was looking for was "expand Everything", not just expand till opened folders.

Now I see there are multiple mappings / function you would have to do to fully support the `expand_all_nodes`. Actions like: `expand_everything_from_cursor`, `close_everything_from_cursor`, etc... It's not so simple as I thought :)

**Comment by cseickel** [comment]
> Hi @cseickel , I'm using the main branch right now, and the `expand_all_nodes` functionality works fine. The feature I was looking for was "expand Everything", not just expand till opened folders.

That's just a bug, not what I intended. 🤷🏼‍♂️ I'll fix this so that it really expands **everything**.

**Comment by cseickel** [comment]
Now I remember why I have never done this before. Child folders are lazy loaded, so the way I wrote it, it will only expand folders that have been opened since the last root navigation. Expanding the rest of the folders will require me to reload the entire tree recursively, which is entirely different. I'll make that change but it will take a little longer.

**Comment by ziontee113** [comment]
I see. Thanks a lot man. Take your time :+1:

**Comment by cseickel** [comment]
It should work as expected now. There's no safety mechanism or optimizations for expanding deeply nested directories, so use with caution.

**Comment by ziontee113** [comment]
Thanks man, I'll try it out.

**Comment by ziontee113** [comment]
Okay.. Lookin' smooth. Thank you very much. I don't work with large folder structures so IDK how this will scale but this works file for me atm.
