### ISSUE TITLE
NeoTree always opens files on the top left window

### ISSUE THREAD

**Issue by jcmuller** [nvim-neo-tree/neo-tree.nvim#40]
I really need to have NeoTree open the file I need in the window that was focused when NeoTree was toggled. Is this something that can be configured?

Thanks a lot!

**Comment by danilshvalov** [comment]
Do you want to reuse the current buffer instead of creating a new one?

Or do you want to open a file in the last used window without a choice?

**Comment by cseickel** [comment]
@jcmuller This is surprisingly tricky, but I can definitely add this as an option. That was my first strategy for where to open a file, but it got complicated once I started adding floating windows.

You can also add your own "open" command and map to that to implement your own window choosing strategy... But if you can wait a day or two I will add this behavior as an option.

**Comment by smjonas** [comment]
Thanks for fixing this so quickly, it works great!

**Comment by jcmuller** [comment]
Yes. That. Thanks!
