### ISSUE TITLE
Option to not display root folder in filesystem

### ISSUE THREAD

**Issue by SergioBenitez** [nvim-neo-tree/neo-tree.nvim#404]
Hi there!

I'm rendering the root of the file system tree outside of `neo-tree`. I'd like to not display the root twice, but I've been unable to find a way to tell `neo-tree` not to render the root without modifying `neo-tree` itself. Unfortunately the docs don't elucidate anything here, at least not after a few readings. It also doesn't seem that custom renderers are able to skip rendering a node entirely. Is there something I'm missing?

Thanks!

**Comment by Shougo** [comment]
I think the root node is needed.
Because the directory is empty, the buffer become empty.

**Comment by SergioBenitez** [comment]
Ah, apologies, allow me to clarify.

`neo-tree` currently renders the tree as:

```
ROOT
├── dir
├── dir
│   ├── dir
│   │   ├── file.lua
│   │   └── file.lua
│   └── dir
└── dir
```

I'm adding my own rendering of `ROOT` (on the bufferline), which makes my tree look like:

```
ROOT
ROOT
├── dir
├── dir
│   ├── dir
│   │   ├── file.lua
│   │   └── file.lua
│   └── dir
└── dir
```

To avoid the duplication, I'd need `neo-tree` to not render the root node, like this:

```
├── dir
├── dir
│   ├── dir
│   │   ├── file.lua
│   │   └── file.lua
│   └── dir
└── dir
```

**Comment by cseickel** [comment]
There is no way to configure this yet, but it won't be that hard to add. I almost wanted the same thing when I added winbar, but I ended up going for a blank winbar instead which I think looks better.

I'll add the option.

**Comment by cseickel** [comment]
This has been added in the `main` branch. Can you try it out and let me know if it works as expected?

You just need to add this option:

```lua
    require("neo-tree").setup({
        hide_root_node = true
    })
```

BTW - It's kind of funny that this issue ended up being number 404, isn't it? 😄

**Comment by cseickel** [comment]
Well, you can get to the desired indent by playing with the padding of the `indent` component:
```lua
    require("neo-tree").setup({
      hide_root_node = true,
      default_component_configs = {
        indent = {
          indent_size = 2,
          padding = 3,
        }
      }
    })
```

Adding the phantom indent guides is not going to happen though.

**Comment by cseickel** [comment]
As an alternative, you could also just render the statusline space above Neo-tree as blank space. That's what I do and here is how it looks with the standard tree setup:

![image](https://user-images.githubusercontent.com/5160605/177672628-6d449069-02cc-44aa-9db5-7e1b1ac2e697.png)

Technically I hide the tabline completely and use winbar, but the effect would be similar.
