### ISSUE TITLE
VimLeave event is not triggered when using close_if_last_window

### ISSUE THREAD

**Issue by iverberk** [nvim-neo-tree/neo-tree.nvim#405]
I'm using a session plugin that automatically saves on a VimLeave event. I noticed that my sessions were not being saved and narrowed it down to the automatic closing of the neo-tree window. You can easily test this by running neovim with a debug log (nvim -V10nvim.log) and settings the close_if_last_window option to true and closing the non-neo-tree window, so that this triggers an automatic close of the neo-tree window. You will find that the logs shows that there is no Vimleave event generated at the end. In contrast, when the neo-tree window is not open and you exit, a VimLeave event is generated.

I'm not sure if this has to do with the fact that the vim.cmd('q!') is triggered in a WinEnter auto-command or that it's something else. I'm hoping someone can explain why the VimLeave event is not triggered.

**Comment by cseickel** [comment]
I think the latest commit on the `main` branch should fix this. Can you give it a try and let me know if it works?

**Comment by iverberk** [comment]
Yup, defintely works, thanks!
