### ISSUE TITLE
Question: maybe formatter should be used?

### ISSUE THREAD

**Issue by danilshvalov** [nvim-neo-tree/neo-tree.nvim#41]
What about using [`stylua`](https://github.com/johnnymorganz/stylua)? This makes it easier to contribute in one style.

You (or I in a PR) could just add a `stylua.toml` file in the base of the repo.

 In addition, you can create coding style checks before committing (`stylua --check` for example).

**Comment by cseickel** [comment]
Sounds great! Feel free to submit a PR to main with a stylua config.

**Comment by cseickel** [comment]
Thanks @danilshvalov ! 
Question: do you have stylua integrated into nvim? What are you using?

**Comment by levouh** [comment]
I would recommend using `null-ls`.

**Comment by danilshvalov** [comment]
> Question: do you have stylua integrated into nvim? What are you using?

I use a [`formatter.nvim`](https://github.com/mhartington/formatter.nvim) with the following config:

```lua
require("formatter").setup({
    filetype = {
        lua = {
            function()
                return {
                    exe = "stylua",
                    args = { "-s", "-" },
                    stdin = true,
                }
            end,
        },
    },
})
```
