### ISSUE TITLE
BUG: `hide_root_node = true` and creating file freezes nvim

### ISSUE THREAD

**Issue by pysan3** [nvim-neo-tree/neo-tree.nvim#410]
Hi, Thanks for the awesome plugin :)

I stumbled across a fatal error that freezes my nvim completely with the following setup.

### Reproduce

- Config
```lua
require("neo-tree").setup({
  hide_root_node = true,
  filesystem = {
    follow_current_file = true,
  },
})
```
- Example File Structure
```txt
- root/
  - dir-A/
    - dir-A-B/
      - file-A-B-C.lua <- current file
  - file-B.lua
```

1. Open a file that is **2 or more deeper than `cwd`**. (`file-A-B-C.lua`)
2. Open Neotree with `:Neotree toggle<CR>`.
3. (cursor is focused on `file-A-B-C.lua` on open by setting config `filesystem.follow_current_file = true`)
4. Press `G` to go to the end of buffer. (cursor focus on `file-B.lua`)
5. Press `a` or `A` to create new file / dir.
6. Nvim freezes.

### Notes

- Not happening with `hide_root_node = false`.
- neo-tree
  - branch: `v2.x`
  - commit: 4ad045871c38fbc8bb88c28141842a708fa51c1a

### Details

- nvim --version output:
  - NVIM v0.8.0-dev+nightly
  - Build type: RelWithDebInfo
  - LuaJIT 2.1.0-beta3
- Operating system: `5.10.102.1-microsoft-standard-WSL2`

- Screen Record

![neo-tree](https://user-images.githubusercontent.com/41065736/178158353-5246e172-690d-44cb-8284-3e11f3b1c045.gif)

**Comment by pysan3** [comment]
Oh, it seems to be working until this commmit. 747de4fdd1b8eb501b6f8087c48d708282e4a2d6

So the latest commit should be the one causing the error.

**Comment by MunifTanjim** [comment]
@cseickel if `NuiTree` supports returning `nil` from `prepare_node`, would that help in this situation?

**Comment by cseickel** [comment]
> @cseickel if `NuiTree` supports returning `nil` from `prepare_node`, would that help in this situation? The root node would still be there, it just won't be rendered anymore if `prepare_node` returns `nil` for it.

YES that will help @MunifTanjim ! Thanks for letting me know about that, it really simplifies everything.

**Comment by pysan3** [comment]
I checked the related commit and it seems to be fixed!!

Thank you very much @cseickel and @MunifTanjim !!
