### ISSUE TITLE
Remove first level indent when root node is hidden

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#426]
See #424. If someone prefers to keep this indent, it's better for them to add a positive padding than to support others removing it with a negative padding.

**Comment by SergioBenitez** [comment]
> If someone prefers to keep this indent, it's better for them to add a positive padding than to support others removing it with a negative padding.

These aren't the same thing, however. The ident enables the expander while simply using padding does not; I really prefer the former. As far as I can tell, there's no alternative that enables the expanders aside from the indent. Perhaps there should be an option for this instead of hard-coding one thing or the other?

**Comment by cseickel** [comment]
I'm sorry I didn't notice that interaction. I will add an option to control this. Do these options make sense?

```lua
-- Hide root node but keep the indent (@SergioBenitez's desired behavior)
require("neo-tree").setup({
  hide_root_node = true,
  retain_hidden_root_indent = true,
})

-- Hide root node AND the indent (current behavior when root hidden)
require("neo-tree").setup({
  hide_root_node = true,
  retain_hidden_root_indent = false,
})

-- Don't hide anything (default behavior)
require("neo-tree").setup({
  hide_root_node = false,
  retain_hidden_root_indent = false,
})

**Comment by SergioBenitez** [comment]
I think so! I would have expected something to the effect of `initial_indent`, but this is more precise, which may or may not be good.
