### ISSUE TITLE
How to behave when neo-tree becomes the only window

### ISSUE THREAD

**Issue by smjonas** [nvim-neo-tree/neo-tree.nvim#43]
Steps to reproduce:
- open any file
- `:NeoTreeReveal`
- select that same file in the tree and delete it with `d` (the opened file then closes and the only window left is NeoTree)
- select another file and open it with `Enter` (this closes the NeoTree window, not sure why)
- `:NeoTreeReveal`

Expected behaviour: tree viewer should open
Actual behavior: nothing happens, presumably because NeoTree thinks it's already open even though it's not in the buffer list anymore

My config is the default one (an empty table passed to `setup`). Let me know if you need any further info.

**Comment by cseickel** [comment]
I'm not getting this issue, but I also don't understand one thing: what is closing Neo-tree? Following the above steps, it should remain open after a file is opened, so NeoTreeReveal should do nothing but focus the already open window.

**Comment by smjonas** [comment]
I have updated the reproduction steps

**Comment by cseickel** [comment]
Oh I understand now! The true issues are:

1. How to handle the situation where Neo-tree is the only window. 
   a. I think it should open the file with split in that situation, regardless of whether the user explicitly choose split now not. This would conflict with some people's desire to have a netrw style behavior, so it needs to be configurable.
  b. Another option is to just create a new blank buffer automatically to take the place of the deleted one, that way a sidebar is still a sidebar, and a floating window does not become the only window left.

2. What to do when the Neo-tree window has been taken over by another buffer. This one is clearly a bug in that it should be searching for the buffer id and not the window id to determine if/where it is open.

I will definitely just fix 2. What are your thoughts on how 1 should be handled?

**Comment by smjonas** [comment]
Here are my thoughts about your first point:
The way other plugins like `fern.vim` handle it is that the tree sidebar becomes a fullscreen window once an open file was deleted. Selecting a file afterwards simply opens that file in a new buffer (fullscreen) and closes the sidebar. However, I agree this is not optimal because the user will expect that the sidebar remains open to do further file-related edits like moving or renaming a different file (this is also the case for more conventional editors where the sidebar remains open).

There are two alternatives that I can see right now:
1. Replace the deleted buffer with an empty one (what you suggested in b).
2. After the opened file was deleted, make the sidebar a fullscreen window. Then once the users opens a different file, restore the sidebar so that the user does not have to open the sidebar again.

I personally prefer 2 but would love to hear your opinion on this as well!

**Comment by smjonas** [comment]
Thanks for fixing this so quickly, it works great!
