### ISSUE TITLE
Feature Request: Re-render floating neo-tree on window size change

### ISSUE THREAD

**Issue by ziontee113** [nvim-neo-tree/neo-tree.nvim#438]
Hi! I wonder if it's possible for neo-tree to Re-render the floating neo-tree on window size change. Since the "floating window calculation" is already there, maybe we could hook an event to it?

This is before:
![Screenshot from 2022-07-17 13-39-36](https://user-images.githubusercontent.com/102876811/179387135-093dfd29-a0a9-493a-9217-3ab5fa41ac1c.png)

This is the current behavior
![Screenshot from 2022-07-17 13-38-19](https://user-images.githubusercontent.com/102876811/179387089-5c055602-1f38-4f9d-981a-18755f79782d.png)

This is the wanted behavior (automatic)
![Screenshot from 2022-07-17 13-38-24](https://user-images.githubusercontent.com/102876811/179387103-f911215f-4717-4d3a-8320-2224b66ed1fb.png)

Thank you very much!

**Comment by cseickel** [comment]
This actually seems like a really strange use case, why would you leave a floating window open while adding a split?  For that matter, how did you even do this? The window is supposed to close automatically as soon as it loses focus.

**Comment by ziontee113** [comment]
That's not a split, that a different "desktop window". I use Linux and Awesome Window Manager, I have `Super+N` to open Neovim.

**Comment by cseickel** [comment]
> That's not a split, that a different "desktop window". I use Linux and Awesome Window Manager, I have `Super+N` to open Neovim. There's a gap between those "windows".

Oh ok, that's completely different then. This can probably be handled with a VimResize event

**Comment by Shougo** [comment]
VimResized exists, but WinResized is not exist yet.

https://github.com/neovim/neovim/issues/11532

**Comment by ziontee113** [comment]
Yeah I think VimResized is what we're looking for. I didn't know about that event before opening this issue.
