### ISSUE TITLE
Is a PR for notification / dialog options welcome?

### ISSUE THREAD

**Issue by tobealive** [nvim-neo-tree/neo-tree.nvim#439]
I'm glad I found your plugin. Thanks so much for all the work. It's really next level 🚀

_No. 1:_  I would like to make notifications configurable. Currently, I just have this pretty dirty modified on my local machine and maybe redoing it clean is worth a PR. I thought of **render style**, **timeout length** and **notification position**.

Render style and timeout should be pretty simple and straightforward as these are just args we can pass when calling notify.
To set the position I would write a small notification lib which allows choosing the notification position.

Where does this idea come from? Basically from using a tree mainly on the right side and impairments with that. (Why right? It won't shift the text when opening the tree. Also having a lot of photoshop hours on my back from my early days as a media designer I really got accustomed to having my document structure and layers on the right side, it feels more out of the way). A "minimal" rendered notification would not overlap that much of the file tree. A notification positioned on the bottom would stay even more out of the way.

---

_No 2.:_  Another thing when the tree is positioned on the right is anchoring of dialogs. E.g., when triggering renaming or adding a file. Currently, **parts of the dialogs are outside the ui** when not using an overly wide tree. This should be a simple fix to implement. Probably just changing window anchors if the tree is opened on the right. Also, it is probably more crucial as the first one.

If such options are welcome and someone wants to take one of these please feel free to join on this contrib.

**Comment by cseickel** [comment]
> I'm glad I found your plugin. Thanks so much for all the work. It's really next level 🚀

Thanks!

> What I would like to make notifications configurable. Currently, I just have this pretty dirty modified on my local machine and maybe redoing it clean is worth a PR. I thought of render style, timeout length and notification position.
>
> Render style and timeout should be pretty simple and straightforward as these are just args we can pass when calling notify.
To set the position I would write a small notification lib which allows choosing the notification position.

I remember thinking that I will need to add some config options for this eventually when I add `vim.notify` support. I'd be happy to merge a PR for this. I would just say that for any new options, always make sure it is opt-in and does not affect users that are not interested in this feature. Also, it's probably better to discuss the proposed config structure first in a draft PR before writing the actual code.

-----

> Another thing when the tree is positioned on the right is anchoring of dialogs. E.g., when triggering renaming or adding a file. Currently, parts of the dialogs are outside the ui when not using an overly wide tree. 

That's true that I never use it on the right hand side so I'm sure there are some oversights there. It would be great to have a right side user submit some quality of life fixes for that situation.

**Comment by tobealive** [comment]
Thanks for your reply!

Great then let's just do it step by step 😊. I'll try to make a first one this night when it fits and if not in the coming week.

**Comment by tobealive** [comment]
The issue I mentioned back then regarding configurable notification positions due to overlap with a right tree position has pretty much faded away. As there are plenty of methods to hook into `vim.notify` and also to use notification providers other than nvim-notify.

The more critical issue with dialogs appearing outside the UI was fixed back then so I'm closing this here.
