### ISSUE TITLE
New feature: indent guides

### ISSUE THREAD

**Issue by danilshvalov** [nvim-neo-tree/neo-tree.nvim#44]
Add the ability to enable indent guides like this:

<img width="301" alt="indent guides" src="https://user-images.githubusercontent.com/57654917/148857712-dbc94222-b8e3-42f0-b9b2-44c9769232fc.png">

I have some developments, so I can open a pull request, if you think it's worth adding this feature.

**Comment by cseickel** [comment]
It's definitively worth having. I would prefer they be a component that people can add to their renderers. Is that how you have done this?

**Comment by danilshvalov** [comment]
It's possible, but I need to add new fields to the node (for example I use fields from [`renderer.lua`](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v1.x/lua/neo-tree/ui/renderer.lua)):
```diff
local nodeData = {
  id = item.id,
  name = item.name,
  type = item.type,
  loaded = item.loaded,
  indent = node_indent,
  extra = item.extra,
  path = item.path,
  ext = item.ext,
  search_pattern = item.search_pattern,
+ level = level,
+ is_last = i == #source_items,
}
```

**Comment by cseickel** [comment]
The hard part about this is to make it in a way that is open ended and configurable. Here is what I am thinking right now:

1. We add the two properties, but call the second one `is_last_child` to be more explicit.
2. We add a config option for a special component called "**indent_renderer**" which follows the interface of a component but is at the global config level. That component has options for:

-` indent_marker` which defaults to "  " (two spaces)
- `last_indent_marker` which also defaults to "  " (two spaces)
- `highlight` which is the highlight group to use for this NuiText, defaulting to nil 

Then I (as an end user) can tweak it in any way I want to change the amount of indent or add any style of markers.

How does that sound?

**Comment by cseickel** [comment]
... and your specific config there could be an example in the README or the wiki.

**Comment by danilshvalov** [comment]
I think this is the best option. I will create a pull request with indent guides this week.

**Comment by danilshvalov** [comment]
I've added this feature in #107.
