### ISSUE TITLE
Support rendering indent marker for "(hidden items)" message

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#441]
I see what needs to be done and I can take care of it later if you've stopped working on this.

_Originally posted by @cseickel in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/436#issuecomment-1186601166_

There are three situations to cover cleanly:

- [x] User has no indent markers
- [x] User has indent markers for all but the message (the default)
- [x] User enables indent markers for all including the (hidden items) message

**Comment by cseickel** [comment]
@smoka7 This feature is in `main` right now. If you enable markers for the `message` renderer, it will have the effect that you want:

```lua
  require('neo-tree').setup({
    renderers = {
      message = {
        { "indent", with_markers = true },
        { "name", highlight = "NeoTreeMessage" },
      }
    }
  })
```

**Comment by smoka7** [comment]
Thanks for the fix, Good work. 👍👍👍
