### ISSUE TITLE
How do I open a file under the cursor in tree with the default application?

### ISSUE THREAD

**Issue by kalyan860** [nvim-neo-tree/neo-tree.nvim#442]
I need a key mapping in the tree to open the file under cursor with default system application. For eg., open the pdf file under cursor with adobe reader.   

Or is there any option to run a shell command on a file under the cursor in the sidebar? That way I use xdg-open (or start on windows)

**Comment by benbrastmckie** [comment]
Here's a working version of that link:https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipies#open-with-system-viewer
