### ISSUE TITLE
Fold-style mappings

### ISSUE THREAD

**Issue by swarn** [nvim-neo-tree/neo-tree.nvim#445]
Being used to folding in vim, I duplicated those operations for neo-tree. I'm pretty happy with these, so I thought I might add them to the wiki, but I thought I'd get comments here first. The recursive open was tricky.
```lua
local neotree = require "neo-tree"
local renderer = require "neo-tree.ui.renderer"

-- Expand a node and load filesystem info if needed.
local function open_dir(state, dir_node)
  local fs = require "neo-tree.sources.filesystem"
  fs.toggle_directory(state, dir_node, nil, true, false)
end

-- Expand a node and all its children, optionally stopping at max_depth.
local function recursive_open(state, node, max_depth)
  local max_depth_reached = 1
  local stack = { node }
  while next(stack) ~= nil do
    node = table.remove(stack)
    if node.type == "directory" and not node:is_expanded() then
      open_dir(state, node)
    end

    local depth = node:get_depth()
    max_depth_reached = math.max(depth, max_depth_reached)

    if not max_depth or depth < max_depth - 1 then
      local children = state.tree:get_nodes(node:get_id())
      for _, v in ipairs(children) do
        table.insert(stack, v)
      end
    end
  end

  return max_depth_reached
end

--- Open the fold under the cursor, recursing if count is given.
local function neotree_zo(state, open_all)
  local node = state.tree:get_node()

  if open_all then
    recursive_open(state, node)
  else
    recursive_open(state, node, node:get_depth() + vim.v.count1)
  end

  renderer.redraw(state)
end

--- Recursively open the current folder and all folders it contains.
local function neotree_zO(state)
  neotree_zo(state, true)
end

-- The nodes inside the root folder are depth 2.
local MIN_DEPTH = 2

--- Close the node and its parents, optionally stopping at max_depth.
local function recursive_close(state, node, max_depth)
  if max_depth == nil or max_depth <= MIN_DEPTH then
    max_depth = MIN_DEPTH
  end

  local last = node
  while node and node:get_depth() >= max_depth do
    if node:has_children() and node:is_expanded() then
      node:collapse()
    end
    last = node
    node = state.tree:get_node(node:get_parent_id())
  end

  return last
end

--- Close a folder, or a number of folders equal to count.
local function neotree_zc(state, close_all)
  local node = state.tree:get_node()
  if not node then
    return
  end

  local max_depth
  if not close_all then
    max_depth = node:get_depth() - vim.v.count1
    if node:has_children() and node:is_expanded() then
      max_depth = max_depth + 1
    end
  end

  local last = recursive_close(state, node, max_depth)
  renderer.redraw(state)
  renderer.focus_node(state, last:get_id())
end

-- Close all containing folders back to the top level.
local function neotree_zC(state)
  neotree_zc(state, true)
end

--- Open a closed folder or close an open one, with an optional count.
local function neotree_za(state, toggle_all)
  local node = state.tree:get_node()
  if not node then
    return
  end

  if node.type == "directory" and not node:is_expanded() then
    neotree_zo(state, toggle_all)
  else
    neotree_zc(state, toggle_all)
  end
end

--- Recursively close an open folder or recursively open a closed folder.
local function neotree_zA(state)
  neotree_za(state, true)
end

--- Set depthlevel, analagous to foldlevel, for the neo-tree file tree.
local function set_depthlevel(state, depthlevel)
  if depthlevel < MIN_DEPTH then
    depthlevel = MIN_DEPTH
  end

  local stack = state.tree:get_nodes()
  while next(stack) ~= nil do
    local node = table.remove(stack)

    if node.type == "directory" then
      local should_be_open = depthlevel == nil or node:get_depth() < depthlevel
      if should_be_open and not node:is_expanded() then
        open_dir(state, node)
      elseif not should_be_open and node:is_expanded() then
        node:collapse()
      end
    end

    local children = state.tree:get_nodes(node:get_id())
    for _, v in ipairs(children) do
      table.insert(stack, v)
    end
  end

  vim.b.neotree_depthlevel = depthlevel
end

--- Refresh the tree UI after a change of depthlevel.
-- @bool stay Keep the current node revealed and selected
local function redraw_after_depthlevel_change(state, stay)
  local node = state.tree:get_node()

  if stay then
    require("neo-tree.ui.renderer").expand_to_node(state.tree, node)
  else
    -- Find the closest parent that is still visible.
    local parent = state.tree:get_node(node:get_parent_id())
    while not parent:is_expanded() and parent:get_depth() > 1 do
      node = parent
      parent = state.tree:get_node(node:get_parent_id())
    end
  end

  renderer.redraw(state)
  renderer.focus_node(state, node:get_id())
end

--- Update all open/closed folders by depthlevel, then reveal current node.
local function neotree_zx(state)
  set_depthlevel(state, vim.b.neotree_depthlevel or MIN_DEPTH)
  redraw_after_depthlevel_change(state, true)
end

--- Update all open/closed folders by depthlevel.
local function neotree_zX(state)
  set_depthlevel(state, vim.b.neotree_depthlevel or MIN_DEPTH)
  redraw_after_depthlevel_change(state, false)
end

-- Collapse more folders: decrease depthlevel by 1 or count.
local function neotree_zm(state)
  local depthlevel = vim.b.neotree_depthlevel or MIN_DEPTH
  set_depthlevel(state, depthlevel - vim.v.count1)
  redraw_after_depthlevel_change(state, false)
end

-- Collapse all folders. Set depthlevel to MIN_DEPTH.
local function neotree_zM(state)
  set_depthlevel(state, MIN_DEPTH)
  redraw_after_depthlevel_change(state, false)
end

-- Expand more folders: increase depthlevel by 1 or count.
local function neotree_zr(state)
  local depthlevel = vim.b.neotree_depthlevel or MIN_DEPTH
  set_depthlevel(state, depthlevel + vim.v.count1)
  redraw_after_depthlevel_change(state, false)
end

-- Expand all folders. Set depthlevel to the deepest node level.
local function neotree_zR(state)
  local top_level_nodes = state.tree:get_nodes()

  local max_depth = 1
  for _, node in ipairs(top_level_nodes) do
    max_depth = math.max(max_depth, recursive_open(state, node))
  end

  vim.b.neotree_depthlevel = max_depth
  redraw_after_depthlevel_change(state, false)
end

neotree.setup {
  filesystem = {
    window = {
      mappings = {
        ["z"] = "none",

        ["zo"] = neotree_zo,
        ["zO"] = neotree_zO,
        ["zc"] = neotree_zc,
        ["zC"] = neotree_zC,
        ["za"] = neotree_za,
        ["zA"] = neotree_zA,
        ["zx"] = neotree_zx,
        ["zX"] = neotree_zX,
        ["zm"] = neotree_zm,
        ["zM"] = neotree_zM,
        ["zr"] = neotree_zr,
        ["zR"] = neotree_zR,
      },
    },
  },
}
```

**Comment by cseickel** [comment]
The code looks good to me.

**Comment by swarn** [comment]
Thanks for taking a look! After the first post, I went a little overboard and implemented the whole fold system: behavior like foldlevel, commands accepting counts for depth of expand/collapse, etc. That's the new edit. If it doesn't break for a week or so of use, I'll copy it into the wiki and close this.

Thanks for the plugin, it's nice. I like how you can seamless use both vinegar-style and tree-style at the same time.

**Comment by swarn** [comment]
Added to the wiki.

**Comment by farzadmf** [comment]
Hey @swarn , question: do you have function(s) to do these things:
- On a directory node, expand ALL the child nodes recursively
- On a directory node, collapse ALL the child nodes recursively

I thought `neotree_zO` should take care of the first and `neotree_zC` should take care of the second one, but when I try:
- `zO` doesn't expand recursively, and I need to keep pressing it to expand the remaining child nodes
- `zC` closes and goes to the top-level parent, however:
  - When I re-open that node, all the children that were expanded are still expanded and are not collapsed
  - I need it to just remain on the node I'm currently on
  - I need to recursively collapse all children

I'm confused by the API as a directory doesn't seem to have `children` unless it's expanded. `node:expand()` on it basically has no effect (still no children)

I would really, really appreciate if you can help as I've been banging my head against the wall for a few days trying to implement those 2 simple features, which, I thought should be available in any file explorer.

**Comment by cseickel** [comment]
There are already built-in commands called `close_all_nodes` and `expand_all_nodes` that you can reference. If you don't want to just expand/collapse ALL nodes in the tree and instead limit it to one branch, you can start with their implementation and adjust it accordingly.

> I'm confused by the API as a directory doesn't seem to have children unless it's expanded. node:expand() on it basically has no effect (still no children)

The "filesystem" source is unique in that all folders are lazy loaded, so simply expanding the NuiNode won't cause that lazy load to happen. You have to call `neo-tree.sources.filesystem.toggle_directory` to expand **and** lazy load if needed. That is being done in @swarn's code.

Here is the built-in `expand_all_nodes` for the filesystem:

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/8238865e1d9c61f1a260c290653f2c419503e0a9/lua/neo-tree/sources/filesystem/commands.lua#L70-L75

Which is itself just a wrapper around the core `expand_all_nodes` function to add that lazy load logic:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/8238865e1d9c61f1a260c290653f2c419503e0a9/lua/neo-tree/sources/common/commands.lua#L105-L134

**Comment by farzadmf** [comment]
Thank you @cseickel for your answer, I'm checking things out

I was expecting if I pass `true` as the last argument to `toggle_directory` (the `recursive` argument), it should do what I want, but it doesn't seem to

In general, don't you think expanding/collapsing a node recursively is a very common use case for a file tree and is worth being included in the "native" functions so that a mapping can easily be set to those built-in functions?

**Comment by swarn** [comment]
@farzadmf, note that the `neotree_zc` and `neotree_zC` functions that I wrote call my `recursive_close` function, which closes the node *and its parents*. So if you are at the top level, it will not close the children of the node. This is emulating vim folding.

@cseickel, while testing this I noticed that, with a config of
``` lua
filesystem = { window = { mappings = {
  ["zM"] = neotree_zM,
}}}
```
The mapping doesn't works inconsistently. As in, sometimes vim thinks I'm trying to use the native `zM` and complains there's no fold. After a few tries, it works. If I add a wait, like this:
``` lua
filesystem = { window = { mappings = {
  ["zM"] = function (state)
    vim.defer_fn(function() neotree_zM(state) end, 50)
  end,
}}}
```
It works every time. Is there an async thing happening that I'm not understanding?

<details>
<summary>Complete config</summary>

``` lua
  require("neo-tree").setup {
    popup_border_style = "rounded",
    sources = {
      "filesystem",
    },
    default_component_configs = {
      indent = {
        indent_size = 2,
        padding = 0,
        indent_marker = "│",
        last_indent_marker = "└",
      },
      icon = {
        folder_closed = "",
        folder_open = "",
        folder_empty = "",
        default = "",
      },
      name = {
        trailing_slash = true,
        use_git_status_colors = false,
      },
      git_status = {
        symbols = {
          -- Change type
          added = "✚",
          deleted = "✖",
          modified = "",
          renamed = "",
          -- Status type
          untracked = "",
          ignored = "",
          unstaged = "",
          staged = "",
          conflict = "",
        },
      },
    },
    renderers = {
      directory = {
        { "indent" },
        { "current_filter" },
        {
          "container",
          width = "100%",
          right_padding = 0,
          content = {
            { "name", zindex = 10 },
            { "clipboard", zindex = 10 },
            { "diagnostics", errors_only = true, zindex = 20, align = "right" },
          },
        },
      },
      file = {
        { "indent" },
        {
          "container",
          width = "100%",
          right_padding = 0,
          content = {
            {
              "name",
              zindex = 10,
            },
            { "clipboard", zindex = 10 },
            { "bufnr", zindex = 10 },
            { "modified", zindex = 20, align = "right" },
            { "diagnostics", zindex = 20, align = "right" },
            { "git_status", zindex = 20, align = "right" },
          },
        },
      },
    },
    filesystem = {
      bind_to_cwd = false,
      hijack_netrw_behavior = "open_current",
      use_libuv_file_watcher = true,
      filtered_items = {
        show_hidden_count = false,
      },
      window = {
        mappings = {
          ["s"] = "none",
          ["z"] = "none",
          ["y"] = "none",

          ["-"] = vinegar_up,
          ["<C-s>"] = "split_with_window_picker",
          ["<C-v>"] = "vsplit_with_window_picker",
          ["<C-t>"] = "open_tabnew",

          ["zo"] = neotree_zo,
          ["zO"] = neotree_zO,
          ["zc"] = neotree_zc,
          ["zC"] = neotree_zC,
          ["za"] = neotree_za,
          ["zA"] = neotree_zA,
          ["zx"] = neotree_zx,
          ["zX"] = neotree_zX,
          ["zm"] = neotree_zm,
          ["zM"] = function (state)
            vim.defer_fn(function() neotree_zM(state) end, 50)
          end,
          ["zr"] = neotree_zr,
          ["zR"] = neotree_zR,

          ["c"] = "copy_to_clipboard",

          ["yy"] = copy_abs_path,
          ["K"] = quicklook,
        },
      },
    },
  }
```
</details>

**Comment by farzadmf** [comment]
Right @swarn , that's the part I was confused about as well. The node's children is always empty even after calling `toggle_directory`

I think/thought that if we pass `true` to the last argument of `toggle_directory` (which is [the `recursive` argument](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/sources/filesystem/init.lua#L378)), it's supposed to toggle everything recursively.

I tried researching a bit, and I saw this in [fs_scan.lua](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/sources/filesystem/lib/fs_scan.lua#L192) (or [in the async version](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/sources/filesystem/lib/fs_scan.lua#L209)) that's doing this:
```lua
if
  grandchild_nodes == nil
  or #grandchild_nodes == 0
  or #grandchild_nodes == 1 and grandchild_nodes[1].type == "directory
then ...
```

I'm not yet sure why it's only taking the first grandchild and checking if it's a directory (I was expecting to somehow consider all the grand children or something)

I think the change was made by @zenoli , so it would be really nice if they can maybe explain what the logic is like that

**Comment by cseickel** [comment]
> I think/thought that if we pass `true` to the last argument of `toggle_directory` (which is [the `recursive` argument](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/sources/filesystem/init.lua#L378)), it's supposed to toggle everything recursively.

It is __**supposed to**__ expand all nodes recursively, and at one point in time I know that it did. It must have picked up a bug in recent updates. There have been several major changes in the fs_scan module recently.

**Comment by farzadmf** [comment]
> It is ****supposed to**** expand all nodes recursively,

@cseickel that's what I was thinking as well: basically, do:
1. Pass `true` to `toggle_directory` to do a recursive toggle
2. Call `renderer.redraw(state)`
3. Enjoy!

But, it wasn't happening 🙁

**Comment by zenoli** [comment]
@farzadmf
I added this in #600 . Here is a comment trying to explain the new behaviour:
https://github.com/nvim-neo-tree/neo-tree.nvim/pull/600#issuecomment-1323672348

I intended to write it in a way that the mentioned function `scan_dir_async` only gets called if `scan_mode = "deep" is set (which is not the default). Do you have said option set? If I use the default ("shallow"-mode) and press Z to expand all nodes I get a lot of errors.

**Comment by farzadmf** [comment]
Hey @zenoli , I think I have it set:
```json
setup({
  ...
  filesystem = {
    scan_mode = 'deep'
  }
})
```

And the function I'm trying to use (that I was hoping to expand recursively) is this:
```lua
local fs = require "neo-tree.sources.filesystem"
local node = state.tree:get_node()
fs.toggle_directory(state, node, nil, false, true)
renderer.redraw(state)
```

**Comment by zenoli** [comment]
@farzadmf ok, then it "makes sense" that it is not expanding the entire tree, as I did not handle the recursive case in the new scanning implementation, sorry about that :-)

I quickly skimmed over the code and I think it should be not too hard to consider the state of the `recursisve` option in the new scanning functions as well. However, I don't think I will have time to work on this before the weekend.

What I am more concerned about is that expanding all nodes in the "shallow" mode is broken completely (I'll have to check whether this is related to my PR as well.)

**Comment by zenoli** [comment]
I had a look at it today and it seema to be a race condition between loading the nodes and rendering them: when I debug the code using nvim-dap the expand_all function behaves correctly sometimes which makes debugging hard.
