### ISSUE TITLE
[FEATURE REQUEST] Enable the plugin to "unhide" gitignore'ed object(s)

### ISSUE THREAD

**Issue by Jarmos-san** [nvim-neo-tree/neo-tree.nvim#446]
## The Current Issue I'm Facing

A current project I'm working on has a couple of files/folders _gitignore'ed_ since they're only supposed to be worked on locally & not on production. Unfortunately for me, the following configurations hides that specific file I need to work on locally as well:
```lua
  filesystem = {
    filtered_items = {
      hide_gitignored = true,
    },
  },
```

Having to constantly toggle hiding/unhiding files & folders gets monotonous & annoying, so I was wondering if it was possible to add a configuration value which forcibly "unhides" said files/folders?

## A Possible Solution to Fix the Issue

I imagine the functionality could be on similar lines of how `hide_by_name` works but the caveat is, instead of hiding files it would unhide the list of provided files/folder names. The configuration could even be named as `unhide_by_name` or something similar.

**Comment by cseickel** [comment]
This seems like a good idea. Assuming you still want the file to be marked in a hidden file font, and/or gitgnored symbol, I think the option name should refer to being `visible` instead of hidden, maybe `always_visible`?

**Comment by Jarmos-san** [comment]
Yup, it makes sense to mark that specific file as "_gitignored_" & has been made "_always visible_". Also yeah the option name `always_visible` sounds more explicit than a simple `visible`.

**Comment by MunifTanjim** [comment]
> maybe `always_visible`?

There's already a `never_show`, so why not `always_show`?

**Comment by cseickel** [comment]
> There's already a `never_show`, so why not `always_show`?

Yeah, I think that makes sense.

**Comment by cseickel** [comment]
This is in `main` now and will be released tonight. The new config option is called `always_show`. Here is the updated section of the help file:

```help
>
    require("neo-tree").setup({
      filesystem = {
        filtered_items = {
          visible = false, -- when true, they will just be displayed differently than normal items
          hide_dotfiles = true,
          hide_gitignored = true,
          hide_hidden = true, -- only works on Windows for hidden files/directories
          hide_by_name = {
            ".DS_Store",
            "thumbs.db",
            --"node_modules",
          },
          hide_by_pattern = {
            --"*.meta",
          },
          always_show = { -- remains visible even if other settings would normally hide it
            --".gitignored",
          },
          never_show = { -- remains hidden even if visible is toggled to true, this overrides always_show
            --".DS_Store",
            --"thumbs.db",
          },
        },
      }
    })
<

The `visible` option just defines the default value. This value is toggled by
the "toggle_hidden" command, which is mapped to H by default.

The `hide_dotfiles` option just hides anything that starts with `. `(period).

The `hide_gitignored` option will query git for the files and folders being
shown, and hide those that are marked as ignored.

The `hide_hidden` option only will work on Windows using the Windows logic
that determines if a file or directory is hidden.

The `hide_by_name` option is a list of file/folder names that should be
hidden. This is an exact match.

The `hide_by_pattern` option uses glob syntax, which is converted to lua
patterns. No gaurantees on how it handles advanced patterns.

The `always_show` option is a list of file/folder names that will always be 
visible, even if other settings would normally hide it. This section takes
precedence over all other options except for `never_show`.

The `never_show` option is the same as `hide_by_name`, except that those items
will remain hidden even if you toggle `visible` to true. This section takes
precedence over the others.
```

**Comment by Shatur** [comment]
@cseickel is there an option to just show hidden files visible by default?
If I set
```
      hide_dotfiles = false,
      hide_gitignored = false,
      hide_hidden = false,
```
I won't be able to toggle hidden files.

**Comment by cseickel** [comment]
> @cseickel is there an option to just show hidden files visible by default?

Yeah, `visible = true`
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/9acf8ac8396cde6286b8c7b02dbca86a46944d3d/lua/neo-tree/defaults.lua#L334

**Comment by Shatur** [comment]
> Yeah, visible = true

Oh, sorry, I was confused by the option description. Just what I need, thank you!
