### ISSUE TITLE
How I exit fuzzy finder without close tree?

### ISSUE THREAD

**Issue by guilhermeprokisch** [nvim-neo-tree/neo-tree.nvim#451]
How I do search with '/' and exit to navigate the result tree?

<img width="559" alt="image" src="https://user-images.githubusercontent.com/12011070/180267007-936138de-176d-4bb3-a9b4-11251ad77598.png">

**Comment by guilhermeprokisch** [comment]
Thanks, but it's doesn't working 

 Why not just exit the the filter mode and keep the tree without refresh keeping the filter?

**Comment by cseickel** [comment]
> Why not just exit the filter mode and keep the tree without refresh and keeping the filter?

That's not really how a fuzzy finder should work to me. You can use the `filter_on_submit` command to keep a filtered list after leaving the search popup.

I think the more constructive thing would be to figure out why the navigation mappings are not working. Could it be they are being overridden with different mappings in some autocmd you have configured?

**Comment by guilhermeprokisch** [comment]
> That's not really how a fuzzy finder should work to me. You can use the filter_on_submit command to keep a filtered list after leaving the search popup. That command is mapped to f by default.

That's exactly the functionality that I was looking for :)

**Comment by cseickel** [comment]
> > You can use the `<Up>`/`<C-p>` and `<Down>`/`<C-n>` keys to select items in the search results, then hit enter to open it.
> 
> and or the arrows don't work for me... Also, I can't find it documented in :help neo-tree.

You're right that it's not documented, it's just common convention. I assume everyone has used Telescope or fzf and that these movements would be intuitive.

If it's not working, you probably have something in your config that is overriding the mappings.

**Comment by adoyle-h** [comment]
`<Up>/<C-p>` and `<Down>/<C-n>` keys not work for me too. And there is no keymap binding for `:map <C-n>`.
@cseickel

**Comment by cseickel** [comment]
Same answer @adoyle-h, there must be something in your config which is overriding these mappings. If it's not explicitly written in your own config files, it could be another plugin.

Those mapping would be commonly used by an autocomplete plugin, maybe it's in that config.

**Comment by nyngwang** [comment]
> `<Up>/<C-p>` and `<Down>/<C-n>` keys not work for me too. And there is no keymap binding for `:map <C-n>`. @cseickel

@adoyle-h And it's possible that you set `setup { use_default_mappings = false }`. Did you resolve it?

**Comment by adoyle-h** [comment]
@nyngwang I have found it is my fault. It not key mapping overridden, but the cursor line off.
Because I wrote `vim.api.nvim_create_autocmd({ 'WinLeave', 'BufLeave' }, { command = 'set nocursorline' })`, so that the cursor line is invisible in filter mode. Thanks anyway.

**Comment by ditsuke** [comment]
> You can use the `<Up>`/`<C-p>` and `<Down>`/`<C-n>` keys to select items in the search results, then hit enter to open it.

@adoyle-h I was wondering if these mappings can be customized? I use `<C-j/k>` for Telescope, cmp and virtually every other input area so it'll be nice to have it with Neo-tree too.

**Comment by adoyle-h** [comment]
@ditsuke I created the PR #818 . You can use `config.fuzzy_finder_mappings` to define your keymaps.

```lua
require('neo-tree').setup {
    fuzzy_finder_mappings = function(input, state, scroll_padding)
        input:map('i', '<C-j>', function()
            local renderer = require('neo-tree.ui.renderer')
            renderer.focus_node(state, nil, true, 1, scroll_padding)
        end, { noremap = true })

        input:map('i', '<C-k>', function()
            local renderer = require('neo-tree.ui.renderer')
            renderer.focus_node(state, nil, true, -1, scroll_padding)
            vim.cmd('redraw!')
        end, { noremap = true })
    end,
}
```

**Comment by ditsuke** [comment]
@adoyle-h thank you for exposing the configuration!
