### ISSUE TITLE
Directory fuzzy finder only reliably works when cursor is not on top of a folder

### ISSUE THREAD

**Issue by charbelnicolas** [nvim-neo-tree/neo-tree.nvim#456]
When using "D" to fuzzy find a directory when the cursor is on top of a folder it will find it but will fail to select it. Please see the video below:

https://user-images.githubusercontent.com/14960414/180858004-024ff002-ac8d-496a-8faa-27ffb6a0d8b3.mp4

It only works reliably when the cursor is not on top of a folder.

**Comment by cseickel** [comment]
It's hard for me to see what is happening because you don't have cursorline enabled in the video. Are you using the `<Up>`/`<Down>` arrows to select the desired folder before hitting enter?

**Comment by charbelnicolas** [comment]
> It's hard for me to see what is happening because you don't have cursorline enabled in the video. Are you using the `<Up>`/`<Down>` arrows to select the desired folder before hitting enter?

Sorry, I was using this feature incorrectly... I thought that neo-tree would auto select the last folder being shown in the directory fuzzy finder when hitting enter. I now know I need to select the folder myself because otherwise I ended up selecting a parent directory instead.

**Comment by cseickel** [comment]
The normal fuzzy finder does select the first **file** in the list automatically, but in the case of the folder version they are all folders so there's no attempt to pre-select anything.
