### ISSUE TITLE
Allow unmapping keybindings or remove the default ones

### ISSUE THREAD

**Issue by phaazon** [nvim-neo-tree/neo-tree.nvim#460]
Hey,

I’m using the [bépo](https://bepo.fr/wiki/Accueil) keyboard layout and I every time a plugin provides its mappings, I have to remap things. Here, I started to try to remove the mapping for `s` and `t` (since I use them for up and down), but setting them to `nil` in my config doesn’t seem to actually unmap them.

Any idea?

**Comment by cseickel** [comment]
If you don't want to use any default mappings, you can set
`use_default_mappings = false` in your config.

If you want to disable one mapping at a time, set it to the string `"none"`.

**Comment by phaazon** [comment]
Cool, thanks!

**Comment by phaazon** [comment]
Just one last question: is there a list of the command somewhere? Like if I want to rebind what `s` was bound to, to another key?

**Comment by cseickel** [comment]
See
```
:h neo-tree-mappings
```

or look at the [defaults.lua](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/a922c3aff32f3a9498466dd1aa99e14df360fbc5/lua/neo-tree/defaults.lua#L270) file
