### ISSUE TITLE
`buffer_delete` breaks buffer settings

### ISSUE THREAD

**Issue by bandithedoge** [nvim-neo-tree/neo-tree.nvim#461]
When calling `buffer_delete` from a buffer window, reopening that buffer later causes it to ignore certain buffer settings (folds not working, gitsigns not showing up, etc.). This does not happen when using `:bdelete` and gets fixed after restarting.

```
NVIM v0.8.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/fk7srbkzgbi2rw8mjqjvvdx422ynqvrv-neovim-unwrapped-master/share/nvim
"
```

**Comment by cseickel** [comment]
I don't have the same issues. Maybe it's a particular sequence of actions or depends on Neo-tree configuration or is a conflict with another plugin.

Can you post your neo-tree config and give me detailed step by step instructions on how to recreate the issue? 

If I still don't get the same problem, testing with a minimal config that only includes Neo-tree and dependencies that would be the next step.

**Comment by bandithedoge** [comment]
https://github.com/bandithedoge/dotfiles/blob/b7cdedb4cbac52a43e8ee1091cd1dac884e5dba9/users/profiles/editors/nvim/fnl/config/ui.fnl#L130

Here's my configuration. If there's nothing obviously wrong with it I'll try a minimal one later.

**Comment by bandithedoge** [comment]
Hold on, I just noticed something interesting. Running `:bdelete` directly *does* in fact have the same result. I usually use [mini.nvim's `bufremove`](https://github.com/echasnovski/mini.nvim#minibufremove) module which does not have these effects. Therefore I have a different question now: is there a way to change the command that `buffer_delete` calls to something else (possibly a function)?

**Comment by cseickel** [comment]
Yes. I don't have time for an example today, but it is in the documentation.

**Comment by cseickel** [comment]
Here is more information. What you want to do is replace the built-in `buffer_delete` command with your own, here is a snippet to get you started:

```lua
require("neo-tree").setup({
  -- if your want to use this command in other sources, you'll need to define it for each one
  filesystem = {
    commands = {
      buffer_delete = function(state)
        local node = state.tree:get_node()
        local path = node:get_id()
        -- now do whatever custom command you want...
        -- `path` is the full path of the file the cursor is on.
      end,
    },
  },
})
```

You can also define a function separately and just reference it if you want to reuse it for multiple sources:
```lua
local my_buffer_delete = function(state)
    local node = state.tree:get_node()
    local path = node:get_id()
    -- now do whatever custom command you want...
    -- `path` is the full path of the file the cursor is on.
end

require("neo-tree").setup({
  filesystem = {
    commands = {
      buffer_delete = my_buffer_delete
    }
  },  
  buffers = {
    commands = {
      buffer_delete = my_buffer_delete
    }
  }
})
```

There are more examples here:
https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#commands

**Comment by bandithedoge** [comment]
Right, thank you. I will try this in a bit.

**Comment by cseickel** [comment]
Let me know if you need anything else, I'm going to close this issue for now.
