### ISSUE TITLE
[Feature Request]: Add option to automatically close sidebar when opening a file

### ISSUE THREAD

**Issue by jonasnilsberg** [nvim-neo-tree/neo-tree.nvim#462]
Hi! Really love the plugin, and maybe this is already possible, but is it possible to add an option so that the sidebar automatically closes when a file is opened from it?

For example:

1. Press enter on `vitest.config.ts` so that the file opens

![image](https://user-images.githubusercontent.com/11648233/182409636-1458a7d9-4f01-45a7-84f9-ee8d931204ce.png)

2. `vitest.config.ts` opens and the Neotree sidebar automatically closes

![image](https://user-images.githubusercontent.com/11648233/182409845-4f989dd0-e224-4927-8936-1cefbc162c0a.png)

**Comment by cseickel** [comment]
You can do this with `event_handlers`, there is an example on the wiki: https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#auto-close-on-open-file

**Comment by jonasnilsberg** [comment]
Ahh, my bad! Thank you so much 👍
