### ISSUE TITLE
Change popup title text?

### ISSUE THREAD

**Issue by rodhash** [nvim-neo-tree/neo-tree.nvim#466]
Hi,

Any chance we can change / customize the popup title text (popup_border_text var) other than modifying its source?

`popups.lua > M > popup_options`

I like the way it looks without any text:

![Screenshot from 2022-08-03 22-04-04](https://user-images.githubusercontent.com/29671981/182740941-abfc00c1-0046-4ba5-8474-2f739b397b11.png)

While reading its documentation I found only the highlight group to be customizable, not sure if I missed something. Could you confirm?

Thank you and congrats for this awesome work!

**Comment by cseickel** [comment]
It's no customizable right now. I could see it being a config option on each source that will default to the current values but allow you to override it. Feel free to submit an issue and/or PR to add this functionality.

**Comment by rodhash** [comment]
Ok thanks for confirming. As soon as I have some extra time will work on that and hopefully raise a PR, for now I'm good with this minor hack.
