### ISSUE TITLE
Avoid running `git check-ignore` if `hide_gitignored = false`

### ISSUE THREAD

**Issue by jakobkhansen** [nvim-neo-tree/neo-tree.nvim#469]
Hi,

I've had a problem when working in a large monorepo where Neotree would take multiple seconds to open in a folder with many other folders. I tracked this down to the following git command:

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/a922c3aff32f3a9498466dd1aa99e14df360fbc5/lua/neo-tree/git/ignored.lua#L57

This command runs even if `hide_gitignored = false`.

Is there any reason why this git command needs to be run if `hide_gitignored = false`? If not, it would be a good optimization for large Git repos to not run the check-ignore command.

I can try to make a PR for this if that is welcome :)

**Comment by cseickel** [comment]
I actually already had an uncommitted fix for this, which is now in `main`. The reason it still runs the git ignore check even if you are not hiding this items, is that most people still want to want to indicate that they are ignored with a different highlight group and symbol. 

The way it works with this latest commit is that it will skip the check if BOTH `hide_gitignored = false` and `enable_git_status = false`.

**Comment by jakobkhansen** [comment]
Awesome, works perfectly, thanks!

**Comment by nyngwang** [comment]
> `hide_gitignored = false` and `enable_git_status = false`

@cseickel Sorry for commenting on an old issue, but could I ask you about the tradeoff of doing this? I'm interested in the speed-up it will give since I once experienced the slowdown too.

**Comment by cseickel** [comment]
@nyngwang Those settings disable all git integration, so it won't show any git status symbols/colors and it will not mark git ignored files as hidden.

**Comment by nyngwang** [comment]
@cseickel I like the current functions of git-status. To have both, is it possible to put a limitation so that only the parent folder of the current file will be scanned/explored to apply those git-related info(i.e. ignore those folders which haven't been expanded in neo-tree by users)? This is based on my assumption that this could achieve speed-up that worth of doing.

**Comment by cseickel** [comment]
That is actually how it works now.
