### ISSUE TITLE
option to hide the statusline on neotree window

### ISSUE THREAD

**Issue by duarm** [nvim-neo-tree/neo-tree.nvim#470]
As you can see by the image below, the neotree window has an extra unused line, which is the statusline.
![image](https://user-images.githubusercontent.com/26150581/183300348-ace4c920-94d5-42fe-9e1c-dda0486d713d.png)

As far as I know, the relevant options to completely hide the statusline (`noshowmode, noruler, laststatus=0, noshowcmd`) are global, so setting them would also hide the statusline on my buffer on the right. The workaround currently is to hide and unhide depending on the buffer name. 
It would be nice if neotree could handle that for us with a `hide_statusline` option, which would set those variables when entering the neo-tree buffer, and unset them when leaving.

**Comment by cseickel** [comment]
I'm not sure if you can hide the statusline for one window only, but if you can, you can use these events to set buffer/window local options in Neo-tree:

```lua
    require("neo-tree").setup({
      event_handlers = {
        {
          event = "neo_tree_buffer_enter",
          handler = function()
            vim.wo.statusline = nil
          end
        },
        {
          event = "neo_tree_buffer_leave",
          handler = function()
            vim.wo.statusline = "your normal statusline"
          end
        },
      },
    })
```

The example functions above are just a guess, but I'm sure these events will cover what you need if it is possible.

**Comment by duarm** [comment]
```lua
	event_handlers = {
		{
			event = "neo_tree_buffer_enter",
			handler = function()
				vim.o.showmode = false
				vim.o.ruler = false
				vim.o.laststatus = 0
				vim.o.showcmd = false
			end
		},
		{
			event = "neo_tree_buffer_leave",
			handler = function()
				vim.o.showmode = true
				vim.o.ruler = true
				vim.o.laststatus = 2
				vim.o.showcmd = true
			end
		},
	},
```

is easy enough, thanks
