### ISSUE TITLE
Can't filter

### ISSUE THREAD

**Issue by jcmuller** [nvim-neo-tree/neo-tree.nvim#48]
Any time I attempt to filter the tree I get

```
Error executing luv callback:
...neo-tree.nvim/lua/neo-tree/sources/common/file-items.lua:51: attempt to index field 'name' (a nil value)
stack traceback:
        [builtin#36]: at 0x562387a7d900
```
I added a check for `item.name`'s presence. The error is gone, but the filtering doesn't yield any results.

Any idea of what I'm doing wrong?

Cheers

**Comment by cseickel** [comment]
Maybe it's something about the particular items in the directory you are working with. Can you try different directories? If you've forked this repo, is the cwd set to the root of the repo?

**Comment by jcmuller** [comment]
I've tried this across many directories, across two computers.

1. I believe it did the very first time I tried the plugin about 10 days ago.
2. Linux
3. I do have both fd (fdfind) an find.

Though, on this computer I am getting a different stack trace (running against latest version of your plugin):

```
Error executing luv callback:
...jcmuller/.vim/plugged/neo-tree.nvim/lua/neo-tree/log.lua:149: E5560: nvim_exec must not be called in a lua loop callback
stack traceback:
        [builtin#36]: at 0x56011de7a770
```

ah. After commenting out the problem loop, the original error comes back:

```
Error executing luv callback:
...neo-tree.nvim/lua/neo-tree/sources/common/file-items.lua:52: attempt to index field 'name' (a nil value)
stack traceback:
        [builtin#36]: at 0x55eb86218770
```

Ah. Changing `find_command` to `find` it started working.

My systems are running `fdfind` version `7.4.0`. Ah. It doesn't support `--max-results`.

**Comment by cseickel** [comment]
Thanks for the detailed analysis. That error should definitely be bubbled up, and I should check versions of programs and adjust the commands accordingly. I'll take a look at this now.

**Comment by cseickel** [comment]
This should be fixed now even if you don't manually specify a `find_command`. I also fixed the logging problem which could have been a problem in lots of situations.

Thanks again for the detailed bug report!

**Comment by zolrath** [comment]
On my WSL2 installation of ubuntu I'm seeing an issue where it seems to be attempting to filter using `fd`, which is an entirely different application on Ubuntu. Unfortunately it uses `fdfind` for what is elsewhere `fd`.

You test for the existence of `fd` and `fdfind` but if there is a way to disambiguate the two and swap to `fdfind` if the machine has an improper `fd`, that would solve the need to override it.

**Comment by MKdir98** [comment]
The error gets fixed by `apt install fd-find`. Thanks, guys
