### ISSUE TITLE
Include gutter width in right align calculations

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#481]
> Thanks for all @cseickel, best regards!

You're welcome!

BTW - I'd also consider it a bug that the sign and number columns are not accounted for when right aligning. I'd like to fix that one day as well...

_Originally posted by @cseickel in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/415#issuecomment-1207399462_

**Comment by cseickel** [comment]
There is actually an easy way to do this: https://github.com/neovim/neovim/issues/17229#issuecomment-1024847971

**Comment by barreiroleo** [comment]
Works fine, thanks @cseickel!
