### ISSUE TITLE
git commit broken on windows

### ISSUE THREAD

**Issue by gsuuon** [nvim-neo-tree/neo-tree.nvim#491]
Git commit on windows throws `error: pathspec 'bar'' did not match any file(s) known to git`
https://stackoverflow.com/a/25716030/

#345 looks like it was changed here

**Comment by cseickel** [comment]
Do you mean that you are using `main` and it worked correctly before that commit? Or are you on `v2.x` right now?

**Comment by gsuuon** [comment]
I'm on v2.x right now

**Comment by cseickel** [comment]
In that case, I think it is fixed in `main`, but I need a Windows user to test it and confirm.

**Comment by gsuuon** [comment]
Ok I can give it a shot

**Comment by gsuuon** [comment]
Works for me on main! Thanks for the super fast response, closing.
