### ISSUE TITLE
Open float filesystem 3 times occurs error invalid window id in function close

### ISSUE THREAD

**Issue by dobbbri** [nvim-neo-tree/neo-tree.nvim#492]
:Neotree toggle float filesystem
:Neotree toggle float filesystem
:Neotree toggle float filesystem
occurs error invalid window id in ui/renderer.lua line 108 in function close
![Screen Shot 2022-08-18 at 00 25 51](https://user-images.githubusercontent.com/4087713/185286617-e2944211-daed-41f7-a849-355958272711.jpg)

**Comment by ryoppippi** [comment]
me too
