### ISSUE TITLE
When I run `NeotreeReveal` in the help file, a prompt appears that only displays `y/n`.

### ISSUE THREAD

**Issue by takei0107** [nvim-neo-tree/neo-tree.nvim#493]
### overview
I have neotree open with the keymap `Neotree reveal toggle left`.
When I press this keymap while browsing the help file, I get a prompt with only `y/n` information.

I assume this is a confirmation prompt when changing directories, but why is there no information other than `y/n`?

I am using `nordfox` for the color scheme, is this related?

### screenshots

Run `NeotreeReveal` with the help file.

![Screenshot from 2022-08-20 01-04-41](https://user-images.githubusercontent.com/99521189/185660480-d1a964f2-a475-4696-8b94-d09e91eb4475.png)

Then a prompt appears with only 'y/n'.

![Screenshot from 2022-08-20 01-08-12](https://user-images.githubusercontent.com/99521189/185661117-e31eefc8-6f2b-422e-9bf5-2a109e64b455.png)

The same is true for `Neotree reveal toggle left`, which is usually used for key mapping.

**Comment by cseickel** [comment]
It looks like your highlight group has the same color for foreground and background. Try setting `popup_border_style = "rounded"` in the config or manually setting the `NeoTreeTitleBar` highlight group to something. This might work:
```
:highlight NeoTreeTitleBar guifg=#000000 guibg=#999999
```

**Comment by takei0107** [comment]
Thank you.
It was a problem with my settings.

I set `popup_border_style` and now I can see the confirmation message.
This is the first time I have seen the same message in other prompts. 
Very nice feature.

![Screenshot from 2022-08-20 10-52-29](https://user-images.githubusercontent.com/99521189/185724903-c6d7b319-afc5-457e-8a99-5b778767ecbc.png)

**Comment by eloytoro** [comment]
I also had this issue and I was completely unaware of it, can we improve on the highlighting for most colorschemes?

**Comment by cseickel** [comment]
> I also had this issue and I was completely unaware of it, can we improve on the highlighting for most colorschemes?

Yes. Can you tell me what color scheme you are using so I have something to test against?
