### ISSUE TITLE
Arrows not showing up

### ISSUE THREAD

**Issue by Dax89** [nvim-neo-tree/neo-tree.nvim#495]
Hi! I'm trying neo-tree but I cannot make the expand/collapse arrows showing up:
![Screenshot_20220824_113013](https://user-images.githubusercontent.com/1503603/186383884-184251be-1853-44ff-be7e-6bbcfe03a932.png)

I'm using the colorscheme `catppuccin`, I have also my entire configuration loaded on github (I haven't pushed neo-tree yet) if needed: https://github.com/Dax89/nvim-config

The plugin is installed as:
```lua
use {
  {"nvim-neo-tree/neo-tree.nvim",     
  branch = "v2.x", 
  requires = {"nvim-lua/plenary.nvim", "kyazdani42/nvim-web-devicons", "MunifTanjim/nui.nvim"}},
}
```

Am I doing something wrong?

**Comment by cseickel** [comment]
They are not enabled by default unless you use the file nesting feature. It is documented in `:h neo-tree-expanders` and in the Quickstart of the README. Here is how to enable them:

```lua
    require("neo-tree").setup({
        default_component_configs = {
            indent = {
                with_expanders = true,
            },
        },
    })
```

**Comment by Dax89** [comment]
I have missed that part in the README.
Btw, it works, thanks!
