### ISSUE TITLE
Arrow Background is incorrect

### ISSUE THREAD

**Issue by mbriggs** [nvim-neo-tree/neo-tree.nvim#50]
Hi :)

I got this intermittently before, now it is constant https://github.com/nvim-neo-tree/neo-tree.nvim/issues/32

![image](https://user-images.githubusercontent.com/89260/149444415-ccb94d6d-2a4a-4087-8536-819db13719df.png)

other icons seem fine.

When I got it intermittently, a second PackerCompile would confusingly make it go away (I would think that would be deterministic). Now it is sticking around

**Comment by cseickel** [comment]
Is your theme is applied via packer? If it is, then maybe the highlight groups are affected by the order in which plugins are setup.

The highlight group being used for this is `NeoTreeDirectoryIcon`, which will default to linking to `TabLineSel` if that group exists and has a background or foreground set. Can you check what the value is with `:hi NeoTreeDirectoryIcon`?

This will set it to the default value that I use:
```
:hi NeoTreeDirectoryIcon guibg=NONE guifg=#73cef4
```

Also, are you on 1.x or main?

**Comment by mbriggs** [comment]
> Is your theme is applied via packer? 
yup

I tried changing the order, but maybe I screwed it up. I am using https://github.com/navarasu/onedark.nvim

![image](https://user-images.githubusercontent.com/89260/149449413-a305259e-1361-42b0-a544-94682300582f.png)


> :hi NeoTreeDirectoryIcon guibg=NONE guifg=#73cef4

that fixes it :)

> Also, are you on 1.x or main?

1.x

**Comment by cseickel** [comment]
OK, you'll want to set that highlight group somewhere in your config. Maybe TabLineSel was a bad choice to link to! 

In the next release, I'll just set it to the setting I gave you instead of trying to link to something.
