### ISSUE TITLE
Provide customization option to replace "(cut)" and "(copy)" indicator by custom strings.

### ISSUE THREAD

**Issue by zenoli** [nvim-neo-tree/neo-tree.nvim#503]
First of all, thank you for the great plugin. I just migrated  from nvim-tree because of the fuzzy searching and way better cut/copy ux for multiple files.
It would be awesome if there was an option to replace the "(cut)" and "(copy)" indicators by custom strings. I was thinking about using nerdfont icons for this:

![copy](https://user-images.githubusercontent.com/8073528/187186857-2e7dacf2-01b9-46ad-b4ef-9380aa361e65.png)

![cut](https://user-images.githubusercontent.com/8073528/187186884-6dfb2bf0-8ae8-4416-af8b-8e0e4101dccf.png)

IIRC coc-explorer used to have something like this by default and it's super neat.

**Comment by cseickel** [comment]
You can do this with a custom component, see https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#components for more info.

Here is the default implementation for the `clipboard` component:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/a7d6f05e57487326fd70b24195c3b7a86a88b156/lua/neo-tree/sources/common/components.lua#L42-L52

You can copy that code to use as a starting point and modify it to output the icons you want.

**Comment by cseickel** [comment]
> Edit: I also am trying to disable the notifications when I "cut/copy" something. I can do so by increasing the log level in `log.lua > default_options` (I set `level = error`).
> Is there a way to set this in the `setup` function?

Yup, just set the `log_level`:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/a7d6f05e57487326fd70b24195c3b7a86a88b156/lua/neo-tree/defaults.lua#L33

Setting it to "warn" will also work.

**Comment by zenoli** [comment]
This worked. I was looking for a "log_level" option in the documentation but failed to find any.
Thanks again!
