### ISSUE TITLE
[Enhancement] Allow specifying diagnostic highlights manually

### ISSUE THREAD

**Issue by akinsho** [nvim-neo-tree/neo-tree.nvim#504]
Hi,

So I've recently changed the way highlights are show in my config to highlight the entire line including the sign column a specific colour.

<img width="975" alt="image" src="https://user-images.githubusercontent.com/22454918/188429482-b7fd3b01-dccb-4e41-bf70-ec53b16b30c3.png">

Unfortunately, this also unintentionally changes the signs used by neotree to have the same background colour highlight. Which I don't want/didn't intend, but it turns out that neo-tree uses my sign highlight not the base `Diagnostic{Error|Info|Warn}` etc.

It would be nice to be able to decouple these two things, so I don't have to plan my sign highlights around neo-tree as well.

<img width="142" alt="image" src="https://user-images.githubusercontent.com/22454918/188429704-a9395950-554d-47b0-ba43-664063cc3fc4.png">

**Comment by cseickel** [comment]
Right now it calls `vim.fn.sign_getdefined` to get both the symbol and the highlight. How about if the component took an optional config object that looked like this?

```lua
  default_component_configs = {
    diagnostics = {
      symbols = {
        hint = "H",
        info = "I",
        warn = "!",
        error = "X",
      },
      highlights = {
        hint = "DiagnosticSignHint",
        info = "DiagnosticSignInfo",
        warn = "DiagnosticSignWarn",
        error = "DiagnosticSignError",
      },
     },
     ...
```

Another thought I had was to just have a single 'highlight_prefix' config option which could be concatenated with the diagnostic level text to get the highlight group.

**Comment by akinsho** [comment]
@cseickel that proposed API looks good to me since it doesn't force the user to specify icons manually or to specify highlights, and they can presumably fill out as much or as little of both tables independently.

Re. adding a prefix I guess that would also work, but I slightly prefer the above example since it feels more straightforward but not by much 🤷🏿

**Comment by cseickel** [comment]
I added the component config option in `main`. It will take a little while for the next release because I have a half finished preview feature in main right now which is taking longer than expected.

Using the `main` branch, you can set your highlight groups like this:

```lua
  default_component_configs = {
    diagnostics = {
      highlights = {
        hint = "DiagnosticSignHint",
        info = "DiagnosticSignInfo",
        warn = "DiagnosticSignWarn",
        error = "DiagnosticSignError",
      },
     },
     ...
```

**Comment by akinsho** [comment]
@cseickel that works like a charm, thanks 👍🏿
