### ISSUE TITLE
changing keymaps

### ISSUE THREAD

**Issue by bryant-the-coder** [nvim-neo-tree/neo-tree.nvim#506]
i hv change `toggle_hidden` to `<C-h>` but when i press `H` which in my mappings.lua is move to the left window. `H` still toggle_hidden. is there anyway to remove `H` as the default keybind?

**Comment by cseickel** [comment]
Yes, just map `["H"] = "none"` to remove the built-in mapping.

**Comment by nyngwang** [comment]
@cseickel where to put the `use_default_mappings = false`?

**Comment by cseickel** [comment]
> My question now become: does `use_default_mappings` disable all mappings or just those ones under `window`?

It disables all configurable mappings, which are all technically under `window` or `[source].window`. The only ones I can think of that are not affected are the navigation mappings in fuzzy finder mode.
