### ISSUE TITLE
bug: indent marker disappears with `default_component_configs.indent.padding < 1`

### ISSUE THREAD

**Issue by pysan3** [nvim-neo-tree/neo-tree.nvim#509]
Hi, Thanks for the awesome plugin :)

I found out that when setting the padding to 0, the indent marker on the first indentation (far left) disappears as in the following screenshot. (indent of `lua/` in the picture.)
I think it is more intuitive to have it not disappear especially since I `hide_root_node = true`.

If this is indented, may I kindly ask you to expose some kind of setting that I can change in the setup?

## Reproduce

```lua
local neotree = require("neo-tree")
neotree.setup({
  hide_root_node = true, -- disappears with `false` as well
  retain_hidden_root_indent = false,
  filesystem = {
    follow_current_file = true,
  },
  default_component_configs = {
    indent = {
      indent_size = 2,
      padding = 0, -- HERE
    },
  },
})
```

- `padding = 0` (disappears)
![image](https://user-images.githubusercontent.com/41065736/189354764-2efc6720-4f88-40cf-a496-e519e2a2abf8.png)

- `padding = 1` (no problem)
![image](https://user-images.githubusercontent.com/41065736/189355033-400129ba-caff-4d28-a91b-12f67d8f0712.png)

### Notes

- neo-tree
  - branch: `main`
  - commit: 9f5119a7d47edcb0c30f0c44e6f4580b5101b5f5

### Details

- `nvim --version`
  - NVIM v0.8.0-dev+nightly
  - Build type: RelWithDebInfo
  - LuaJIT 2.1.0-beta3
- Operating system: `5.10.102.1-microsoft-standard-WSL2`

Best,
@pysan3

**Comment by pysan3** [comment]
Hi @cseickel, this issue seems to be not yet fixed.

Do you have any plans on working on it?

**Comment by cseickel** [comment]
Hey @pysan3, sorry I missed this one. Life has been very busy lately so I am just keeping up with PRs and bug reports and not adding much new code myself.

It seems like this doesn't really need configuration, the indent component should just force a minimum padding of 1 if the indent guides or expand markers are enabled. Does that make sense to you.

**Comment by pysan3** [comment]
I see. Yes when I do not set anything to `default_component_configs.indent.padding`, it seems to work alright.
I think I'll go with this for now so closing this issue.

BTW, I might be able to help you especially for issues related to the source selector, so feel free to ping me. (mentioning with @pysan3 should send an email to me?)
