### ISSUE TITLE
How to disallow use some buffers for opening files?

### ISSUE THREAD

**Issue by Wansmer** [nvim-neo-tree/neo-tree.nvim#511]
Now neo-tree opens the file in the last used buffer.
This is convenient in most cases, but if there were "toggleterm" or "packer" buffers before, it becomes inconvenient.
How to disable the use of these types of buffers for opening files?

**Comment by cseickel** [comment]
There's no config option to specify which buffer types to never replace, but you can implement that logic yourself by handling the `"file_open_requested"` event: https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#custom-window-chooser-for-file-open-commands

My suggestion is always to use `:Neotree reveal current' in the window you intend to open the file in, that way there's no ambiguity about where that file will open.

**Comment by Wansmer** [comment]
Thanks for the answer. I'll try to use 'file_open_requested'.
P.S. I think it would be cool if future releases add this functionality to the config (as in 'nvim-window-picker' config: `filter_rules.bo.filetype`). It will be very helpful.

**Comment by zolrath** [comment]
I agree that having this exposed more easily would be great.
Currently experiencing neo-tree opening files in a [noice.nvim](https://github.com/folke/noice.nvim) popup buffer when vim is first launched.

**Comment by nhat-vo** [comment]
Not very sure if this answers the problem, but the `*_with_window_picker` commands allow you to choose which window to open the buffer in.

**Comment by cseickel** [comment]
This has been fixed by #694 and this option:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/039aff445280dd4ffce3c4b97e25d7962c0bcfd4/lua/neo-tree/defaults.lua#L37
