### ISSUE TITLE
Problem with symbol for staged files

### ISSUE THREAD

**Issue by v1nns** [nvim-neo-tree/neo-tree.nvim#512]
I can't see the git_status symbol for staged files, and I found in source code that this snippet (in **git_status** method from _sources/common/components.lua_) is the responsible for this behavior:

![image](https://user-images.githubusercontent.com/22479290/189793876-d0276529-4ec1-4a5d-8c46-83ba35ab2d38.png)

May be that the output from **git diff** is wrong? Or maybe that this if-statement should be modified?

For example, in the image below, staged symbol should have appeared in the "_highlights.lua_" file entry.

![image](https://user-images.githubusercontent.com/22479290/189793722-854a4d32-2f12-4931-be66-32f52976dad6.png)

**Comment by cseickel** [comment]
This is caused by the #501 fix, which needs to be handled differently. I'll fix it.
