### ISSUE TITLE
Way to change move cursor keymaps in filter mode

### ISSUE THREAD

**Issue by s1n7ax** [nvim-neo-tree/neo-tree.nvim#515]
At the moment there are hard coded keymaps defined to move cursor up and down while in filter mode.

**filter.lua**

```lua
input:map("i", "<down>", move_cursor_down, { noremap = true })
input:map("i", "<C-n>", move_cursor_down, { noremap = true })
input:map("i", "<up>", move_cursor_up, { noremap = true })
input:map("i", "<C-p>", move_cursor_up, { noremap = true })
```

I would love to have them configurable the same way

```lua
["<c-n>"] = "move_cursor_down",
["<c-e>"] = "move_cursor_up",
["<down>"] = "move_cursor_down",
["<up>"] = "move_cursor_up",
```

**Comment by antgubarev** [comment]
And for other inputs. For example "add file" input.

**Comment by pysan3** [comment]
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/230e9383c664061bdf3517c998ed1bf6ed409c59/lua/neo-tree/defaults.lua#L434-L438

Ref https://github.com/nvim-neo-tree/neo-tree.nvim/pull/818
