### ISSUE TITLE
Neo tree buffers will not display all buffers in different folders

### ISSUE THREAD

**Issue by Leiyi548** [nvim-neo-tree/neo-tree.nvim#517]
When I open two files in different folders, Neo tree buffers will not display all the buffers but only the current ones

![image](https://user-images.githubusercontent.com/76139422/190128319-01bb332e-1ae4-4fb7-ac10-1f0106e58cd6.png)

![image](https://user-images.githubusercontent.com/76139422/190128667-0038427b-9cdf-46b2-8565-7eb42bd35dcd.png)

I want show all buffers

**Comment by cseickel** [comment]
It shows all folders within the current working directory. If you have buffers open that are outside of your working directory, you will need to change to a directory which is common to all open files to see them all in Neo-tree. By default, the `<Backspace>` key will navigate up one directory.
