### ISSUE TITLE
Tree not rendering properly with multiple windows on screen

### ISSUE THREAD

**Issue by ShaharNaveh** [nvim-neo-tree/neo-tree.nvim#518]
After updating to b13425d57111a7885961110f8e51907fa630642b there was a strange problem where neo-tree would not render properly if there is another horizontal window in the same screen (not a vim-split window)

https://user-images.githubusercontent.com/50263213/190137856-0b37e5c8-ea27-46f9-8a7f-0a96d17e4366.mp4

Here, at first I had two windows open, and after moving the bottom window to another pane, and closing neo-tree then opening it agian eveything worked.

---

neo-tree conf file:
<details>

```lua
local neotree = require("neo-tree")

vim.g.neo_tree_remove_legacy_commands = 1

neotree.setup({
    enable_git_status = true,
    enable_diagnostics = true,
    filesystem = {
        filtered_items = {
            hide_gitignored = false,
            visible = true,
            hide_dotfiles = false,
        },
        hide_by_name = { "\\.dmypy\\.json", "__pycache__" },
        hide_by_pattern = { "^.git$" },
        never_show = {},
    },
    window = {
        position = "left",
        width = 30,
    },
})
```

</details>

---

I am on Arch Linux, and my WM is qtile on xorg.

---

Would happily supply any other information in order to help

**Comment by cseickel** [comment]
I don't think that particular commit could have changed anything for you with that config. Is it possible your problem was caused by updating another plugin as part of that set of updates?

You could try pinning it to prior commits and working backwards to see if this issue changes with older versions.

https://github.com/nvim-neo-tree/neo-tree.nvim/commits/v2.x

**Comment by ShaharNaveh** [comment]
> Is it possible your problem was caused by updating another plugin as part of that set of updates?
> 
> You could try pinning it to prior commits and working backwards to see if this issue changes with older versions.


I did that with a commit that I know for a fact that was working properly, and the problem still persist.
I guess it's exactly as you said, that another plugin is messing it up.

TY for the response!
Closing the issue, as it's not a direct neo-tree bug
