### ISSUE TITLE
How to change the window options on leaving the buffer?

### ISSUE THREAD

**Issue by pedromss** [nvim-neo-tree/neo-tree.nvim#519]
On big file trees I like having `number` and `relativenumber` to move faster, so I set an event handler for `neo_tree_buffer_enter`. Now after selecting a file and leaving the Neotree window/buffer, the extra space taken by `number` and `relativenumber` is wasted so I'd like to revert those 2 options when I leave the buffer.

I thought `neo_tree_buffer_leave` would do it but any options set there seem to afect the new buffer that is opened, not the neo tree buffer.

This is odd behaviour to me because if I wanted to afect a new buffer I'd set an `autocmd` on `BufAdd` for example, not an event handler on Neo tree.

1. Is this event being fired at the right time? (i.e. what I described is by design and won't change)
2. Is there another event I can hook into for what I want to do?

**Comment by cseickel** [comment]
> I thought `neo_tree_buffer_leave` would do it but any options set there seem to afect the new buffer that is opened, not the neo tree buffer.
> 
> This is odd behaviour to me because if I wanted to afect a new buffer I'd set an `autocmd` on `BufAdd` for example, not an event handler on Neo tree.
> 
> 1. Is this event being fired at the right time? (i.e. what I described is by design and won't change)

Yes, it's actually intended for the purpose of restoring window local variables when a neo-tree buffer gets replaced by another. That way you can set neo-tree specific option on `enter`, and undo them on `leave`, so that the given options only affect neo-tree. It's more applicable when using the "current" position.

The good news is that you can find the winid/bufnr of a neo-tree sidebar at any time using neo-tree's own state management:

```lua
  local manager = require("neo-tree.sources.manager")
  local state = manager.get_state("filesystem")
  local winid = state.winid
  local bufnr = state.bufnr
  vim.api.nvim_win_set_option(winid, "number", false)
```
NOTE: thats all from memory and may have errors.

**Comment by nyngwang** [comment]
I think the idea/convention of events like `on_foo_enter`, `on_foo_leave` are that these actions(`enter`, `leave`) already happened, i.e. you're reacting to an already/just happened event. So for `neo_tree_buffer_leave`, I will interpret it as "on `neo_tree_buffer_leave`" and thus now your current buffer is not neo-tree anymore.

With the hint given by @cseickel, you just need to directly call its "name"(here the `winid`), not the implicit "current buffer"(and your assumption on "current buffer" is neo-tree is wrong).

**Comment by pedromss** [comment]
Thank you both.


@nyngwang I interpret `neo_tree_buffer_leave` as you described but I was "hopeful" that it did what I wanted to do. I was going to follow up with, could we add something like  `neo_tree_window_before_leave`, since there's already a `neo_tree_window_before_close` which I would interpret as "do something in the neo tree window, before we leave it".

@cseickel thank you, that did the trick with a slight variation

```lua
{
	event = "neo_tree_buffer_leave",
	handler = function()
		local state = require("neo-tree.sources.manager").get_state("filesystem")
		local winid = state.winid
		if winid ~= nil then
			vim.api.nvim_win_set_option(tonumber(winid), "number", false)
			vim.api.nvim_win_set_option(tonumber(winid), "relativenumber", false)
		end
	end,
}
```
Notice the `winid ~= nil`:
Putting a `print` in this event shows it runs twice after I use `:Neotree`. 

I expected this event to only run when neo-tree was opened and I moved to a different window. 

It is firing **twice** when the neotree appears. Its also firing when I move out of the neotree window, this part is correct, but there's clearly 2 fires.

I'm mentioning this in case you or someone else wants to take a look at this as it seems unnecessary to fire twice when the window appears, given the name of the event.

Closing this issue, thank you.

**Comment by cseickel** [comment]
> I expected this event to only run when neo-tree was opened and I moved to a different window.
> 
> It is firing **twice** when the neotree appears. Its also firing when I move out of the neotree window, this part is correct, but there's clearly 2 fires.
> 
> I'm mentioning this in case you or someone else wants to take a look at this as it seems unnecessary to fire twice when the window appears, given the name of the event.

Good to know, thanks for reporting.
