### ISSUE TITLE
Preview window frozen when collapse-and-expand the other folder

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#521]
I think it is more easily understood by a short clip:

https://user-images.githubusercontent.com/24765272/190400435-7228cedf-f94e-4fec-a153-bd30bf47a7f9.mov

**Nvim version**

```
NVIM v0.8.0-dev-1086-ga8c9e721d
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by cseickel** [comment]
Well that's annoying!

**Comment by nyngwang** [comment]
@cseickel btw, is it possible to enable preview by default?

**Comment by cseickel** [comment]
Not right now. I have thought about adding the option for floating windows, but not for sidebars. Did you want to preview by default for the sidebar?

**Comment by nyngwang** [comment]
> I have thought about adding the option for floating windows, but not for sidebars. Did you want to preview by default for the sidebar?

Great :) I prefer things done in floating windows (so the existing layout is kept) too. I haven't tried the sidebar version.
