### ISSUE TITLE
Neotree does not update window options (when opened in autocmd handler)

### ISSUE THREAD

**Issue by gj86** [nvim-neo-tree/neo-tree.nvim#526]
If Neotree is invoked with `Neotree show` or `Neotree toggle show`  it does not update the colorschemes, various window options (number, relativenumber etc.)

**Comment by cseickel** [comment]
I'm not sure what you mean. Can you provide more details about what you are expecting to happen and what actually happens? Can you also provide your config?

You mention that the problem affects `Neotree show`, does that mean it works fine for `Neotree` or `Neotree focus`?

**Comment by gj86** [comment]
First of all thanks for this wonderful plugin. I use it everyday.

And no, this does not happen if **Neotree** is opened with any command that puts the focus on **Neotree** window.
It only happens if the opened **Neotree** window doesn't get focus.

When opening **Neotree** with `Neotree show` the **Neotree** window looks like the following screenshot.
[Before Neotree window have focus](https://i2.paste.pics/eda4a39853726cf6dba6b9bb20047d28.png)

After activating **Neotree** window the following happens.
[After Neotree window have focus](https://i2.paste.pics/53b8f70643d112175546a7c15397bf9a.png)

**Comment by cseickel** [comment]
I don't see the same behavior on my end. I do understand how this could happen if neotree is opened within another autocmd. Neo-tree applies the window settings within a BufWinEnter autocmd, and by default nested autocmds are not allowed by nvim. 

Does it work correctly when you run the command manually?

If it does, there are workarounds. It might work around teh nesting issue if you wrap the callback in a scheduled call like: 
```lua
    callback = vim.schedule_wrap(function() vim.cmd("Neotree show") end)
```

You can also manually fire Neotree's handler for this event like:
```lua
    vim.cmd("Neotree show")
    local events = require("neo-tree.events")
    events.fire_event(events.VIM_BUFFER_ENTER)
```

**Comment by gj86** [comment]
> Does it work correctly when you run the command manually?

Yes. The problem only occurs when **Neotree** is triggered by `autocmd` 

I have tried both workarounds, and they both work.

**Comment by cseickel** [comment]
> Yes. The problem only occurs when **Neotree** is triggered by `autocmd`
> 
> I have tried both workarounds, and they both work.

Great, glad to hear it. I'm going to close this as completed.
