### ISSUE TITLE
How to ignore files by pattern (not hide) ?

### ISSUE THREAD

**Issue by soifou** [nvim-neo-tree/neo-tree.nvim#527]
Recently, a [PR from null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1075) changes the path where are stored the temp files of some diagnostics/formatters.
For example on linux, there were stored to `$XDG_RUNTIME_DIR` (or `/tmp` as fallback). Now there are stored  to the current buffer dir. 

This has some visuals annoying consequences with my setup when I'm working with the filesystem opened . My first thought was to add a pattern in option `filtered_items.hide_by_pattern` but this only seems to hide them (as the name suggests). 

Below the visual annoyances in action (first hidden, then displayed).

https://user-images.githubusercontent.com/7377369/190828424-6e38ee57-46e5-4029-9bd9-9deb7de5321a.mp4

 I'd like Neotree completely forget about theses files. Is something going wrong with my settings or this is not yet implemented (something like `never_show_by_pattern`)?

Thanks in advance for your help!

```lua
     require("neo-tree").setup({
          close_floats_on_escape_key = false,
          use_popups_for_input = false,
          popup_border_style = my_borders,
          enable_diagnostics = false,
          enable_modified_markers = true,
          -- Refresh the tree when a file is written. Only used if `use_libuv_file_watcher` is false.
          enable_refresh_on_write = false,
          default_component_configs = { ⋯
          },
          window = { ⋯
          },
          filesystem = {
              async_directory_scan = "auto",
              follow_current_file = true,
              use_libuv_file_watcher = true,
              -- These filters are applied to both browsing and searching
              filtered_items = {
                  visible = false,
                  hide_dotfiles = true,
                  hide_gitignored = true,
                  hide_by_pattern = { "_null-ls_*" },
                  never_show = { ".git" },
              },
              commands = { ⋯
              },
              components = { ⋯
              },
          },
      })
```

**Comment by cseickel** [comment]
@soifou I have the first of a two part fix done, which is to make the file watchers ignore the null-ls temp files so the tree doesn't keep refreshing. Can you switch to the `main` and try it out?

I also intend to add a `never_show_by_pattern` option, but I think the file watcher change is all you really need for this specific case.

**Comment by soifou** [comment]
Unfortunately not. 

The [next related PR](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1114) has just been merged, so the pattern matching you set is incorrect, it should be `^%.null[-]ls_.+` instead.

By changing to this pattern, the `watch_folder` skips these temp files and does not fire unnecessary event.
But the git tree keeps refreshing with "?" signs (the `watch_git_index` does not catch any of theses temp files)
As well as the hidden count keeps... counting.

> I also intend to add a never_show_by_pattern option, but I think the file watcher change is all you really need for this specific case.

That's good to hear because the thing is what if they change again the pattern? This needs to be reflected here.

**Comment by soifou** [comment]
Yes `never_show_by_pattern` is working as intended! Thanks a lot.

One (minor) issue though but this is not really on your side.

Since a temp file is created for a few sec when I'm doing some operations on a buffer, Neotree git watch index detects it and the parent directories reflect this by showing the question mark sign. That could lead to some misunderstanding about the current state. Question marks disappears if I toggle the tree or save again the buffer or spawn a new term on the project root dir, etc.

I could add an entry to my `.gitignore` and this will solve the problem but maybe you have a better idea how you could handle it in Neotree?

**Comment by cseickel** [comment]
> I could add an entry to my `.gitignore` and this will solve the problem but maybe you have a better idea how you could handle it in Neotree?

I actually think that is the best way to handle this. That will also cover the situation where a temp file is not cleaned up by null-ls.

**Comment by soifou** [comment]
Ok then feel free to close this issue! And by the way, null-ls will handle the cleanup on its side :wink:

Thanks again for your support!
