### ISSUE TITLE
Debounce filesystem_navigate error: Vim:E475: Invalid value for argument cmd: 'git' is not executable

### ISSUE THREAD

**Issue by gogito** [nvim-neo-tree/neo-tree.nvim#534]
Hi, I'm getting this when trying to run NeoTree, and I can't install git on this system. Is there a way aroung this?

Thanks in advance!

**Comment by cseickel** [comment]
There are two settings that will utilize `git` if they are enabled, just set them to false:

```lua
    require("neo-tree").setup({
      enable_git_status = false,
      filesystem = {
        filtered_items = {
          hide_gitignored = false,
        },
    })
```

**Comment by mehalter** [comment]
I am also trying to accomplish this and I have both of these options set to `false` as well as the sources list manually set to not include `git_status` at all and I am still getting this message every time I run `:Neotree` except the first one
