### ISSUE TITLE
How to detect that the preview mode is enabled?

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#535]
I want to customize the `<Esc>` mappings on filesystem source so that when the preview mode is enabled, it will do `toggle_preview` to disable the preview. But when preview mode is not enabled, the neo-tree will get closed. So, as title.

**Comment by cseickel** [comment]
There is not a way to know at the moment, but I can add one.

**Comment by cseickel** [comment]
Yes it is. It has not been released yet though, it is still in `main`.
