### ISSUE TITLE
What's the name of the highlight group on the right of neo-tree's border?

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#536]
(**update**: Actually, I'm not sure whether this is related to neo-tree or not now..., still trying to find the culprit.)

As title. These are the facts I found:

1. It only happens on the first buffer after neovim started and I start to move the cursor.
2. Or after I change the colorscheme by shortcut.
3. Or after I exit command mode(`:`).
4. To get rid of it, I need to call `:e` after toggling neo-tree several times. (See the demo below)

Intuition: it seems that the first file is implicitly seen as "git tracked file", but I don't track my `~/.config` with git. So this is strange.

<img src="https://user-images.githubusercontent.com/24765272/191502832-dbd751c8-0e5a-476a-b393-6c4bb85f2f1d.png" width="500">

And if I run this command: `:hi clear GitSignsAdd` it becomes grey. But I want to remove it totally(i.e. make it transparent):

<img src="https://user-images.githubusercontent.com/24765272/191503337-f78c58cd-e44c-469c-a960-5e7e53272a36.png" width="500">

https://user-images.githubusercontent.com/24765272/191510271-91fbd269-1b0d-4c47-9555-1c51110284ce.mov

**Comment by nyngwang** [comment]
OK, it seems that I just found an important clue: It's because I start neovim on the path where the parent folder is tracked by git, i.e. I run the command `nvim ~/.config/...` on path `~/GitHub/NeoNoName.lua/...` and the folder `~/GitHub/` is where I used to clone my git-tracked projects.

**Comment by cseickel** [comment]
I use [gitsigns](https://github.com/lewis6991/gitsigns.nvim) and I think it works very well.

**Comment by nyngwang** [comment]
@cseickel Does it show the git-gutter/sign on the first opened file(this file is not on the same folder as cwd) when the path you start `nvim` is a git-tracked folder?

**Comment by cseickel** [comment]
> @cseickel Does it show the git-gutter/sign on the first opened file(this file is not on the same folder as cwd) when the path you start `nvim` is a git-tracked folder?

I don't think it matters if the file is in the cwd or not. As far as I know, it always works perfectly and accurately.
