### ISSUE TITLE
How to call a default mapping inside `event_handlers[0].handler`?

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#546]
That is, I want to enable the preview mode by default. The following way caused an error saying that the buffer is not modifiable. But if I call `vim.cmd('normal! P')` directly from command mode `:lua ...` when my cursor is at neo-tree buffer, it does work. So I think either I should use the `require('neo-tree.sources.common.preview')` way to call the `preview()`(but this way the `state` is missing) or the detection of event like "neo-tree buffer did get loaded" is needed?

And is it possible to return a string to my custom command defined under `commands`, so I can just use `handler = 'my_command'`?

```lua
event_handlers = {
  {
    event = 'neo_tree_buffer_enter',
    handler = function ()
      if not require('neo-tree.sources.common.preview').is_active() then
        vim.cmd('normal! P')
      end
    end
  },
},
```

**Comment by cseickel** [comment]
The trick is that you need to get the `state` first. This should work:

```lua
local state = require("neo-tree.sources.manager").get_state("filesystem")
state.commands.toggle_preview(state)
```

**Comment by nyngwang** [comment]
@cseickel The following are the modified codes and the new error:

```lua
{
  event = 'neo_tree_buffer_enter',
  handler = function ()
    local state = require('neo-tree.sources.manager').get_state('filesystem')
    if not require('neo-tree.sources.common.preview').is_active() then
      state.commands.toggle_preview(state)
    end
  end
},
```

```
Error in event handler for event neo_tree_buffer_enter[table: 0x01038c1f10]: ...rt/neo-tree.nvim/lua/neo-tree/sources/common/preview.lua:354: attempt to index field 'tree' (a nil value)
```

**Comment by cseickel** [comment]
I guess there is a timing issue there where the tree has not yet been created. You could try moving that same code to the `after_render` event. The only downside there is that it will also re-open the preview after every refresh. If what you want is to have preview mode always open, then that's perfect. 

If you want to have it open when the window is first created, but be able to turn it off later, then that will require a little more thought.

**Comment by mrbjarksen** [comment]
I've been trying to implement this for a bit and have encountered the same issue. The best solution I have found is to simply wrap the handler in a `vim.defer_fn` call. It's not very clean though.

**Comment by nyngwang** [comment]
> If what you want is to have preview mode always open [...]

Yes. I think this is great :) Let me try it.

**Comment by cseickel** [comment]
If the goal is to have preview open with every new window, but allow it to be closed, the  I would start with the `neo_tree_after_open` event. Of course, the tree won't be created yet when that event fires, but you can then subscribe to the next `after_render` event from there with `once = true` in the event handler to just handle the very next firing of the event.

**Comment by nyngwang** [comment]
@cseickel a new error shown with `after_render`:

```
Error in event handler for event after_render[table: 0x0105304868]: ...rt/neo-tree.nvim/lua/neo-tree/sources/common/preview.lua:212: attempt to index field 'config' (a nil value)
```

**Comment by cseickel** [comment]
@nyngwang Sorry I missed that, you'll need to add the `config` table that is defined in the mapping to the state object:

```lua
{
  event = 'after_render',
  handler = function ()
    local state = require('neo-tree.sources.manager').get_state('filesystem')
    if not require('neo-tree.sources.common.preview').is_active() then
      state.config = { use_float = false } -- or whatever your config is
      state.commands.toggle_preview(state)
    end
  end
},
```

**Comment by nyngwang** [comment]
@cseickel: This one works :) Thank you a lot!

**Comment by msva** [comment]
@cseickel and what is a way to achieve that if:
1) neo-tree is started with node type of `directory` (well, it does it all the ways I use it, except if I call it like "Neotree %")
2) and (not sure if related) is configured to use "float" mode?

[This](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/sources/common/preview.lua#L355) line of code prevents preview to show on "directory" nodes, and "after_render" event only triggers once: when   neo-tree ends render the file tree.
So, there is no preview window appears, as node selected by default is directory.
And it will not appear even if I select file (as `after_render` doesn't trigger anymore)...

**Comment by cseickel** [comment]
@msva There is no preview for directory so it make sense to me. If you want to start with a preview open, the only logical thing to me is to open it with the `reveal` flag to show the current file so there is something to preview. You could also just find and select the first file in the tree in the `after_render` event, but that seems like like a lot of unnecessary work.

I don't think being in `float` mode makes any difference.

I suppose the code could be altered so that a preview window can be opened for a directory. In that case, the buffer shown would have to be a scratch buffer that shows a message or maybe some extra info about the directory. I would take a PR for that extra functionality if you were interested.
