### ISSUE TITLE
Bug with `barbar.nvim`

### ISSUE THREAD

**Issue by Iron-E** [nvim-neo-tree/neo-tree.nvim#551]
Hello,

I am one of the maintainers of [barbar.nvim](https://github.com/romgrk/barbar.nvim). One of our users is having an issue using the two of our plugins together (romgrk/barbar.nvim#277), and I believe I have tracked down the line of code causing the issue in https://github.com/nvim-neo-tree/neo-tree.nvim/commit/4ff628c1a7e3b368d91f3556423c5a9a7b810798.

It seems neo-tree is deleting and recreating buffers, which — while normally fine — is a problem when used in combination with our plugin because closing the buffer and re-opening it reorders the tabline. It is an admittedly workable bug, however, the user in question would like it to be fixed if possible. 

Unfortunately, we can't fix it from our side, because in subscribing to the events for closing and opening buffers, this operation is indistinguishable from a user doing the same thing. However if you believe I am missing something on our side, I'm certainly open to that idea.

**Comment by cseickel** [comment]
That code should only run if you try to open a file within neo-tree's window when it is in a sidebar. The best solution is to make sure that neo-tree is not active the window before opening a buffer.

If that's not possible, maybe using [eventignore](https://neovim.io/doc/user/options.html#'eventignore') would work around the problem? I would apply it before the code you removed in neo-tree and see if that fixes the issue. I haven;t used that before so i'm not sure if it's a one shot setting or you have to unset it after the event occurs.

**Comment by Iron-E** [comment]
> The best solution is to make sure that neo-tree is not active the window before opening a buffer.

Unfortunately, his use case is opening files from the tree rendered as a sidebar.

---

I'll play around with `eventignore`, thanks for the recommendation

**Comment by Iron-E** [comment]
Since the original author hasn't responded in a while, I'm going to close this as stale. It can always be reopened later.
