### ISSUE TITLE
Changes for v3.0

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#555]
It's time for a 3.0. This issue will be used to keep track of the changes planned or made for that release:

## Breaking Changes

- [ ] #1027
- [ ] #1028
- [ ] #1031
- [ ] #1032
- [ ] #1029

## Other Changes
- [ ] #1030

**Comment by Lazerbeak12345** [comment]
(feature request) could the default icons be made to be the Nerd Font v3 icons in neo-tree.vim v3? (see readme for what I'm talking about)

**Comment by cseickel** [comment]
@miversen33 @nhat-vo @pysan3 I think it's time to cut over to working on v3.0 now. I really want to get the nerd font icon changes out and since #1017 will have a new config migration it's enough to finally push me over the edge of getting this done. 

I think from here forward anything merged to `main` will be destined for the `v3x` branch and the next release we make will be `v3.0`. Also, once `3.0` is released, `main` will be the default branch.

Any comments or objections?

**Comment by miversen33** [comment]
@cseickel 
I think that is a great idea :) I know @nhat-vo  and @pysan3  spend more time working on the fancy new things, I just poke the borked shit ;) But still, I think moving forward is a good idea. Might be worth setting up a milestone and pinning issues to it so we have a general idea of what work we want to do for v3.x?

**Comment by pysan3** [comment]
Totally agree. Let me just finish #1017 before the upgrade but other than that, I think it's a good time to upgrade. 

I agree with making a milestone and I want @cseickel to actively distribute the feature requests into those milestones (v3.x, v4.x, or otherwise, never-implement) since we have a growing number of `enhancement` issues piling up with no hope of being addressed.

**Comment by cseickel** [comment]
Sure, I can make a milestone for v3.0. I don't think we need milestones for future versions though because we only get a new major version number when breaking changes are needed. 

Outside of that it's just a new minor version on every release, and I release every time we have new changes that have had some completely arbitrary amount of time sitting in main. Honestly, it's not completely arbitrary, I make judgment calls based on how long I think it should take to get bug reports on a given set of changes if there are any bugs to be found.

This all means that nothing is planned for v4 yet and there's no way we would ever think ahead more than one major version.

**Comment by cseickel** [comment]
I'm closing this issue now that it has been converted to a milestone.

**Comment by pysan3** [comment]
We may want to unpin this from the issue tab as well @cseickel?

As well as #486? tho I'm not sure why it's pinned in the first place.

**Comment by cseickel** [comment]
I don't actually remember why "Extract git module into separate library? #1032" exists. I'm going to just close it. If anyone else remembers what this is, let me know.

**Comment by cseickel** [comment]
> As well as #486? tho I'm not sure why it's pinned in the first place.

I think I pinned it because enough people asked that I got sick of answering it. I think we can unpin both though.
