### ISSUE TITLE
NeoTreeFileNameOpened hightlight option doesn't seem to work

### ISSUE THREAD

**Issue by emxxjnm** [nvim-neo-tree/neo-tree.nvim#556]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54089360/194209918-e0910b97-7c84-43bc-8afa-fdf45c42efa5.png">

**Comment by cseickel** [comment]
That's right, as it says in `:help neo-tree-highlights`:

```
NeoTreeFileNameOpened     File name when the file is open. Not used yet.
```

I think you are the first to actually ask for this feature.

**Comment by zach-wahrer** [comment]
This would be an awesome feature to see implemented. Really the only thing I'm missing with neo-tree.

**Comment by pysan3** [comment]
Closing with #838.
