### ISSUE TITLE
Question: is it possible to select the window?

### ISSUE THREAD

**Issue by Integralist** [nvim-neo-tree/neo-tree.nvim#559]
👋🏻 

I'm migrating from nvim-tree and one feature I like is that when I have multiple splits open, or I'm going to open a file (from the tree view) into a split, then nvim-tree will ask me which window it wants me to open the file, or which window to make a new split.

In neo-tree it looks like it just chooses the last active window.

Is there a way to make it behave similar to nvim-tree or would this be a feature request?

Many thanks!

**Comment by lopi-py** [comment]
Yes, just check the [example config](https://github.com/nvim-neo-tree/neo-tree.nvim/#quickstart):
```lua
use {
  "nvim-neo-tree/neo-tree.nvim",
  branch = "v2.x",
  requires = { 
    "nvim-lua/plenary.nvim",
    "kyazdani42/nvim-web-devicons", -- not strictly required, but recommended
    "MunifTanjim/nui.nvim",
    {
      -- only needed if you want to use the commands with "_with_window_picker" suffix
      's1n7ax/nvim-window-picker',
      tag = "v1.*",
      config = function()
        require'window-picker'.setup({
          ... -- for full config see: github.com/s1n7ax/nvim-window-picker
        })
      end,
    }
  },
  config = function ()
    require("neo-tree").setup({
      window = {
        mappings = {
          ...
          ["w"] = "open_with_window_picker",
          ...
        }
      },
    })
  end,
}
```

**Comment by Integralist** [comment]
Perfect thanks!
