### ISSUE TITLE
Question: is it possible to find file within the tree via the active window/buffer?

### ISSUE THREAD

**Issue by Integralist** [nvim-neo-tree/neo-tree.nvim#560]
👋🏻 

I'm migrating from nvim-tree and one feature I like is its `NvimTreeFindFile`. I'm not sure if there is something similar in neo-tree?

Also, is it possible to re-home the local working directory? For example, it's very common for me to be in a random directory and then I'll directly open up a file from another project like so...

```
nvim ~/.config/nvim/init.lua
```

Now what I then need to do is change the root of the project to be (in this example) `~/.config/nvim` so I'll run `:lcd ~/.config/nvim` but that's kinda tedious as I have to retype the path (OK it's not a long path, but that's just this particular example). Also, and more problematically, this doesn't update neo-tree when I open it, which will be the directory my shell is currently in. I'm wondering if there's any way to re-home to the currently active file?

Many thanks!

**Comment by cseickel** [comment]
We call that feature `reveal`, the command you probably want is ':Neotree reveal_force_cwd`.

See https://github.com/nvim-neo-tree/neo-tree.nvim#the-neotree-command for more information  about the `Neotree` command and all of the available options.

**Comment by Integralist** [comment]
That works great. Thanks!
