### ISSUE TITLE
Doesn't detect `modified` if the tree is closed

### ISSUE THREAD

**Issue by lopi-py** [nvim-neo-tree/neo-tree.nvim#561]
if you have a file open and modifiy it while keeping the tree open, it will detect it as modified. but if the tree is closed when file is being modified and the tree is opened, it won't detect it as modified

**Comment by cseickel** [comment]
I think this has been fixed as a side effect of fixing something else in the events system. Can you confirm?

**Comment by nhat-vo** [comment]
This has been inactive for a while, so I'll close it as solved.
