### ISSUE TITLE
Clickable filesystem source winbar component closes neo-tree immediately

### ISSUE THREAD

**Issue by axieax** [nvim-neo-tree/neo-tree.nvim#565]
Clicking the filesystem source in my neo-tree winbar seems to instantly close the neo-tree buffer. Other components seem to not have this issue when clicked.
Note: navigating between sources with `<` and `>` still works as intended.

Config: https://github.com/axieax/dotconfig/blob/4870bba67f90f068f9e01dae547c49d1c0cbadb2/nvim/lua/axie/plugins/neotree.lua

**Comment by cseickel** [comment]
This happens for me as well. I'll take a look.

**Comment by cseickel** [comment]
I think @pysan3's commit fixes this issue. It is in `main` now and will go out in the next release.

**Comment by axieax** [comment]
Sounds good! Thanks @cseickel and @pysan3 :))
