### ISSUE TITLE
move between tabs with keyboard

### ISSUE THREAD

**Issue by azinsharaf** [nvim-neo-tree/neo-tree.nvim#566]
how can we move between these 3 tabs with keyboard?
![image](https://user-images.githubusercontent.com/10101468/195727751-db58a33b-ff8d-4e2a-af72-850793ea28c6.png)

**Comment by lopi-py** [comment]
try `<` and `>`

**Comment by azinsharaf** [comment]
yes, it works! Thanks.

**Comment by cseickel** [comment]
Thanks for the assist @lopi-py!
