### ISSUE TITLE
Error when opening file with existing swapfile when using windowpicker

### ISSUE THREAD

**Issue by oddlama** [nvim-neo-tree/neo-tree.nvim#567]
Opening a file for which you will be asked to open as readonly, delete swapfile, open readwrite, causes an error in neo-tree. The file is still opened as expected, but you have to dismiss the error message.

To reproduce:
1. Keep a file open in a secondary nvim instance
2. Start a new neovim and select the file in neo-tree
3. Answer neovim's builtin message window to open the file (e.g. select open as readonly)
4. select a window to open it in with the window-picker
5. experience the error message and dismiss it (the file is then opened as expected)

This is the message:

```
E5108: Error executing lua: ...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:633: Vim(edit):E325: ATTENTION
stack traceback:
        [C]: in function 'cmd'
        ...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:633: in function 'open_file'
        ...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:482: in function 'open'
        ...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:515: in function 'open_with_cmd'
        ...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:640: in function 'open_with_window_picker'
        ...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:193: in function 'func'
        .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:708: in function <.../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:706>

**Comment by cseickel** [comment]
I think the latest commit in `main` fixes this problem. Can you give it a try and let me know?

**Comment by oddlama** [comment]
Sorry, the bug still occurs. What's changed is that the message appears one step later now. Before the order was the following:
1. open file
2. answer neovim message
3. error
4. pick window
5. file opened

Now:
1. open file
2. answer neovim message
3. pick window
4. error
5. file opened

The message is slightly different due to changed line numbers:

```
E5108: Error executing lua: ...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:644: Vim(edit):E325: ATTENTION
stack traceback:
        [C]: in function 'cmd'
        ...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:644: in function 'open_file'
        ...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:493: in function 'open'
        ...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:526: in function 'open_with_cmd'
        ...t/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:657: in function 'open_with_window_picker'
        ...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:193: in function 'func'
        .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:708: in function <.../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:706>
```

**Comment by cseickel** [comment]
Sorry about that, the fix was incomplete before. Can you try again?

**Comment by oddlama** [comment]
Now it works, thanks for fixing! :)
