### ISSUE TITLE
We need this.

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#572]
VSCode has https://github.com/tonybaloney/vscode-pets. And I just saw [a thread from reddit](https://www.reddit.com/r/neovim/comments/y68su4/do_we_have_something_similar_to_vscodepets/) discussing it. If it is possible, could you please make it happen?

![screenshot](https://github.com/tonybaloney/vscode-pets/raw/master/screenshots/screenshot.gif)

**Comment by Shougo** [comment]
why the feature is requested to the plugin?

**Comment by cseickel** [comment]
Definitely not for me.
