### ISSUE TITLE
Custom integration components ignored on render

### ISSUE THREAD

**Issue by miversen33** [nvim-neo-tree/neo-tree.nvim#578]
Heyo! I am working through the integration of Netman, and I am running into a UI problem that I am sure is just me not quite understanding the UI pieces of Neo-tree.

To avoid issues, I have pushed my current work to a branch on Netman, it can be found [here](https://github.com/miversen33/netman.nvim/tree/9c3b33a5a54f5e3f8bfe578bcc91d67fa78c707e/lua/netman/ui/neo-tree)

To use this, I have the following code in my `neo-tree` setup
```lua
  neo_tree.setup({
      sources = {
        "netman.ui.neo-tree",
     }
  })
```

I can do pretty much everything needed, commands appear to be working, I can see the proper navigation steps in netman. The only thing catching me up is that I cannot for the life of me get the components to render properly. This is what I am seeing currently when I run the command `:Neotree remote`
![Screenshot_20221023_140528](https://user-images.githubusercontent.com/2640668/197410800-c0acbc68-1b20-45d3-924f-a161685ef5a9.png)

[Per my Component](https://github.com/miversen33/netman.nvim/blob/9c3b33a5a54f5e3f8bfe578bcc91d67fa78c707e/lua/netman/ui/neo-tree/components.lua) (if I am reading how to do components right), I should only see the text `"IS TEST"` but I am instead seeing the type of the component followed by the name of the component. 

I can verify that if I specify my components in my setup it "works", but that is obviously not desirable. I can also confirm that Neo-tree is infact sourcing my components module (through various logging and object reflection shenanigans). But when it comes time to render, it is seemingly ignoring the components. What am I missing?

**Comment by miversen33** [comment]
To avoid people having to dig through my codebase, here are the relevant files
[`init.lua`](https://github.com/miversen33/netman.nvim/blob/9c3b33a5a54f5e3f8bfe578bcc91d67fa78c707e/lua/netman/ui/neo-tree/init.lua#L102-L160)
[`commands.lua`](https://github.com/miversen33/netman.nvim/blob/9c3b33a5a54f5e3f8bfe578bcc91d67fa78c707e/lua/netman/ui/neo-tree/commands.lua)
[`components.lua`](https://github.com/miversen33/netman.nvim/blob/9c3b33a5a54f5e3f8bfe578bcc91d67fa78c707e/lua/netman/ui/neo-tree/components.lua)

**Comment by cseickel** [comment]
It could be that this is happening because you don't have a default config. See this for an example:

https://github.com/mrbjarksen/neo-tree-diagnostics.nvim/blob/main/lua/neo-tree/sources/diagnostics/defaults.lua

and:
https://github.com/mrbjarksen/neo-tree-diagnostics.nvim/blob/137ba57620249cebf3c756bf3aed2367faa77985/lua/neo-tree/sources/diagnostics/init.lua#L198

**Comment by miversen33** [comment]
@cseickel that might be it! I added a default config section and now _name_ is being called! If I have more issues I will open another issue, but I think that hit it on the head :)

![Screenshot_20221023_193615](https://user-images.githubusercontent.com/2640668/197426579-447fa445-def1-4281-9e2c-35e6a8fbdbf6.png)

**Comment by miversen33** [comment]
I'm closing in on complete with this. I really appreciate your help so far with my integration questions :) Here's a little sneak peak of how it looks (I need to clean up how docker is displaying a bit)

![Screenshot_20221023_211636](https://user-images.githubusercontent.com/2640668/197435777-d92d003a-b1f3-49e5-a409-6e46fb283d3f.png)

**Comment by cseickel** [comment]
That is really awesome! I can't wait to have docker and ssh browsing in the tree!

**Comment by miversen33** [comment]
I really appreciate the framework you provided :) I could see a ton of uses with this with Netman on basically any remote "tree" structure. I have someone queued to migrate their S3 plugin to Netman once I get this done and it should just automagically work in Neo-tree :)

You're awesome and I think this will be really exciting once I get it complete. That said, I would _love_ to turn over the integration bit of this to the Neo-tree team once I get it complete as I dont know that I can keep up with the various ui tools to ensure proper integration long term. Whats your thoughts on me turning over the integration code to Neo-tree as a core source?

**Comment by cseickel** [comment]
This is probably big and complicated enough that it makes sense to be an optional external source. TBH, I don't have a lot of time for maintenance either and there isn't an official team yet. I do think I will start looking for more maintainers to help out soon though.

One thing I would suggest is that you could release it under the `nvim-neo-tree` organization instead of your personal account. That way it's easier to pass off maintenance to others later. At that point, I will either maintain it myself or solicit help.

**Comment by miversen33** [comment]
That makes sense to me. Obviously short term this will live under the netman umbrella with some instructions on how to use it as an external source in neo-tree.

I am not familiar with Github organizations so I am not exactly sure how I would go about releasing the integration code under the org, but thats down the road enough that once I get to that point (where the integration code is stable and I am ready to move onto another integration/project), I will reach out :)

Thank you for your help on this adventure!

**Comment by oddlama** [comment]
@miversen33 Wow thanks for making this! I have been searching for something like this for at least a decade. Is there somewhere I can watch for updates on the matter? I'd love to try this as soon as it is somewhat working :P

**Comment by miversen33** [comment]
@oddlama  sure! I haven't opened a new PR for this yet, but check out [v1.1 of netman](https://github.com/miversen33/netman.nvim/tree/v1.1)

I am working on the finishing touches for a beta for this right now :) Also follow the subreddit /r/neovim, I post my updates there as well.
