### ISSUE TITLE
Icon meanings?

### ISSUE THREAD

**Issue by Integralist** [nvim-neo-tree/neo-tree.nvim#581]
👋🏻 

Sorry if this is documented somewhere but I searched the README, the wiki and also the neovim help files and still couldn't find any info on the icons used.

For example, what do these means?

<img width="58" alt="Screenshot 2022-10-24 at 14 46 37" src="https://user-images.githubusercontent.com/180050/197540935-9c080035-0e72-45c0-a5ed-8bba904a652f.png">

I'm pretty sure the dot is a modified file, but the first and last icon I'm not sure what they're indicating.

Thanks.

**Comment by cseickel** [comment]
The first icon is from lsp diagnostics and it means there are warnings for that file coming from lsp. That icon is determined by you somewhere in your config. If you copy and pasted your neo-tree config from the Quickstart in the README, it included a command to configure those diagnostics icons in neovim.

The second and third icons are for git and are configurable within your neo-tree config. They mean that the file is modified and unstaged. You can see all of the default values in:
```
:h neo-tree-git-status
```

**Comment by Integralist** [comment]
Thanks 👍
