### ISSUE TITLE
Retrieve selected path to use in script

### ISSUE THREAD

**Issue by mriva** [nvim-neo-tree/neo-tree.nvim#585]
I want to run a telescope command limited to the path currently selected in neo-tree, is there a way to get the value of the selected path (a variable or function) that can be used in a script?

I used to do this in NERDTree with:

```
local selected_dir = vim.api.nvim_eval('g:NERDTreeDirNode.GetSelected().path.str()')
```

but I can't find anything similar in neo-tree

**Comment by cseickel** [comment]
Sorry for the long delay. If you want to get the path of a `filesystem` tree loaded as a sidebar, you can use this:

```lua
require("neo-tree.sources.manager").get_state("filesystem").tree:get_node().path
```

**Comment by mriva** [comment]
Thanks, is there a way to tell if the selected node is a file or a directory?

**Comment by cseickel** [comment]
> Thanks, is there a way to tell if the selected node is a file or a directory?

Yes. `get_node()` returns an object that represents the node with lots of relevant properties:

```lua
local node = require("neo-tree.sources.manager").get_state("filesystem").tree:get_node()
if node.type == "directory" then
  print(node.path)
else
  print("Not a directory")
end if
```

If you want to get real fancy and find the parent directory of any node you can reuse this function:
```lua
---Gets the node parent folder recursively
---@param tree table to look for nodes
---@param node table to look for folder parent
---@return table table
local function get_folder_node(tree, node)
  if not node then
    node = tree:get_node()
  end
  if node.type == "directory" then
    return node
  end
  return get_folder_node(tree, tree:get_node(node:get_parent_id()))
end

local tree = require("neo-tree.sources.manager").get_state("filesystem").tree
local dir = get_folder_node(tree)
print(dir.path)
```

**Comment by mriva** [comment]
Thanks a lot, that was exactly what I needed.
Btw awesome plugin.

**Comment by cseickel** [comment]
> Btw awesome plugin.

Thanks!

**Comment by Townk** [comment]
Sorry to revive this bug, but I tried to use this on my config today and found a crash. Basically, the first time I open NeoTree everything works as expecte, but onthe second time it crashes saying that is expects the `winid` to be a number.

I can share all the details, but maybe there is some new way to get the selected node from NeoTree?
