### ISSUE TITLE
How do I update (add node to or change the text of) an existing tree?

### ISSUE THREAD

**Issue by miversen33** [nvim-neo-tree/neo-tree.nvim#587]
This is a bit more complex question that is likely targeted at @cseickel 

When generating a tree, it appears that I can simply call `require('neo-tree.ui.renderer').show_nodes()` and the Neo-tree Renderer does its thing. This is fantastic, however I am struggling to figure out how to add new nodes to a tree _without_ creating my own subsequent [NuiNodes](https://github.com/MunifTanjim/nui.nvim/tree/main/lua/nui/tree#nuitreenode). It appears that the renderer actually has a function inside of it that is called during the `show_nodes` call to generate an appropriate NuiNode (including calling out to my custom components) for each item that is provided to it. However this [create_nodes](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/b13425d57111a7885961110f8e51907fa630642b/lua/neo-tree/ui/renderer.lua#L182-L280) function is (as far as I can tell) not exposed and thus not accessible.

The main crux of my issue is that I can add and remove nodes just fine, however I cannot figure out how to add new nodes to an existing tree without completely reimplementing the component process that Neo-tree uses. I am certain I am just missing something, but when trying to dig through the `filesystem` source code (as that is the closest thing to Netman in regards to a source), its a bit to complex for me to fully figure out how this "update node" process is working.

For context, I am currently being tripped up on the `Refresh` process. I can do everything needed within my source, but I am struggling to figure out how its expected to cleanly update the UI to reflect whatever changes have been made to the source.

**Comment by miversen33** [comment]
For reference, The main issue I am having is the below exampl
```
Tree Head
| _ Tree Child 1
| _ Tree Child 2
```

If I have this tree, how do I _add_ `Tree Child 3` to it without completely regenerating the Tree? Or am I expected to regenerate the entire tree?

EG
```
Tree Head
| _ Tree Child 1
| _ Tree Child 2
|_ * (New Node) Tree Child 3
```

**Comment by cseickel** [comment]
I'm on my phone so I can't reference the code, but I'm pretty sure that show_nodes takes an argument for parent_id. If that is provided then the nodes you pass in are added as children of the node with that id.

**Comment by miversen33** [comment]
It certainly does and that works great for nesting nodes under a leaf. However (and I could be doing it incorrectly), it _appears_ to cause the tree to rerender _all_ items? IE, if I want to use the `show_nodes` function with a parent ID, I will need to recreate all the node tables for the function to then recreate all the nodes rendered? 

A side note (and a very simple example to illustrate what I am getting hung up with), is how the filesystem executes single node update after a `rename`. That is really the crux of what is tripping me up. I was able to trace this rename/refresh through the code until eventually I get lost in the abstraction of contexts and such.

If you rename a file in filesystem, it appears to refresh that single node, updating its text and icon (I assume this is done via a re-render of that single component). I don't know how that is being done and its the exact behavior I am looking for.

**Comment by cseickel** [comment]
The tree does technically re-render on every change, but it's really not that much work to do so so long as you do not have 10,000 items visible.

Most actions, like renames or file watcher events, just reload the entire tree. In your case, I assume it;s much slower to load that state through ssh or docker than it would be for the local filesystem. I would suggest that maybe you keep your own internal state of a filesystem and update that incrementally, but let Neo-tree just request the whole thing when it updates to keep things simple.

**Comment by miversen33** [comment]
I was afraid that was going to be the answer. I like easy work lol I was hoping there was just something I was missing. That's ok though :) I will work through the internal state tracking (I was kinda working through that already but wasn't completely sure if that was the right route to take).

I appreciate you :) I think we can call this good, I'm closing this out.
