### ISSUE TITLE
`dir` option not working for `git_status`

### ISSUE THREAD

**Issue by K1DV5** [nvim-neo-tree/neo-tree.nvim#588]
I know it's mentioned in the docs, but...why not?

**Comment by cseickel** [comment]
It doesn't make sense to me. Why would you only want to see the changed files in a sub-directory?

**Comment by K1DV5** [comment]
Seeing changes in a sub directory is not the only use case for the option. I for instance currently use `neogit` and asked the same question there because sometimes I need to edit my neovim config while I'm working on my main project. So I open the config, edit it and when I open the `neogit` status, I see the status of my config repo because the current file belongs to that repo, not my project repo.  Then I commit and push my changes, close the status buffer, and I'm back at my project.

So what I'm asking is to choose a directory and for `neo-tree` choose the repo based on the given path: the repo at the directory itself or its closest ancestor repo.

**Comment by cseickel** [comment]
Neo-tree will actually use the current working directory, so if you are using it as a sidebar or float, you can 
```
:tcd the/dir/you/want
``` 
or 
```
:cd the/dir/you/want
```

If you are using it with `position=current`, then it uses the window's working directory so 
```
:lcd the/dir/you/want
```
would have the desired effect.

Of course, if you are using a plugin that automatically changes the working directory to match the file you are focused on, that's the entire source of your problems with both neo-tree and neogit. If you get rid of that, this would work the way you want it to without having to fix your working directory.

**Comment by K1DV5** [comment]
Fair enough, thank you for the explanation. Closing.
