### ISSUE TITLE
Slow working

### ISSUE THREAD

**Issue by IcyKit** [nvim-neo-tree/neo-tree.nvim#592]
NeoTree creates and deletes a file for 15 seconds, sometimes it goes up to 30 seconds. After that, the whole NeoVim starts to freezing terribly.

Example in video
https://user-images.githubusercontent.com/84917134/200032040-0f40f068-8707-418c-9e77-a0b8ea20b342.mp4

**Comment by pysan3** [comment]
Could you give me your config file?
Especially what do you have for `filesystem.async_directory_scan`?

Besides, is running a command `:lua =vim.fn.system({ "echo", "true" })` slow on your system?

**Comment by IcyKit** [comment]
I found the source of the problem. The plugin was very slow due to the fact that there was a Git file in the home directory with a huge number of changes. I don't know where it came from, but after removing it, everything began to work fine
