### ISSUE TITLE
Improve documentation (suggestions welcome)

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#60]
Basic usage is OK, but we need much better documentation on how to customize Neo-tree.  I think the wiki is the place for this.

Things to document include:

- [x] Basic overview of all the ways it can be customized, with example use cases for each one
- [x] List all built-in components along with their config options
- [x] Full explanation of components and renderers
- [x] Full explanation of mappings to custom functions (or defining commands)
- [x] Full explanation of events (the vim doc is pretty good, maybe just copy to the wiki)
- [x] Add some Recipes for custom components
- [x] Add some Recipes for mapping to a custom function
- [x] Add some recipes for event_handler usage
- [x] LINK TO THE WIKI IN THE README!
- [x] Remove README in `lua/sources/filesystem`, it's just a maintenance problem

If there is anything else you feel needs to be added or have any ideas at all on this subject, please add a comment. Also, if anything here seems like a particular priority, let me know what you think that order should be.

**Comment by levouh** [comment]
I think using [md2vim](https://github.com/FooSoft/md2vim) would make this super easy, as you get "viewable" markdown files for those using the web, and direct translation into Vim help docs with zero effort.

**Comment by cseickel** [comment]
I think that is a great idea @levouh !
