### ISSUE TITLE
How can i set the tree position

### ISSUE THREAD

**Issue by louisrc3ys** [nvim-neo-tree/neo-tree.nvim#603]
![image](https://user-images.githubusercontent.com/71259902/201249517-8517c67c-5acd-4885-9f67-92de815ac363.png)

I want to display in top right corner, but i cannot to find it to help

**Comment by louisrc3ys** [comment]
I need to go to a specific size of a certain piece, not the whole column

**Comment by cseickel** [comment]
Sorry, that's not an option. You could always just map a command to open it then `:split` it and put whatever you want below.

**Comment by louisrc3ys** [comment]
> Sorry, that's not an option. You could always just map a command to open it then `:split` it and put whatever you want below.

Oright, Could  change the position or size of the float mode？

**Comment by cseickel** [comment]
Yes: https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Visual-Customizations#floating-window-settings

**Comment by louisrc3ys** [comment]
> Yes: https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Visual-Customizations#floating-window-settings

Thank you very much!

**Comment by cseickel** [comment]
I'm going to close this because I think the floating options fit your needs, and I am not going to add a position which would be just the top half of a sidebar.

If anything was added, it would be something like #360

**Comment by louisrc3ys** [comment]
> I'm going to close this because I think the floating options fit your needs, and I am not going to add a position which would be just the top half of a sidebar.
> 
> If anything was added, it would be something like #360

![image](https://user-images.githubusercontent.com/71259902/201566039-0aa1216a-34f9-4765-b88f-6ffc04103392.png)
Perfect!
