### ISSUE TITLE
`close_if_last_window` causes error when closing an unsaved new file

### ISSUE THREAD

**Issue by mehalter** [nvim-neo-tree/neo-tree.nvim#605]
I am getting some weirdness where if I have `close_if_last_window = true` and I have a new, unsaved file and run `:q` it causes a bunch of weirdness. It should just show an error that the file has not been saved, but I think `neo-tree` thinks it should be closed. This causes some weird error and then it closes itself.

Error before `neo-tree` closes:

```
[Neo-tree ERROR] Error in event handler for event vim_win_enter[neo-tree-win-enter]: ...k/packer/start/neo-tree.nvim/lua/neo-tree/setup/
init.lua:228: Vim(quit):E37: No write since last change
```

### Minimal `neo-tree` Configuration

To replicate this, you just need to have `close_if_last_window = true` when setting up `neo-tree`.

### Recordings

Vanilla Neovim (`vim -u NONE`): https://asciinema.org/a/ygkRP7mowPqcTVooRcgOyoPsx

With stock Neovim with just Packer and neo-tree: https://asciinema.org/a/QJIXtDwAWzsrOMKB1owOzLdTo

### Minimal `init.lua` File

Here is the `init.lua` file that I used to test this:

```lua
-- Minimal init file to run neo-tree with the most basic functionality
-- Run from top-level directory using:
-- nvim --noplugin -u minimal_init.lua

local function load_plugins()
	local packer = require("packer")
	local use = packer.use

	packer.reset()
	packer.init({
		git = {
			clone_timeout = -1,
		},
	})

	use("wbthomason/packer.nvim")
	use({
		"nvim-neo-tree/neo-tree.nvim",
		branch = "v2.x",
		requires = {
			"nvim-lua/plenary.nvim",
			"kyazdani42/nvim-web-devicons",
			"MunifTanjim/nui.nvim",
		},
	})

	packer.sync()
end

local function load_config()
	require("neo-tree").setup({
		close_if_last_window = true,
	})
end

local install_path = vim.fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"

vim.g.loaded_remote_plugins = 1

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
end

load_plugins()

vim.api.nvim_create_autocmd("User", {
	pattern = "PackerComplete",
	callback = load_config,
	once = true,
})
```

**Comment by cseickel** [comment]
Thanks @mehalter, this is an excellent bug report! Sorry it took me so long to respond. I'll take a look now.

**Comment by zesty39** [comment]
hello, i get same error when closing existed file without saving

![neo-tree](https://user-images.githubusercontent.com/115854501/231720377-6c88432d-e39e-4936-9057-28124945ccb4.gif)
