### ISSUE TITLE
Feature request: Show relative line numbers in the neotree file listing

### ISSUE THREAD

**Issue by robin-randhawa-sifive** [nvim-neo-tree/neo-tree.nvim#608]
Hi.

I tried to check if this was already asked for and I think it wasn't but please bear with me if it was.

I'm a recent NERDTree to Neo-tree convert. With the former I use relative line numbers extensively to jump to the point of interest in large file/dir listings (eg while working on the Linux kernel source).

If this is not already supported, would it be possible to add it ?

Many thanks for an excellent tool!

**Comment by gregdezeeuw** [comment]
Adding the following to your config should work.
```
require("neo-tree").setup({
  event_handlers = {
    {
      event = "neo_tree_buffer_enter",
      handler = function(arg)
        vim.cmd [[
          setlocal relativenumber
        ]]
      end,
    }
  },
```

**Comment by robin-randhawa-sifive** [comment]
Works like a charm! Thank you!!!

**Comment by lu5her-s** [comment]
How to set in lazy
