### ISSUE TITLE
Diagnostics error while editing buffer

### ISSUE THREAD

**Issue by happenslol** [nvim-neo-tree/neo-tree.nvim#615]
I'm intermittently getting the following error while I'm editing a buffer with lsp/diagnostics enabled:

```
Error detected while processing function targets#e[10]..<SNR>60_getKeyAsStr:
line    3:
[Neo-tree ERROR] Error in event handler for event vim_diagnostic_changed[filesystem.vim_diagnostic_changed]: ...im/site/pack/packer/start/nui.nvim/lua/nui/tree/init.lua:456: E565: Not allowed to change text or change window
```

The only time I've noticed it happening is when I'm issuing text object commands (like `ciw` or `cit`), I haven't been able to narrow down in which specific cases it happens. The error pops up after `ci` and before I input the text object.

The other notable thing is that highlighting is turned off in the neo-tree window right after the error occurs, but turns back on as soon as I make another edit in the buffer.

**Comment by cseickel** [comment]
Something probably needs to be `vim.schedule`d here. In the mean time, if you turn off updating diagnostics in edit mode, it will probably fix the problem.

```lua
      vim.diagnostic.config({
        update_in_insert = false,
      })
```
