### ISSUE TITLE
[Feature request] Update imports for the file after file is renamed

### ISSUE THREAD

**Issue by sidlatau** [nvim-neo-tree/neo-tree.nvim#623]
## Problem:
I am using this plugin for file rename/move operations. I would want to integrate these operations with LSP. Some LSP servers support functionality to update imports after the file is renamed or moved. Client sends [workspace/willRenameFiles](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_willRenameFiles) notification to LSP, which returns import changes. [dartls](https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/tool/lsp_spec/README.md) supports this notification. I want a hook to file rename flow to be able to call LSP and apply returned results.

## Possible implementation:
It would be nice to be able to setup this hook in neo-tree, possible implementation: 
https://github.com/nvim-neo-tree/neo-tree.nvim/compare/v2.x...sidlatau:neo-tree.nvim:update-imports?expand=1

Then user needs to setup this hook:
```lua
neo_tree.setup {
    ...
    hooks = {
      on_rename_file = function(data)
        ("dart-lsp-refactorings").on_rename_file(data)
      end,
    },
}
```
where data is:
```lua
{
  source= "/path_to_source",
  destination = "/path_to_destination",
  callback = function()
    -- Function called to finish rename process
  end
}
```

## Alternatives tried:
I tried to use events infrastructure in `neo-tree`, added new `WILL_FILE_RENAME` event, but problem with them is that they does not block a flow. When request reaches LSP about renamed file, server returns empty results, I suspect file is already renamed and server does not see it. In above provided solution I can control when actual rename occurs.

I think several such hooks could be useful - for file rename, file move, maybe even for operations with folders.

Would it be feasible to add such hooks to `neo-tree`?
I may create PR then.

**Comment by cseickel** [comment]
I have been using the technique linked to in this comment: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/308#issuecomment-1304765940

It works great for me. I'm sure you can adjust that for other languages.

**Comment by cseickel** [comment]
Sorry, wrong button. I didn't mean to close it!

**Comment by sidlatau** [comment]
Nice solution, but I think that only works for typescript. `_typescript.applyRenameFile` is not a standard LSP command, I am unable to find an exact replacement in LSP specs.
I am getting an error when trying this:
```
ERROR dartls: -32005: workspace/willRenameFiles is not a valid command identifier 
```
Here is my implementation that works with `dartls`: https://github.com/sidlatau/dart-lsp-refactorings.nvim/blob/main/lua/dart-lsp-refactorings/rename-file.lua

But that needs changes in `neo-tree` codebase. I need to call LSP, apply changes, and only then rename/move the file.

**Comment by cseickel** [comment]
OK, I see. If you wanted to add the new event I would accept that as a PR. I think this would be the callback point:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/e00391097df82d246c75117cef4d7add864d4eaf/lua/neo-tree/sources/filesystem/lib/fs_actions.lua#L533

**Comment by sidlatau** [comment]
Not sure I understand what "callback point" means - is it an event with a callback? 
Either way, I created PR https://github.com/nvim-neo-tree/neo-tree.nvim/pull/625 as a starting point.

**Comment by mehalter** [comment]
It would also probably be a good idea to add similar events for `BEFORE_FILE_ADD` and `BEFORE_FILE_DELETE` as well since are similar LSP file operations like `willRenameFiles` there are `willDeleteFiles` and `willCreateFiles` that would be nice to be able to support with neo-tree events :)

Let me know if you think this should be opened as a new issue for a feature request or if here is more succinct rather than opening new issues.

Thanks for the initial `BEFORE_FILE_MOVE` and `BEFORE_FILE_RENAME` support @sidlatau !

**Comment by cseickel** [comment]
@mehalter it definitely should be a new issue to add the new events.
