### ISSUE TITLE
[Bug] - results from event handlers are not returned to the caller

### ISSUE THREAD

**Issue by sidlatau** [nvim-neo-tree/neo-tree.nvim#631]
I am registering a separate issue from https://github.com/nvim-neo-tree/neo-tree.nvim/pull/625#issuecomment-1328341370

I see there `for loop` was replaced with `foreach` function, but [`return`](https://github.com/nvim-neo-tree/neo-tree.nvim/commit/6dac7b5b46c27af921369dc5ea1390025f0e58ae#diff-b651c8a500ec9d637a451566ade44d8b291b3143dd5ab65e8fec66505b7b17cdL142-L144)  in lines L142-L144 now does not return from `fire_event_internal` as it was in the original implementation, but returns from the inner function of `queue:for_each(function(event_handler)`. 

 Link to the commit:
https://github.com/nvim-neo-tree/neo-tree.nvim/commit/6dac7b5b46c27af921369dc5ea1390025f0e58ae#diff-b651c8a500ec9d637a451566ade44d8b291b3143dd5ab65e8fec66505b7b17cdL124-R208

So now when I call:
```lua
    local event_result = events.fire_event(events.BEFORE_FILE_RENAME, {
      source = path,
      destination = destination,
      callback = fs_rename,
    }) 
```
I get `nil` value for `event_result`. Is this an intended behavior?

**Comment by cseickel** [comment]
> Is this an intended behavior?

No, certainly not. Any handlers that return a result with `{ handled = true }` should stop the loop and return that table to the `fire_event` caller. If that was changed then it is a bug that needs to be fixed.

I'll take a look at it.
