### ISSUE TITLE
Allow configuring winhighlight for popups

### ISSUE THREAD

**Issue by figsoda** [nvim-neo-tree/neo-tree.nvim#634]
It is already possible to configure borders, but it would be nice to be able to configure `NormalFloat` or `winhighlight` directly for popup windows as well:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/7c6903b05b13c5d4c3882c896a59e6101cb51ea7/lua/neo-tree/ui/popups.lua#L39

If someone gives me a green light, I can work on a pr for this

**Comment by cseickel** [comment]
More control over highlight groups would be good. Should the highlight group be named `FLOAT_NORMAL` to be consistent with `FLOAT_BORDER`?

**Comment by figsoda** [comment]
sounds like a good idea

**Comment by figsoda** [comment]
not sure why this wasn't automatically merged by github
