### ISSUE TITLE
bug: Component symlink_target not found.

### ISSUE THREAD

**Issue by pysan3** [nvim-neo-tree/neo-tree.nvim#635]
Hi, thank you as always for the awesome plugin.

I am having this error in `buffers` and `git` sources for quite a while but not sure if this is due to my bad configuration.

![image](https://user-images.githubusercontent.com/41065736/205286994-cf36bca0-83b1-4d5c-a9ec-fcde7334a410.png)

I know this is caused by what I pass to `setup()` but it is the taken from what is written as a comment in `defaults.lua`.

```lua
require("neo-tree").setup({
  renderers = {
    directory = {
      { "indent" },
      { "icon" },
      { "current_filter" },
      {
        "container",
        width = "100%",
        right_padding = 1,
        content = {
          { "name", zindex = 10 },
          {
            "symlink_target", -- ========= THIS CONTENT !!! =========
            zindex = 10,
            highlight = "NeoTreeSymbolicLinkTarget",
          },
          { "clipboard", zindex = 10 },
          { "diagnostics", errors_only = true, zindex = 20, align = "right" },
        },
      },
    },
    file = {
      { "indent" },
      { "icon" },
      {
        "container",
        width = "100%",
        right_padding = 1,
        content = {
          { "name", use_git_status_colors = true, zindex = 10 },
          {
            "symlink_target", -- ========= AND THIS CONTENT !!! =========
            zindex = 10,
            highlight = "NeoTreeSymbolicLinkTarget",
          },
          { "clipboard", zindex = 10 },
          { "bufnr", zindex = 10 },
          { "modified", zindex = 20, align = "right" },
          { "diagnostics", zindex = 20, align = "right" },
          { "git_status", zindex = 20, align = "right" },
        },
      },
    },
})
```

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/7c6903b05b13c5d4c3882c896a59e6101cb51ea7/lua/neo-tree/defaults.lua#L230-L272

## Possible Fix?

`M.symlink_target()` module is only defined in `neo-tree.sources.filesystem.components` which I believe should be placed in `neo-tree.sources.common.components` to fix this problem? (`filesystem` -> `common`)

**Comment by cseickel** [comment]
> `M.symlink_target()` module is only defined in `neo-tree.sources.filesystem.components` which I believe should be placed in `neo-tree.sources.common.components` to fix this problem? (`filesystem` -> `common`)

Yup, that would definitely fix it.

**Comment by pysan3** [comment]
Glad to hear that. May I hand it to you @cseickel to fix this because I'm quite busy right now?

**Comment by pysan3** [comment]
@cseickel Are you working on this?

If not, I am thinking of making a PR because I have spare time now.

**Comment by cseickel** [comment]
Nope, go for it @pysan3
