### ISSUE TITLE
[Bug] Rename `ai.lua` to `AI.lua` but it says `AI.lua` already exists.

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#638]
As title. Can reproduce it by title.

**Comment by korniychuk** [comment]
Notice: there are case-sensitive and case-insensitive file systems.
I also use case-sensitive fs to store the code base and `AI.lua` & `ai.lua` are different names in this case.

**Comment by cseickel** [comment]
I don't have this problem on linux. Could it be that there was a hidden file called AI.lua or maybe some other plugin causing the error?

**Comment by Shougo** [comment]
macOS X default file system is case-insentive.

https://www.macworld.com/article/233319/how-to-convert-a-case-sensitive-mac-hfs-partition-into-a-case-insensitive-one.html

**Comment by nyngwang** [comment]
I recently added these options:

```lua
vim.opt.ignorecase = true
vim.opt.smartcase = true
```

not sure whether or not related.

**Comment by cseickel** [comment]
Sorry to not respond for so long. I don't think there is anything I can do here. Neo-tree just relays your desired actions to whatever file system you are using. If the underlying file system is case insensitive, neo-tree can't do anything to change that.

**Comment by nyngwang** [comment]
@cseickel Thanks for your response. Maybe you're right but on my macOS if I have a file named `ai.lua`, then I can do:

```zsh
mv ai.lua AI.lua
```

without the error saying that `AI.lua` already exists:

<img src="https://user-images.githubusercontent.com/24765272/211311556-b48a2147-c95f-4caa-a808-6d36b64c7d12.png" width="300">
