### ISSUE TITLE
Is there a way I can detect if neo-tree is visible?

### ISSUE THREAD

**Issue by YuCao16** [nvim-neo-tree/neo-tree.nvim#639]
I'm switching from `nvim-tree` to `neo-tree` and rewrite some functions for `nvim-tree`. There is a `is_visible` function in `nvim-tree`, is there a similar function in `neo-tree`?

**Comment by nyngwang** [comment]
Do you mean something like asking "Is neo-tree currently open?"? If so, I need this too.

**Comment by cseickel** [comment]
This should do it:
```lua
function is_neotree_open()
  local state = require("neo-tree.sources.manager").get_state("filesystem")
  return require("neo-tree.ui.renderer").is_window_valid(state.winid)
end
```

That works for a sidebar style tree in the current tab. If you want another tab, add the tab number as the second argument to `get_state`. If you want to know if there are any trees open in a split window style, it will need a few more lines to iterate over all possible states for the tab.

**Comment by nyngwang** [comment]
> That works for a sidebar style tree in the current tab. If you want another tab, add the tab number as the second argument to `get_state`.

Thanks a lot! In my case, I also need to check for all tabs. Really appreciate your maintaining of this plugin!

**Comment by cseickel** [comment]
Actually, @nyngwang's function from #651 is better than mine. Use that instead:
```lua
local function is_neotree_open()
  for _, win in ipairs(vim.api.nvim_tabpage_list_wins(0)) do
    if vim.api.nvim_buf_get_option(vim.api.nvim_win_get_buf(win), 'ft') == 'neo-tree' then
      return true
    end
  end
  return false
end
```

**Comment by cseickel** [comment]
Closing this as done, the above [comment](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/639#issuecomment-1345617435) is the optimal answer.

**Comment by airtonix** [comment]
Thanks @nyngwang 👍🏻 🤝 

```lua
return {
    'romgrk/barbar.nvim',
    dependencies = {
        'nvim-tree/nvim-web-devicons'
    },
    config = function()
        local filetreename = 'neo-tree'
        local function get_filetree_window()
            for _, windowId in ipairs(vim.api.nvim_tabpage_list_wins(0)) do
                local buffer = vim.api.nvim_win_get_buf(windowId)
                if vim.api.nvim_buf_get_option(buffer, 'ft') == filetreename then
                    return windowId
                end
            end
            return nil
        end

        local function get_filetree_width()
            local windowId = get_filetree_window()
            if windowId == nil then return end
            return vim.fn.winwidth(windowId)
        end

        vim.api.nvim_create_autocmd({ 'BufWinEnter', 'WinScrolled', 'BufWinLeave', 'BufWipeout' }, {
            callback = function()
                local width = get_filetree_width()

                require('bufferline.api').set_offset(width or 0)
            end
        })
    end
}
```
