### ISSUE TITLE
[Feature Request] Include quick cd functionality via z.lua

### ISSUE THREAD

**Issue by azolus** [nvim-neo-tree/neo-tree.nvim#640]
There is this amazing tool called [z.lua](https://github.com/skywind3000/z.lua), which keeps track of visited directories, and matches them against input RegExes, sorting by a mix of most often and most recently visited. This enables incredibly fast directory hopping between projects and could be very useful for quickly changing the tree-root.

**Comment by cseickel** [comment]
I use a version of that. There is nothing to integrate here. Unless you change the default settings, Neo-tree will follow your current working directory. There are already plugins that will change your working directory with z. Go ahead and use them and Neo-tree will update it's root to match.

I use https://github.com/nanotee/zoxide.vim myself.
