### ISSUE TITLE
[Cross-Plugins] Cannot work with session plugin projections.nvim

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#642]
As title. After restoring the session, some empty buffer(i.e. `[No Name]`) that is `nonmodifiable`, filetype `neo-tree`, buftype `nofile` causing error on `:Neotree toggle focus`:

```
Error executing vim.schedule lua callback: .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:874: Failed to rename buffer
stack traceback:
        [C]: in function 'nvim_buf_set_name'
        .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:874: in function 'create_window'
        .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1013: in function 'draw'
        .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1151: in function 'show_nodes'
        ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:95: in function 'render_context'
        ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:118: in function <...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:117>
```

reported there too https://github.com/GnikDroy/projections.nvim/issues/4. This is probably a consequence of #633

**Comment by cseickel** [comment]
In any session plugin, Neo-tree windows/buffers need to be excluded from being saved.

**Comment by nyngwang** [comment]
@cseickel Yes, I know that. That plugin provides me a `store_hooks` field in its `setup`. But the problem is that I have tried calling:

```
store_hooks = {
  pre = function () vim.cmd('tabd Neotree ') end,
  post = function () require 'neo-tree.sources.manager'.close_all() end,
},
```

I still cannot close the neo-tree "window(s)". Notice that the neo-tree buffer did get closed, but I said "window(s)" because of the way of neo-tree trying to "replace/occupy" another window #633.

**Comment by nyngwang** [comment]
I just found that problem on that plugin. Sorry for my misunderstood. It's related to the usage of `switcher`. Let me close this issue for now.
