### ISSUE TITLE
Issue when closing node together with hide_root_node

### ISSUE THREAD

**Issue by sQVe** [nvim-neo-tree/neo-tree.nvim#646]
👋🏼,

I've been trying the `hide_root_node` setting, since it gives a cleaner look but noting that it doesn't play nicely when triggering `close_node`. It basically leaves you in a state that is completely empty and triggering `open` results in an error. The only way, that I've found, to repair the state is to press <kbd>R</kbd>. 

Reproduce:
- Enable `hide_root_node`.
- Open `Neotree`.
- Press `C`.
- You're now in an empty state.
- Press `CR`: it should give you an error.
- Press `R` to reset and repair the state.

**Comment by nhat-vo** [comment]
@sQVe Does making `C` in the top level collapse nothing suit your needs?
