### ISSUE TITLE
[Feature Request] Brace expansion for creating files/folders

### ISSUE THREAD

**Issue by etrnal70** [nvim-neo-tree/neo-tree.nvim#647]
Basically the ability to use curly brace to create multiple files/folders like in shell

`user/user.{controller,schema,route}.ts`

**Comment by pysan3** [comment]
I would love to have this feature as well.

I'll try to implement it and make a PR when I'm done.

**Comment by pysan3** [comment]
Hi @etrnal70, I implemented this feature but as mentioned in the PR, I am not 100% sure if this is going to work.

May I ask you to test my implementation in your setup?

If you are using `packer.nvim`,
```lua
  use({
    "pysan3/neo-tree.nvim",
    branch = "add-brace-expansion",
    requires = { 
      "nvim-lua/plenary.nvim",
      "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
      "MunifTanjim/nui.nvim",
    },
    config = function()
      ... -- Your configuration
    end,
  })
```
And it should work out of the box.

Thanks in advance :)

**Comment by etrnal70** [comment]
Ccol ! I'll give it a shot today
