### ISSUE TITLE
[Bug] Only floating window would remain after deleting buffer

### ISSUE THREAD

**Issue by levouh** [nvim-neo-tree/neo-tree.nvim#65]
Filing for later, will likely poke at this myself.

After deleting a file in the tree (floating state), if the buffer deleted is the only other window open, we get an error noting the title of this issue.

**Comment by cseickel** [comment]
What should happen in this case? Would you replace the last window with a blank buffer?

**Comment by levouh** [comment]
Either an empty buffer or the "next" buffer in the current tabpage would work.
