### ISSUE TITLE
e key being remapped

### ISSUE THREAD

**Issue by s1n7ax** [nvim-neo-tree/neo-tree.nvim#650]
I'm a colemak dh user. I have remapped the `hjkl` keys to `mnei` keys in `n` `x` `o` modes. For a long time these keys has been working but within this month it stopped working.

When I run `:nmap n`
```
n  n           * j
```

`:nmap e`

```
n  e           *@<Lua 357: ~/.local/share/nvim/site/pack/packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:751>n  e           * k
```

In the documentation I couldn't find any default mapping with `e`.

**Comment by s1n7ax** [comment]
Sorry. My bad. [This](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/defaults.lua) has the complete list of defaults.
I added following and everything works fine. For the record, assigning nil is not working.

```
            mappings = {
                ['e'] = ''
            },
```

**Comment by cseickel** [comment]
You actually need to assign "noop" or "none" to disable a default mapping. It was a complication with merging commands that can be defined either globally or within a specific source.
