### ISSUE TITLE
Add option to disable italic styling?

### ISSUE THREAD

**Issue by ChrisMGeo** [nvim-neo-tree/neo-tree.nvim#652]
The font I use with `neovim` has special cursive italic font which doesn't fit well with `neo-tree`. Is there any way I can disable every italic styling from `neo-tree`?

**Comment by cseickel** [comment]
There is no way to do that with a single config change, but there are only a handful of highlight groups that use italics by default:

Module Constant | Highlight Group Name
----------------|---------------------
MESSAGE | NeoTreeMessage
ROOT_NAME | NeoTreeRootName
GIT_CONFLICT | NeoTreeGitConflict
GIT_UNTRACKED | NeoTreeGitUntracked


See `:h neo-tree-highlights` for a full listing of highlight groups.
