### ISSUE TITLE
Is it possible to use a different color for when a folder is opened vs when it is closed?

### ISSUE THREAD

**Issue by ChrisMGeo** [nvim-neo-tree/neo-tree.nvim#655]
I want my folder icons to be grey when untouched but orange when they're expanded. Is this possible in `neo-tree`? I can't find any highlight groups that say so.

**Comment by cseickel** [comment]
There is no built-in logic for that, but you can replace the icon component with your own implementation that adds this in. 

Here is how you would replace the icon component with your own:
```lua
require("neo-tree").setup({
  filesystem = {
    components = {
      icon = function ()
       return { text = "*", highlight = "Normal" }
      end,
    }
  }
})
```

and here is the built-in icon component:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/7c6903b05b13c5d4c3882c896a59e6101cb51ea7/lua/neo-tree/sources/common/components.lua#L265-L284

You can probably just copy and paste that and add in your custom highlight group for open folders.
