### ISSUE TITLE
Is it possible to make `set_root` to call `tcd` and make a `bind_to_tcd` option?

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#656]
What I want to achieve is that:

1. ~~My plugin depends on `DirChanged` with the pattern `global` to restore sessions.~~ I will use `getcwd(-1,-1)` to detect the project root, so I need to make sure that neo-tree's `bind_to_cwd` would not change it.
2. Within each project, ~~I usually have many tabs and I found it useful to have a different `cwd` for each tab. i.e. I will need to faciliate `tcd`.~~ I will follow the rule that always calls `tcd` instead of `cd` on any tab created.
3. So, I will need to make sure that the `set_root` mapping of `filesystem.window.mappings` will not affect the result of `getcwd(-1,-1)` and it will call `tcd` during the changing of cwd.

---

https://github.com/nvim-neo-tree/neo-tree.nvim/blob/b13425d57111a7885961110f8e51907fa630642b/lua/neo-tree/sources/filesystem/commands.lua#L208-L217

**Comment by nyngwang** [comment]
After many fucking hours of testing I finally found all answers to my own questions: (really sorry for my messy question):

1. Feel free to set `bind_to_cwd = true`, it **won't** affect the result of `vim.fn.getcwd(-1,-1)`. (so doing `set_root` with `bind_to_cwd = true`, neo-tree will actually do `:tcd`, which is firmly safe.)
2. Yes, by my testing neo-tree indeed follows the rule: one should always prefer `:tcd` when trying to change `current-directory`.
3. Already answered.

**Comment by cseickel** [comment]
There is technically a hidden config option for this too:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/7c6903b05b13c5d4c3882c896a59e6101cb51ea7/lua/neo-tree/defaults.lua#L368-L371

Someone could configure it to set it to `global` or `window` if they prefer.

**Comment by nyngwang** [comment]
@cseickel Thanks for the info :) I did read though that but I didn't understand it fully. I forgot about what `current` stands for... But I set `window.position` to `right`.
