### ISSUE TITLE
File tab not opening active files' folder

### ISSUE THREAD

**Issue by TheCrowd** [nvim-neo-tree/neo-tree.nvim#659]
Let's say I open nvim in path `c:/`, and then open a recent file in `F:/folder`, and then I open neo-tree, the file would be in `c:/`, not in `F:/folder` , is there a way to config the tool ,so that the folder would be the same as the file opened?

**Comment by cseickel** [comment]
Use this command to open Neo-tree:
```
:Neotree reveal_force_cwd
```

https://github.com/nvim-neo-tree/neo-tree.nvim#reveal_force_cwd

**Comment by TheCrowd** [comment]
@cseickel thanks for the help, instead of using a command, is it possible to make it the default behavior?

**Comment by cseickel** [comment]
That seems unnecessary. If you open it with a mapping, just change your mapping to use this command. If you open it with a command but don't want to type it out, make your own user command by putting something like this in your init.vim:
```vim
command! Nt Neotree reveal_force_cwd
```

Then you can open it with:
```
:Nt
```
and get the behavior you want.

**Comment by TheCrowd** [comment]
@cseickel  Actually I am using `AstroNvim`, and I would normally open neo-tree with `<Leader> + e`,  given that I would open recent files from history, I want to open the file explorer in the same folder as the file.

**Comment by cseickel** [comment]
What you want to do is change the `<leader>n` mapping to use the command you want. I'm not sure how AstroNvim organizes its config. If you've never changed a mapping and don't know how to do that, you should ask how on the [AstroNvim](https://github.com/AstroNvim/AstroNvim/issues) project.

**Comment by TheCrowd** [comment]
@cseickel  Thanks for your help, I will close this issue for now.
