### ISSUE TITLE
Problem with executing command when open file via neo-tree

### ISSUE THREAD

**Issue by RAprogramm** [nvim-neo-tree/neo-tree.nvim#674]
### this is what i get 
![Screenshot from 2023-01-02 09-29-35](https://user-images.githubusercontent.com/70325462/210188446-645e9ea0-7ffe-430d-9d9a-98d659fbaa4c.png)

### and this happens everytime when i use command like this
![nui function](https://user-images.githubusercontent.com/70325462/210188133-29e65fd8-2ce3-4c34-9769-3b90eed47c88.png)

### **BUT** when i open files via telescope for example - all is ok.

NVIM v0.9.0-dev-377+gc9adbcafa

**Comment by cseickel** [comment]
I'm not sure how this relates to Neo-tree. What calls that `inputMod` function?

**Comment by RAprogramm** [comment]
which-key plugin
![Screenshot from 2023-01-03 11-07-30](https://user-images.githubusercontent.com/70325462/210291636-3c23985f-2f8b-4f26-9df9-81f1a7fb953c.png)

**Comment by RAprogramm** [comment]
today i tryed do same as yesterday, and all works fine...
i am confusing.
sorry about issue

**Comment by RAprogramm** [comment]
https://github.com/MunifTanjim/nui.nvim/issues/232
