### ISSUE TITLE
Filters didn't work

### ISSUE THREAD

**Issue by bachrilq** [nvim-neo-tree/neo-tree.nvim#686]
Hi, so I try all the filter features like `fuzzy_finder`, `fuzzy_finder_directory`, and `filter_on_submit`, but none of them are working on my laptop, is there any other config that I need to add? here I attach the screen recording, thank you.

My current setup:
nvim version : v.0.8.2
installed neo-tree with packer, commit 3b41f0d17139bb156f1acd907608f63e0e307caf
macos BigSur Version 11.7

https://user-images.githubusercontent.com/40727644/211448360-1543624d-0803-437e-8562-60ce71a75b6e.mov

**Comment by cseickel** [comment]
You do need either `fd` or `find` installed. If you do have one of them, can you tell me what version it is?

**Comment by bachrilq** [comment]
Ah, I see, Is this requirement specified on the wiki? on my mac already install the `find` binary, but I cannot check the version, and because the `find` binary is the default Mac I think the behavior is different from the `find` GNU version, so I try to install `fd` binary via homebrew, and now the filters are working, Thank You!! 🙏 
<img width="332" alt="image" src="https://user-images.githubusercontent.com/40727644/211474815-fb90133a-f97c-417f-a127-5dd09f273b65.png">
