### ISSUE TITLE
Refactor common functionality for sources

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#69]
In 1.0, sources only had to implement a few simple methods and there was no real shared functionality. Now we have gotten to the point where there is, or should be, a lot of shared code between them.

Most of my life this would mean "extract a base class and/or interface", but I'm not sure if that's the right way to go here. Partly because lua has a pretty shoddy class and type system, but also because this was simply not designed in an OOP fashion from the start.

This issue exists to let others know this refactor is happening and to collect any discussion that may happen around this work. This may or may not create breaking changes that requires a 2.x branch.

**Comment by levouh** [comment]
@cseickel I've been _mostly_ trying to keep up with this one, but wanted to confirm with you before continuing #31. You think it is in a good enough state for further iterations there?

**Comment by cseickel** [comment]
Yes @levouh, I think this is solid now and I'm happy with where it ended up. I'm actually about to release it.
