### ISSUE TITLE
neo-tree opens files into noice.nvim popups

### ISSUE THREAD

**Issue by zolrath** [nvim-neo-tree/neo-tree.nvim#692]
Hello!
When opening a file in neo-tree it normally opens into the currently active buffer, but if [noice.nvim](https://github.com/folke/noice.nvim) has an active notification pop-up displayed the new file is opened into that tiny popup buffer instead.

![image](https://user-images.githubusercontent.com/454563/211950351-9614449c-a31f-4544-8a7a-58f1ad96fed5.png)
This shows the effect while at the dashboard, but even with a file in an active buffer the result is the same.

Perhaps being able to be filter specific buffers ala #511 could help solve this but I found it interesting that my current buffer is being ignored.

This is reproducible using [the lazyvim starter](https://github.com/LazyVim/starter)

**Comment by cseickel** [comment]
I think that this is a special case that shouldn't need configuration. Files should **never** open in a floating window. I will put in a fix for this right away.

**Comment by cseickel** [comment]
This should be fixed with the latest commit to main, can you test it out?
