### ISSUE TITLE
Remapping does not delete default mapping

### ISSUE THREAD

**Issue by goodshort** [nvim-neo-tree/neo-tree.nvim#695]
Hi!

In my situation, I have decided to remap the `prev_source` and `next_source` to `<C-h>` and `<C-l>`. My expectation was that the default values `<` and `>` would be overwritten but instead it kept them and created a total of 4 mappings. See below config and screeenshot of help page.

<img width="395" alt="Screenshot 2023-01-13 at 00 37 11" src="https://user-images.githubusercontent.com/33832653/212210783-f5f595b1-50ea-4337-9f49-e47c55a3c407.png">

```lua
mappings = {
    ["<space>"] = {
        "toggle_node",
        nowait = false, -- disable `nowait` if you have existing combos starting with this char that you want to use
    },
    ["<2-LeftMouse>"] = "open",
    ["<cr>"] = "open",
    ["<esc>"] = "revert_preview",
    ["P"] = { "toggle_preview", config = { use_float = true } },
    ["S"] = "open_split",
    ["s"] = "open_vsplit",
    ["t"] = "open_tabnew",
    -- ["<cr>"] = "open_drop",
    -- ["t"] = "open_tab_drop",
    ["w"] = "open_with_window_picker",
    -- ["P"] = "toggle_preview", -- enter preview mode, which shows the current node without focusing
    ["C"] = "close_node",
    ["z"] = "close_all_nodes",
    -- ["Z"] = "expand_all_nodes",
    ["a"] = {
        "add",
        config = {
            show_path = "none" -- "none", "relative", "absolute"
        }
    },
    ["A"] = "add_directory", -- also accepts the optional config.show_path option like "add". this also supports BASH style brace expansion.
    ["d"] = "delete",
    ["r"] = "rename",
    ["y"] = "copy_to_clipboard",
    ["x"] = "cut_to_clipboard",
    ["p"] = "paste_from_clipboard",
    ["c"] = "copy", -- takes text input for destination, also accepts the optional config.show_path option like "add":
    ["m"] = "move", -- takes text input for destination, also accepts the optional config.show_path option like "add".
    ["q"] = "close_window",
    ["R"] = "refresh",
    ["?"] = "show_help",
    ["<c-h>"] = "prev_source",
    ["<c-l>"] = "next_source",
}
```

**Comment by goodshort** [comment]
After some more digging, I found `use_default_mappings` in [defaults.lua](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/3b41f0d17139bb156f1acd907608f63e0e307caf/lua/neo-tree/defaults.lua#L43), and setting it to `false` fixes my issue.

It might be interesting to note that I copied [the longer example](https://github.com/nvim-neo-tree/neo-tree.nvim#longer-example-for-packer) from the README. By the look of the example, when I saw some mappings commented out I assumed that `use_default_mappings` would be the behaviour when a mapping is provided.

If more people reports this issue, it might be worth adding a comment somewhere in [the longer example](https://github.com/nvim-neo-tree/neo-tree.nvim#longer-example-for-packer) or adding the `use_default_mappings` parameter.

**Comment by tmpm697** [comment]
same step, need to set `use_default_mappings = false` for user's own keybindings to work even though you set it via `mappings`, this needs to clarify in README.md.

**Comment by cseickel** [comment]
> same step, need to set use_default_mappings = false for user's own keybindings to work

That's not true at all. If you read the help file, it explains that you need to set a mapping to "none" if you want to disable a built-in mapping. The commented out mappings in the README are just suggestions, they are not standard mappings that are being disabled.

The README is not the documentation.
