### ISSUE TITLE
When in a directory, collapse and focus on parent

### ISSUE THREAD

**Issue by farzadmf** [nvim-neo-tree/neo-tree.nvim#696]
I'm following [this tip](https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Tips#navigation-with-hjkl) to help navigating with `h` and `l`

When doing `h` inside of a directory, that script needs `2` keystrokes to collpase:
- First one goes to the parent
- Second one collapses

Thank you

**Comment by cseickel** [comment]
I'm not sure what this issue is. Do you have a question to ask or bug to report?

**Comment by farzadmf** [comment]
OMG, sorry, I was editing it, and removed the question part, my bad!

Here it was:
> I was wondering if the steps can be achieved with a single keystroke

Sorry again

**Comment by farzadmf** [comment]
@cseickel just checking in to see if there's a way for this

**Comment by cseickel** [comment]
You don't need to use a custom function for that. `close_node`, which is mapped to `C` by default, already does that.

**Comment by farzadmf** [comment]
Oh wow, thank you @cseickel  , that's super useful! May I bother you with one more question:

Is there a way to recursively close all child nodes of the current node? What `C` does is close it and when I open it, whatever was expanded is already expanded, I want all of them to be collapsed

**Comment by nhat-vo** [comment]
I don't think there is a built-in command to do that. There is `close_all_nodes` (mapped to `z`) which closes everything up to the root node. You can use `set_root` (mapped to `.`) on the parent directory, use `z` to collapese everything, and then use `navigate_up` (mapped to `<bs>`) to go back to your previous root. 

I agree that this is a bit inconvenient, so if you want I could help implement this feature.

**Comment by farzadmf** [comment]
Sorry @nhat-vo for the late reply, I was busy and wanted to get back to this when I'm free.

And wow, I guess you already implemented it?

**Comment by miversen33** [comment]
It does appear so. @nhat-vo  moves quick lol. Closing this out as  completed in #764

**Comment by nhat-vo** [comment]
I had a bit of free-time yesterday, and this fix is quite similar to another PR I did, so I just went ahead and do it 😄

**Comment by farzadmf** [comment]
@nhat-vo thank you very much, question: is there a command to do the opposite? Basically, when on a node, recursively open all the subnodes? (recursively is the important big 🙂 )

**Comment by miversen33** [comment]
@farzadmf so an auto expand of _all_ nodes under a current node? That seems... dangerous for memory lol.

**Comment by farzadmf** [comment]
Thank you @miversen33 , I completely agree. Usually I don't get replies on the new questions I ask, so I tried to get an answer for that from here 😝 , but I completely agree with your point to keep issues focused on their scope.
