### ISSUE TITLE
Allow global commands for window

### ISSUE THREAD

**Issue by mehalter** [nvim-neo-tree/neo-tree.nvim#707]
It is great that I can use the `commands` table to define commands that can easily be used in mappings and also provide context to the help menu, but this only works with specific sources like `filesystem`. It would be great to be able to define commands for the entire window that work for all sources or give a way to name a function so that when I press `?` it doesn't just say a mapping is `<function>`

**Comment by cseickel** [comment]
As long as your mapping is always to a command identified by name, it will work the way you want it to. If you want to use the same function as a command across multiple sources, you can just define the named function outside of the config table, and then include a reference to it in the `commands` table for each source.  

```lua
      local my_global_command = function()
        print("Hello from my global command!")
      end

      require("neo-tree").setup({
        window = {
          mappings = {
            ["M"] = "my_global_command",
          },
        },
        filesystem = {
          commands = {
            my_global_command = my_global_command,
          },
        },
        buffers = {
          commands = {
            my_global_command = my_global_command,
          },
        },
        git_status = {
          commands = {
            my_global_command = my_global_command,
          },
        },
      })
```

The reason the `commands` are defined separately for each source is that they usually don't work in a generic way and need to have slightly different implementations for each source.

**Comment by mehalter** [comment]
Would it not make sense to add a better syntax for the several cases where it is the same between sources? Stuff like global navigation commands moving up and down the trees or executing a command on a selected node? It seems extremely verbose when I have 3 commands that are global and I have to add at least 12 lines just to define the command not including the actual function of the command

**Comment by mehalter** [comment]
It seems like a 4x decrease in duplicated lines for these cases is a pretty decent improvement

**Comment by cseickel** [comment]
> Would it not make sense to add a better syntax for the several cases where it is the same between sources? Stuff like global navigation commands moving up and down the trees or executing a command on a selected node? It seems extremely verbose when I have 3 commands that are global and I have to add at least 12 lines just to define the command not including the actual function of the command

Yes, it certainly sounds logical and it would be nice to have. I'll mark it as an enhancement.

**Comment by pysan3** [comment]
Not a solution, but you can simplify the code to something like this.

```lua
      local my_global_command = function()
        print("Hello from my global command!")
      end

      local add_global = function(t)
        t.my_global_command = my_global_command
        return t
      end

      require("neo-tree").setup({
        window = {
          mappings = {
            ["M"] = "my_global_command",
          },
        },
        filesystem = {
          commands = add_global {
          },
        },
        buffers = {
          commands = add_global {
          },
        },
        git_status = {
          commands = add_global {
          },
        },
      })
```
