### ISSUE TITLE
[Feature/Bug] Show hidden files by default

### ISSUE THREAD

**Issue by levouh** [nvim-neo-tree/neo-tree.nvim#71]
Using the following configuration:

```lua
require("neo-tree").setup({
  filesystem = {
    window = {
      mappings = {
        ["<CR>"] = "open",
        ["<C-x>"] = "open_split",
        ["<C-v>"] = "open_vsplit",
        [".."] = "navigate_up",
        ["<BS>"] = "close_node",
        ["<C-]>"] = "set_root",
        ["H"] = "toggle_hidden",
        ["I"] = "toggle_gitignore",
        ["R"] = "refresh",
        ["/"] = "filter_as_you_type",
        ["f"] = "filter_on_submit",
        ["<C-l>"] = "clear_filter",
        ["o"] = "add",
        ["dd"] = "delete",
        ["r"] = "rename",
        ["yy"] = "copy_to_clipboard",
        ["x"] = "cut_to_clipboard",
        ["p"] = "paste_from_clipboard",
      },
      position = "float",
      popup = {
        border = {
          top = "",
          style = "rounded",
        },
        size = {
          width = 35,
          height = "100%",
        },
        position = {
          row = "0%",
          col = "0%",
        },
      },
    },
    bind_to_cwd = true,
    filters = {
      show_hidden = true,
      respect_gitignore = false,
    },
    before_render = function(_)
      return
    end,
    components = {
      user_icon = require("user.pack.config.tree.components").user_icon,
    },
    renderers = {
      directory = {
        {
          "user_icon",
          folder_closed = "",
          folder_open = "",
          folder_empty_closed = "",
          folder_empty_open = "",
          padding = " ",
        },
        { "current_filter" },
        { "name" },
        {
          "clipboard",
          highlight = highlights.DIM_TEXT,
        },
      },
    },
  },
})
```

I observe that when trying to try to expand a node for a directory that contains only hidden files with `<CR>`, nothing is expanded. The behavior of:

```lua
    filters = {
      show_hidden = true,
      respect_gitignore = false,
    },
```

is strictly related to filters (e.g. `/`), correct? Or is there a bug there and setting `show_hidden = true` should actually do what is noted here? As it stands right now, without using the (default) mapping of `H`, there is no other way to have this directory (containing only hidden files) expand. From what I can tell, this might just be a matter of things being copied over to the current `state` correctly, but I' not entirely sure how things are intended to behave.

This behavior is shown below:

https://user-images.githubusercontent.com/31262046/149869860-d299b27f-c7f4-4f51-a13d-2e2b13371c27.mp4

**Comment by jgottzen** [comment]
Though it's not documented, and I'm not sure if it is intentional or not, you can achieve this by adding this to your config:

```lua
require("neo-tree").setup({
  filesystem = {
    show_hidden = true, -- show hidden files by default
    respect_gitignore = true -- hide git ignored files by default
    ...
```
That is the flag the `H` toggles.

**Comment by cseickel** [comment]
@levouh The behavior of the "filters" section of the config actually applies to both browsing and the search mode. It may have been clearer to call the search functionality search instead of also referring to it as filtering. As far as I can see, this is working as intended.

**Comment by jgottzen** [comment]
@cseickel The `show_hidden` is actually toggled directly on the state object, not on `state.filters`:

https://github.com/jgottzen/neo-tree.nvim/blob/8a2d3e86638bfeaf2e97d18063b480d247992955/lua/neo-tree/sources/filesystem/commands.lua#L97-L100

and

https://github.com/jgottzen/neo-tree.nvim/blob/8a2d3e86638bfeaf2e97d18063b480d247992955/lua/neo-tree/sources/filesystem/lib/fs_scan.lua#L104-L109

**Comment by levouh** [comment]
> Though it's not documented, and I'm not sure if it is intentional or not, you can achieve this by adding this to your config:
> 
> ```lua
> require("neo-tree").setup({
>   filesystem = {
>     show_hidden = true, -- show hidden files by default
>     ...
> ```
> 
> That is the flag the `H` toggles.

Gotcha, this was the issue. I only saw the text `show_hidden` under the `filter` table, thanks @jgottzen!

@cseickel I'm happy to submit a mini _PR_ to document this, but would it be easier to do on #60 if the docs method is being reworked?

**Comment by cseickel** [comment]
Good catch @levouh and @jgottzen! This is the sort of thing I tend to miss because I generally stick with the defaults. The documentation is wrong in this case and I would consider that a bug. Bugs always get fixed first in my book, so I wouldn't hold this up for a larger documentation effort.

PRs are welcome!

**Comment by cseickel** [comment]
To make things more confused, I see that the filter feature (search) is using the flags within in the `filter` table as documented. Browsing and filtering should use the same flags, so there is a code change here.

I think the correct thing to do is to make both situations use the flags within the `filter` table to align with the documentation.

**Comment by jgottzen** [comment]
@cseickel Ok, I can do a PR for that, if you want?

**Comment by cseickel** [comment]
That would be great, thanks!

**Comment by nyngwang** [comment]
In case you might have forgot: the README.md has __NOT__ been updated!

**Comment by cseickel** [comment]
@nyngwang I don't think it needs to be. This issue morphed from a request to change the default behavior to a bug fix becuase the code didn't match the existing documentation. The final fix was to update the code to match that documentation but leave the defaults alone.

**Comment by nyngwang** [comment]
@cseickel: How to show the hidden files by default in the current version? In my current case only If the current buffer is a hidden file then all hidden files/dirs are revealed. Should I need to hit `H` manually every time I open `nvim` from my terminal?

**Comment by cseickel** [comment]
Here is how to change the option and always show hidden files:

```lua
require("neo-tree").setup({
  filesystem = {
    filters = {
      show_hidden = true,
      --respect_gitignore = false,
    },
  },
})
```

**Comment by nyngwang** [comment]
> @cseickel: In case this would be forgotten: the README.md has **NOT** been updated!
> 
> ```
>   show_hidden = true,
> ```

Maybe you could document this in the README.md? Thanks for your helps!

**Comment by cseickel** [comment]
Sure. I was thinking that it was already there but now I realize it's only in the vim help file. I'll include in the readme for the next release.
