### ISSUE TITLE
Respect user's winhighlight?

### ISSUE THREAD

**Issue by tmpm697** [nvim-neo-tree/neo-tree.nvim#711]
Currently this plugin always set `winhl` and even though i have like autcmd on `WinEnter` to set winhl, this plugin always keep overwrite it.

how to allow user to set their custom winhl?

**Comment by cseickel** [comment]
You should use the neo-tree event system to make sure your settings are applied in the correct order:
```
:h neo-tree-events
```

In particular, I think the `neo_tree_buffer_enter` event is what you want to use. Here's an example of using that event from the wiki just so you have the syntax:
```lua
  require('neo-tree').setup({
    event_handlers = {
      {
        event = "neo_tree_buffer_enter",
        handler = function()
          -- This effectively hides the cursor
          vim.cmd 'highlight! Cursor blend=100'
        end
      },
      {
        event = "neo_tree_buffer_leave",
        handler = function()
          -- Make this whatever your current Cursor highlight group is.
          vim.cmd 'highlight! Cursor guibg=#5f87af blend=0'
        end
      }
    },
  })
```
