### ISSUE TITLE
use_popups_for_input not working for me

### ISSUE THREAD

**Issue by gnmdrive** [nvim-neo-tree/neo-tree.nvim#719]
I hava tried to disable input popups from nui through setting `use_popups_for_input` to false, but i haven't seen any changes, when i try to rename or add a file i still call the nui plugin to display popus, also when i fuzzy find inside neo-tree i'd like to use vim.ui.input(), what can i do to change this behavior?

**Comment by miversen33** [comment]
I am not able to recreate this issue, can you provide a minimal configuration for reproduction?

**Comment by nhat-vo** [comment]
This has been inactive for a while, so I'll close it as stale.
