### ISSUE TITLE
Wrong background colors for git status

### ISSUE THREAD

**Issue by npupko** [nvim-neo-tree/neo-tree.nvim#727]
I'm using [Gruvbox](https://github.com/ellisonleao/gruvbox.nvim) colorscheme and for some reason part of git statuses displayed with wrong bg-color:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/5938539/216625721-cd008896-1cd1-4247-8549-9e145023e9d6.png">

When I'm trying to modify them via
```lua
vim.api.nvim_set_hl(0, 'NeoTreeGitAdded', {bg='#282828'})
vim.api.nvim_set_hl(0, 'NeoTreeGitConflict', {bg='#282828'})
vim.api.nvim_set_hl(0, 'NeoTreeGitDeleted', {bg='#282828'})
vim.api.nvim_set_hl(0, 'NeoTreeGitIgnored', {bg='#282828'})
vim.api.nvim_set_hl(0, 'NeoTreeGitModified', {bg='#282828'})
vim.api.nvim_set_hl(0, 'NeoTreeGitUntracked', {bg='#282828'})
```

it behaves weird on selection active file:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/5938539/216627037-fec4d898-876d-4e96-93b8-ac1352119f1e.png">

Could you advice me any options how could I handle this?

**Comment by nhat-vo** [comment]
Hi! You can do 
```
vim.cmd([[
highlight NeoTreeGitAdded bg=none,
highlight NeoTreeGitConflict bg=none,
...
]])
```

I'd use vimscript for this instead of lua api to keep the other attributes (e.g `fg`, `gui`, ...)

**Comment by npupko** [comment]
@nhat-vo Doesn't work for me. I.e. the results still same for some reason

**Comment by nhat-vo** [comment]
Where do you put these lines? You should put them at the end of your configuration

**Comment by npupko** [comment]
@nhat-vo Here is how it looks for me.
P.S. Moving `colorscheme` at the bottom did not change things
The `neo-tree` is lazy-loaded:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/5938539/218463849-3ca8664e-faa0-4ee6-9a4d-bab305e8d564.png">

**Comment by nhat-vo** [comment]
Could you try putting 
```lua
vim.cmd([[
highlight NeoTreeGitAdded bg=none,
highlight NeoTreeGitConflict bg=none,
...
]])
```
at the end of your `init.lua` file? Neo-tree set those highlight groups on load, so what you wrote in the gruvbox's init will be overwritten.

**Comment by npupko** [comment]
Still same result

**Comment by nhat-vo** [comment]
Do you mean same result as in the original behavior (the first image that you sent)? 
If so, did you try doing `:highlight NeoTreeGitUntracked bg=none` etc. in nvim and see if it changes anything?

If this still does not fix your issue, could you send me your config so I could have a better look?

**Comment by npupko** [comment]
@nhat-vo In that case it says
<img width="298" alt="image" src="https://user-images.githubusercontent.com/5938539/219078065-b48f8554-502d-4c17-8a22-8bad3530e8c2.png">

**Comment by nhat-vo** [comment]
Try changing `bg` to `guibg` or `ctermbg` instead. One of those should work, depending on how you run nvim.

**Comment by npupko** [comment]
@nhat-vo This helps, thanks! But the colors are gone.
But, I've investigated it deeper and find out that:

NeoTreeGitModified links to GitSignsChange
GitSignsChange links to GruvboxAquaSign
and GruvboxAquaSign has this [config](https://github.com/ellisonleao/gruvbox.nvim/blob/b9d23a64dc8f22b4af8fa708d9fcbffbbf5747c6/lua/gruvbox/groups.lua): 
```
    GruvboxAquaSign = config.transparent_mode and { fg = colors.aqua, reverse = config.invert_signs }
```

So, as a temporary solution, I just enabled transparent mode and set the background of my terminal to the same color as my neovim theme and it fixed the problem.

Anyway, this looks like a bug, but I am not sure this is related to the `neo-tree` itself. Looks like this is more for colorscheme.

**Comment by nhat-vo** [comment]
Gruvbox is quite different from many other themes (e.g tokyonight, rose-pine, catppuccin, etc.) in that it use a different background color for `signcolumn` from the main background. As a result, when used outside the `signcolumn`, they will be rendered with a different background, resulting in the error as above. I also encountered the same weird behavior with [noice.nvim](https://github.com/folke/noice.nvim).

**Comment by nhat-vo** [comment]
You can also add 
```
require("gruvbox").setup({
    overrides = {
        SignColumn = { link = "GruvboxBg0" }
    }
})
```
which removes the `signcolumn` color. 

I'm closing this issue as solved.
