### ISSUE TITLE
I want to use / to search text as done in vim.

### ISSUE THREAD

**Issue by shaffaaf-mohe** [nvim-neo-tree/neo-tree.nvim#73]
I want to use / to search text as done in vim instead of the filter now being done. Changing key to "F" does not remove default keymap. Instead it maps both "/" and "F" to filter.

**Comment by cseickel** [comment]
Sorry, this should have been documented. You can override the built-in mapping by re-mapping it to something that is neither a valid string or a function. I would suggest one of these mappings:

```lua
    ["/"] = "noop"
    ["/"] = {}
```

I meant to support `nil` as a means of removing the built-in mapping as well but that doesn't seem right now. I will fix the documentation to include this.
