### ISSUE TITLE
Paths with non-ascii characters are marked as hidden

### ISSUE THREAD

**Issue by gabrielcarloto** [nvim-neo-tree/neo-tree.nvim#731]
Basically the title. I think I don't have any steps to reproduce and I didn't find any issue related to this. 
I'm new to vim so I may have done something wrong. This is my config:

```lua
{
    "nvim-neo-tree/neo-tree.nvim",
    cmd = "Neotree",
    branch = "v2.x",
    keys = {
        { "<leader>ft", "<cmd>Neotree toggle<cr>", desc = "NeoTree" },
    },
    dependencies = {
        "nvim-lua/plenary.nvim",
        "MunifTanjim/nui.nvim",
    },
    config = {
        filesystem = {
            follow_current_file = true,
            hijack_netrw_behaviour = "open_current",
        },
    },
}
```

This config is from https://github.com/nvim-lua/kickstart.nvim, which I changed to use lazy instead of packer. I don't think this is an issue with my config as it happened on a fresh install of AstroNvim too. 

Info:

OS: Windows 11
NVIM v0.8.2

Screenshots:

![image](https://user-images.githubusercontent.com/68694907/216837388-2f1a8cff-a82e-41d7-b755-b5b9ee4b22fa.png)

![image](https://user-images.githubusercontent.com/68694907/216837376-792d806c-adbf-4a41-a824-d10ee8bd3abf.png)

My config is not hidden

![image](https://user-images.githubusercontent.com/68694907/216837892-b7f02721-3914-47bf-aa01-d894ccb57365.png)

But when I tested it with AstroNvim, only the folder `lua/user` was hidden (along with some dot files). I can't exactly tell what will be hidden and what will be visible.

**Comment by miversen33** [comment]
Just for kicks, what happens if you add
```lua
filtered_items = { visible = true }
```
to the `filesystem` attribute in your neo-tree config?

So
```lua
{
    "nvim-neo-tree/neo-tree.nvim",
    cmd = "Neotree",
    branch = "v2.x",
    keys = {
        { "<leader>ft", "<cmd>Neotree toggle<cr>", desc = "NeoTree" },
    },
    dependencies = {
        "nvim-lua/plenary.nvim",
        "MunifTanjim/nui.nvim",
    },
    config = {
        filesystem = {
            filtered_items = { visible = true },
            follow_current_file = true,
            hijack_netrw_behaviour = "open_current",
        },
    },
}
```

**Comment by gabrielcarloto** [comment]
Isn't it the same as pressing `h` to show the hidden files while the tree is open? I think I tried this setting, but I can't remember. I mean, I can still use it but seeing all files with this dimmed font color is not the best experience, so I ended up switching to Nvim Tree, which is working as expected.

I get the feeling that this is some obscure bug that only happens on my machine. Setting up neovim on windows is a pain, I should've used wsl.

Anyway, I'll add this config later and see if anything changes. Thanks for your answer.

**Comment by cseickel** [comment]
The big question is, are the files **actually** hidden or are they just being incorrectly displayed as hidden? If it's just a display problem, I would look at whether it might be a unicode bug. Try working in a folder that's just called `test` and see if that makes any difference.

**Comment by gabrielcarloto** [comment]
No, they aren't actually hidden, just displayed incorrectly. It happens in any folder.

**Comment by ddzizz** [comment]
Same issue if path include chinese characters 
` F:/Projects/测试/testproj/test.lua `
![Snipaste_2023-02-26_16-27-22](https://user-images.githubusercontent.com/73836582/221400142-730f4af4-0db8-4404-809e-37d2c288e987.png)


Problem is gone after change chinese characters to english
`F:/Projects/test/testproj/test.lua`
![Snipaste_2023-02-26_16-25-03](https://user-images.githubusercontent.com/73836582/221400062-a6f6202b-f304-4f20-85eb-35cbf7694e3f.png)

**Comment by gabrielcarloto** [comment]
Just tested it, makes sense. In my case, folders with accented characters are hidden.

**Comment by Fuann-Kinoko** [comment]
to be more precise, it is a bug that only happens for `Windows`

**Comment by pysan3** [comment]
This should be fixed in the latest release.

I am going to close this issue. Please reopen and ping me if you still experience this issue.

- https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1353
