### ISSUE TITLE
How to autofocus on file that is currently active ?

### ISSUE THREAD

**Issue by radvil2** [nvim-neo-tree/neo-tree.nvim#732]
I want to highlight my current opened file in the tree structure. How ?? please

**Comment by miversen33** [comment]
See [the readme](https://github.com/nvim-neo-tree/neo-tree.nvim#user-experience-good-slightly_smiling_face-thumbsup)

```lua
require("neo-tree").setup({
    filesystem = {
         follow_current_file = true
   }
})
```

It looks like this isn't in the help doc, though it _is_ on the main readme of the project.

**Comment by miversen33** [comment]
Whoops, accidentally closed this lol, we need to update the help doc to include this option

**Comment by nhat-vo** [comment]
@miversen33 The [help doc](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/doc/neo-tree.txt#L652) specifies that not all configs are documented there but in `default.lua` instead (which makes sense, as there are lots of configs), so I don't think we'll need to add it there.

I'll close this issue as solved, but feel free to reopen it if you think we should add it to the help doc.
