### ISSUE TITLE
Hide cursor when select neo-tree window?

### ISSUE THREAD

**Issue by tmpm697** [nvim-neo-tree/neo-tree.nvim#736]
when i surfing file to create/edit/select file in neo-tree, i don't find the need for cursor appears in neo-tree buffer, the current line is already highlighted in my case.

how to hide cursor in neo-tree buffer or trick its color to the same as line in neo-tree buffer?

the cursor in neo-tree buffer:
![color](https://i.imgur.com/8vj7AKp.png)

**Comment by cseickel** [comment]
Here's an example: https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Visual-Customizations#hide-cursor-in-neo-tree-window

**Comment by cseickel** [comment]
Maybe nvim is not setting the cursor at all in your setup, which would make this an impossible task. 

here is how I set my cursor using vimscript, if you do the same (or something similar) it may work the way you want it with the neo-tree config I linked to in the prior comment:

```vim
highlight Cursor guibg=#5f87af ctermbg=67
highlight iCursor guibg=#ffffaf ctermbg=229
highlight rCursor guibg=#d70000 ctermbg=124

set guicursor=n-v-c:block-Cursor/lCursor
            \,i-ci-ve:ver100-iCursor
            \,r-cr:block-rCursor
            \,o:hor50-Cursor/lCursor
            \,sm:block-iCursor
            \,a:blinkwait1000-blinkon500-blinkoff250
```
