### ISSUE TITLE
`neo-tree` is stuck when switching between splits in the presence of `vim-rooter`.

### ISSUE THREAD

**Issue by ioreshnikov** [nvim-neo-tree/neo-tree.nvim#74]
Hi!

I've found another issue with `vim-rooter` on the most recent `main` branch. The sidebar is not feeling well if you jump between the panes that belong to different projects. Here's how to reproduce it:

1. In a fresh nvim session split your window into two vertical splits and toggle `neo-tree` sidebar.
2. In the first split open a file from project P1 (let's say `.config/nvim/init.vim`). In the second split open a file from P2 (let's say `.local/share/nvim/plugged/neo-tree`).
3. You are now in the second split. Your `cwd` is set to P2 by `vim-rooter`. Switch to the first split. `cwd` is set to P1 and the tree is updated. Switch back to the second split. `cwd` is set back to P2, but the tree is still showing P1's `cwd`, but now collapsed.

This time I don't think it's related to debouncing and it happens if I wait for 10 seconds before each consequetive switch.

As usual, let me know if you need additional info.

Best,
Ivan

**Comment by cseickel** [comment]
I think this may be the intersection of the `follow_file` option with vim-rooter. I'll test it out tonight.
