### ISSUE TITLE
Automatically opening with window picker if more than one non-Neotree window open

### ISSUE THREAD

**Issue by Maritsu** [nvim-neo-tree/neo-tree.nvim#742]
Would it be possible to automatically open files using the window picker (<kbd>w</kbd>) instead of the normal open (<kbd>\<CR\></kbd>) when more than one non-Neotree window is open?  
Not even asking to be added as a function, just asking if something like this would be possible via config.  
Thanks!

**Comment by nhat-vo** [comment]
Hi! I'm not sure what you mean by this. Do you mean making `<CR>` use the `open_with_window_picker` mapping instead of the normal `open`?

**Comment by Maritsu** [comment]
Yes, although only when more than one window is currently open (excluding Neotree)

**Comment by nhat-vo** [comment]
You can set `window-picker`'s configuration to `autoselect_one = true` and `include_current=false` (similarly to how it's done in the [example](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/8238865e1d9c61f1a260c290653f2c419503e0a9/README.md?plain=1#L82-L103)). This will prompt you to pick a window if there are multiple, and automatically choose when there is only one.

You can then bind the `<CR>` to this mapping like this
```lua
 ["<cr>"] = "open_with_window_picker",
```

Does that answer your question? 😁

**Comment by Maritsu** [comment]
yup! thanks very much
