### ISSUE TITLE
Render the window right away, even when async

### ISSUE THREAD

**Issue by musjj** [nvim-neo-tree/neo-tree.nvim#744]
File scanning can take a particularly long time, so having `async_directory_scan = "always"` can introduce a huge delay before the window is finally opened.
A better behavior would be to open the window right away, before scanning the directory.

**Comment by pysan3** [comment]
Partially related: #713.

**Comment by charbelnicolas** [comment]
Hopefully something can be done to fix this issue

**Comment by pysan3** [comment]
Hi, I created a possible solution to this issue at #752.

Besides, I am thinking of mainly discussing about this over on #713 so please follow that issue if you are interested.

**Comment by cseickel** [comment]
I have a new fix for this in #1015. Can someone try it out and let me know how it works? 
@musjj @charbelnicolas
