### ISSUE TITLE
highlighting/showing symlinks differently

### ISSUE THREAD

**Issue by figsoda** [nvim-neo-tree/neo-tree.nvim#746]
Something like this `from-file -> to-file`

**Comment by cseickel** [comment]
That exists as a component already, it's just not enabled by default:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/245cf1e68840defcc75a16297740f6203f5a045d/lua/neo-tree/defaults.lua#L261-L265

**Comment by figsoda** [comment]
Would I have to copy this whole part to enable it? https://github.com/nvim-neo-tree/neo-tree.nvim/blob/245cf1e68840defcc75a16297740f6203f5a045d/lua/neo-tree/defaults.lua#L252-L271

**Comment by cseickel** [comment]
> Thanks! Would I have to copy this whole part to enable it?

Yes. 

I think I implemented the ability to disable components so that they can be in the default renderer as disabled and then enabled with `default_component_configs` instead of having to define an entire custom renderer, but unfortunately I haven't actually put that ability to use yet.
