### ISSUE TITLE
Window resize on open NeoTree

### ISSUE THREAD

**Issue by Distantoff** [nvim-neo-tree/neo-tree.nvim#751]
Hello! Thank you for your work! Is it possible to automatically change the size of buffers when opening a Neo Tree? The problem is that when I open NeoTree, it only changes the size of the first buffer. Or am I doing something wrong?
![Screenshot_20230215_205722](https://user-images.githubusercontent.com/17424600/219008899-fae9bc6a-862d-4def-a07f-c40201a54011.png)
![Screenshot_20230215_205730](https://user-images.githubusercontent.com/17424600/219008913-a96ac3f4-e931-4e9a-812b-90dc6d0768a4.png)

**Comment by musjj** [comment]
https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#equalize-window-sizes-on-neo-tree-open-and-close

**Comment by Distantoff** [comment]
> https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#equalize-window-sizes-on-neo-tree-open-and-close

Thank you! It's works.

**Comment by mazulo** [comment]
Thank you so much @musjj!! I was struggling with this for so long and finally could manage to find a search that led me to this issue and your comment! 🚀
