### ISSUE TITLE
Neo-tree closes when writing to buffer

### ISSUE THREAD

**Issue by Maritsu** [nvim-neo-tree/neo-tree.nvim#756]
**Neovim version:** 0.8.3
**OS:** Arch Linux x86_64

I'm having a particularly annoying issue with Neo-tree - as the title says, when I write to any buffer (`:w`), the Neo-tree window closes by itself.  
The tree window is opened using ```:Neotree left reveal filesystem``` if that's of any use.

**Comment by miversen33** [comment]
Can you provide a minimal reproducible configuration? As it stands currently, saving a buffer while Neo-tree is open works as expected on my machine and I would assume it works as expected for a majority of users. We will need some more info in order to diagnose this

**Comment by Maritsu** [comment]
```lua
require('packer').startup({function(use)
	use 'wbthomason/packer.nvim'
	use {
		'nvim-neo-tree/neo-tree.nvim',
		branch - 'v2.x'
	}
end})

vim.g.neo_tree_remove_legacy_commands = 1
require('neo-tree').setup({
	window = {
		width = 45,
		mappings = {
			["<cr>"] = "open_with_window_picker"
		},
	},
	filesystem = {
		visible = true,
		hide_dotfiles = false,
		hide_hidden = false,
	},
})
vim.keymap.set("n", "<leader>nf", ":Neotree left reveal filesystem<CR>")
```

**Comment by pysan3** [comment]
Do you have these dependencies installed?
And be sure that you can successfully `require` them. (Be careful with lazy loading)

```lua
      "nvim-lua/plenary.nvim",
      "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
      "MunifTanjim/nui.nvim",
      {
        -- only needed if you want to use the commands with "_with_window_picker" suffix
        's1n7ax/nvim-window-picker',
        tag = "v1.*",
        config = function()
          require'window-picker'.setup({
            autoselect_one = true,
            include_current = false,
            filter_rules = {
              -- filter using buffer options
              bo = {
                -- if the file type is one of following, the window will be ignored
                filetype = { 'neo-tree', "neo-tree-popup", "notify" },

                -- if the buffer type is one of following, the window will be ignored
                buftype = { 'terminal', "quickfix" },
              },
            },
            other_win_hl_color = '#e35e4f',
          })
        end,
      }
```

**Comment by miversen33** [comment]
Using your provided config with [the current stable version of neovim](https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz) (this is version 0.8.3), I am not able to replicate the described issue. 

Here is a dockerfile you can use to verify that the provided config "works" in a basic stripped down arch installation
```docker
FROM archlinux:latest

RUN \
    # Downloading dependencies
    yes | pacman -Sy wget git &&\
    # Downloading neovim
    wget -O /tmp/nvim-linux64.tar.gz https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz &&\
    # Extracting neovim
    tar -C /tmp/ -xzf /tmp/nvim-linux64.tar.gz &&\
    # Downloading gist config
    wget -O /tmp/mini.lua https://gist.githubusercontent.com/miversen33/ca6c4aece361da237728efadc4e3c18e/raw/8855a077c82f549ba2b7a471c30e13f2db321b87/lua
ENTRYPOINT ["/tmp/nvim-linux64/bin/nvim", "-u", "/tmp/mini.lua", "/tmp/testfile.lua"]
```

I do not know what is causing your issue but I don't believe it is related directly to Neo-tree itself. Maybe a rogue auto command?

**Comment by Maritsu** [comment]
> Do you have these dependencies installed?
> And be sure that you can successfully `require` them. (Be careful with lazy loading)
> 
> ```lua
>       "nvim-lua/plenary.nvim",
>       "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
>       "MunifTanjim/nui.nvim",
>       {
>         -- only needed if you want to use the commands with "_with_window_picker" suffix
>         's1n7ax/nvim-window-picker',
>         tag = "v1.*",
>         config = function()
>           require'window-picker'.setup({
>             autoselect_one = true,
>             include_current = false,
>             filter_rules = {
>               -- filter using buffer options
>               bo = {
>                 -- if the file type is one of following, the window will be ignored
>                 filetype = { 'neo-tree', "neo-tree-popup", "notify" },
> 
>                 -- if the buffer type is one of following, the window will be ignored
>                 buftype = { 'terminal', "quickfix" },
>               },
>             },
>             other_win_hl_color = '#e35e4f',
>           })
>         end,
>       }
> ```

Yep

**Comment by Maritsu** [comment]
> Maybe a rogue auto command?

Seems like it, I'll go and check later today.

**Comment by Maritsu** [comment]
It appears it was a `BufWritePost` autocmd. Done and resolved, thanks for pointing me in the correct direction!
