### ISSUE TITLE
Line relative number

### ISSUE THREAD

**Issue by lu5her-s** [nvim-neo-tree/neo-tree.nvim#757]
How or Can add line relative number to this.

**Comment by miversen33** [comment]
I don't believe there is a way baked into Neo-tree to do so. I just took a peek at the source that renders the buffer where Neo-tree lives and it doesn't appear to check the configuration for anything along those lines. If you wanted this feature, you will likely need to do a bit of other shenanigans within vim itself.

I am not super sure why one would want a number line in a tree but in the event that you do want that unfortunately there doesn't appear to be a way to accomplish this with Neo-tree itself.

I would contend this is likely out of scope of the project as well though I won't close this (I will leave that up to @cseickel who may swoop in an call me a liar and explain exactly how to do the thing I just got done saying isn't possible lol)

**Comment by miversen33** [comment]
Called it lol

**Comment by radvil** [comment]
@miversen33 dude, you missleading us newbies, lol
