### ISSUE TITLE
[Bug] Resizing in tmux pane errors

### ISSUE THREAD

**Issue by YodaEmbedding** [nvim-neo-tree/neo-tree.nvim#759]
Resizing in a tmux pane gives an error message:

```
[Neo-tree ERROR] Error in event handler for event vim_resized[table: 0x7fcde9dc7048]: ...q/.local/share/nvim/lazy/nui.nvim/lua/nui/utils/init.lua:23: Invalid window id: 1027
```

**Comment by nhat-vo** [comment]
Could you elaborate more (perhaps what you did to produce the error or your configs)?

**Comment by miversen33** [comment]
@YodaEmbedding 
I can open Neo-tree with `:Neotree` and then resize the tmux pane it is in and I do _not_ receive any vim errors. I performed a resize both horizontally and vertically, with mouse and keyboard. Please provide a minimal configuration to recreate this error.

**Comment by shibotto** [comment]
Not OP, but I can reliably reproduce it too with neo-tree float lazy loaded.

<details>
<summary>Minimal config</summary>

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  {
    "nvim-neo-tree/neo-tree.nvim",
    branch = "v2.x",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-tree/nvim-web-devicons",
      "MunifTanjim/nui.nvim",
    },
    keys = {
      { "<leader>e", "<cmd>Neotree float<cr>", desc = "NeoTree" },
    }
  }
})
```

</details>

### Steps to reproduce

1. Open Neovim
2. Open a split (either `:split` or `:vsplit`)
3. Open neo-tree float (`<leader>e` in my mapping)
4. Close neo-tree float
5. Close one of the split
6. Resize the terminal

![Schermata da 2023-02-18 21-41-09](https://user-images.githubusercontent.com/3816409/219898363-4605157b-6692-4a17-b9cc-2fe9e4fef881.png)

**Comment by nhat-vo** [comment]
Thanks a lot! I have been able to reproduce the error. This seems to be a bug with `Neotree float`, when the `nvim` window is resized (does not need to be inside a tmux session). I will have a look into this.
