### ISSUE TITLE
typo.nvim integration

### ISSUE THREAD

**Issue by axieax** [nvim-neo-tree/neo-tree.nvim#766]
Hi! I'm currently developing a plugin which aims to display a `vim.ui.select` popup after a directory netrw hijack. I've managed to make it work with both netrw and nvim-tree, but it seems that neo-tree is causing the following error since it does seem to successfully hijack in time, before the popup is displayed, whereas the popup appears after the hijack for the other plugins. I'm not sure if there is a way around this, and was wondering if you had any suggestions (or maybe a minor patch to make this compatible). Thanks!

Using a `vim.defer_fn` with a timeout of 1000, instead of `vim.schedule` [here](https://github.com/axieax/typo.nvim/blob/f58b6b68b7ccd956996726fc58d1ffdabcde5a78/lua/typo.lua#L63-L74) shows that this works after hijack.

```
Error executing vim.schedule lua callback: ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:896: Failed to se
t buffer 7
stack traceback:
        [C]: in function 'nvim_win_set_buf'
        ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:896: in function 'create_window'
        ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1051: in function 'draw'
        ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1199: in function 'show_nodes'
        ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:98: in function 'render_context'
        ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:126: in function <...ree.nvim/lua/neo-tree/sources/f
ilesystem/lib/fs_scan.lua:125>
```

Alternate solution: it seems that nvim-tree doesn't have any conflicts since it'll continue loading the hijacked directory buffer AFTER the popup. Would it be possible for neo-tree to do something similar?

**Comment by axieax** [comment]
Resolved on my end

**Comment by axieax** [comment]
Seems like `vim.ui.input` is blocking neo-tree from setting the buffer. Anything we can do to resolve this?

**Comment by axieax** [comment]
All good! I believe the issue is due to neo-tree setting the buf win with `vim.ui.input` blocking the event loop (see `:h textlock`). Ideally, I want neo-tree to set the buf (and show the tree) before `vim.ui.input` is displayed, but this is difficult due to typo.nvim's `BufWinEnter` event firing before neo-tree's `BufEnter` event (and I'm not sure whether this can be updated in the background - it works for nvim tree but maybe they do something differently?). I don't think the event is necessary if it doesn't resolve this issue, since it's the same as users disabling the `filesystem.hijack_netrw_behavior` option otherwise.

**Comment by cseickel** [comment]
I'm not fully comprehending what the situation is because I am running low on available brain power right now. Could you lay out the chain of events that is happening now and how you would ideally change it?

**Comment by axieax** [comment]
Sorry for not making this clearer before:

[typo.nvim] BufWinEnter autocmd [starts](https://github.com/axieax/typo.nvim/blob/main/lua/typo/autocmd.lua#L44)
[neo-tree] BufEnter event fires
[neo-tree] Netrw hijack occurs
[typo.nvim] vim.schedule in autocmd callback fires (https://github.com/axieax/typo.nvim/blob/main/lua/typo/autocmd.lua#L49)
[neo-tree] calls `navigate_internal`
[typo.nvim] opens `vim.ui.input` with [dressing.nvim](https://github.com/stevearc/dressing.nvim) which creates a new window
[neo-tree] another BufEnter event fires (with a different buffer and window number due to `vim.ui.input`)
[neo-tree] render_context -> create_window -> ... (stack trace from description)

**Comment by axieax** [comment]
Since `vim.ui.input` opens a new window, nvim seens to have issues with neo-tree setting the contents of the other window with `vim.api.nvim_win_set_buf`. Without using dressing.nvim to make `vim.ui.input` a floating Telescope window, this issue does not occur.

Just wondering if there is a way to perhaps update the contents of the neo-tree fs in the background, or for there to be a way to ensure that neo-tree window is updated BEFORE typo.nvim's `vim.ui.input` opens? I've tested this with nvim-tree and native netrw and they don't seem to have this conflicting issue, working as expected (i.e. buffer rendered with directory view hijack --> typo.nvim's vim.ui.input popup is displayed)

**Comment by cseickel** [comment]
I think I see what the problem could be. Neo-tree loads asynchronously, and the last thing to happen is to create the buffer. It determines what window to display itself in at that last moment by just getting whatever the currently focused window is.

I'm guessing that it is getting a window used by dressing that can't be replaced at that moment. 

This could easily happen in other situations where the tree ends up displaying in the wrong window from this kind of timing issue. What should happen is that the window to display in should be set in stone at the beginning of this chain of events instead of at the end.

This will probably fix your issue. Either way it is definitely the more correct way for neo-tree to work so I will fix that and we'll see if it helps your situation.

**Comment by cseickel** [comment]
That ended up being exceptionally easy because I was already tracking the correct window id. Can you try it out with the `main` branch and let me know how it works?

**Comment by axieax** [comment]
That explains it, and it works perfectly now! Thanks so much for investigating and fixing this!! 🎉
