### ISSUE TITLE
Prefer diagnostic icons from the config table rather than lsp signs

### ISSUE THREAD

**Issue by utilyre** [nvim-neo-tree/neo-tree.nvim#774]
Hello! Thank you for the amazing plugin.

I've defined lsp diagnostic signs not to have icons but only be a line number highlight, something like this:

```lua
vim.fn.sign_define("DiagnosticSignHint", { numhl = "DiagnosticSignHint" })
```

But then I'd like to have icons in neotree, so I configured icons but it (still) uses the sign's icon instead.

```lua
{
  default_component_configs = {
    diagnostics = {
      symbols = {
        hint = vim.g.icons.widget.inline.Hint,
        info = vim.g.icons.widget.inline.Info,
        warn = vim.g.icons.widget.inline.Warn,
        error = vim.g.icons.widget.inline.Error,
      },
    },
  },
}
```

I think neotree should prioritize configuration icons over diagnostic signs.

**Comment by pysan3** [comment]
It's not that the diagnostic signs are overwriting config values but I found a bug in a code causing this issue.

Will fix ASAP.

**Comment by pysan3** [comment]
Closing with #980
