### ISSUE TITLE
Automatic buffer cleaning after session restore should be opt-in

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#778]
@nhat-vo @cseickel this breaks when using `views` in neovim with `mkview` and `loadview`. It seems that Neo-tree now thinks that it is restoring a session, so it closes the neotree sidebar that's open even though I'm not restoring an entire session. This needs to be fixed

_Originally posted by @mehalter in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/748#issuecomment-1447124435_

**Comment by khaneliman** [comment]
This explains why neo-tree started becoming really obnoxious and closing my sidebar every time i switch to an existing buffer...

**Comment by nhat-vo** [comment]
@cseickel just want to note that in #771 I added a check to only remove the invalid neo-tree buffers. If I'm not wrong, that should fix the issues mentioned with `mkview` and `loadview`.

**Comment by cseickel** [comment]
@mehalter @khaneliman This feature is now disabled by default in version 2.52.

To enable the auto session cleanup, you will need to set this option:
```lua
  auto_clean_after_session_restore = true, -- Automatically clean up broken neo-tree buffers saved in sessions
```
