### ISSUE TITLE
Is there config to customize root node?

### ISSUE THREAD

**Issue by Orgil** [nvim-neo-tree/neo-tree.nvim#780]
Currently root node showing `cwd` as absolute path. is it possible to show as relative path?

**Comment by nhat-vo** [comment]
What do you mean by relative path? Which directory should the root be relative to?

**Comment by Orgil** [comment]
@nhat-vo actually it is not relative path. I was trying to customize how current root displayed. Currently my project folder path is under many levels of folder like `/Volumes/Projects/Folder/../project` so root node shows as full path and truncated which is really hard to see what project currently i'm in. I want to show it only current folder name instead of full path on the root node.

**Comment by cseickel** [comment]
The way to change that is to replace the `name` component with your own version that just displays the tail of the root node. It explains how to create a custom component using the `name` component as an example in the help file:
```
:h neo-tree-component 
```

Here is the code you can use as your starting point:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/aec592bb1f0cf67f7e1123053d1eb17700aa9ed4/doc/neo-tree.txt#L1536-L1563
