### ISSUE TITLE
feature: when window.position is current, don't put the tree buffer in the buffer-list and in the alternate buffer

### ISSUE THREAD

**Issue by lucax88x** [nvim-neo-tree/neo-tree.nvim#785]
While using window.position: current, let's assume I have two files, "a" and "b".

I'm on file "a", I want to go to "b" by using the tree, I'll open my tree and switch to "b".

Now, if I use C-^ for the alternate file, it will navigate to the tree buffer instead of the "a" file, and it's a bit annoying.

btw, crazy good tree, I found it to be much better and snappier than the nvim-tree!

**Comment by ajitid** [comment]
On a similar note, upon hitting `q` to `close_window`, neo-tree should restore the actual alternate file. So if I'm on "a" which has alt. file "b", and I open neo-tree and quit it using `close_window`, while it should land be back on "a", hitting `C-^` should give me "b". Right now, it tells me there's no alternate buffer. 

Neo-tree was able to do this and what the issue's author mentioned.

**Comment by cseickel** [comment]
You can probably fix these things up by handling the `neo_tree_buffer_leave` event:
```
:h neo-tree-events 
```

Not everyone would agree that this is the desired behavior so it shouldn't be the default behavior.

Personally, I navigate buffers using https://github.com/ton/vim-bufsurf and then I configure it to ignore the neo-tree buffers with:
```vim
let g:BufSurfIgnore = 'neo-tree .* \[.*\],^$'
```

**Comment by ajitid** [comment]
Thank you. @lucax88x, [these changes](https://github.com/ajitid/dotfiles/compare/048b60ee6424d78ba3042a5426b388ecb8c758e4...abce737ea98e4f8bae3973d258e41ecb77583f5b) fixes both of our issues. 

You can go fancy-schmancy with Lua but I couldn't care less and hence used `vim.fn`.

**Comment by nhat-vo** [comment]
Closing this issue as solved.

**Comment by oredaze** [comment]
I would like to know what the solution to this was. The link is dead.
