### ISSUE TITLE
NeoTreeShow is broken in the latest main

### ISSUE THREAD

**Issue by ioreshnikov** [nvim-neo-tree/neo-tree.nvim#79]
Hi!

Just updated to the latest `main` (`b580e39`) and `NeoTreeShow` command seems to be broken. `NeoTreeReveal` still works and `NeoTreeShowToggle` is still correctly closing the side-panel.

Best,
Ivan

**Comment by cseickel** [comment]
It works for me, can you provide your config? Do you get any errors?

**Comment by cseickel** [comment]
I figured it out, it's broken when using the `follow-current-file` option. I'll fix it.

**Comment by cseickel** [comment]
This should be fixed in **main** now. Can you give it a try and let me know if you see any more issues?

**Comment by ioreshnikov** [comment]
Weird thing: it opens the first time, but if I do an open-close-open sequence, then I get an error `invalid window id: 1012`. And it's always 1012 for some reason as well. `NeoTreeRevealToggle` still works, though.

**Comment by cseickel** [comment]
I get that too, different window id, but same idea. I'll figure it out.

**Comment by cseickel** [comment]
That issue is fixed now, let me know if you find anything else.

**Comment by ioreshnikov** [comment]
Yes, it's fixed! Thanks!
