### ISSUE TITLE
[Bug] neotree errors when a git repo contains any executable/binary file (.o, .exe, .elf, .a, etc)

### ISSUE THREAD

**Issue by TerrificTable** [nvim-neo-tree/neo-tree.nvim#792]
# Issue
When having some kind of executable/binary (.o, .exe, .elf, .a, etc) file in some directory, trying to open/expand that directory in NeoTree results in the below error (screenshot)

# How to reproduce
1. Compile any program (i used C/C++)
2. open the folder the compiled file was put into
3. the below error appears

![image](https://user-images.githubusercontent.com/85793326/224127975-538b98b9-553f-43e7-9da2-655206828d40.png)

## Environment
OS: Windows x64
NeoVim (v0.9.0-dev-964+g1539f7136) installed trough chocolatey
Im using packer.nvim for packages
neo-tree config: default

packer neo-tree setup: 
```lua
use { "nvim-neo-tree/neo-tree.nvim", 
  branch = "v2.x",	
  requires = {
    "nvim-lua/plenary.nvim",
    "nvim-tree/nvim-web-devicons",
    "MunifTanjim/nui.nvim",
  },
}
```

**Comment by TerrificTable** [comment]
It seems to be something with git, if i copy the folder and remote the .git folder, it works fine without error
but as soon as i initialize a git repo in that folder it starts erroring

**Comment by cseickel** [comment]
I can't recreate the issue on my computer using linux and copying the `find` executable to a git repo. I don't have a Windows computer so I can't test it there.

Based on the error message though, I would think that it is actually a problem with UTF handling in the filename. Can you confirm that the file or folder in question has some non-ascii characters? Can you give me the full path of a file that causes this error?

**Comment by TerrificTable** [comment]
the error occours when having (almost) any executable
in the screenshot it was the output of this makefile (from <https://github.com/TerrificTable/6502-Emulator>): 
```make
CXX 	 	:= g++
CXXFLAGS 	:= -std=c++20 -g -Wall -Wextra -Werror


OUT := bin/main.exe

SRC := $(wildcard src/**/*.cpp) $(wildcard src/*.cpp)
OBJ := $(patsubst src/%.cpp,bin/%.o,$(SRC))

all: $(OBJ)
	@mkdir -p $(dir $(OUT))
	$(CXX) $(CXXFLAGS) -o $(OUT) $(OBJ)
	./$(OUT)

bin/%.o: src/%.cpp
	@mkdir -p $(@D)
	$(CXX) $(CXXFLAGS) -c $< -o $@


clean:
	rm -r $(dir $(OUT))
```

**Comment by cseickel** [comment]
I think my last commit will fix this, can you try again using the `main` branch?

**Comment by TerrificTable** [comment]
Neo-tree opens, but now im getting this error when hiding/unhiding files, changing wording directory and some other things
![image](https://user-images.githubusercontent.com/85793326/226140036-a7f0aed0-62ce-4247-a6f1-cef6fbbd5497.png)

**Comment by cseickel** [comment]
I had an error there. Can you update and try again?

**Comment by TerrificTable** [comment]
it works without any errors now, but well... some files/folders are/look like they're hidden (or were hidden) even tho they dont start with a `.` nor are their names in my hidden files configuration
![image](https://user-images.githubusercontent.com/85793326/226144413-d477b1b4-66dd-46cf-84a7-768200abbd34.png)
![image](https://user-images.githubusercontent.com/85793326/226144453-976c75ba-7c07-4ebe-be9f-0904661ad236.png)
(only .git should be hidden, .gitignore and .gitmodules should be gray because they're in my hidden files configuration thingy)

**Comment by cseickel** [comment]
Those files are gitignored, you can change:
```
hide_gitignored = true,
```
if you want them to show normal.
