### ISSUE TITLE
Symbols after cyrillic 'r' become missing when renaming files

### ISSUE THREAD

**Issue by MagnetizedFreckles** [nvim-neo-tree/neo-tree.nvim#796]
### Environment

**Nvim configuration:** Neovim 0.8.3-1 from Arch repo, with [LazyVim](https://github.com/LazyVim/LazyVim) 1.18.1, mostly default config but changed colorscheme.
**Neo-tree version:** 2.52.0

### Issue

When renaming files using 'r' in the file tree, and the present filename contains cyrillic symbol 'р', letter is lost after it from the "new name" prompt, making it harder to change the filename just slightly.  

The omitted symbol can be both cyrillic and English.
If after 'р' is a hyphen or underscore, TWO symbols are lost — hyphen/underscore and anything after them. _This may happen with other special characters as well, however, I haven't checked it._

The contents of the file don't seem to make difference — this bug occured to me both with empty and populated files.

### Reproducing the bug

For this, I have created a directory with 14 empty files (for that I used 'a' in neo-tree, had no problems with that) and different filename for each one. 
All of them contain 'р' symbol.
Some of them are fully cyrillic, some are partly English; some include dashes or underscores, some aren't.
![image](https://user-images.githubusercontent.com/81415404/224417956-884d8ee4-df71-4c93-a169-acc9813ca6a2.png)

For your convenience, here are the names in the same order as in screenshot:
```
some-more-тестировние.txt
демонстрация.txt
еще-одна-проверка.txt
проверка.txt
p--.txt
p-.txt
p_.txt
p__.txt
р__english.txt
р_english.txt
рenglish.txt
работа.txt
тест_нижнее_подчеркивание.txt
четыре-е-ееее.txt
```

After that, I pressed 'r' in neo-tree on every file in directory, checking for my issue.

Here are all screenshots, with the number of lost symbols:
1. One letter
![image](https://user-images.githubusercontent.com/81415404/224420112-0948f0f6-98bc-4719-859e-aa1af9793fc7.png)
2. One letter
![image](https://user-images.githubusercontent.com/81415404/224420331-550060c2-ac2c-4557-ac6e-a25ae093425c.png)
3. Two letters (just because of two 'р')
![image](https://user-images.githubusercontent.com/81415404/224420763-6fbbad78-25e4-4d2d-97dc-54b617ec9b30.png)
4. Two letters (just because of two 'р')
![image](https://user-images.githubusercontent.com/81415404/224420931-90903493-b831-4835-a23d-b4372bb7949f.png)
5. Two dashes
![image](https://user-images.githubusercontent.com/81415404/224421023-dd226837-bfae-476d-8522-7b264b614ec3.png)
6. Two symbols, dash and dot
![image](https://user-images.githubusercontent.com/81415404/224421104-7947cebb-55a6-4491-83be-9d1a8cbb624d.png)
7. Two symbols, underscore and dot
![image](https://user-images.githubusercontent.com/81415404/224421195-4d27b348-e4fa-4840-aaab-4de5073d6b26.png)
8. Two underscores
![image](https://user-images.githubusercontent.com/81415404/224421279-c53deb14-f814-4807-b349-c48c89514341.png)
9. Two underscores
![image](https://user-images.githubusercontent.com/81415404/224421368-ee72fe43-5e74-4d94-89f7-522ad399c2d5.png)
10. Two symbols, underscore and 'e'
![image](https://user-images.githubusercontent.com/81415404/224421498-23a8e1d4-704b-44dd-b3b2-40b6ecaf9af0.png)
11. One letter
![image](https://user-images.githubusercontent.com/81415404/224421615-3ef11667-cf0c-4872-a288-c87ec84e3229.png)
12. One letter
![image](https://user-images.githubusercontent.com/81415404/224421662-6947fa2d-c3ff-471d-a321-ef09797fc002.png)
13. One letter
![image](https://user-images.githubusercontent.com/81415404/224421727-c166b8da-7e6c-46a5-9b1c-e69b6f19bdac.png)
14. One letter
![image](https://user-images.githubusercontent.com/81415404/224421827-f180f2cd-d067-43e8-9843-915addc4dab3.png)

After reloading Nvim I get all the same results.

### Conclusion

I have no idea, why this bug exists, what are the possible reasons behind it.

And also there may be other symbols like 'р', which "delete" other symbols. However, I have only noticed it happening with 'р'.

**Comment by pysan3** [comment]
Wow this is an interesting issue. 

It seems to be an issue coming from `nui.nvim` which is a plugin neo-tree depends on to open that input placeholder.

I'll open an issue over there so please wait and see what they will respond.

**Comment by pysan3** [comment]
Fixed! Thanks @MunifTanjim 

It seems I don't have the permission to close this issue.
Please close this @MagnetizedFreckles when you see this msg :)

**Comment by MagnetizedFreckles** [comment]
Thank you very much for helping to fix this issue!

**Comment by cseickel** [comment]
Thanks @pysan3!
