### ISSUE TITLE
Floating window support

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#8]
Support showing neo-tree as a floating window, as an alternative option to showing as a sidebar.

The following may be problematic:
1. One issue is that the window is currently named `split`, and should be renamed to something more generic like `window`.
2. Another issue is that the "open" commands assume it is a sidebar and choose the window to the left/right of the tree.
3. Finally, there may be issues with the other pop-up windows being used, when there are pop-ups on another pop-up.

**Comment by levouh** [comment]
+1 on this, having a floating file tree would be awesome.

**Comment by cseickel** [comment]
Do the eyes emoji mean your thinking about contributing this feature? If so, lay out your plans here so I don't interfere with any changes I end up making in the meantime.

**Comment by cseickel** [comment]
I got started on this because I was curious:
![image](https://user-images.githubusercontent.com/5160605/148484288-e87671be-caf9-449d-908e-8ec8c12d58bb.png)

There is still a fair amount of work in changing the behaviors of the open commands, placement and sizing of the window, when to close it, etc. It turns out it is really not any kind of breaking change though.

**Comment by cseickel** [comment]
Floating windows added in [Release v1.6](https://github.com/nvim-neo-tree/neo-tree.nvim/releases/tag/v1.6)
