### ISSUE TITLE
Neotree opens file buffer in terminal window when terminal window focused

### ISSUE THREAD

**Issue by airtonix** [nvim-neo-tree/neo-tree.nvim#802]
Your favourite mouth breathing, mouse using frontend developer peasant here.

![](https://api.iconify.design/noto:camping.svg?width=96)

Not sure if this is a problem with neo-tree, neovim, or just that I'm a filthy frontend developer, but: 

- be focused in a terminal window
- use the unclean dirty mouse to move hover over the neotree window 😄 
- use the mouse to double click 😱 on a file
- see that your terminal window is now a confusing `not-a-terminal-window` 😭 

Should this be some kind of : 

- bug fix in neo-tree
- an `autocmd` that something something something sprinkle-vim-sorcery force open in non-terminal window? 
- something else?

**Comment by cseickel** [comment]
You finally convinced me to do something about this even though it doesn't matter to me one bit. I guess it's because your issue was entertaining and I just can't get enough of well placed emojis.

Anyhow, neo-tree will now avoid replacing certain buffers based on their filetypes. If you want to control which filetypes it will avoid, change this new config option:

```lua
require("neo-tree").setup({
  open_files_do_not_replace_filetypes = { "terminal", "trouble", "qf" }, -- when opening files, do not use windows containing these filetypes
})
```

**Comment by cseickel** [comment]
Correction, **now** it will work, and the option has been renamed to:

```lua
require("neo-tree").setup({
  open_files_do_not_replace_types = { "terminal", "trouble", "qf" }, -- when opening files, do not use windows containing these filetypes or buftypes
})
```

**Comment by airtonix** [comment]
![image](https://user-images.githubusercontent.com/61225/224588931-46518772-64c1-45f3-9093-098f8b9575f6.png)
