### ISSUE TITLE
How can I install this plugin using vim-plug?

### ISSUE THREAD

**Issue by orsenthil** [nvim-neo-tree/neo-tree.nvim#807]
Is it possible to install this plugin using [vim-plug](https://github.com/junegunn/vim-plug) ?

**Comment by nhat-vo** [comment]
I personally don't use vim-plug, but maybe
```
Plug "nvim-lua/plenary.nvim"
Plug "nvim-tree/nvim-web-devicons"
Plug "MunifTanjim/nui.nvim"
Plug "nvim-neo-tree/neo-tree.nvim", { branch = "v2.x" }
```
Does this work for you?

**Comment by devenv** [comment]
@nhat-vo Works great, a small syntax fix though:
```
Plug "nvim-lua/plenary.nvim"
Plug "nvim-tree/nvim-web-devicons"
Plug "MunifTanjim/nui.nvim"
Plug "nvim-neo-tree/neo-tree.nvim", { branch = "v2.x" }
```

**Comment by nhat-vo** [comment]
@devenv Thanks for the fix! It's been a while since I use Vimscript, so I completely forgot about `"` vs `'` 😅

Closing this issue as solved.
