### ISSUE TITLE
how to increase zindex of neotree?

### ISSUE THREAD

**Issue by RAprogramm** [nvim-neo-tree/neo-tree.nvim#812]
[Screencast_00002.webm](https://user-images.githubusercontent.com/70325462/225833557-9ba811e7-3753-4813-b78f-66d19bc56593.webm)

i set up zindex of terminal with animation to 1 and neotree still under it

**Comment by cseickel** [comment]
It looks to me like neo-tree is a sidebar and your animation is a floating window. If that is the case, z-index is not relevant since a normal window can never display above a floating window under any circumstance.
