### ISSUE TITLE
Error executing vim.schedule lua callback in the latest version from nui.nvim

### ISSUE THREAD

**Issue by lucax88x** [nvim-neo-tree/neo-tree.nvim#822]
Since yesterday I'm getting the following error:

<img width="1719" alt="Screenshot 2023-03-21 at 19 08 16" src="https://user-images.githubusercontent.com/6294464/226702182-826ac097-d906-4412-8e35-fb4c83a89f7b.png">

I guess there's some breaking changes from nui?

**Comment by cseickel** [comment]
The most important part of that message is cutoff. Can you post the full message, particularly the top line?

I just updated this morning and I'm not getting that error, so I think it's something other than a breaking change in nui.

**Comment by lucax88x** [comment]
for some reason notify is showing a different error.. interesting.

I had to remove it and noice in order to show the real message..

[Neo-tree ERROR] debounce  filesystem_navigate  error:  ...zi/.local/share/nvim/lazy/nui.nvim/lua/nui/tree/init.lua:185: missin
g bufnr

**Comment by benplante** [comment]
Hi, I'm noticing this issue as well. It happens if I open nvim on a directory and if I run the 'Neotree' command with no arguments. I found that the commit fee76c06e2bfd7d3dbb39b197fc208f6d5c0410c introduced the error message for me though since that commit only adds minimal error checking I'm guessing the issue is somewhere else. Minimal config to reproduce is below.

`packer.lua`
```
local fn = vim.fn
local packer_install_path = fn.stdpath('data') ..'/site/pack/packer/start/packer.nvim'
local packer_compile_path = fn.stdpath('config') .. '/lua/packer_compiled.lua'

if fn.empty(fn.glob(packer_install_path)) > 0 then
  packer_bootstrap = fn.system({ 'rm', '-f', packer_compile_path })
  fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', packer_install_path})
  print "Installing packer, close and reopen nvim"
  vim.cmd [[packadd packer.nvim]]
end

if fn.filereadable(packer_compile_path) == 1 then
  require('packer_compiled')
end

vim.cmd [[
  augroup packer_user_config
    autocmd!
    autocmd BufWritePost packer.lua source <afile> | PackerSync
  augroup end
]]

local ok_packer, packer = pcall(require, 'packer')
if not ok_packer then
  return
end
local ok_util, util = pcall(require, 'packer.util')
if not ok_util then
  return
end

packer.init({
  compile_path = packer_compile_path,
  profile = {
    enable = true
  },
  display = {
    open_fn = function()
      return util.float({
        border = 'single',
        height = math.ceil(vim.o.lines * 0.5),
      })
    end,
  },
})

packer.startup(function(use)
  use { 'wbthomason/packer.nvim' }

  use {
    'nvim-neo-tree/neo-tree.nvim',
    branch = 'v2.x',
    requires = {
      'nvim-lua/plenary.nvim',
      'kyazdani42/nvim-web-devicons',
      'MunifTanjim/nui.nvim'
    },
    config = require('benpl.neo-tree'),
  }

  if packer_bootstrap then
    require('packer').sync()
  end
end)
```

`neo-tree.lua`
```
return function()
  vim.cmd [[let g:neo_tree_remove_legacy_commands = 1]]

  vim.fn.sign_define("DiagnosticSignError",
    { text = " ", texthl = "DiagnosticSignError" })
  vim.fn.sign_define("DiagnosticSignWarn",
    { text = " ", texthl = "DiagnosticSignWarn" })
  vim.fn.sign_define("DiagnosticSignInfo",
    { text = " ", texthl = "DiagnosticSignInfo" })
  vim.fn.sign_define("DiagnosticSignHint",
    { text = "", texthl = "DiagnosticSignHint" })

  require('neo-tree').setup {
    log_level = "trace",
    log_to_file = true,
    enable_git_status = true,
    enable_diagnostics = true,
    sort_case_insensitive = false,
    windows = {
      position = "current"
    },
    filesystem = {
      netrw_hijack_behavior = 'open_current',
      use_libuv_file_watcher = true,
    }
  }

end
```
neo-tree logs of the issue are attached below.

[neo-tree.nvim.log](https://github.com/nvim-neo-tree/neo-tree.nvim/files/11042164/neo-tree.nvim.log)

**Comment by lucax88x** [comment]
Was able to track it down.. this happens when position = "current"

**Comment by cseickel** [comment]
I don't have the same problem. I'd bet it's caused by an interaction with another plugin.

What happened in the commit that @benplante identified is that I started using the window id that was current at the moment that the Neotree command was issued, whereas before this I was using the window that was current after the asynchronous loading of files is complete, just as neo-tree is about to be rendered.

If you have a session manager or lots of pop ups with status updates then they could be getting in the way and causing conflicts.

**Comment by benplante** [comment]
Unfortunately, I'm still noticing the error when I started fresh with a new user in MacOS 13 and ran nvim with exactly the `init.lua` shown below. Opening nvim with a directory passed argument or running `:Neotree` or `:Neotree [filesystem|git_status|buffers]` when `window.position = 'current'` seems to cause the command to fail and print the error message as @lucax88x mentioned.
```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  "nvim-neo-tree/neo-tree.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "nvim-tree/nvim-web-devicons",
    "MunifTanjim/nui.nvim",
  },
  config = function()
    require("neo-tree").setup({
      window = {
	position = "current"
      }
    })
  end
})
```

**Comment by benplante** [comment]
I spent some time digging through the neo-tree codebase and I think I understand why this is happening, though I have zero experience writing neovim plugins so in all likelihood I'm wrong about this. 

In [lua/neo-tree/command/init.lua line 75-80](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/20c2f2f5ba083bbb1e37b8bc3d590621434f31e9/lua/neo-tree/command/init.lua#L75) `manager.get_state()` is only called with the current window id if the `position=current` argument is set in the command line thus `state.id` differs from the current window id when the `:Neotree` is executed without a position arg and `config.window.position = 'current'`.

**Comment by cseickel** [comment]
What happens is that for any positions other than "current", the tree belongs to the tab and there is only one instance per tab, so the id is the current tabnr. For position=current however, there can be one tree per window so the id is the winid for the window that the tree was opened in.

When the window is eventually created, all other position types just create or reuse a window based on the window position specified, while position = current is for the specific winid of the window that the command was issued in. In the case where the window focus is changed after the command is issued, using the id of the state insures that the tree is opened in the correct window and not some popup window that opened automatically at the wrong time.
