### ISSUE TITLE
Highlight symbolic links in different color

### ISSUE THREAD

**Issue by mriva** [nvim-neo-tree/neo-tree.nvim#823]
Is it possible to have symlinks highlighted in a different color than regular files?

I tried changing `NeoTreeSymbolicLinkTarget` highlight group but that seems to have no effect.

**Comment by mriva** [comment]
How can I detect when an object is a symlink? I tried `node.type == "symlink"` as a guess based on `file_type_map` in `filter_external.lua` but it's not working.

**Comment by cseickel** [comment]
> How can I detect when an object is a symlink? I tried `node.type == "symlink"` as a guess based on `file_type_map` in `filter_external.lua` but it's not working.

Use `node.is_link`. Also, `node.link_to` will give you the target of the link if you need it.
