### ISSUE TITLE
Switching <source> to <buffers> and then using <toggle> does not work well

### ISSUE THREAD

**Issue by Sleepful** [nvim-neo-tree/neo-tree.nvim#824]
Replicate:

`Neotree buffers`: shows buffers, this is ok.
`Neotree toggle`: does not toggle, instead it opens the filesystem view, not ok.

Alternative:
`Neotree buffers`
`Neotree close`
`Neotree show`: does not open back in `buffers`, it opens in filesystem.

**Comment by nhat-vo** [comment]
Closing this as solved.
