### ISSUE TITLE
How to set the background transparent of neotree panel?

### ISSUE THREAD

**Issue by shawnbreak** [nvim-neo-tree/neo-tree.nvim#825]
<img width="886" alt="image" src="https://user-images.githubusercontent.com/38004716/227707370-be5fff5b-643e-4417-8842-202c344b109c.png">

**Comment by cseickel** [comment]
You probably just need to set your theme before calling neo-tree's setup function. You can also set the highlight groups manually, see `:h neo-tree-highlights` for a list of highlight groups being used.

**Comment by jrock2004** [comment]
So I am using a transparency plugin and I have the following config but neotree is still not transparent. Maybe I have the wrong highlight groups?

```
return {
  "xiyaowong/transparent.nvim",
  extra_groups = {
    "NeoTreeNormal",
    "NeoTreeNormalNC",
    "NormalFloat",
  },
}
```

**Comment by thechucklingatom** [comment]
I use the same transparency plugin, and I was able to solve this using this config.
```
-- File: lua/custom/plugins/transparent.lua

return {
  "xiyaowong/transparent.nvim",
  config = function()
    require('transparent').setup {
      extra_groups = {
        "NeoTreeNormal",
        "NeoTreeNormalNC",
        "NormalFloat",
      },
    }
  end,
}```
