### ISSUE TITLE
Remove prefix in window title

### ISSUE THREAD

**Issue by Hacksore** [nvim-neo-tree/neo-tree.nvim#827]
This is a great plugin for a new vimer!

One thing I was looking around for is there any way to disable the prepended string when the tree is focused?

<img width="840" alt="image" src="https://user-images.githubusercontent.com/996134/227725336-68f5f9f9-217d-45f0-803d-2695fcb26d29.png">

**Comment by nhat-vo** [comment]
In (neo)vim's design, everything is a buffer, and each opened buffer must have a name. The `Neotree` pane that you see is a buffer, named `neo-tree filesystem [1]`. There is no way to remove this name.

You can, however, suppress this name from being displayed. For example, in this case, you can have a look at `:h titlestring`. You can wrap this in an `autocmd` with `BufEnter` to change the window's title dynamically.

**Comment by Hacksore** [comment]
These are great pointers @nhat-vo, really appreciate it.

Since this is not an issue with neo-tree I can close this out while I attempt to make a lua function to do this.
