### ISSUE TITLE
Auto coalesce nested folders when using `group_empty_dirs`

### ISSUE THREAD

**Issue by oddlama** [nvim-neo-tree/neo-tree.nvim#832]
I sometimes have to work with java projects, which have deeply nested folder structures, where many folders are completely empty except for a subfolder. `group_empty_dirs` is an awesome feature to tame that mess. What I'd wish neo-tree would do is to automatically peek into encountered folders to see whether they are otherwise empty, so that I don't have to enter each stage manually. It should be easy to detect this and would be a great UX improvement for `group_empty_dirs`. What do you think?

![image](https://user-images.githubusercontent.com/31919558/228087683-e60e3761-a982-4961-8e74-b639e92e2fa4.png)
[Enter]
![image](https://user-images.githubusercontent.com/31919558/228087702-5478c7e1-d9a8-410e-b810-d917e8f13177.png)
[Enter]
![image](https://user-images.githubusercontent.com/31919558/228087731-f86f8bbe-e335-4865-8532-88b568a6fd19.png)
[Enter]
![image](https://user-images.githubusercontent.com/31919558/228087788-5b9f0cd3-6812-4e4b-bb3b-fad9571bbead.png)

Neo-tree has been absolutely awesome and that's one of the only things I'm missing since I switched from nvim-tree last year. Thanks for making it.

**Comment by ghostbuster91** [comment]
It seems that it has been somehow address by https://github.com/nvim-neo-tree/neo-tree.nvim/pull/600 

You can enable it by setting:
```
        filesystem = {
            group_empty_dirs = true,
            scan_mode = "shallow",
        },
```

It is not the same though as it clutters the view on start with all these empty nodes being collapsed and visible.

**Comment by pysan3** [comment]
Thanks @ghostbuster91 !

Does this achieve what you need @oddlama ?
