### ISSUE TITLE
Getting error: No editor command Neotree.

### ISSUE THREAD

**Issue by pawelurbanski** [nvim-neo-tree/neo-tree.nvim#839]
I am experiencing the following error and behavior:

1. Neo-vree used ot work in either 0.8.3 or 0.9.0 (nightly) - tested in March 2023,
2. It suddenly stopped working without introducing changes to setup options or init.lua file,
3. Running tests from the /pack/wsl/start/neo-tree.nvim where I cloned the repository passes without errors.

Requiring the neo-tree module w a protected call returns true and the Neo-tree's table with exported API. Calling setup() with or without options does not remove hte error.

What are the more detailed debug steps I could take ot resolve this problem?

Thank you for your effort, time and commitment to this great plugin...
Pawel

**Comment by cseickel** [comment]
Can you provide more detail about what you are doing to get that error? It kind of sounds like it isn't installed. Could it be that it is configured to load lazily with packer or lazy and that is what has changed?

**Comment by pawelurbanski** [comment]
Hi,
My init.lua is as simple as it can be - just some 8 key mappings since I use Colemak layout.
I don't use a package manager. The folder structure in my configuration directory is also bare minimum for I am developing a plugin. I'm using native loadin gmechanism, namely the /pack/<dir>/start/neo-vree structure. The other plugins that are loaded are: nvim-cmp, cmp-buffer and nvim-lspconfig. I load the Neo-tree dependencies as well. All are checked out in the `start` folder so there should not be lazy loading.

The only thing that could mess things up is appending the path of a plugin I'm working on to a runtime path.

```lua
vim.opt.runtimepath:append('/mnt/d/work/neovim/<mane-of-my-plugin>')
```

When I do the following there are no errors:

```lua
local loaded, neoTree = pcall(require, 'neo-tree')
```

Then I instantiate Neo-tree with defaults:

```lua
neoTree.setup()
```

loaded is true and neoTree is a table and Neovim's commandline prompt does complete functions and variables. Unfortunately the error is very stubborn. What is puzzling, Neo-tree used to work like a beautiful charm...

**Comment by cseickel** [comment]
What if you use the lua api instead?

```lua
:lua require("neo-tree.command").execute()
```

**Comment by miversen33** [comment]
@pawelurbanski 

I have produced a _very_ simple config that requires no package manager and manages loading neo-tree and its dependencies into the neovim space for you.

```lua
-- Minimal configuration
-- mini.lua

local mod_path = '/tmp/nvim_mods'
if vim.loop.fs_stat(mod_path) then
    -- Clearing out the mods directory and recreating it so 
    -- you have a fresh run everytime
    vim.fn.delete(mod_path, 'rf')
end

vim.fn.mkdir(mod_path, 'p')

local modules = {
    'nvim-lua/plenary.nvim',
    'nvim-tree/nvim-web-devicons',
    'MunifTanjim/nui.nvim',
    'nvim-neo-tree/neo-tree.nvim'
}
for _, module in ipairs(modules) do
    local module_name = module:match('/(.*)')
    local module_path = string.format('%s/%s', mod_path, module_name)
    if not vim.loop.fs_stat(module_name) then
        -- The module doesn't exist, download it
        vim.fn.system({
            'git',
            'clone',
            string.format('https://github.com/%s', module),
            module_path
        })
        print(string.format("Downloaded %s", module_name))
    end
    vim.opt.runtimepath:append(module_path)
end

-- We should be able to safely assume everything exists and is pathed correctly
local loaded, neoTree = pcall(require, 'neo-tree')
if not loaded then
    vim.notify('Unable to load neo-tree!', vim.log.levels.ERROR)
    return
end

-- Setting up neotree
neoTree.setup()
print("Loaded Neotree!")

```

I can confirm that this works on the latest stable version of neovim
```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az183-550

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

Can you give this config a shot and see if you still experience the issue you described? To ensure a perfectly clean environment, I would use the `-u mini.lua` and `--clean` flags. So for example
```shell
$ nvim -u mini.lua --clean
```

Once it has loaded up (you will see a thing print telling you its loaded Neo-tree), run the `:Neotree` command and let me know if you still get your error.

The idea behind this is, lets try to isolate where your issue is occuring

**Comment by pawelurbanski** [comment]
Dear Mike,
Yes, your config works. I will take things step by step now.
Remove Neovim and all directories - I can do i tfor it is my development setup. Clone dependencies, Neo-tree and make shure it works.
Once it is completed setup nvim-cmp with its basic LSP support.

I am really puzzeled by this behavior since my init.lua has a handful remaps due ot using the fantastic Colemak layout. I am appending hte path for my custom plugin but it is not doing anything drastic: not loading libraries or any magic. While Neovim is fantastic I started developing htis plugin as my first one. I therefore kept the setup to the bare minimum.

Neo-tree is fantastic, I just need to digg a little bit more... :)

**Comment by miversen33** [comment]
Well at this point, unless you provide a configuration that we can use to reproduce your issue, I'm afraid all we can do is say it's a problem with your configuration and this issue is invalid.

If you can provide a configuration that reproduces this, I'd be more than happy to work through it and see if I can find your problem. As it stands though, I am reasonably confident this is not a neo-tree issue and can be closed as invalid
