### ISSUE TITLE
Neotree setting position=current is broken

### ISSUE THREAD

**Issue by keturiosakys** [nvim-neo-tree/neo-tree.nvim#845]
Hi! Just wanted to report that since about a couple of weeks ago Neotree breaks if it's declared to open as part of the existing buffer (Netrw-like)`window = { position = "current" }`. Here's the error I'm getting when trying to run `:Neotree toggle` after that.

<img width="1594" alt="CleanShot 2023-04-05 at 09 35 47@2x" src="https://user-images.githubusercontent.com/17225208/230043198-7599ef70-f1e9-45bb-b708-12f8e13e0815.png">

Curiously, running `:Neotree show position=current` works fine...🤔

Steps to reproduce the issue:
1. Install Neotree + nui dependencies
2. In the settings set the following:
```lua
require("neo-tree").setup({
  window = {
    position = "current"
  }
})
```
3. Run `:Neotree toggle`

**Comment by cseickel** [comment]
I can recreate the problem. Interestingly, it works fine if you include the position as an arg to the command. This is how my mappings are set which is why I never noticed:

```
:Neotree toggle current
```

I'll fix this soon.
