### ISSUE TITLE
buffers tab empty in fvim wsl astronvim

### ISSUE THREAD

**Issue by gralech** [nvim-neo-tree/neo-tree.nvim#849]
Good day!

windows10, fvim + wsl Ubuntu 20.04 + nvim 0.8.3 + astronvim
neo-tree buffers tab empty

but if i start nvim in wsl, without fvim frontend - neo-tree buffers tab work as expected

any advice?

**Comment by nhat-vo** [comment]
Which wsl version are you using? I'm using wsl2 on windows11 with nvim nightly, and things seem to be working fine.
![image](https://user-images.githubusercontent.com/30724347/230735182-6412ad07-5256-47bf-ab8a-471e18e5624f.png)

**Comment by gralech** [comment]
Good day, thank you for your response!

I'm using wsl2
wsl.exe -l -v
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  docker-desktop-data    Stopped         2
  docker-desktop         Stopped         2

I managed to resolve issue by running:
 wsl --update

previous version:
wsl.exe --version
WSL version: 1.1.6.0
Kernel version: 5.15.90.1
WSLg version: 1.0.50
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.2728

now version:
wsl.exe --version
WSL version: 1.2.0.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.2728

Buffers tab now working.

Thank you!
