### ISSUE TITLE
cannot use copy_to_clipboard

### ISSUE THREAD

**Issue by sf8193** [nvim-neo-tree/neo-tree.nvim#850]
whenever i try to copy to clipbaord i get no feedback. My clipboard doesn't change. Is there a way to override which register `copy_to_clipboard` copies to? I see that sometimes it does get copied, just not into the register i want

happy to provide any logs just tell me what will be helpful

**Comment by nhat-vo** [comment]
@sf8193 I think there is some confusion here. The word "clipboard" in `copy_to_clipboard` doesn't refer to vim's registers. Rather, it is more of a neo-tree's clipboard, in the sense that you mark files to be used for later operations like `paste_to_clipboard`. 

So for example, you can do `copy_to_clipboard` for file `a`, then go into folder `b` and `paste_to_clipboard` to copy it there. This behavior can be more intuitive than having to specify a location to paste to like `copy` do. The details of these commands are specified in the [docs](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/2b2f74828eeb02cf29d6b21aa32eedadadc94ca7/doc/neo-tree.txt#L272-L278):
```
y    = copy_to_clipboard:    Mark file to be copied.
                             Supports visual selection.~

x    = cut_to_clipboard:     Mark file to be cut (moved).
                             Supports visual selection.~

p    = paste_from_clipboard: Copy/move each marked file to the selected folder.
```

Does this answer your question?

**Comment by sf8193** [comment]
ah that does answer my question. is there a way to copy to a register? Copy doesn't seem to do it either

**Comment by nhat-vo** [comment]
@sf8193 I'm not sure what you want to do by "copy to a register". If you want to copy the path to the file, you can create a custom command as below. You can also modify the register to copy to and what to copy.
```lua
require("neo-tree").setup({
	filesystem = {
		window = {
			mappings = {
				["y"] = "yank_path",
			},
		},
		commands = {
			yank_path = function(state)
				-- copy path of current node to unnamed register
				vim.fn.setreg("", state.tree:get_node().path)
			end
		},
	},
})
```

**Comment by nhat-vo** [comment]
Closing this as solved
