### ISSUE TITLE
How to change color of folder

### ISSUE THREAD

**Issue by kaykhan** [nvim-neo-tree/neo-tree.nvim#854]
Im attempting to migrate from nvim-tree to neo-tree and just looking for some help on how to do 2 things;

1. Change the color of the folders

I would like the colors folder color to be blue but by default it appears to be green.

2. Change the position of the github/diagnostic icons

Is it possible for the icon position to be shown at the front (before the filename).

Left (nvim-tree) Right (neo-tree)
![image](https://user-images.githubusercontent.com/5202527/230765180-91fa23aa-4d9e-49d0-8e31-2365d9624933.png)

thank you.

**Comment by nhat-vo** [comment]
@kaykhan Regarding the folder colors, you can modify the highlight groups `NeoTreeDirectoryIcon` and `NeoTreeDirectoryName` to your liking. A complete list of highlight groups can be viewed [here](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/ui/highlights.lua#L12-L13).

For the diagnostic/git status icons, you can modify the renderers like this
```lua
require("neo-tree").setup({
  renderers = {
    directory = {
      { "indent" },
      { "icon" },
      { "current_filter" },      
      { "diagnostics", errors_only = true, hide_when_expanded = true },
      { "git_status", hide_when_expanded = true },
      { "name" },
      { "clipboard" },
    },
    file = {
      { "indent" },
      { "icon" },
      { "diagnostics" },
      { "git_status" },
      { "name" },
      { "clipboard" },
      { "modified" },
    },
  },
})
```

Have a look at [here](https://github.com/nvim-neo-tree/neo-tree.nvim#configuration-and-customization) and the [wiki](https://github.com/nvim-neo-tree/neo-tree.nvim/wiki) for these customizations.
