### ISSUE TITLE
alway_show directories are gray

### ISSUE THREAD

**Issue by mvolkmann** [nvim-neo-tree/neo-tree.nvim#863]
I have the following in my configuration for neo-tree. It makes it always show my `user` directory, but it is gray instead of the color used for other directories. What do I need to do to tell neo-tree that it shouldn't tree that directory differently from other directories?

```lua
return {
  "nvim-neo-tree/neo-tree.nvim",
  opts = function()
    return {
      filesystem = {
        filtered_items = {
          always_show = { "user" }
        }
      }
    }
  end
}
```

**Comment by miversen33** [comment]
The few other times this has popped up, it has been because of a stray `.gitignore` file laying around. Can you verify that there isn't a `.gitignore` hanging out in your `user` directory?

**Comment by miversen33** [comment]
RE: #731, #792, #508,

**Comment by mvolkmann** [comment]
@miversen33 Looking at those previous issues helped! My `~/.config/nvim/lua/user` directory is not hidden if I delete the line `lua/user` from `~/.config/nvim/.gitignore` file. But do you think that is a good way to achieve the goal of not hiding the `user` directory?

**Comment by miversen33** [comment]
@mvolkmann It depends.

You have 2 options.

1) Remove the item from your gitignore as Neo-tree by default respects gitignore (honestly something I don't really like, which leads nicely into option 2)  
2) [Take a peek at the readme](https://github.com/nvim-neo-tree/neo-tree.nvim#quickstart) and use the `filesystem.filtered_items.hide_gitignored = false` configuration option to not hide your git ignored files

```lua
require("neo-tree").setup({
    filesystem = {
        filtered_items = {
            hide_gitignored = false
        }
    }
})
```
Refer to `:h neo-tree-filtered-items` for details on this :)

Does that answer your question?

**Comment by mvolkmann** [comment]
Yes, thanks!
