### ISSUE TITLE
Foldcolumn getting overriden and not restored

### ISSUE THREAD

**Issue by mehalter** [nvim-neo-tree/neo-tree.nvim#867]
Similar to #684, I noticed that for some reason `neo-tree` is overriding `foldcolumn` and not restoring it. Here is a minimal `init.lua` file that is able to replicate this. All it does is set up neo-tree with `netrw` hijacking and then sets `foldcolumn=1`.

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--branch=stable",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  {
    "nvim-neo-tree/neo-tree.nvim",
    dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
    opts = {
      filesystem = {
        hijack_netrw_behavior = "open_current",
      },
    },
  },
})

vim.opt.foldcolumn = "1"
```

### Steps to Replicate

1. Use this minimal `init.lua`
2. run `nvim` and see that `:set foldcolumn` shows it's set to `1` which is what we want
3. Close Neovim and rerun with the `netrw` hijacking: `nvim .`
4. See `:set foldcolumn` shows `0` which makes sense in the file browser, select a file and see that `:set foldcolumn` is still showing `0`

**Comment by miversen33** [comment]
@mehalter are we clear to close this given the merging of #868 ?

**Comment by mehalter** [comment]
Yup good to close with that! Looking forward to a release with that :)

**Comment by miversen33** [comment]
Wonderful!
