### ISSUE TITLE
Warning on open: `[WARN] .../neo-tree.lua/lua/neo-tree/ui/renderer.lua:450: Invalid mapping for %s: %s S nil`

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#87]
<img src="https://user-images.githubusercontent.com/24765272/150649157-2ea68e52-b267-4a09-83d2-a3a9f2e7ac3a.png" width="1000">

Error message to copy:

```
[WARN] .../neo-tree.lua/lua/neo-tree/ui/renderer.lua:450: Invalid mapping for %s: %s S nil
```

I have tried this, which doesn't work:

```
vim.keymap.set('n', ';', "<cmd>silent! lua require('neo-tree').float(nil, true)<CR>", {noremap=true, nowait=true, silent=true})
```

#### NVIM Version
```
NVIM v0.7.0-dev+913-ge07a4b97f
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by cseickel** [comment]
Have you defined custom mappings where S is assigned to nil?

**Comment by nyngwang** [comment]
> Have you defined custom mappings where S is assigned to nil?

Exactly.

**Comment by cseickel** [comment]
That should work without errors. This must be a bug, I'll take a look.

**Comment by cseickel** [comment]
As it turns out, it is all working as expected, it is just a nuisance warning that should not be there. You can ignore it for now, I'll remove it in the next release.

**Comment by nyngwang** [comment]
Just confirmed this works, thanks for your fix :)
