### ISSUE TITLE
Neo-tree source selector crashes with user provided external sources

### ISSUE THREAD

**Issue by miversen33** [nvim-neo-tree/neo-tree.nvim#873]
Related: https://github.com/miversen33/netman.nvim/issues/155

When providing a "third party" source, the source selector appears to fail on loading the state of that source.

The specific error being thrown is
```
E5108: Error executing lua ...nvim/lazy/neo-tree.nvim/lua/neo-tree/sources/manager.lua:39: attempt to index local 'state' (a nil value)
stack traceback:
        ...nvim/lazy/neo-tree.nvim/lua/neo-tree/sources/manager.lua:39: in function 'create_state'
        ...nvim/lazy/neo-tree.nvim/lua/neo-tree/sources/manager.lua:111: in function 'get_state'
        ...re/nvim/lazy/neo-tree.nvim/lua/neo-tree/command/init.lua:79: in function 'execute'
        ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/selector.lua:384: in function <...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/selector.lua:373>
```

That gibberish may not make a ton of sense so below I will attempt to explain what I am seeing and what I believe the problem is.

-----

In order to provide a third party source, a user must specify that source in their neo-tree configuration. This is usually done as follows
```lua
require("neo-tree").setup({
    sources = {
        "path.to.custom.source", -- The third party source we care about
    }
})
```

Following the setup path, this module is checked [here](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/0a2e518d3169aeb62d544329e6aa1a1925d1e0fd/lua/neo-tree/setup/init.lua#L527-L543)
```lua
    else
      -- fully qualified module name
      -- or just a root level module name
      is_external_ns, module = pcall(require, source)
      if is_external_ns then
        name = module.name or name
        all_sources[name] = source
      else
        log.error("Source module not found", source)
        name = nil
      end
    end
    if name then
      default_config[name] = module.default_config or default_config[name]
      table.insert(all_source_names, name)
    end
  end
```

The important bit to note here is how `name` is being populated and used later.
If not provided, name defaults to the last bit of the module path (though this is just to clarify what name will be here, it doesn't have a ton of importance).
Name default source: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/0a2e518d3169aeb62d544329e6aa1a1925d1e0fd/lua/neo-tree/setup/init.lua#L515-L516

```lua
    local parts = utils.split(source, ".")
    local name = parts[#parts]
```

Notice that if a name is found, a configuration is loaded and stored for that source based on its **name**? Keep that in mind.

---

[Moving forward to the source selector generation](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/e865e11006c7a11f3d027eec9f56e043c252f4ce/lua/neo-tree/ui/selector.lua#L91-L131)

```lua
---get_selector_tab_info:
-- Returns information to create a tab
---@param source_name string: name of source. should be same as names in `config.sources`
---@param source_index integer: index of source_name
---@param is_active boolean: whether this source is currently focused
---@param separator table: `{ left = .., right = .. }`: output from `get_separators()`
---@return table (see code): Note: `length`: length of whole tab (including seps), `text_length`: length of tab excluding seps
local get_selector_tab_info = function(source_name, source_index, is_active, separator)
  local config = require("neo-tree").config
  local separator_config = utils.resolve_config_option(config, "source_selector", nil)
  if separator_config == nil then
    log.warn("Cannot find source_selector config. `create_selector` abort.")
    return {}
  end
  local get_strlen = vim.api.nvim_strwidth
  local text = separator_config.tab_labels[source_name] or source_name
  local text_length = get_strlen(text)
  if separator_config.tabs_min_width ~= nil and text_length < separator_config.tabs_min_width then
    text = M.text_layout(text, separator_config.content_layout, separator_config.tabs_min_width)
    text_length = separator_config.tabs_min_width
  end
  if separator_config.tabs_max_width ~= nil and text_length > separator_config.tabs_max_width then
    text = M.text_layout(text, separator_config.content_layout, separator_config.tabs_max_width)
    text_length = separator_config.tabs_max_width
  end
  local tab_hl = is_active and separator_config.highlight_tab_active
    or separator_config.highlight_tab
  local sep_hl = is_active and separator_config.highlight_separator_active
    or separator_config.highlight_separator
  return {
    index = source_index,
    is_active = is_active,
    left = separator.left,
    right = separator.right,
    text = text,
    tab_hl = tab_hl,
    sep_hl = sep_hl,
    length = text_length + get_strlen(separator.left) + get_strlen(separator.right),
    text_length = text_length,
  }
end
```

So to generate the sources for the winbar, we are pulling the sources (by module path) out of the loaded neo-tree configuration. [The source selection code is below](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/e865e11006c7a11f3d027eec9f56e043c252f4ce/lua/neo-tree/ui/selector.lua#L371-L389)

```lua
-- @v:lua@ in the tabline only supports global functions, so this is
-- the only way to add click handlers without autoloaded vimscript functions
_G.___neotree_selector_click = function(id, _, _, _)
  if id < 1 then
    return
  end
  local sources = require("neo-tree").config.sources
  local winid, source_index = calc_source_from_click_id(id)
  local state = manager.get_state_for_window(winid)
  if state == nil then
    log.warn("state not found for window ", winid, "; ignoring click")
    return
  end
  require("neo-tree.command").execute({
    source = sources[source_index],
    position = state.current_position,
    action = "focus",
  })
end
```

When a source is selected, we pull the source and execute a focus event on that source. 

Digging down the stack a bit, while this focus event is being executed, the neo-tree source manager attempts to get the current state of the selected source (either by fetching the state or creating a new one. In either case we get the above crash so it doesn't really matter).

When the manager attempts to create the state for the first time, it passes the source name to the internal `create_state` function within [`neo-tree.sources.manager`](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/2b2f74828eeb02cf29d6b21aa32eedadadc94ca7/lua/neo-tree/sources/manager.lua#L36-L48)
```lua
local function create_state(tabnr, sd, winid)
  local default_config = default_configs[sd.name]
  local state = vim.deepcopy(default_config, { noref = 1 })
  state.tabnr = tabnr
  state.id = winid or tabnr
  state.dirty = true
  state.position = {
    is = { restorable = false },
  }
  state.git_base = "HEAD"
  table.insert(all_states, state)
  return state
end
```

The crash is happening on the third line of this function, where we attempt to index the newly created `state` object by deepcopying the `default_configs[sd.name]` object.

Ok so to wrap this back around, `sd.name` is the literal source path as that is what is found in `require("neo-tree").config.sources`. So the code is trying to fetch (in my above example) `default_configs["path.to.custom.source"]`. **HOWEVER** if you recall, the configuration for this source is _actually_ located at `default_configs["source"]` as the name is assumed to be either the _last item_ in the module path, or a name provided with the module. In either case though, we are specifically looking for the source of the module path, which is incorrect.

----

I do not have a "simple" way to reproduce this, however I can replicate this behavior with the aforementioned `netman` external source (which is how I ended up here). I will work to create a simple external source to replicate this behavior, however you can also simply download the netman plugin, add `netman.ui.neo-tree` as a source to neo-tree and you should be able to replicate this behavior.

I don't know the best way to address this. There are a few spots this could be addressed, however a byproduct of us using the source path for the selector is that we also get some nasty names displayed, as we are not respecting the source name

![image](https://user-images.githubusercontent.com/2640668/232235474-1142ed6e-f4f0-4d04-9da4-f101194b5751.png)

I would think we should have `get_selector_tab_info` use the name of the source instead of the path as the default.

Something like
```lua
-- https://github.com/nvim-neo-tree/neo-tree.nvim/blob/e865e11006c7a11f3d027eec9f56e043c252f4ce/lua/neo-tree/ui/selector.lua#L106
-- local text = separator_config.tab_labels[source_name] or source_name
local text = separator_config.tab_labels[source_name] or ???
```
The main issue I see with this solution is that there doesn't appear to be any sort of "mapping" that we save to indicate a "short form name" (selector name) to the selector module path. It might be worth adding the full path to the source in its config? We can then simply iterate over the available source configurations to match a config up with the source and then pull the correct name out? This might also be a solve problem elsewhere that I am not seeing, I'm not completely sure.

Thoughts? This seems like bad behavior but I could also have something misconfigured.

**Comment by miversen33** [comment]
Ok so I have created a dummy extension that does absolutely nothing and can replicate this issue. You can find the "source" here
https://github.com/miversen33/neo-tree-dummy-extension

To use it, the below `init.lua` script can be used (the same what I include in the readme of the repo)
```lua
-- Minimal configuration
-- mini.lua
-- Use with the --clean -u flags. EG nvim --clean -u mini.lua
-- This config will create a temp directory and will blow away that temp directory
-- everytime this configuration is loaded. Great for simulating a new installation
-- of a plugin

-- Setting some basic vim options
vim.opt.termguicolors = true
-- If you want to play around with this, you can set the do_clean
-- variable to false. This will allow changes made to
-- underlying plugins to persist between sessions, while
-- still keeping everything in its own directory so
-- as to not affect your existing neovim installation.
--
-- Setting this to true will result in a fresh clone of
-- all modules
local do_clean = true

-- Dummy var to make the dummy extension not provide a name
-- Set this to true to make the dummy extension not provide a name
-- otherwise it will provide the name "dummy"
-- vim.g.neo_tree_dummy_extension_no_name = true

local sep = vim.loop.os_uname().sysname:lower():match('windows') and '\\' or '/' -- \ for windows, mac and linux both use \

local mod_path = string.format("%s%sclean-test%s", vim.fn.stdpath('cache'), sep, sep)
if vim.loop.fs_stat(mod_path) and do_clean then
    print("Found previous clean test setup. Cleaning it out")
    -- Clearing out the mods directory and recreating it so 
    -- you have a fresh run everytime
    vim.fn.delete(mod_path, 'rf')
end

vim.fn.mkdir(mod_path, 'p')

local modules = {
    {'nvim-lua/plenary.nvim'},
    {'nvim-tree/nvim-web-devicons'},
    {'MunifTanjim/nui.nvim'},
    {'nvim-neo-tree/neo-tree.nvim', branch = "v2.x", mod = "neo-tree"},
    {'miversen33/neo-tree-dummy-extension'}
}

for _, module in ipairs(modules) do
    local repo = module[1]
    local branch = module.branch
    local module_name = repo:match('/(.*)')
    local module_path = string.format('%s%s%s', mod_path, sep, module_name)
    if not vim.loop.fs_stat(module_name) then
        -- The module doesn't exist, download it
        local cmd = {
            'git',
            'clone'
        }
        if branch then
            table.insert(cmd, '--branch')
            table.insert(cmd, branch)
        end
        table.insert(cmd, string.format('https://github.com/%s', repo))
        table.insert(cmd, module_path)
        vim.fn.system(cmd)
        local message = string.format("Downloaded %s", module_name)
        if branch then
            message = string.format("%s on branch %s", message, branch)
        end
        print(message)
    end
    vim.opt.runtimepath:append(module_path)
end

print("Finished installing plugins. Beginning Setup of plugins")

for _, module in ipairs(modules) do
    if module.mod then
        print(string.format("Loading %s", module.mod))
        local success, err = pcall(require, module.mod)
        if not success then
            print(string.format("Failed to load module %s", module.mod))
            error(err)
        end
    end
end

-- --> Do you module setups below this line <-- --

local neo_tree = require("neo-tree")


neo_tree.setup({
    source_selector = {
        winbar = true,
    },
    sources = {
        "neo-tree-dummy-extension"
    },
})

-- --> Do your module setups above this line <-- --

print("Completed minimal setup!")
```

To use this, open your neovim instance with the `--clean -u mini.lua` flag. Once it completes run
`:Neotree toggle` and you will see the exact same crash as indicated in this bug report.

**Comment by cseickel** [comment]
I'd say that the right thing to do here is to make sure that an external source is always referred to by it's name and never by the path to the module. The path to the module should only ever be used in the user config sources list as a means the identify the extension to be enabled. After setup is complete, it should always be keyed/referred to by its name.

There should probably also be a separate "display name" that is provided by the extension and used in the source selector tabs.

**Comment by miversen33** [comment]
I will see about a PR (famous last words).

I'm thinking, should I close out #479 and just include that logic in this PR? The entire PR will be broken after this change anyway and honestly I need to redo that PR as it is given the feedback that was provided and the fact that its been sitting forever lol

**Comment by cseickel** [comment]
This is definitely an overlap. I would say you should either update that PR to include these changes or just start a new one and reference that PR to link up the discussions that have happened around this. Whatever works best for you.

**Comment by miversen33** [comment]
Fun fact!

Turns out omitting `filesystem` from your `sources` in your user config also breaks the source selector as it assumes `filesystem` will exist. That is actually what is breaking in the above minimal configuration. Its the exact same error so I assumed it was the fact that my third party module was breaking it, but it is infact because the source selector is looking for the filesystem module (or rather, the `neo-tree.config.default_source` module, which happens to be `filesystem` by default).

So there are a handful of issues that need to be addressed with the source selector. I will see if I can get that issue addressed as well

**Comment by miversen33** [comment]
@cseickel 

I assume this is intentional but I wanted to check with you.

[In the initial setup of neo-tree, there is a section where we load the sources](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/0a2e518d3169aeb62d544329e6aa1a1925d1e0fd/lua/neo-tree/setup/init.lua#L514)

```lua
for _, source in ipairs(user_config.sources or default_config.sources) do
```

So in short, we are _either_ using the user provided sources **or** the default sources that we have included in Neo-tree. This makes sense, but then we [go on to use `"filesystem"` as our default source](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/89761951fa6d6a17b569fe7189a9bfb0c76b2cf1/lua/neo-tree/defaults.lua#L17) assuming it will exist. However if the user doesn't specify `filesystem` in their user provided configuration and we don't merge the user provided sources with the default sources, its possible that our default source doesn't exist. 

This causes errors down the road, for example [in `neo-tree.command`](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/ce1e4165b6887b05dff3a4e050840d41e0424cd4/lua/neo-tree/command/init.lua#L21-L27)
```lua
---  source = string   The source to use for this action. This will default
---                    to the default_source specified in the user's config.
---                    Can be one of:
---                    "filesystem",
---                    "buffers",
---                    "git_status",
--                     "migrations"
```

Here we are making the assumption that the user set a `default_source` or that one of our default sources exist. Its absolutely possible that neither are the case, and we don't currently check for that.

------

Thoughts on throwing an error on Neo-tree setup if there is no **valid** `default_source` set?

For the above test, I have updated it to include the `filesystem` source (so that it is valid for this test)

**Comment by cseickel** [comment]
> Thoughts on throwing an error on Neo-tree setup if there is no valid default_source set?

I think that it would be a better user experience if the default source doesn't exist or is invalid, then it will be selected for you as the first source in the list of available sources.

**Comment by miversen33** [comment]
> I think that it would be a better user experience if the default source doesn't exist or is invalid, then it will be selected for you as the first source in the list of available sources.

Just to argue my position for a sec ;)

If a user is providing a list of sources to use instead of the defaults, IMO it should be fair to toss an error that they also need to provide a default source.

That said, if you do not agree, I will put a bit of logic in to "pick" a default source if we don't have one.

**Comment by cseickel** [comment]
How about we split the difference? Pick a default source and then log a warning about it?

**Comment by miversen33** [comment]
Works for me :)

I will include that in this PR as well since its in the general same area I am working in. I should have a PR up soon ish for review (once I get that handled)

**Comment by miversen33** [comment]
@cseickel did you want me to close this out? Given that I added a new "feature" (attribute that sources can provide), I feel like I should document that somewhere but I don't really know where.

**Comment by cseickel** [comment]
@miversen33 close if it's fixed! As far as documentation, there is an example source at https://github.com/nvim-neo-tree/example-source, which should probably be linked to from somewhere in the main project if it's not already.

**Comment by miversen33** [comment]
[Submitted a PR](https://github.com/nvim-neo-tree/example-source/pull/1) to get the doc for `display_name` added :)
