### ISSUE TITLE
Issues "rerendering" state on `navigate` event.

### ISSUE THREAD

**Issue by miversen33** [nvim-neo-tree/neo-tree.nvim#887]
RE: [Netman issue #154](https://github.com/miversen33/netman.nvim/issues/154)

I am having some issues understanding how sources are "meant" to rerender their tree on a `navigate` event.

I am currently having navigate called for all open events and it turns out that is incorrect and bad behavior (which is why my state is constantly being reset). Taking a look at how other sources manage this, they seem to have their own `open` function that is called with the various `open` commands.

Cool, makes sense to me. However, I cannot seem to figure out how to rerender the tree state as it was "previously" when a user left the source.

The wording here might not make a ton of sense so pictures are good.

A user navigates to something within the `Netman` source.
![image](https://user-images.githubusercontent.com/2640668/233500077-6a4ec7a0-b301-40e6-9cd6-f793846cc592.png)

They change sources
![image](https://user-images.githubusercontent.com/2640668/233500175-918f9da0-016c-43ad-90a1-3966dde12bb5.png)

And then they navigate back to the `Netman` source.
![image](https://user-images.githubusercontent.com/2640668/233500219-de8f0d08-7381-4a6e-a3b1-7e6f6870814b.png)

Of course this is my code doing this, but I don't understand the "proper" way to rerender the tree back out, so I just have it redoing the entire start of the tree again. What is most frustrating is I can see the tree has the nodes still in it from the previous state. In fact, attempting to add one of those nodes back to the tree with the same ID throws a fun error stating its already in the tree (because of course, it is). However, I cannot get the tree associated with the state to render back into the buffer.

I have attempted the following things
- Extracting the nodes from the tree and readding the entire tree
    - Ended up with the fun above error of "This node is already in the tree"
- Simply calling `require("neo-tree.ui").renderer.redraw(state)`
    - This just closed the Neo-tree buffer and left me with an empty buffer
- Calling `state.tree:render()`
    - This throws an error stating the buffer ID is invalid.
    
I'm sure this is simple but god help me if I can't figure this out. What am I missing?

**Comment by cseickel** [comment]
Actually, the other sources just start from scratch every time and don't really have any state to worry about. The only exception is the filesystem source which just remembers what folders were opened and reapplies those open folders as it's loading. There is no attempt to save and restore the Nui TreeNodes though.

**Comment by miversen33** [comment]
Got it, so this isn't a solved problem. Or rather, this isn't a problem for any other sources within Neo-tree. Fun! Well I will close this out and bang my head against the wall for a bit :joy:

**Comment by cseickel** [comment]
Where I would go with this is to make it so the existing buffer is reused instead of discarding it like may be happening now. That combined with the existing `state` is all you really need to pick up where you left off. If you use position = "current" and just manually switch buffers using plain vim methods (like `:b#`) you'll probably find it works fine and your state is saved. The source selector is a little bit of a hack and should be re-worked to just switch buffers instead of recreating the whole thing.

**Comment by miversen33** [comment]
> Where I would go with this is to make it so the existing buffer is reused instead of discarding it like may be happening now

My checking into this, the buffer is indeed discarded after source switch. Which seems expensive. I might dig into that a bit, mainly for selfish reasons as I don't feel like doing a whole bunch of extra expensive work lol. At worst though, if I can figure out how to clear the tree out, I do have the full serialized tree I can re-render. The main issue with this is that the nodes will have the same ID and for some reason the tree seems to maintain the nodes even with `nilling` the tree out, setting the nodes to `{}`, etc. Likely some closure shenanigans making my changes void but still lol.
