### ISSUE TITLE
Paths with parentheses on Windows cannot be opened

### ISSUE THREAD

**Issue by SilverMira** [nvim-neo-tree/neo-tree.nvim#889]
Hi, I noticed this bug while using Neotree in a Sveltekit project, where routes can be grouped in a folder with parentheses in its name. This bug only happens on Windows presumably due to the backslash path separator is escaping the opening parentheses somehow.

![image](https://user-images.githubusercontent.com/66930495/233666722-7d796401-b3b0-42d7-b9f2-74d346bfdf4c.png)

Notice how Neotree opened a buffer at `outer(inner)\file.txt` instead of `outer\(inner)\file.txt`. Additionally, I discovered that `:e outer\(inner)\file.txt` in a `nvim --clean`  instance is also unable to open the file, whereas `:e outer\\(inner)\\file.txt` can, perhaps a fix can be implemented by escaping all backslashes from the path on Windows before opening the file.

**Comment by miversen33** [comment]
This is a plenary issue. As an example, I have the following directory structure on a windows machine
```
C:\Users\miver\Application Data
C:\Users\miver\Cookies
C:\Users\miver\dummy(file).txt
C:\Users\miver\Local Settings
C:\Users\miver\My Documents
C:\Users\miver\OneDrive
C:\Users\miver\Recent
C:\Users\miver\SendTo
C:\Users\miver\Start Menu
C:\Users\miver\Templates
```

And running the following lua code
```lua
local Path = require("plenary.path")
local scandir = require("plenary.scandir").scan_dir
print(scandir(vim.loop.cwd(), { depth = 1}))
```

I get the following output

```lua
{ "C:\\Users\\miver\\Application Data", "C:\\Users\\miver\\Cookies", "C:\\Users\\miver\\dummy(file).txt", "C:\\Users\\miver\\Local Settings", "C:\\Users\\miver\\My Documents", C:\\Users\\miver\\OneDrive", C:\\Users\\miver\\Recent", "C:\\Users\\miver\\SendTo", "C:\\Users\\miver\\Start Menu", "C:\\Users\\miver\\Templates" }
```

Notice that `dummy(file).txt` is not escaped? I will open an issue with plenary. This is not something we should fix (within Neo-tree anyway).

**Comment by SilverMira** [comment]
With the directory structure that you have, I believe Neo-tree can open `dummy(file).txt` perfectly fine. 

In my testing, the bug only occurs if the path contains a `(` directly after the path separator `\` no matter if the segment that starts with `(` is a file or directory.

If the cwd is at `D:\projects\test`, opening the following files will result in opening a wrong buffer at
```
D:\projects\test\(test).txt -> D:\projects\test(test).txt
D:\projects\test\(test)\file.txt -> D:\projects\test(test)\file.txt
D:\projects\test\folder\(test).txt -> D:\projects\folder(test).txt
```

**Comment by miversen33** [comment]
I have recreated the issue. Below is a minimal configuration that can reliably reproduce it.
```lua
-- Minimal configuration
-- mini.lua
-- Use with the --clean -u flags. EG nvim --clean -u mini.lua
-- This config will create a temp directory and will blow away that temp directory
-- everytime this configuration is loaded. Great for simulating a new installation
-- of a plugin

-- Setting some basic vim options
-- Some junk because I am sick of formatting tables in print
local _print = _G.print
local clean_string = function(...)
    local args = { n = select("#", ...), ... }
    local formatted_args = {}
    for i=1, args.n do
        local item = select(i, ...)
        if not item then item = 'nil' end
        local t_type = type(item)
        if t_type == 'table' or t_type == 'function' or t_type == 'userdata' then
            item = vim.inspect(item)
        end
        table.insert(formatted_args, item)
    end
    return table.concat(formatted_args, ' ')
end
_G.print = function(...)
    _print(clean_string(...))
end

vim.opt.mouse = 'a'
vim.opt.termguicolors = true
-- If you want to play around with this, you can set the do_clean
-- variable to false. This will allow changes made to
-- underlying plugins to persist between sessions, while
-- still keeping everything in its own directory so
-- as to not affect your existing neovim installation.
--
-- Setting this to true will result in a fresh clone of
-- all modules
local do_clean = true

local sep = vim.loop.os_uname().sysname:lower():match('windows') and '\\' or '/' -- \ for windows, mac and linux both use \

local mod_path = string.format("%s%sclean-test%s", vim.fn.stdpath('cache'), sep, sep)
if vim.loop.fs_stat(mod_path) and do_clean then
    print("Found previous clean test setup. Cleaning it out")
    -- Clearing out the mods directory and recreating it so 
    -- you have a fresh run everytime
    vim.fn.delete(mod_path, 'rf')
end

vim.fn.mkdir(mod_path, 'p')

local modules = {
    {'nvim-lua/plenary.nvim'},
    {'nvim-tree/nvim-web-devicons'},
    {'MunifTanjim/nui.nvim'},
    {'nvim-neo-tree/neo-tree.nvim', branch='v2.x', mod = 'neo-tree'},
}

for _, module in ipairs(modules) do
    local repo = module[1]
    local branch = module.branch
    local module_name = repo:match('/(.*)')
    local module_path = string.format('%s%s%s', mod_path, sep, module_name)
    if not vim.loop.fs_stat(module_name) then
        -- The module doesn't exist, download it
        local cmd = {
            'git',
            'clone'
        }
        if branch then
            table.insert(cmd, '--branch')
            table.insert(cmd, branch)
        end
        table.insert(cmd, string.format('https://github.com/%s', repo))
        table.insert(cmd, module_path)
        vim.fn.system(cmd)
        local message = string.format("Downloaded %s", module_name)
        if branch then
            message = string.format("%s on branch %s", message, branch)
        end
        print(message)
    end
    vim.opt.runtimepath:append(module_path)
end

print("Finished installing plugins. Beginning Setup of plugins")

for _, module in ipairs(modules) do
    if module.mod then
        print(string.format("Loading %s", module.mod))
        local success, err = pcall(require, module.mod)
        if not success then
            print(string.format("Failed to load module %s", module.mod))
            error(err)
        end
    end
end

-- --> Do you module setups below this line <-- --

local neo_tree = require("neo-tree")


neo_tree.setup(
{
    sources = {
        "filesystem",
    },
    filesystem = {
        follow_current_file = true,
    },
}
)

-- --> Do your module setups above this line <-- --

print("Creating Environment to emulate #889")
vim.fn.delete('./test', 'rf')
vim.fn.mkdir('./test/outer/(inner)', 'p')
local h = nil
h = io.open('./test/outer/(inner)/file.txt', 'w')
h:write("file.txt content\n")
h:close()
h = io.open('./test/outer/test.txt', 'w')
h:write("test.txt content\n")
h:close()
vim.api.nvim_command('cd ./test/')
print("Created environment")
print("Completed minimal setup!")
```

**Comment by miversen33** [comment]
Alright so after alot of digging into the source, I can verify this is an escaping issue of some kind. The file we are trying to open (in this case) is

> .\test\outer\(inner)\file.txt

If you try to open that in vim itself (the command we generate is just `:e .\test\outer\(inner)\file.txt`), vim does not throw up, but it does _not_ open the file and an `ls` of the open buffers shows
```vim
:ls
  1 %a   "~\test\outer(inner)\file.txt" line 1
```

Whats really weird (and what led me initially to believe this was a plenary issue) is that we are _not_ manually performing any escapes. We are in fact allowing [vim to escape the filename for us](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/utils.lua#L542) which in this case produces ` .\test\outer\(inner)\file.txt`. So this is most likely an upstream issue in vim itself. That said, the fix here is probably reasonably simple and something we can put in place right after the above listed line. Something that auto escapes `\(` and `\)` if they aren't already escaped. I will see if I can figure out a string glob for that.

In the mean time, @cseickel any thoughts on this? Am I completely lost and there is a more sensible solution here?

**Comment by cseickel** [comment]
@miversen33 I would first check the neovim repo for issue. Regardless of when it might be fixed, just the discussion there could be very informative.

As far as escaping ourselves, I wonder if there is any built-in vim or lua function that already exists and can handle all edge cases?

**Comment by miversen33** [comment]
Good call! Seems [#3912](https://github.com/neovim/neovim/issues/3912) is what is biting us here. 

To the second point, I am not terribly well versed in the apis that vim provides (I always forget all kinds of shit exists). To the lua side, not really. At least not without an external library. I did a bit of testing with `plenary.path` but it produces the same kind of "improperly" escaped path when using `plenary.path:new(path):absolute()`. The issue isn't exactly that the path is being improperly escaped (hence the quotes above), but more so that the parenthesis are _technically_ already escaped due to their location in the path string. 

I think if we want to resolve this specific issue, we will need to either

a) Wait until the above `fnameescape` behavior is patched upstream  
b) Add a work around and do the escape ourselves.

**Comment by cseickel** [comment]
Well, that issue hasn't been touched since 2015, so I wouldn't hold my breath. I guess we can put in our own special handling. I don't like it, but I don't see another solution.

**Comment by treturner** [comment]
Just checking in to see if there's been any updates to thus issue? I've recently moved over to NextJS's app directory and it sucks not being able to open directories surrounded by parentheses.

**Comment by miversen33** [comment]
I'll be honest, I completely forgot about this. I'll throw it near the top of things to do this week. It seems past me apparently had figured this out so it should just be implementation of a glob replacement. I'll let you know when I get a branch up and tested

**Comment by SilverMira** [comment]
For the time being I have just stuck this inside my config, very naive approach but works well enough for me, fixes `Telescope find_files` for opening `\(` files too.
```lua
-- FIXME: this is a workaround for inconsistent file opening behavior on Windows
if vim.fn.has("win32") then
  local ori_fnameescape = vim.fn.fnameescape
  ---@diagnostic disable-next-line: duplicate-set-field
  vim.fn.fnameescape = function(...)
    local result = ori_fnameescape(...)
    return result:gsub("\\", "/")
  end
end

```

**Comment by miversen33** [comment]
I haven't had a ton of time to work on this this week (I decided to hurt myself in the middle of the week and have been away from my computer) but in the bit of time I have had, I am working through trying to verify which cases we need to escape. Which is proving a bit more difficult than I would like.

Taking your example filestructure for this issue, I added a file called `(inner2)` which should _not_ be escaped
![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/2640668/84400acb-3f19-4de9-a20f-1e60ade1a9a7)

The code we create needs to be able to figure out which of these it should escape and which it should not. Unfortunately simply adding the path escape above to all will likely not work. Though I am glad that it is a valid workaround for your specific situation :)

**Comment by gabemcguire** [comment]
> ```lua
> if vim.fn.has("win32") then
>   local ori_fnameescape = vim.fn.fnameescape
>   ---@diagnostic disable-next-line: duplicate-set-field
>   vim.fn.fnameescape = function(...)
>     local result = ori_fnameescape(...)
>     return result:gsub("\\", "/")
>   end
> end
> ```

THANK YOU!!

**Comment by Ngdaz** [comment]
Till get error to open the file inside app router nextJS, is there any help   
![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/47729815/9e02d3d7-5b20-4c7c-98a8-46c646e5a6ee)
