### ISSUE TITLE
[Bug] Cannot :tabnew from neo-tree buffer

### ISSUE THREAD

**Issue by levouh** [nvim-neo-tree/neo-tree.nvim#89]
Using a minimal configuration such as:

```lua
vim.cmd("packadd plenary.nvim")
vim.cmd("packadd neo-tree.nvim")

require("neo-tree").setup({})
```

located in something like `/tmp/neo-tree.lua`, perform the following:

1. `nvim --noplugin -u /tmp/neo-tree.lua`
2. Open a file somewhere in the current working directory
3. `:NeoTreeFocus`
4. `:tabnew`

Observe that no tab is actually opened, and the `neo-tree` buffer is now closed.

---

Is this reproducible for others?

**Comment by cseickel** [comment]
Confirmed.

**Comment by levouh** [comment]
Doing `:9verbose tabnew` shows what all is being triggered, although I'm sure you might already have some ideas.

**Comment by cseickel** [comment]
Yeah, it is a problem with the logic that prevents other buffers from stealing neo-tree's window. I just need to figure out the right logic for new tabs.

**Comment by cseickel** [comment]
This also pointed me to a much more serious bug when opening a file with neo-tree as the only window, it created a never ending loop of new splits. I'm going to push this fix right out to v1.x very soon.
