### ISSUE TITLE
Help, how do I change positions of these things? I am completely lost

### ISSUE THREAD

**Issue by AnezeR** [nvim-neo-tree/neo-tree.nvim#890]
<img width="252" alt="image" src="https://user-images.githubusercontent.com/31391185/233741199-2630ae71-475b-462b-b838-91676cf499b9.png">

**Comment by miversen33** [comment]
Take a peek at `:h neo-tree-source-selector`

Also the [the defaults](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/defaults.lua#L48-L58) to see how it is currently configured.

**Comment by AnezeR** [comment]
```lua
      source_selector = {
        winbar = true,
        content_layout = "center",
        tab_labels = {
          filesystem = get_icon "FolderClosed" .. " File",
          buffers = get_icon "DefaultFile" .. " Bufs",
          git_status = get_icon "Git" .. " Git",
          diagnostics = get_icon "Diagnostic" .. " Diagnostic",
        },
      },
```  
This is the code in my neo-tree.lua file, and the tabs are in the correct order.
They, however, seem to be shuffling seemingly randomly sometimes, and I have no idea why, but I reckon this is not the defaults problem.
I can try and send the whole file, but I'm pretty much sure it is the [default config file created by astronvim](https://github.com/AstroNvim/AstroNvim/blob/08a57a6c80b8397d24f0d98c421c58124cf937c4/lua/plugins/neo-tree.lua)

**Comment by miversen33** [comment]
Are you pinned to a specific commit? `source_selector.tab_labels` was deprecated in commit [92624d0](https://github.com/nvim-neo-tree/neo-tree.nvim/commit/92624d0952aec2b187af1520acd2af08f7a635dc) so you _should_ be seeing a warning telling you to stop using `tab_labels`.

Also note, the default link I provided you above (which specifically is linked to the source selector bit) does _not_ include `tab_labels`.

Please revisit the above documentation link. Consider updating your neo-tree version if you are pinned to a commit that is older than whatever the head of the [`v2.x`](https://github.com/nvim-neo-tree/neo-tree.nvim/tree/v2.x) branch is and see if your issue goes away.

**Comment by miversen33** [comment]
Unceremoniously closing this. If you still have this issue @AnezeR , please comment and I will reopen it.
