### ISSUE TITLE
Rename a file (and also move) check is not case-sensitive

### ISSUE THREAD

**Issue by Divinato** [nvim-neo-tree/neo-tree.nvim#893]
Hi, I'm on macOS and when I try to rename (or move) a file "driving.tsx" to "Driving.tsx" I get the warning "path/Driving.tsx already exists" and so no action.

I have search where the check is done and I think that "loop.fs_stat" are not case-sensitive :
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/7a6b0d43d70636edfec183fb49c02f725765da73/lua/neo-tree/sources/filesystem/lib/fs_actions.lua#L546

**Comment by Shougo** [comment]
Because your FS is not case sensitive.
driving.tsx and Driving.tsx are same name.

**Comment by Divinato** [comment]
I didn't even think it was possible not to be...
Thanks for the explanation 👍
