### ISSUE TITLE
[Feature request] Allow hiding the source selector depending on different positions

### ISSUE THREAD

**Issue by akinsho** [nvim-neo-tree/neo-tree.nvim#895]
The main use case for this feature request is that when running neo-tree in a float or more commonly for me the current position if I navigate into a directory, I don't need or want to see the source selector since the only source I want in this case is the filesystem, In this case I want neo tree to be as simple as possible and find the selectors confusing to see in this context. I think it would be nice to optionally not display it in certain circumstances.

**Comment by miversen33** [comment]
IMO the best way to approach this would be to not show the source selector if the user manually specifies a source.

EG

-- No source selector
> :Neotree filesystem

-- Source Selector
> :Neotree
> :Neotree toggle

@cseickel @nhat-vo thoughts?

**Comment by cseickel** [comment]
@miversen33 I don't think that would work for everyone that wants to use the source selector. My first solution would be to see if this special case can be handled with an event handler like `neo_tree_window_before_open` or `neo_tree_buffer_enter`. Maybe the source selector config for the state can be enabled/disabled in one of those events before it even gets applied.

If enough people want this specific condition, then we could add an option to the source selector config to specify what positions it is enabled for.

**Comment by akinsho** [comment]
I think having to manually disable it in a callback of some kind might be complicated for the user to implement since they have to write the logic to determine if they've just entered a directory (I'm fine to do that but think it might tough for anyone new to neovim who wanted the same thing). Unless there was something like:
```lua
 neo_tree_directory_entered = function(state)
   state.source_selector = false
 end
```
Although I think in terms of sane default, seems like people generally wouldn't have a need for the selector when navigating into a directory and rather than there being any hoops, the selector just doesn't show in the specific context of opening neovim in the current window. I think no other (n)vim explorer plugins do anything like this i.e. showing a winbar in this context so presumably generally people won't expect to have one. 


As a side note, it doesn't also actually scale well to being open at this size (each tab is gigantic, although this isn't really my main motivation)

<img width="965" alt="image" src="https://user-images.githubusercontent.com/22454918/234022912-990be4e8-de33-4fdd-b157-2c42bff253cd.png">

**Comment by cseickel** [comment]
> I think having to manually disable it in a callback of some kind might be complicated for the user to implement since they have to write the logic to determine if they've just entered a directory (I'm fine to do that but think it might tough for anyone new to neovim who wanted the same thing)

At this point, I'm working under the assumption that this is not a common enough preference to warrant adding another option to the config, which si why I'm thinking through whether there are existing extensionn points you can use to customize this for yourself.I think that most people tend to be either sidebar or current window users, and to be honest I don't get the distinction of why the filesystem would be treated differently than other sources. That a very personal choice to me.

If enough other people chime on with agreement that this configuration is wanted, then I would accept that PR.

**Comment by akinsho** [comment]
Very fair, tbh I haven't a clue how other people use this functionality, perhaps they are either or users as you say. Definitely not pressing the point. I sort of assumed that if any user of `neo-tree` navigated into a directory for any reason e.g. `nvim .` then if they were also a user of the source selector, they would get the experience I'm describing (assuming that netrw is disabled and opening in the current dir is the default behaviour).

Re. the rationale for treating the filesystem source differently. It's not really about the filesystem explorer specifically but the way the tree is being shown. There desire is something like "if a source is full window, it would be nice to have a distraction free mode i.e. remove the source selector, and if applicable (but isn't) other decorations"

As you say it's pretty hard to know if it's just me so fair enough to see if anyone else reports something like this 🤷🏾‍♂️

**Comment by miversen33** [comment]
Personally I like the idea of being able to conditionally toggle the source selector on/off. I don't know that we should include that functionality directly (IE I don't know if we should expose a configuration option that does this). There are loads of events that are thrown in neo-tree, I think this is a great place to use the event system (they are synchronously thrown, so you can rely on your response to an event being reflected in the render of the tree).

**Comment by pysan3** [comment]
I think you can call the setup function anytime you want to overwrite the existing config.

So you can do something like this in the event handler.

```lua
      {
        event = "before_render",
        handler = function(state)
          -- whatever *not* condition
          if not vim.tbl_contains(vim.fn.argv(), ".") then
            return
          end
          require("neo-tree").setup({
            source_selector = {
              winbar = false,
            },
          })
          vim.wo.winbar = "" -- delete winbar set previously
        end,
      },
```

Besides, there are plenty options to configure how the tabs are laid out.
I think `tab_max_width` will be useful in your situation.

```lua
    content_layout = "start", -- only with `tabs_layout` = "equal", "focus"
    --                start  : |/ 裡 bufname     \/...
    --                end    : |/     裡 bufname \/...
    --                center : |/   裡 bufname   \/...
    tabs_layout = "equal", -- start, end, center, equal, focus
    --             start  : |/  a  \/  b  \/  c  \            |
    --             end    : |            /  a  \/  b  \/  c  \|
    --             center : |      /  a  \/  b  \/  c  \      |
    --             equal  : |/    a    \/    b    \/    c    \|
    --             active : |/  focused tab    \/  b  \/  c  \|
    truncation_character = "…", -- character to use when truncating the tab label
    tabs_min_width = nil, -- nil | int: if int padding is added based on `content_layout`
    tabs_max_width = nil, -- this will truncate text even if `text_trunc_to_fit = false`
```

**Comment by pysan3** [comment]
As #1187 is merged, you can now use `:Neotree selector=false` to disable source selector for that tree. 

I believe this feature fulfills this feature request so I'll close this issue.
