### ISSUE TITLE
[Feature request] Show file system stat in preview

### ISSUE THREAD

**Issue by ideless** [nvim-neo-tree/neo-tree.nvim#913]
It would be really helpful if neo-tree could offer a way to view fs stat. Sometimes I need to check the size, modification time, or other details of a file, and it is a hassle to open a terminal, type or navigate to the specific folder to get the information.

A natural solution could be to display the stat in the preview window. When the preview is toggled, the neo-tree could display the contents of a file if the selected node is a file, or the fs stat if the selected node is a folder. [telescope-file-browser.nvim](https://github.com/nvim-telescope/telescope-file-browser.nvim) is using this logic too.  Here is their [demo](https://user-images.githubusercontent.com/39233597/149016073-6fcc9383-a761-422b-be40-17d4b854cd3c.gif).

**Comment by pysan3** [comment]
It would be a hassle if we need to add more functionality to the preview window but if your purpose is just to view the details, you could add your own command like below.

I believe this would be an _adequate_ solution for your case.

```lua
    filesystem = {
      window = {
        mappings = {
          ["S"] = "show_fs_stat",
        },
      },
      commands = {
        show_fs_stat = function(state)
          local node = state.tree:get_node()
          vim.notify(vim.inspect(vim.loop.fs_stat(node.path)))
        end,
      },
    },
```

**Comment by ideless** [comment]
@pysan3 Cool! I also did some formating so that the result is more readable. Here's what I end up with, if anyone needs it:
```lua
filesystem = {
  window = {
    mappings = {
      ["i"] = "show_fs_stat",
    },
  },
  commands = {
    show_fs_stat = function(state)
      local node = state.tree:get_node()
      local stat = vim.loop.fs_stat(node.path)
      local str = ""
      str = str .. string.format("Type: %s\n", stat.type)
      str = str .. string.format("Size: %s\n", utils.format_size(stat.size))
      str = str .. string.format("Time: %s\n", utils.format_time(stat.mtime.sec))
      str = str .. string.format("Mode: %s\n", utils.format_mode(stat.mode, stat.type))
      vim.notify(str)
    end,
  },
}
```
Here `format_size`, `format_time` and `format_mode` are copied and modified from https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/master/lua/telescope/_extensions/file_browser/fs_stat.lua

**Comment by pysan3** [comment]
Nice! Closing ;)
