### ISSUE TITLE
Icons broken with nerdfont 3.0

### ISSUE THREAD

**Issue by patrickpichler** [nvim-neo-tree/neo-tree.nvim#916]
Nerdfont 3.0 remove all mdi icons. This causes neo-tree to have some broken icons.

![image](https://user-images.githubusercontent.com/13838138/236561600-6fca37b9-a19e-4cbf-aa46-1a8b4c368643.png)

**Comment by nhat-vo** [comment]
A guide to fix this issue has been merged in #921. I will close this as complete.

**Comment by GaetanLepage** [comment]
icons for `svg` file seems to still be broken (after applying the fix).
![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/33058747/53250018-556c-4391-aaee-61f6aa932862)

**Comment by cseickel** [comment]
@GaetanLepage file icons would be an upstream issues: https://github.com/nvim-tree/nvim-web-devicons

**Comment by GaetanLepage** [comment]
Indeed. Furthermore they have already fixed this !
