### ISSUE TITLE
Something need to be updated to README.md

### ISSUE THREAD

**Issue by nyngwang** [nvim-neo-tree/neo-tree.nvim#92]
Here are things (caused by me) that need to be added to the README.md:

- `excluded_filetypes = { 'fzf', 'neo-tree', 'packer', '' }, -- the last one resolved this issue.`, #91 
    - Context: floating window current don't have a name. I think it will be better to set an informative filetype for these little floating windows, instead of a blank one ''
- `require("neo-tree").setup({ open_files_in_last_window = true, ...})`, #85 
    - Context: If it helps, there is also a `open_files_in_last_window` option.
- `filters = { show_hidden = true, ...`, #71 
    - Context: How to show the hidden files by default in the current version?, was already there but now I realize it's only in the vim help file.

Q&A:

- Is it possible to use the plain-old built-in / to highlight the keyword I want to search inside the file tree? #86 

Since my English is not good, I left this chore to you~

**Comment by cseickel** [comment]
I think all this is documented now. Bear in mind that I am considering the vim help file to be the primary documentation. Feel free to add to the [Wiki](https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Tips) if you want to point things out for others.
