### ISSUE TITLE
`hide_gitignored` takes precedence over `hide_by_*` and `never_show*`

### ISSUE THREAD

**Issue by AThePeanut4** [nvim-neo-tree/neo-tree.nvim#929]
It seems that the `hide_gitignored = false` option takes precedence over `hide_by_name`, `hide_by_pattern`, `never_show` and `never_show_by_pattern`, which I believe to be counter-intuitive.

My situation is that I have a javascript project with a .gitignored `node_modules` folder. I want to be able to hide the `node_modules` folder while still keeping other .gitignored files visible.

I also have `.DS_Store` set to `never_show`, but this again doesn't work if `.DS_Store` is .gitignored.

As soon as I remove `node_modules` or `.DS_Store` from the `.gitignore` file they then get hidden.

The issue appears with `hide_by_pattern` and `never_show_by_pattern` as well.

These are the relevant config lines:
```lua
{
  filesystem = {
    filtered_items = {
      hide_dotfiles = false,
      hide_gitignored = false,
      hide_by_name = {
        ".git",
        "node_modules",
      },
      never_show = {
        ".DS_Store",
      },
    },
  }
}
```

I would expect all files in `hide_by_name`, `hide_by_pattern`, `never_show` and `never_show_by_pattern` to be hidden irrespective of the `hide_gitignored` option. This is what happens with `hide_dotfiles` - hiding the `.git` directory works even though I have `hide_dotfiles = false`. 

This is a similar issue to #682.

**Comment by pysan3** [comment]
Reproducible, and I think so too.

> It seems that the hide_gitignored = false option takes precedence over hide_by_name, hide_by_pattern, never_show and never_show_by_pattern, which I believe to be counter-intuitive.

Do you @cseickel agree on this? If so, I'll work on it.

**Comment by pysan3** [comment]
Closing with #946
