### ISSUE TITLE
Is there a way to set cwd from neo-tree?

### ISSUE THREAD

**Issue by LangdalP** [nvim-neo-tree/neo-tree.nvim#937]
Hi

I like using neo-tree, but one small frustration is that I sometimes wish that the "set root"-command would also `cd` to the new folder, so that the telescope file finder will only search for files under the new root.

Is there a way to achieve this? Ideally I would want it to be a command that shows up when opening the "?" menu.

**Comment by nhat-vo** [comment]
You can set `bind_to_cwd = true`. Have a look here https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/defaults.lua#L405

**Comment by LangdalP** [comment]
Thank you. I still think it would be nice with an option to manually set cwd from neo-tree (with `bind_to_cwd = false`), but this will do for now. Is there a way for me to script my proposal? If so, could you point me in the right direction?

Otherwise, you can close this issue.

**Comment by nhat-vo** [comment]
You can write your own command in this case. Have a look at `:h neo-tree custom-commands` and the  [wiki](https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#commands) for how to write them.

What you can do is add a command to override the default `set_root` like this:
```lua
["."] = function(state)
		local current_node = state.tree:get_node()		-- this is the current node
		local path = current_node:get_id()					-- this gives you the path

		require("neo-tree.sources.filesystem.commands").set_root(state)		-- call the default set_root

		-- do whatever you want to do here
		vim.cmd("cd " .. path)
	end,
```

**Comment by LangdalP** [comment]
Very helpful, thank you!

**Comment by Aman9das** [comment]
```
 ["="] = {
            function(state)
              local path = state.path -- this gives you the path

              -- do whatever you want to do here
              vim.cmd("cd " .. path)
            end,
            desc = "cd to current root",
          },
```

This only changes the working directory to current root.

**Comment by cseickel** [comment]
The comment says "do whatever you want to do here". The snippet is not meant to do anything, it's showing how to create a generic custom command with placeholder code.
