### ISSUE TITLE
Auto close the tree when use open_with_window_picker

### ISSUE THREAD

**Issue by NGPONG** [nvim-neo-tree/neo-tree.nvim#940]
As the title says, when I use the open_with_window_picker command to open a node it prompts me to select a window, and when I select a window the tree closes automatically. Is there any way to reject this behavior?

**Comment by NGPONG** [comment]
When I commented out this line of code `util.clear_prompt()`(in nvim-window-picker/lua/window-picker/init.lua:216), everything worked fine

I'm not quite sure if this will help you guys, I'm sorry I'm a rookie at this, so please ignore me if I'm wrong.

**Comment by cseickel** [comment]
How are you opening neo-tree? Is it in a float window or "current", or is it a sidebar? If it is a float, then it's supposed to close when you open a file. If it is a sidebar, can you post your neo-tree config?

**Comment by NGPONG** [comment]
Hi @cseickel, Thanks for such a quick reply!

Following the clues you provided, I finally found that it was caused by a keymap conflict. Here are my own keymaps:

```
-- clear default keymaps
keymap(E_NORMAL, ':', '<NOP>')
keymap(E_NORMAL, 'e', '<NOP>')
keymap(E_NORMAL, 'sc', '<CMD>wincmd c<CR>', { remap = false })

-- rebind keymap behavior
keymap(E_NORMAL, ':', '<C-e>', { remap = false })
keymap(E_NORMAL, '\\', ':', { remap = false, silent = false })
```

However, nvim-window-picker executes the following command when clear_prompt is executed

```
-- nvim-window-picker/lua/window-picker/util.lua:24
function M.clear_prompt()
    v.api.nvim_command('normal :esc<CR>')
end
```

So, when typing ':', it triggers <C-e>, and then parses to 'sc', which sets off the window closing.

I'm not sure what this command does yet, so I've make a attempted of this, I tried changing the code of clear_prompt to the following, but I'm still not sure if this is the right way to do it, is there something I'm missing here? Please correct me if I'm wrong, I'd appreciate it!

```
-- nvim-window-picker/lua/window-picker/util.lua:24
function M.clear_prompt()
    v.api.nvim_command('normal <CMD>esc<CR>')
end
```

**Comment by cseickel** [comment]
I am completely lost, but either way I don't think any of this has anything to do with neo-tree. Everything you are discussing here seems to be about a weird conflict between nvim-window-picker and your own remaps. I would suggest you take this issue to the nvim-window-picker porject.

**Comment by NGPONG** [comment]
Yes, I also realize that this problem seems to be out of the neo-tree project, and I'll be ready to send a new issuse in nvim-window-picker to try to fix it after completed a targeted test.

On a side note, I saw some very interesting features after migrating from nvim-tree, thanks for your contribution and thanks again for taking the time out of your busy schedule to reply!
