### ISSUE TITLE
NeoTreeGitUnstaged icon missing (but no others)

### ISSUE THREAD

**Issue by ddbrierton** [nvim-neo-tree/neo-tree.nvim#941]
Let me say immediately that I **am** aware of the 3.0 update to Nerd Fonts.

[**Edit**: I forgot to specify, this is on macOS 13.3.1 (a)]

I’m using `JetBrainsMono Nerd Font` v3.0.1, and according to Lazy all of my plugins are up to date. I have:

- NeoTree 2.62.0
- nvim-web-devicons hash 986875b

All of my other icons are working just fine, there is just this one for GitUnstaged that is missing:

<img width="455" alt="Screenshot 2023-05-19 at 22 19 05" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/7255543/08ea893b-129e-43d2-9124-e36cc68b6717">

Compare the icon shown when the file is staged:

<img width="458" alt="Screenshot 2023-05-19 at 22 20 05" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/7255543/6476df8c-8fa1-41f4-802a-debd90c5b2e7">

My recollection is that the unstaged icon should be an orange rectangle just like the staged icon without a tick.

But I just can’t understand how I can be the only one seeing this. I’ve searched through all the issues and discussions, both open and closed, here and for nvim-web-devicons and Nerd Fonts and no one else has reported this. Everyone uses Git and JetBrainsMono is as far as I know a very popular font. I have tried uninstalling it and reinstalling it again.

[**Edit**: I have since my original report tried installing different nerd fonts and using them and I still see the same missing icon, so I don’t think it is specific to JetBrainsMono.]

Of course it may be nothing to do with Neo-Tree in which case apologies for wasting your time but I can’t figure out how to track down what is causing this.

**Comment by nhat-vo** [comment]
If possible, could you provide extra information on your config? It's hard to see what happens without it.

Have you added the configuration for nerdfont v3 in the README? https://github.com/nvim-neo-tree/neo-tree.nvim#configuration-for-nerd-fonts-v3-users

**Comment by ddbrierton** [comment]
> Have you added the configuration for nerdfont v3 in the README? https://github.com/nvim-neo-tree/neo-tree.nvim#configuration-for-nerd-fonts-v3-users

Oh! I had completely missed that update in the README. Thank you so much @nhat-vo that was the solution.
