### ISSUE TITLE
Closing an open file with `:bd` expands explorer instead of moving to other buffer

### ISSUE THREAD

**Issue by agctute** [nvim-neo-tree/neo-tree.nvim#947]
If I have two buffers tabs in the bufferline tab bar and have the explorer open, then when I close the current buffer with `:bd`, then instead of switching to the other available buffer, neovim will fill the screen with the explorer. 

**How to Replicate**:
Install the bufferline plugin
Open two tabs and focus to one
keep explorer open and run `:bd`

The explorer would then fill the screen instead of switching to the other buffer.

**Comment by Shougo** [comment]
You should not use :bd directly.
It is feature of neovim.
Because the command closes current window automatically.

**Comment by agctute** [comment]
What should I do in order to close the current buffer/tab and have the other ones appear?

**Comment by nhat-vo** [comment]
Have a look at https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/FAQ#bdelete-makes-the-tree-spans-the-whole-window-how-do-i-prevent-it
