### ISSUE TITLE
BUG: Plugin doesn't work in windows with folder with restrictive permissions

### ISSUE THREAD

**Issue by lnc3l0t** [nvim-neo-tree/neo-tree.nvim#960]
When using the plugin in Windows within a folder that contains subfolders with restricted permissions, the plugin attempts to open the folders using `fs_opendir` function https://github.com/nvim-neo-tree/neo-tree.nvim/blob/8c89efb93b8383666a6f989762c2f610f5f2c930/lua/neo-tree/sources/filesystem/lib/fs_scan.lua#L152. 
However, this operation fails, and when `print(vim.inspect(dir))` is executed, it displays "EPERM Operation not permitted" in addittion to return nil. Despite the error, success from pcall is still evaluated as true.

As a result of this issue, when the plugin tries to close the directory immediately after, https://github.com/nvim-neo-tree/neo-tree.nvim/blob/8c89efb93b8383666a6f989762c2f610f5f2c930/lua/neo-tree/sources/filesystem/lib/fs_scan.lua#L163 it raises an error. This error can be one of the following, depending on whether you ran `nvim` or `nvim file`:
```bash
[Neo-tree ERROR] debounce  filesystem_navigate  error:  ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:165: bad argument #1 to 'fs_closedir' (uv_dir expected, got nil)
```
or
```bash
Error executing luv callback:
...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:165: bad argument #1 to 'fs_closedir' (uv_dir expected, got nil)
stack traceback:
        [C]: in function 'fs_closedir'
        ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:165: in function 'get_children_sync'
        ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:208: in function 'callback'
        ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:180: in function <...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:171>
```

**Comment by pysan3** [comment]
Shall we close this? @cseickel

**Comment by cseickel** [comment]
yup
