### ISSUE TITLE
Automatically resize Neotree window to contents?

### ISSUE THREAD

**Issue by tmpm697** [nvim-neo-tree/neo-tree.nvim#966]
Very often in my nvim session, I have to navigate neo-tree window to adjust its size to match its content size. 

Mostly dues to I change filename to a long/verbose one or I nevigate a folder in the tree that contain long file name.

Is there an option to auto adjust to the best window size (width) to its content?

i.e:
```
neo-tree window
  this-is-very-long-file-name-that-excess-neo-tree-window-width
```

**Comment by cseickel** [comment]
There is: `window.auto_expand_wdith`
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/8c89efb93b8383666a6f989762c2f610f5f2c930/lua/neo-tree/defaults.lua#L313
