### ISSUE TITLE
case sensitivity causes false 'File not in cwd' in Windows

### ISSUE THREAD

**Issue by Rodrigodd** [nvim-neo-tree/neo-tree.nvim#97]
This is similar neovim/nvim-lspconfig#1168. See also neovim/neovim#16331.

Windows paths are not case sensitive in most cases, but this is not a problem normally. But lsp servers report paths with the drive letter normalized to lower case, but windows paths usually have upper case drive letters. This means that when cwd is, for example, `C:\my_project\`, sometimes I have a file `c:\my_project\a_file.rs`, which trigger the 'File not in cwd' prompt when running `:NeoTreeReveal`.

I temporally solve this problem by replacing the condition in [this line](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/1020de30e09dad63fc59fbbddbe3387913ad3fa5/lua/neo-tree/sources/manager.lua#L261) with `not M.is_subpath(cwd, path)`, from code below. I can open a PR if you wish. I don't know if you may know a better solution or want to wait for neovim/neovim#16331.

``` lua
M.normalize_path = function (path)
    local has_windows_drive_letter = path:match '^%a:'
    if has_windows_drive_letter then
        return path:sub(1,1):lower()..path:sub(2)
    end
    return path
end

M.is_subpath = function(cwd, path)
    cwd = M.normalize_path(cwd)
    path = M.normalize_path(path)
    return string.sub(path, 1, string.len(cwd)) == cwd
end
```

**Comment by cseickel** [comment]
If you could open a PR that would be great. I don't use nvim natively on windows myself so I can't properly test it.

One question though: would it be better to just lowercase the whole path if it is on Windows since the whole path is actually case insensitive? The `neo-tree.utils` module does have a `is_windows` property to determine if it is running on windows.

**Comment by Rodrigodd** [comment]
Ok, so I will try to organize the code a little better, and open a PR.

> would it be better to just lowercase the whole path if it is on Windows since the whole path is actually case insensitive?

There is a way to enable case sensitivity in windows, so I avoided lowercasing the entire path.
