### ISSUE TITLE
Provide default value for prompt "File not in cwd. Change cwd to"

### ISSUE THREAD

**Issue by BruceChanJianLe** [nvim-neo-tree/neo-tree.nvim#973]
Hello there, I went through the neo-tree.txt but I couldn't find the answer.

I am wondering is it possible to provide a default value for the prompt when running ''Neotree focus reveal" command. Current, we can only force it to yes if "reveal_force_cwd" is used.

Is it possible to set it to no? If the file cannot be found on the current tree, then just toggle open the tree without revealing it?

Thank you.

**Comment by wsdjeg** [comment]
I just open an PR about this, #992

**Comment by BruceChanJianLe** [comment]
Hi @wsdjeg,

Thanks for looking into this matter! I shall close this issue when the PR is successful :D

**Comment by cseickel** [comment]
This is really unnecessary. You can get the behavior you want by setting `follow_current_file = true`. With that option, every time you open the tree it will reveal the current file if it is within the cwd, but it won't prompt you if it is not.

In that case you don't need to use the `reveal` option in the command.

The only downside is that it will always follow the current file, not just when you first open the tree. If that's nmot what you want, then someone will need to create a new PR to add the new variation of reveal. Maybe `reveal_without_change_cwd`?

**Comment by BruceChanJianLe** [comment]
That's what I'm looking for! Sorry for not understanding the use of follow_current_file at the first place. Now that you have explained, it makes perfect sense.

I am happy with it following the file for now. If others would like a `reveal_without_change_cwd` perhaps they could open a new PR.

Thank you both @wsdjeg and @cseickel for your time!

**Comment by jakobkhansen** [comment]
Does using `follow_current_file` to suppress the prompt still work? I cannot seem to get it working on my end, it always prompts for y/n to change cwd.

**Comment by cseickel** [comment]
@jakobkhansen if you don't want to be prompted, don't use a `reveal` command. 

If you want it to change cwd without prompting, then use the `reveal_force_cwd` flag instead. If you want it to follow the current file but never change cwd, then just use the `follow_current_file` option without specifying the `reveal` flag.

**Comment by BruceChanJianLe** [comment]
> follow_current_file

My configuration still seems to work for me. I do `Neotree focus` with `follow_current_file` as true.
