### ISSUE TITLE
Error after using filter/search

### ISSUE THREAD

**Issue by doganalper** [nvim-neo-tree/neo-tree.nvim#981]
After using filter/search and trying to enter command on Command mode I get this error.
<img width="1710" alt="image" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/48688801/a93f910c-ac52-404f-bd0a-8449d21d6f06">

**Comment by cseickel** [comment]
This seems to be an error with the Auto Pairs plugin, see: https://github.com/jiangmiao/auto-pairs/issues/366
