### ISSUE TITLE
[Enhencement] Is it possible to open multiple selected files

### ISSUE THREAD

**Issue by Bekaboo** [nvim-neo-tree/neo-tree.nvim#982]
First of all thanks for your work on this awesome plugin!

As the title says, is it possible to open multiple files at once using neo-tree?

I read through the doc and searched the existing issues but cannot find any discussion about it.

Thanks!

**Comment by cseickel** [comment]
No, sorry that functionality does not exist. This functionality might help though: https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Tips#open-file-without-losing-sidebar-focus
