### ISSUE TITLE
Filters still uses popup window with `use_popups_for_input = false`

### ISSUE THREAD

**Issue by aktersnurra** [nvim-neo-tree/neo-tree.nvim#984]
Hello,

I have set `use_popups_for_input = false` and it works as expected for operations such as moving and renaming. However, when I use the filter functions, e.g. / or f, the popup ui is used. Is this expected or is it a bug?

Thanks

**Comment by cseickel** [comment]
That's expected. It's because the primary use for the filter popup is to run search as you type, and there is no way to do that without the popup.
