### ISSUE TITLE
How to change the title of the file window?

### ISSUE THREAD

**Issue by lucasquin** [nvim-neo-tree/neo-tree.nvim#987]
I need help changing the title of the file window, I've looked everywhere but haven't found a way. Is there such a possibility?

![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/65108092/2dcadd5a-1750-4a34-875a-cfd27d992df3)

**Comment by lucasquin** [comment]
That's it, the Head. Any way to custom put or hide the path?

Sample:
![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/65108092/c5be8dbe-7208-47a2-96f3-204a021c4921)

**Comment by cseickel** [comment]
From the screenshot, it looks like you want to display the root folder just like any other folder without special highlighting or showing the full path, is that correct?

If it is, the solution is to replace the `name` component with your own version that has no special handling for the root folder.

**Comment by lucasquin** [comment]
That's right, I would particularly put an icon like 🌲 or something similar, is this only possible by editing the source code or is there some property in the setup()?

**Comment by cseickel** [comment]
Here's an example of how to customize the root node with configuration: https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/681#discussioncomment-5429393

**Comment by lucasquin** [comment]
Very good, it was what I needed. Thank you very much for
personal help.
