### ISSUE TITLE
Alternatives to legacy commands for focus with floating window

### ISSUE THREAD

**Issue by timjackleus** [nvim-neo-tree/neo-tree.nvim#988]
It seems like all commands but `:Neotree` are being deprecated, this makes sense to me but as someone enjoying the floating window alternative, I'm no longer sure how I'm supposed to get around [this issue](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/902).
The `follow_current_file` setting does not help.

**Comment by pysan3** [comment]
Does this help you?

https://github.com/nvim-neo-tree/neo-tree.nvim/issues/394

**Comment by timjackleus** [comment]
@pysan3 it does, thank you!
