### ISSUE TITLE
DirChanged event does not refresh the tree

### ISSUE THREAD

**Issue by cseickel** [nvim-neo-tree/neo-tree.nvim#99]
It looks like the event is captured, because a manual refresh does show the new cwd. It is not automatically refreshing as it should though.

**Comment by nyngwang** [comment]
(might not related to this)

IIRC: there is some bug on neovim itself that the event-triggering-system/event-loop has some bug/design-flaw such that some events are not properly triggered. Ref.: https://github.com/neovim/neovim/issues/12587

**Comment by cseickel** [comment]
Thanks for pointing that out. I _think_ this one is one is just my mistake, but we'll see soon enough...

**Comment by cseickel** [comment]
Yup, it was totally my fault. As usual, `follow_current_file` got in the way.
