### ISSUE TITLE
Name for a custom command to be displayed in the ? menu

### ISSUE THREAD

**Issue by MariaSolOs** [nvim-neo-tree/neo-tree.nvim#990]
As an example, say that I would like to name [this command from the wiki](https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Tips#navigation-with-hjkl) so that it shows up as `"nav_to_parent"` instead of `"<function>"`:
```lua
["h"] = function(state)
  local node = state.tree:get_node()
    if node.type == 'directory' and node:is_expanded() then
      require'neo-tree.sources.filesystem'.toggle_directory(state, node)
    else
      require'neo-tree.ui.renderer'.focus_node(state, node:get_parent_id())
    end
  end,
```

How could I achieve that? I tried the following but it didn't work...
```lua
opts = {
  mappings = { nav_to_parent = function() .. end },
  window = { mappings = ['h'] = 'nav_to_parent' }
}
```

**Comment by MariaSolOs** [comment]
Thank you @miversen33 for your help!
Okay so I'm actually not mapping `h` but [these togglers](https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#switch-between-filesystem-buffers-and-git_status).
Unfortunately, I'm now getting an error:
<img width="1064" alt="image" src="https://github.com/nvim-neo-tree/neo-tree.nvim/assets/62502207/48e2ca2e-7757-4920-9c38-9cef06f3009f">

This happens when I type `?`, which I haven't overridden. 
```
E5108: Error executing lua: ...no/.local/share/nvim/lazy/nui.nvim/lua/nui/line/init.lua:22: attempt to index local 'block' (a nil value)
stack traceback:
        ...no/.local/share/nvim/lazy/nui.nvim/lua/nui/line/init.lua:22: in function 'append'
        .../lazy/neo-tree.nvim/lua/neo-tree/sources/common/help.lua:33: in function 'show'
        ...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:745: in function 'func'
        ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:805: in function <...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:803>
Press ENTER or type command to continue
```

**Comment by miversen33** [comment]
That's odd. Can you provide me your neo-tree config so I can play around with that a bit?

**Comment by MariaSolOs** [comment]
> That's odd. Can you provide me your neo-tree config so I can play around with that a bit?

Sure! [Here's](https://github.com/MariaSolOs/dotfiles/blob/8c557c78fe82eed91cbbf7b4ce78f76c2597bb40/.config/nvim/lua/plugins/neo-tree.lua) my `neo-tree` config.

**Comment by miversen33** [comment]
@MariaSolOs sorry to be the bearer of bad news but I think the issue is somewhere in your configuration _outside_ what you provided me. Your configuration works just fine if you isolate it.

![image](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/2640668/8392c6bb-0bc1-49f2-9d0b-dc30a263fc2e)

Try out this isolated testing configuration
```lua
-- Install package manager.
-- Set <space> as the leader key.
-- Must happen before plugins are required (otherwise the wrong leader will be used).
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

local sep = vim.loop.os_uname().sysname:lower():match('windows') and '\\' or '/' -- \ for windows, mac and linux both use \
print("Cleaning up after previous test")
vim.fn.delete(vim.fn.stdpath('cache') .. sep .. 'clean-test', 'rf')
local lazypath = vim.fn.stdpath 'cache' .. sep .. 'clean-test' .. sep .. 'lazy' .. sep .. 'lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system {
        'git',
        'clone',
        '--filter=blob:none',
        'https://github.com/folke/lazy.nvim.git',
        '--branch=stable',
        lazypath,
    }
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
    -- File tree.
    {
        'nvim-neo-tree/neo-tree.nvim',
        branch = 'v2.x',
        cmd = 'NeoTree',
        dependencies = {
            'nvim-lua/plenary.nvim',
            'nvim-tree/nvim-web-devicons',
            'MunifTanjim/nui.nvim',
        },
        init = function()
            vim.g.neo_tree_remove_legacy_commands = 1
        end,
        opts = {
            sources = { 'filesystem', 'buffers', 'git_status' },
            popup_border_style = 'rounded',
            event_handlers = {
                -- Auto-close when opening a file.
                {
                    event = 'file_opened',
                    handler = function()
                        require('neo-tree').close_all()
                    end,
                },
            },
            filesystem = {
                follow_current_file = true,
            },
            window = {
                mappings = {
                    ['<space>'] = 'none',
                    ['l'] = 'none',
                    ['w'] = 'none',
                    -- TODO: Find a way to make these mappings show up in the ? menu.
                    -- Go to the first child.
                    ['hh'] = function(state)
                        local node = state.tree:get_node()
                        local parent = state.tree:get_node(node:get_parent_id())
                        if parent:has_children() then
                            local first_sibling = state.tree:get_nodes(parent:get_id())[1]
                            require('neo-tree.ui.renderer').focus_node(state, first_sibling:get_id())
                        end
                    end,
                    -- Go to the last child.
                    ['ll'] = function(state)
                        local node = state.tree:get_node()
                        local parent = state.tree:get_node(node:get_parent_id())
                        if parent:has_children() then
                            local children = state.tree:get_nodes(parent:get_id())
                            require('neo-tree.ui.renderer').focus_node(state, children[#children]:get_id())
                        end
                    end,
                    -- Mappings to toggle the explorer mode.
                    ['e'] = 'toggle_filesystem',
                    ['b'] = function()
                        require('neo-tree.command').execute { action = 'focus', source = 'buffers', position = 'left' }
                    end,
                    ['g'] = function()
                        require('neo-tree.command').execute { action = 'focus', source = 'git_status', position = 'left' }
                    end,
                },
            },
            default_component_configs = {
                git_status = {
                    symbols = {
                        deleted = '',
                        renamed = '',
                        untracked = '',
                        ignored = '⊝',
                        unstaged = '',
                        staged = 'ﱣ',
                        conflict = '',
                    },
                },
            },
            commands = {
                toggle_filesystem = function()
                    require('neo-tree.command').execute { action = 'focus', source = 'filesystem', position = 'left' }
                end,

            }
        },
        keys = {
            {
                '<leader>f',
                function()
                    require('neo-tree.command').execute { toggle = true, dir = vim.loop.cwd() }
                end,
                desc = 'Toggle file explorer',
            },
        },
    },
})
```

**Comment by MariaSolOs** [comment]
> @MariaSolOs sorry to be the bearer of bad news but I think the issue is somewhere in your configuration _outside_ what you provided me. Your configuration works just fine if you isolate it.
> 
> ![image](https://user-images.githubusercontent.com/2640668/248145577-8392c6bb-0bc1-49f2-9d0b-dc30a263fc2e.png)
> 
> Try out this isolated testing configuration
> 
> ```lua
> -- Install package manager.
> -- Set <space> as the leader key.
> -- Must happen before plugins are required (otherwise the wrong leader will be used).
> vim.g.mapleader = ' '
> vim.g.maplocalleader = ' '
> 
> local sep = vim.loop.os_uname().sysname:lower():match('windows') and '\\' or '/' -- \ for windows, mac and linux both use \
> print("Cleaning up after previous test")
> vim.fn.delete(vim.fn.stdpath('cache') .. sep .. 'clean-test', 'rf')
> local lazypath = vim.fn.stdpath 'cache' .. sep .. 'clean-test' .. sep .. 'lazy' .. sep .. 'lazy.nvim'
> if not vim.loop.fs_stat(lazypath) then
>     vim.fn.system {
>         'git',
>         'clone',
>         '--filter=blob:none',
>         'https://github.com/folke/lazy.nvim.git',
>         '--branch=stable',
>         lazypath,
>     }
> end
> vim.opt.rtp:prepend(lazypath)
> require("lazy").setup({
>     -- File tree.
>     {
>         'nvim-neo-tree/neo-tree.nvim',
>         branch = 'v2.x',
>         cmd = 'NeoTree',
>         dependencies = {
>             'nvim-lua/plenary.nvim',
>             'nvim-tree/nvim-web-devicons',
>             'MunifTanjim/nui.nvim',
>         },
>         init = function()
>             vim.g.neo_tree_remove_legacy_commands = 1
>         end,
>         opts = {
>             sources = { 'filesystem', 'buffers', 'git_status' },
>             popup_border_style = 'rounded',
>             event_handlers = {
>                 -- Auto-close when opening a file.
>                 {
>                     event = 'file_opened',
>                     handler = function()
>                         require('neo-tree').close_all()
>                     end,
>                 },
>             },
>             filesystem = {
>                 follow_current_file = true,
>             },
>             window = {
>                 mappings = {
>                     ['<space>'] = 'none',
>                     ['l'] = 'none',
>                     ['w'] = 'none',
>                     -- TODO: Find a way to make these mappings show up in the ? menu.
>                     -- Go to the first child.
>                     ['hh'] = function(state)
>                         local node = state.tree:get_node()
>                         local parent = state.tree:get_node(node:get_parent_id())
>                         if parent:has_children() then
>                             local first_sibling = state.tree:get_nodes(parent:get_id())[1]
>                             require('neo-tree.ui.renderer').focus_node(state, first_sibling:get_id())
>                         end
>                     end,
>                     -- Go to the last child.
>                     ['ll'] = function(state)
>                         local node = state.tree:get_node()
>                         local parent = state.tree:get_node(node:get_parent_id())
>                         if parent:has_children() then
>                             local children = state.tree:get_nodes(parent:get_id())
>                             require('neo-tree.ui.renderer').focus_node(state, children[#children]:get_id())
>                         end
>                     end,
>                     -- Mappings to toggle the explorer mode.
>                     ['e'] = 'toggle_filesystem',
>                     ['b'] = function()
>                         require('neo-tree.command').execute { action = 'focus', source = 'buffers', position = 'left' }
>                     end,
>                     ['g'] = function()
>                         require('neo-tree.command').execute { action = 'focus', source = 'git_status', position = 'left' }
>                     end,
>                 },
>             },
>             default_component_configs = {
>                 git_status = {
>                     symbols = {
>                         deleted = '',
>                         renamed = '',
>                         untracked = '',
>                         ignored = '⊝',
>                         unstaged = '',
>                         staged = 'ﱣ',
>                         conflict = '',
>                     },
>                 },
>             },
>             commands = {
>                 toggle_filesystem = function()
>                     require('neo-tree.command').execute { action = 'focus', source = 'filesystem', position = 'left' }
>                 end,
> 
>             }
>         },
>         keys = {
>             {
>                 '<leader>f',
>                 function()
>                     require('neo-tree.command').execute { toggle = true, dir = vim.loop.cwd() }
>                 end,
>                 desc = 'Toggle file explorer',
>             },
>         },
>     },
> })
> ```

Thank you for the careful investigation! I indeed cannot reproduce this with this minimal configuration, so I'll continue debugging on my side. I'll close this now.

**Comment by miki725** [comment]
in my case was able to narrow down the error to specific mapped keys. Filed https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1180 with more details
